### ISSUE TITLE
FR: Symlink exports

### ISSUE THREAD

**Issue by ghost** [hydrusnetwork/hydrus#10]
So, imagine the following usage case: You manage all of your media in Hydrus, but you still need to work on specific queries with other programs in a read-only fashion, without the exported media leaving your computer.

Hydrus supports this well already - there's robust export functionality and there's even a scheduler to automatically update your export folders. But, if you are exporting large queries, that's going to use a lot of disk space, especially if there's significant overlap between different query folders.

Being able to set the export tool to export symlinks - which point to the source media files within Hydrus' DB folder structure - instead of actual image files would add further flexibility for this sort of thing. Again, I have no idea how technically feasible this is, and it's possible that there are really good reasons not to do this and I am just a demented person who likes and uses symlinks far, far too much for his own good, but, something I thought of.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
