### ISSUE TITLE
question: tag manager location

### ISSUE THREAD

**Issue by genbread** [hydrusnetwork/hydrus#1006]
New user here, where can I find the general tag manager? I can only find the tag sibling and parent managers here, and I see no mention of it on the guide. 

![image](https://user-images.githubusercontent.com/82292471/141189519-d9984494-d4c4-4921-aec6-a93f29691afb.png)

(will update with appropriate label when i can figure out where i add them)

**Comment by Zweibach** [comment]
The issue tracker is not for questions and answers. Do read the manual because it's in the sixth line of the page literally called getting started with tags https://hydrusnetwork.github.io/hydrus/help/getting_started_tags.html
