### ISSUE TITLE
Hydrus crashes on audio files

### ISSUE THREAD

**Issue by ShadowJonathan** [hydrusnetwork/hydrus#1007]
### Hydrus version

461

### Operating system

Windows 11

### Install method

Installer

### Install and OS comments

Additional `about` description:

![image](https://user-images.githubusercontent.com/22740616/141866707-a6b6083a-81bd-499d-8c11-6a6a8f878daf.png)

### Bug description and reproduction

Hydrus displays tracebacks and occasionally crashes when playing back audio files.

This is one of the audio files; https://cdn.discordapp.com/attachments/895293596662648841/909943250637430784/4db10e133c372f2954805c44766d4eca75475c775355022a8720dad5ab40e801.flac

### Log output

```text
TypeError
unsupported operand type(s) for -: 'NoneType' and 'int'
  File "hydrus\client\gui\canvas\ClientGUICanvasMedia.py", line 866, in paintEvent
    self._Redraw( painter )
  File "hydrus\client\gui\canvas\ClientGUICanvasMedia.py", line 630, in _Redraw
    self._last_drawn_info = self._GetAnimationBarStatus()
  File "hydrus\client\gui\canvas\ClientGUICanvasMedia.py", line 589, in _GetAnimationBarStatus
    return self._media_window.GetAnimationBarStatus()
  File "hydrus\client\gui\ClientGUIMPV.py", line 301, in GetAnimationBarStatus
    current_frame_index = min( current_frame_index, num_frames - 1 )
```

**Comment by ShadowJonathan** [comment]
(I'm reporting this bug by proxy for a friendo, in case y'all want additional info)

**Comment by floogulinc** [comment]
I can confirm this seems to happen with all or nearly all flac files.

**Comment by floogulinc** [comment]
This issue seems to come from this line:

https://github.com/hydrusnetwork/hydrus/blob/cbacaac44887b0dc369cf58656d69f6d370be526/hydrus/client/gui/ClientGUIMPV.py#L301

This line is outside the previous check for `if num_frames is None`.  This line should be moved to inside the `else` of the previous `if` and could perhaps be refactored as:

```py
if num_frames is None or num_frames == 1:
                   
    current_frame_index = 0
    
else:
    
    current_frame_index = min( int( round( ( current_timestamp_ms / self._media.GetDuration() ) * num_frames ) ), num_frames - 1 )


current_timestamp_ms = min( current_timestamp_ms, self._media.GetDuration() )
```

**Comment by hydrusnetwork** [comment]
Thank you for this report--I am very sorry for the trouble! It is fixed for tomorrow.
