### ISSUE TITLE
Edit Merge Options dialog has no way to edit or set actions on rating services for same quality and alternates

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#1009]
### Hydrus version

v447

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

_(unsure if this is a bug or I'm misunderstanding how this dialog works)_

**Expected**

All modes allow selecting any available action.

**To Reproduce**

1. With the duplicate filter displayed (i.e. the media viewer), select the gear icon in the dialog, then select either 'same quality' or 'alternates'.  _The Edit (whatever) Merge Options dialog appears._
2. Observe there is no Edit button for Rating services.
3. Anything added to either mode automatically is set to action = 'copy in both directions' with no way to choose anything else.

**Context**

I'm not sure I understand what 'copy in both directions' means for ratings or if other actions are not meaningful for ratings.  Would lower ratings ever overwrite higher on any file?   There may be situations where you want to keep the lowest rating (e.g. if you're pruning duplicates and the higher rating is incorrect, though you can always manually set the rating and just not merge anything).

### Log output

```text
N/A
```

**Comment by Zweibach** [comment]
1. You're 15 versions out of date.
2. Being able to edit those settings is a feature request.
