### ISSUE TITLE
'system:number of unnamespaced tags' searches all tags instead of only unnamespaced

### ISSUE THREAD

**Issue by stysmmaker** [hydrusnetwork/hydrus#1017]
### Hydrus version

463

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

1. Perform search with the 'system:number of unnamespaced tags' predicate ('system:number of tags' with the 'all tags' checkbox unchecked and the namespace field blank)
2. Returned results are matched against _all_ tags rather than only unnamespaced tags, thus producing a lot of unwanted results

**Comment by hydrusnetwork** [comment]
Thank you for this report. I made a mistake in the recent update that allowed search to work on multiple domains and was accidentally """"optimising"""" the unnamespaced namespace as if it were '*', or all namespaces. This is fixed for tomorrow's release, let me know if you have any more trouble!
