### ISSUE TITLE
Closed Hydrus normally and lost 8k of links in the queue

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#102]
That happened. Anyway to prevent that? Does the client have a set timer to automatically backup the session?
It's weird because whenever I had to kill the client, no links were lost (that I noticed.)

EDIT:I searched the log thoroughly and found absolutely nothing wrong. Not that keen on trying to reproduce this until this queue is done, which will likely take another week.

**Comment by hydrusnetwork** [comment]
This is related to the unicode problem #101 , so I will close this.
