### ISSUE TITLE
Add hyextract to docker image

### ISSUE THREAD

**Issue by ChronoStriker1** [hydrusnetwork/hydrus#1024]
I was wondering if there was any possibility of adding hyextract to the docker image.  
Until a time where the functionality to extract and add to hydrus on import, it would be a decent stopgap. (Also I can't get it to run successfully from a separate computer so there's that)

**Comment by floogulinc** [comment]
if you setup the mount paths correctly you should be able to run hyextract in it's own container. This would be preferred to including all of node in the Hydrus image. I may make a docker image for hyextract in the future for this purpose.
