### ISSUE TITLE
FEATURE REQUEST: Expose Tags and URLs over the Local Booru

### ISSUE THREAD

**Issue by Ryonez** [hydrusnetwork/hydrus#1025]
Recently I've been sharing media via the local booru behind a reverse proxy. One thing I've noticed is that there's no option to share the tags on a repo or urls to the viewers. At the moment the viewer base is small so I can manually pull them myself and give it on request, but I'd love to see options for us to share this on the booru with the media.

**Comment by Zweibach** [comment]
> future plans
> This was a fun project, but it never advanced beyond a prototype. The future of this system is other people's nice applications plugging into the Client API.
t. <https://hydrusnetwork.github.io/hydrus/help/local_booru.html>

I'll ask dev about it but based on this and some casual conversations there are no plans to improve the local booru, until then these two issues will remain closed. Use Hydrus Web or Hybooru if you want more functionality.

**Comment by Ryonez** [comment]
> Hydrus Web
Not suitable for the use case, it's a web front end to the Hydrus client (I use this for other things), and is not suited to the goal of sharing a select group of images. Would also require them putting in api keys, is much messier than desired.

hybooru looks similar again, exposing pretty much everything in a booru style site.

It's not just about more functionality, but the end goal, which is to share a select group of images. The local booru does this extremely well, but could use a few qol additions. Hench this and #1026.

Eventfully I'm sure something might show that could do this, I might even be able to jury rig something together after a lot of time myself, but the local booru is so close to being just right.

**Comment by Zweibach** [comment]
ipfs can share select groups of images, downside is that it seems somewhat slow depending on the gateway.

**Comment by Ryonez** [comment]
Wouldn't that just lead be back into the same issue I'm having? Except potently slower now?
From what I recall tags and urls still wouldn't be shared over ipfs.
