### ISSUE TITLE
FEATURE REQUEST: Allow Changing Files Shared on Existing Local Booru Shares 

### ISSUE THREAD

**Issue by Ryonez** [hydrusnetwork/hydrus#1026]
Currently when you chare the files via the local booru, whatever you selected to be shared is all that's ever attached to the share. To remove media, or add more, you currently have to create an entire new share. This has the side effect that the urls also change, which could result in needing to change those wherever they've been shared.

It would be great to see a way to add or remove media from a share, even if it's just by changing the list of file_ids or hashes that share points at manually.

**Comment by Zweibach** [comment]
> future plans
> This was a fun project, but it never advanced beyond a prototype. The future of this system is other people's nice applications plugging into the Client API.
t. <https://hydrusnetwork.github.io/hydrus/help/local_booru.html>

I'll ask dev about it but based on this and some casual conversations there are no plans to improve the local booru, until then these two issues will remain closed. Use Hydrus Web or Hybooru if you want more functionality.
