### ISSUE TITLE
Inconsistent file size comparison in duplicate filter

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1028]
### Hydrus version

v466

### Operating system

Windows other (specify in comments)

### Install method

Installer

### Install and OS comments

Windows 7

### Bug description and reproduction

1. Launch duplicate filter
2. Wait until both image sizes are similiar
3. Notice "<" ">" and "≈"

examples: https://i.imgur.com/cVRdei6.png in comparison to https://i.imgur.com/R4QWhDX.png

**Comment by hydrusnetwork** [comment]
Thank you for this report. This was a logical bug on my end and should be fixed for tomorrow's release. Please let me know if you have any further trouble!
