### ISSUE TITLE
option to restart instead of just closing down. 

### ISSUE THREAD

**Issue by AreFinstad** [hydrusnetwork/hydrus#103]
i do notice that when slowdowns happens after a while it helps to turn on and off the program.
i think it would be nice to be able to just click file restart for the program to shut down fully and then start up again once its shut down making it just faster to do.
shutdowns can take a bit of time sometimes and users might forget to check if its finally down or not before manually turning the program on again.

just a small thing is miss from ComicRack that this doesnt have quite yet :D

**Comment by HASJ** [comment]
+1

**Comment by ScoreUnder** [comment]
I don't think this should be necessary.

If you need to restart programs often to get them up to speed, it's most likely that you are paging to disk too aggressively. If they deteriorate over time even if you never switch away from them, that's likely a bug which needs to be fixed. If they are more prone to paging than other applications, perhaps some cache settings need tweaking.

I wouldn't be opposed to a restart, but I think it's something that shouldn't be needed.

**Comment by AreFinstad** [comment]
Even if it was a bug that was fixed it could still be handy in general IMO

**Comment by hydrusnetwork** [comment]
I have added this for v186. Let me know if it doesn't work for you!
