### ISSUE TITLE
video scanbar autohide (Comment)

### ISSUE THREAD

**Issue by LustWolf** [hydrusnetwork/hydrus#1030]
In response to feedback request, I don't mind the change, just please keep that option to toggle the scanbar on/off in place like you currently have it; a lot of gif/video loops are seamless and I'd like to see the remaining time at a glance without having to hit an extra key or moving the mouse.

**Comment by Chipsy2021** [comment]
@LustWolf just goto file -> shortcuts -> global -> add. Then add a shortcut to the command 'force the animation scanbar to show (flip on/off)' apply and then open one of your gif/video press the shortcut and there you go welcome to the old behaviour.

**Comment by LustWolf** [comment]
> @LustWolf just goto file -> shortcuts -> global -> add. Then add a shortcut to the command 'force the animation scanbar to show (flip on/off)' apply the shortcut and then open one of your gif/video press the shortcut and there you go welcome to the old behaviour.

It looks like I failed in my wording.
I put: 

> just please keep that option to toggle the scanbar on/off in place like you currently have it 

to indicate I was aware of the current change.
I just didn't want to press the shortcut key with every video (he currently has it stay active after pressing the shortcut just once, which I like)
