### ISSUE TITLE
Absolute wall of text mitigation

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#1037]
Ok, I have been downloading some galleries that link to imgur, now there aren't many in each gallery that have the 'this image no longer available' image, but enough have piled up that it 100% fills the screen with text if I go to known urls open or copy.

I don't know if hard coding of certain images to not track data or a user 'do not track for this image' is called for, but I see potential issues with common images like this.

for reference 
![9b5936f4006146e4e1e9025b474c02863c0b5614132ad40db4b925a10e8bfbb9](https://user-images.githubusercontent.com/2681758/147574191-70ac71ca-c388-4108-becc-04b94e49bafa.png)

is the image and this is what it does on a 4k screen
![dllhost_2021-12-28_08-05-44](https://user-images.githubusercontent.com/2681758/147574307-49d66d0b-6e81-409e-9984-4527bd411ddc.png)

**Comment by Zweibach** [comment]
While I can sort of understand what you're getting at this is only a problem if you for whatever reason decides to keep these error images.

**Comment by alidan** [comment]
my thought is kind of around what if something like this causes an issue with the program, its not really an issue after you remove it, I think in my case this was about 1 day of getting a few galleries, and you would need to force it to show. it's probably a relatively extreme edge case either way.

**Comment by roachcord3** [comment]
You could rephrase this request as marking certain images as indicating that the returned image from a download was *actually* an error, that the file log can report as an error. Then Hydrus can just not add any parsed tags/URLs to that reference "bad" image.

**Comment by alidan** [comment]
ok, I have another abject wall of text image problem, every now and then one of these images gets redownloaded, this time it was a deviantart image block. tokumei on the preset-creation made an update that grabs images that were failing to be grabbed, and that's where this one comes in
![4c05dda7e59c232a1e7fcdd10800957a939f8f1152035641d3a035bcbf94219c](https://user-images.githubusercontent.com/2681758/155827613-fe98ef76-2a81-4f63-bf88-361add930df5.png)
this one, when right clicked causes around a 7 second program hang, none of the other images do this. im thinking its because of all the urls attached to it. 

now i'm wondering if there is a way to nuke the associated urls for an image from an image. I don't know if this will cause an issue or if it will just always result in a short hang, but i would like to deal with it because I feel like i'm dumb enough to have these images keep reappearing (retrying a deleted image prompts you with do you want to delete the deletion record, yes in the last 5 or so minutes I have been dumb enough to click yes 5 times rather than no) I think making the file lighter will be a good thing.

**Comment by hydrusnetwork** [comment]
Hey, sorry for the trouble and extreme delay here. I kept on procrastinating and then forgetting this issue until Zwei helpfully reminded me of it this week. I've written a 'menu truncater' and made it so URLs and tag siblings/parents/children now truncate to 15/10 items with a '35 more...' at the end. Children can be similarly bananas when you have a tag like 'pokemon' or 'azure lane'. It should be a bit more manageable at this surface layer now.
