### ISSUE TITLE
'only one file is allowed to match in search'-setting for duplicate filter

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#1038]
Ok when I am dealing with duplicates, what I typically do is try and prioritize heavy images first, and when we are talking about duplicates, besides having "both files match" + "10mb or greater" or something along those lines, another way, would be just "10mb or greater", this should put in a 10mb png with a 1mb jpeg or around there as the duplicates.

however I had a thought, what if we had a 'only one matches this' for the filter?

This would force the second file to be a lower file size, or force the other file to not be a png

then adding it with the recent must be pixel dups, setting the filter to png would force every 'these are pixel dups' to have one be a png and the other be a jpeg (I think those are the only two types current in the filter) and you could clear out quite a large chunk of images fast.

with a png filter going on a must be duplicated, I currently have 63,000 images, and in all likelihood, by the time anything could be implemented I may be done with clearing this section of duplicates, but I see a great value to be had even without exact dupes.

**Comment by hydrusnetwork** [comment]
Hey, I am launching 'one file in is search A, the other is in search B' today for v512, so I think this will let you do what you want!
