### ISSUE TITLE
Docker: "server.py: error: unrecognized arguments: --no_daemons"

### ISSUE THREAD

**Issue by ryester27** [hydrusnetwork/hydrus#1039]
### Hydrus version

v467

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Using server container with Podman and Arch Linux

### Bug description and reproduction

Error "server.py: error: unrecognized arguments: --no_daemons" is thrown upon creation and starting of a new container. This does not occur on a v466 server container

Command used to create container:

podman run \
  --name=$SERVICE --net=services \
  --label="io.containers.autoupdate=registry" \
  --ip=192.168.1.xxx \
  -v hydrus_db:/opt/hydrus/db \
  ghcr.io/hydrusnetwork/hydrus:server

### Log output

```text
[ryester27 ~]$ podman logs hydrus
Starting Hydrus with UID/GID : 1000/1000
usage: server.py [-h] [-d DB_DIR] [--temp_dir TEMP_DIR]
                 [--db_journal_mode {WAL,TRUNCATE,PERSIST,MEMORY}]
                 [--db_cache_size DB_CACHE_SIZE]
                 [--db_transaction_commit_period DB_TRANSACTION_COMMIT_PERIOD]
                 [--db_synchronous_override {0,1,2,3}] [--no_db_temp_files]
                 [--boot_debug] [--no_wal] [--db_memory_journaling]
                 [{start,stop,restart}]
server.py: error: unrecognized arguments: --no_daemons
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. Sorry, I removed this parameter last week and didn't realise the docker scripts ever used it. It was a legacy parameter that no longer does anything.

I have fixed this for tomorrow's release, please let me know if you still have trouble.
