### ISSUE TITLE
poor quality of zoomed images

### ISSUE THREAD

**Issue by sttollgrin** [hydrusnetwork/hydrus#104]
![Left is opened externally, right is opened in hydrus, the zoom level for both is similar (~90%)](https://cloud.githubusercontent.com/assets/1424484/11318678/38bd96e0-905c-11e5-9d1e-4a760b93f471.png)
As it can be clearly seen, the quality of the image that is displayed by hydrus is much lower than the one that is opened externally. Isn't there any way to "smooth" resized images?

The issue mostly affects scans (in those images "dark" areas are usually lots of small black dots, which resized by hydrus looks terrible) - example
![scan](https://cloud.githubusercontent.com/assets/1424484/11318739/90cae49e-905e-11e5-95d0-b6a376ff9ee6.png), again left is opened externally right is in hydrus.

**Comment by sttollgrin** [comment]
OK, there's something really weird with how images are resized in Hydrus client. Whenever I open new image the quality is bad, lines are jagged etc., basically what the examples above show. However when I navigate (left, right) to different image and then back to the original, lines become smooth, and the quality is on par with the quality of image opened externally.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
