### ISSUE TITLE
Hydrus falsely reports database as read-only

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#1042]
### Hydrus version

v468, not in v467

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Arch Linux, I am currently maintaining the AUR package and came across this issue.

### Bug description and reproduction

1. Set permissions on hydrus client database to 0600 (which is the default Hydrus uses on my system)
2. Run hydrus

### Log output

```text
v468, 2022/01/07 07:56:06: hydrus client started
v468, 2022/01/07 07:56:07: booting controller…
v468, 2022/01/07 07:56:08: booting db…
v468, 2022/01/07 07:56:08: If the db crashed, another error may be written just above ^.
v468, 2022/01/07 07:56:08: A serious error occurred while trying to start the program. The error will be shown next in a window. More information may have been written to client.log.
v468, 2022/01/07 07:56:08: Traceback (most recent call last):
  File "/opt/hydrus/hydrus/client/ClientController.py", line 2079, in THREADBootEverything
    self.InitModel()
  File "/opt/hydrus/hydrus/client/ClientController.py", line 964, in InitModel
    HydrusController.HydrusController.InitModel( self )
  File "/opt/hydrus/hydrus/core/HydrusController.py", line 545, in InitModel
    self.db = self._InitDB()
  File "/opt/hydrus/hydrus/client/ClientController.py", line 214, in _InitDB
    return ClientDB.DB( self, self.db_dir, 'client' )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 327, in __init__
    HydrusDB.HydrusDB.__init__( self, controller, db_dir, db_name )
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 225, in __init__
    self._InitDB()
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 429, in _InitDB
    self._InitDBConnection()
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 458, in _InitDBConnection
    raise HydrusExceptions.DBAccessException( '"{}" seems to be read-only!'.format( db_path ) )
hydrus.core.HydrusExceptions.DBAccessException: "/home/score/.local/share/hydrus/db/client.db" seems to be read-only!

v468, 2022/01/07 07:56:08: boot error
v468, 2022/01/07 07:56:08: A serious error occurred while trying to start the program. The error will be shown next in a window. More information may have been written to client.log.
v468, 2022/01/07 07:56:09: boot error
v468, 2022/01/07 07:56:09: Traceback (most recent call last):
  File "/opt/hydrus/hydrus/client/ClientController.py", line 2079, in THREADBootEverything
    self.InitModel()
  File "/opt/hydrus/hydrus/client/ClientController.py", line 964, in InitModel
    HydrusController.HydrusController.InitModel( self )
  File "/opt/hydrus/hydrus/core/HydrusController.py", line 545, in InitModel
    self.db = self._InitDB()
  File "/opt/hydrus/hydrus/client/ClientController.py", line 214, in _InitDB
    return ClientDB.DB( self, self.db_dir, 'client' )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 327, in __init__
    HydrusDB.HydrusDB.__init__( self, controller, db_dir, db_name )
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 225, in __init__
    self._InitDB()
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 429, in _InitDB
    self._InitDBConnection()
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 458, in _InitDBConnection
    raise HydrusExceptions.DBAccessException( '"{}" seems to be read-only!'.format( db_path ) )
hydrus.core.HydrusExceptions.DBAccessException: "/home/score/.local/share/hydrus/db/client.db" seems to be read-only!

v468, 2022/01/07 07:56:09: doing fast shutdown…
v468, 2022/01/07 07:56:09: shutting down gui…
v468, 2022/01/07 07:56:09: shutting down db…
v468, 2022/01/07 07:56:09: saving and exiting objects
v468, 2022/01/07 07:56:09: cleaning up…
v468, 2022/01/07 07:56:09: shutting down controller…
v468, 2022/01/07 07:56:09: hydrus client shut down
```

**Comment by ScoreUnder** [comment]
Notably, the FileIsWriteable/DirectoryIsWriteable functions do a lot of work, including requiring ugo+r (all users may read) permissions which may not be desirable to the user. Generally on linux the user can set their default permission set through the `umask`, and on many systems this is `002` or `022` by default (which results in files that can be read by everyone but written only by the owner and group, or only by the owner, respectively). My umask is set to `077` on login,  which makes files readable and writeable only to me by default unless they are explicitly changed. This seems to have interacted poorly with Hydrus because now it is looking to see if other users are allowed to access the hydrus db before it tries to open it.

The standard way to check if a file or directory is writeable is `os.access(path, os.W_OK)`, although checking permissions may not give the full story so reporting the error at the point that it happens (i.e. failed to open for writing) is the most reliable. On linux, you might also want to check X_OK on directories (it's the permission for actually entering the directory and using the files within, rather than just adding and removing files from it).

I'm going to patch the XXXXXIsWriteable functions in the AUR package for now because the only reasonable alternative I can see is to put a bunch of `chmod`s in the startup script, making sure the hydrus client db is forced back to u=rw,go=r permissions.

**Comment by ScoreUnder** [comment]
considering linux only, going to patch them out to this:
```
def DirectoryIsWriteable( path ):
    
    return os.access( path, os.W_OK | os.X_OK )
    
def FileisWriteable( path: str ):
    
    return os.access( path, os.W_OK )
```

**Comment by ScoreUnder** [comment]
Note that 0644 permissions are usually only produced by opening a file with mode 0666, then having the umask (of 022) silently strip the two extra writable bits off.

**Comment by hydrusnetwork** [comment]
Damn, thank you. I just got this from a macOS user as well. I cobbled the new test together from my old garbage and messed it up, thank you for the explainer--I will fix this code up for next week and go `os.access`. I am sorry for the trouble!
