### ISSUE TITLE
Implement xvfb so Hydrus' services can be headless

### ISSUE THREAD

**Issue by AE720** [hydrusnetwork/hydrus#1043]
This is a bit different to my previous request of making an interfaceable client in a headless environment. I know that if you set everything up in advance such as your database, API, services and then try running the client in a headless Debian environment, you'll encounter an error relating to not being able to find a display. I discovered that using xvfb, you can run the command:
`xvfb-run /Path/to/Hydrus/client ` and it will run, services included. It's more of a "dirty" way of doing it but it works. I didn't know how hard it would be in QT to ignore a display check or to embed a solution such as what I discovered.

**Comment by hydrusnetwork** [comment]
Hey, thank you for this. Unfortunately I think I am not expert enough in X11 to do work on this on my end--I had never heard of xvfb before--so I don't think I could do a good job at this.

My current plan is to slowly refactor much of the code to decouple the client GUI from the database and services code so _eventually_ you'll be able to run it with a --headless switch or similar and just control it through the Client API.

If you have luck with this tech though, please let me know how you get on. I will close this issue now, but if you discover a cool way to get the client to work this way and want to write up a document that I can fold into the help for advanced users to do the same, please just let me know.
