### ISSUE TITLE
Trojan in hydrus client exe

### ISSUE THREAD

**Issue by doomsday53** [hydrusnetwork/hydrus#1045]
Windows is claiming that there's a severe trojan inside version 470"s client.exe
I'm using windows 11 and downloaded the install version

**Comment by QueenHek** [comment]
False positive, as usual. Micro$oft is nothing but techno-satanism.

**Comment by doomsday53** [comment]
I guess I'll just have to take your word for it. Strange how its apparently a known one and it wasnt like that in the previous version. It still triggered it but it wasn't severe so i just ignored it.

**Comment by Zweibach** [comment]
https://hydrusnetwork.github.io/hydrus/help/getting_started_installing.html#anti_virus
It happens every single version for the last...well, quite a while now. You've just been lucky that Windows has figured out that it's not a virus by the time you get to it.
