### ISSUE TITLE
 Ability to tell POST /add_urls/add_url to follow gallery urls (and behave as normal search) when given first page of a gallery

### ISSUE THREAD

**Issue by sttollgrin** [hydrusnetwork/hydrus#1046]
Currently API endpoint POST /add_urls/add_url supports gallery urls but only seems to be downloading first page, it would be nice to be able to (optionally) tell hydrus to follow found gallery subpages (and basically behave as search).

ie.: right now submitting url like 'https://safebooru.org/index.php?page=post&s=list&tags=1girl' will download all files from the first page (40 files) and then stop, I would like to be able to tell the downloader to for example continue extracting subsequent gallery urls until it hits some limit.

**Comment by Zweibach** [comment]
That's working as intended. The endpoint sends the URL to an URL downloader page which is made to just grab what it gets, not pursue further queries. For that you want gallery downloader. #350
