### ISSUE TITLE
Impossible to add new tag setting shortcuts to tag services other than 'downloader tags'

### ISSUE THREAD

**Issue by PurpleAzurite** [hydrusnetwork/hydrus#1048]
### Hydrus version

470

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Installed from aur on archlinux

### Bug description and reproduction

When adding new (keyboard) shortcuts for flipping a tag on or off on an item, the program defaults to downloader tags, regardless of what tag service is chosen in the menu. It is effectively impossible to add new shortcuts to other tag services (eg. my tags) atm.

### Log output

```text
no relevant log output
```

**Comment by Zweibach** [comment]
It seems to work as intended on Windows 10, installer.

**Comment by PurpleAzurite** [comment]
This issue does not exist. It only happens due to a specific window manager's misbehavior.
