### ISSUE TITLE
better tag subscription

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#105]
i think the subscription system needs rework.
i think we should be able to sub to a tag across multiple sites under one rule, instead of creating one rule per site like we have to do now.

the list also should contain checkboxes for choosing the sites the sub will pull from. 

also, subs should stop searching if it finds more than a few pages it already has (meaning that the user prob has the rest of the pages aswell)
like this issue here: https://github.com/hydrusnetwork/hydrus/issues/76

that way the user can sub to more tags as they want without having it searching all the pages each time it does something.... something that takes time away from the program where it could be used to get new data instead of old.

there should also be a setting per sub that lets people turn on or off the auto stop downloading function if they want to make sure they have everything from that tag.

i also thing the tag sub should support more than one tag aswell, as many sites might use different tags and so on, we should be able to search for all the tags we want under one sub rule so the differences in tags used doesn't matter.

**Comment by HASJ** [comment]
The amount of bandwidth wasted on both sides downloading multiple duplicated images on multiple boorus makes me want cry just thinking about it.

**Comment by KriPet** [comment]
You could download a list of hashes for each page first and alternate between sources.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
