### ISSUE TITLE
QOI 

### ISSUE THREAD

**Issue by ImportTaste** [hydrusnetwork/hydrus#1051]
[QOI](https://github.com/phoboslab/qoi) is a new lossless image format that boasts far smaller filesizes and significantly faster decoding speed. Converting back and forth between the formats is pretty easy. There are bindings/implementations for it in just about every language you can think of. A simple python wrapper can be found [here](https://github.com/kodonnell/qoi).

Converting downloaded PNGs to QOI on-the-fly would be a wonderful option to have both for storage and for overall performance when scrolling through a gallery. When exporting, Hydrus could offer the option to export the image as PNG or QOI.

It supports alpha, and I believe it supports quantized colorspaces (aka RGB8), though it does not yet support Gray8, nor do I think there are any plans to support animation (so Hydrus would need to make sure it's not APNG).

**Comment by Zweibach** [comment]
Add the first paragraph of your post here to #261, the rest is irrelevant.

**Comment by ImportTaste** [comment]
> Add the first paragraph of your post here to #261, the rest is irrelevant.

The only reason I made the feature request in the first place was for the potential performance improvements. If that's irrelevant then nevermind.
