### ISSUE TITLE
Hydrus looking for wrong version of MPV dll on Windows

### ISSUE THREAD

**Issue by nveaa1** [hydrusnetwork/hydrus#1053]
### Hydrus version

v472a

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

MPV is reported as not available on a fresh extraction of Hydrus Network (i.e., not extracted over a previous version of Hydrus Network) on Windows 10.  In Help --> About, the error shows that the program is indeed looking for mpv-1.dll but the version included with Hydrus is mpv-2.dll. If I copy mpv-1.dll into the Hyrdus Network directory from v471, the mpv version shows in the about screen.

The about screen reports v472 as the version, but it is extracted from Hydrus.Network.472a.-.Windows.-.Extract.only.zip.

**Comment by QueenHek** [comment]
Dev is aware of it and working on it right now.

**Comment by Zweibach** [comment]
Fixed in 472b
