### ISSUE TITLE
Moving Files Between Pages Within a Page of Pages Places Files in New Top-Level Page

### ISSUE THREAD

**Issue by GoAwayNow** [hydrusnetwork/hydrus#1054]
### Hydrus version

v472b

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

1. Have files on pages within a page of pages
2. Try to move a file from one page to another

At this point, the file appears in a new "files" page at the end of top-level tabs. Reproducible, happens every time.

[Bug in action.](https://youtu.be/JgYzY82Uhiw)

**Comment by CatPlanet** [comment]
Can confirm;
DnD-ing files within boundaries of pages-of-pages will automatically "eject" those files to the top row. That seriously limited what I can do now with Hydrus given I use PoP extensively.

**Comment by GoAwayNow** [comment]
For now, the best way to deal with this is to pull the page you want to put something on into top level, move things to it, then move the page back to the page of pages.

**Comment by CatPlanet** [comment]
v473, it works now
