### ISSUE TITLE
Unable to Close Page of Pages

### ISSUE THREAD

**Issue by GoAwayNow** [hydrusnetwork/hydrus#1055]
### Hydrus version

v472b

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

When right-clicking a page-of-pages tab, the only options are 'new page' and 'append sessions' when empty, with an additional 'pages' menu when pages exist.

![2022-02-03 (1)](https://user-images.githubusercontent.com/56808771/152476563-260f5a40-fd06-43a2-a017-7f9bef7170c0.png)

![2022-02-03 (2)](https://user-images.githubusercontent.com/56808771/152476727-8e1b2e76-1b13-49ef-9dae-8c42c51f7cc7.png)

**Comment by CatPlanet** [comment]
You can still close page-of-pages if this page isn't active, but yeah, it's annoying.

**Comment by roachcord3** [comment]
You can't close a page-of-pages if you have a different page-of-pages open. Any page-of-pages being open means you can't close any of them, it seems.

**Comment by GoAwayNow** [comment]
> You can still close page-of-pages if this page isn't active, but yeah, it's annoying.

Confirmed, PoPs can be closed while another page is active.
![2022-02-05](https://user-images.githubusercontent.com/56808771/152635212-89514a00-724c-4078-9e99-99a3f4bc0a23.png)
![2022-02-05 (1)](https://user-images.githubusercontent.com/56808771/152635214-fcb298d4-226e-448e-a7dc-ce00e5c324b6.png)

**Comment by CatPlanet** [comment]
v473, it works now

**Comment by GoAwayNow** [comment]
It do.
![2022-02-14](https://user-images.githubusercontent.com/56808771/153845012-34b5b8dd-fb35-4385-9099-514e16e6cc88.png)
