### ISSUE TITLE
DeviantArt file extended_fetch skip noentrythumb-200.png

### ISSUE THREAD

**Issue by GoAwayNow** [hydrusnetwork/hydrus#1058]
DeviantArt is honestly such a load. This API just spits out totally random shit sometimes. Case-in-point, very rarely, the section that usually contains flash or pdf urls will contain "https:\/\/st.deviantart.net\/misc\/noentrythumb-200.png". Adding the regex match `^(?!https:\/\/st\.deviantart\.net\/misc\/noentrythumb-200\.png$).*$` will prevent this file from being downloaded. This piece is an example of the problem: (Warning: [Furry inflation](https://www.deviantart.com/liliacmoonda/art/Comm-Darling-1-906238123))

That said, it's possible that this can be handled by simply moving lowering the priority of this url, but that could also cause thumbnails to be downloaded instead of actual files. It's also possible that this section isn't even used anymore. Problem is, I don't know of any urls to test.

**Comment by GoAwayNow** [comment]
Eh... this should be marked "bug", shouldn't it? Fuck.

**Comment by Zweibach** [comment]
Upcoming update to default parser might fix this. If not give dev a fixed parser.
