### ISSUE TITLE
command palette bugging out on ESC

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1060]
### Hydrus version

473

### Operating system

Windows other (specify in comments)

### Install method

Installer

### Install and OS comments

Windows 7

### Bug description and reproduction

1. Click image
2. Ctrl+P
3. Press ESC

widget window looks empty, error message pops up, every other attempt to show up palette ends with runtime error and nothing more

### Log output

```text
v473, win32, frozen
AttributeError
'NoneType' object has no attribute 'widget'
  File "hydrus\client\gui\QLocator.py", line 518, in finish
    self.clear()
  File "hydrus\client\gui\QLocator.py", line 632, in clear
    self.deleteAdditionalItems()
  File "hydrus\client\gui\QLocator.py", line 646, in deleteAdditionalItems
    self.resultLayout.takeAt(titleIndex + k).widget().deleteLater()

v473, win32, frozen
RuntimeError
Internal C++ object (QLocatorResultWidget) already deleted.
  File "hydrus\client\gui\ClientGUIShortcuts.py", line 1193, in eventFilter
    shortcut_processed = self._ProcessShortcut( shortcut )
  File "hydrus\client\gui\ClientGUIShortcuts.py", line 1133, in _ProcessShortcut
    command_processed = self._parent.ProcessApplicationCommand( command )
  File "hydrus\client\gui\ClientGUI.py", line 7289, in ProcessApplicationCommand
    self._locator_widget.start()
  File "hydrus\client\gui\QLocator.py", line 509, in start
    self.clear()
  File "hydrus\client\gui\QLocator.py", line 629, in clear
    it.setVisible(False)
```

**Comment by CatPlanet** [comment]
It also happens when I type (for example) "select" and choose "not selected"
```
v473, win32, frozen
AttributeError
'NoneType' object has no attribute 'widget'
  File "hydrus\client\gui\QLocator.py", line 616, in handleResultActivated
    if closeOnSelected: self.finish(True)
  File "hydrus\client\gui\QLocator.py", line 518, in finish
    self.clear()
  File "hydrus\client\gui\QLocator.py", line 632, in clear
    self.deleteAdditionalItems()
  File "hydrus\client\gui\QLocator.py", line 646, in deleteAdditionalItems
    self.resultLayout.takeAt(titleIndex + k).widget().deleteLater()

```

**Comment by LustWolf** [comment]
I'm not having this issue on Win10 (portable or installed).
You can do what you want, but I'd recommend migrating from Win7 since it's End of Life with more and more recent software breaking on it.

I guess as a test for now you could try downloading a clean portable version and doing a quick test to see if it gets the same errors.

**Comment by hydrusnetwork** [comment]
Thank you for these reports. The guy who put the palette together has rolled out a new version that should, fingers crossed, fix this bug for tomorrow. Also adds mouse support. Let me know if you still have any trouble.

**Comment by LustWolf** [comment]
@hydrusnetwork  Awesome, can't wait!
BTW, don't mind all the requests I put out for the command palette, I just noticed no one else had put anything in for some cool features and wanted to get a jump start. I'm certain it's being developed quite a bit 😄

**Comment by CatPlanet** [comment]
I would definitely request some features if not for this pesky bug, for sure ;)
This palette reminds me of IDE feature and even subdues constant pain of not having dedicated shortcuts for selecting inbox/archive items (so I could use keyboard only, finally).
