### ISSUE TITLE
[Idea] Use symbollic links to make sequential viewing more compatible with external viewers

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#107]
Given how the DB works, with files spread among hundreds of folders, external viewing becomes a nuisance since programs will open the exact file in the folder and next/previous won't work.
Would creating a new folder with symbollic links for the selected files in the client be done with that?
I'm still researching on a way to do that and will post later.

**Comment by ScoreUnder** [comment]
In feh, you can do this by simply specifying the images in the right order on the command line. It also accepts a file list, for if it's too long to go into one command line.

Other image viewers will of course behave differently. You can't pass a directory to a lot of image viewers, and if you have a web browser set as your default image viewer you can really only pass one at a time.

If this is implemented then, it should probably be as an option for how to launch the image viewer (with directory / with multiple files / with file list / with single file)

**Comment by sttollgrin** [comment]
IrfanView uses something similar: `i_view32.exe /filelist=d:\files.txt`, the file contains, in each line, a name of an image file, including the full path.

It would be great if we could specify command to use for "open externally" action, with the ability to use filelist path in that command.

**Comment by Link-Satonaka** [comment]
I too brought this up when first starting to use hydrus. Once you actually feel comfortable with hydrus, you'll realize this isn't really necessary. Beside that, there is no real clean or satisfactory way to implement this.
Under Windows, symbolic linking requires UAC elevation, whereas hardlinking does not. So hardlinks MUST be used, at least for Windows. But...
- that's extra code that needs to be separately maintained for Windows and not linux/mac, 
- we run into the limitations of hardlinks in the face of hydrus' new feature of databases that are not on the same drive
- we run into issues with remote files (both the client/server and SAMBA remote features)

The dev might be able to implement it, but it will never work well, it will probably make maintaining the versions harder, it likely won't ever fully support all the features, and consider my first point- it's not actually necessary at all.

Exporting a list of files is about all that can be done neatly, imo. Most image viewers support reading files lists from a stream or text document.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
