### ISSUE TITLE
Duplicate Filtering Conditions not updating from initial on close

### ISSUE THREAD

**Issue by Aegis43615** [hydrusnetwork/hydrus#1079]
### Hydrus version

v474

### Operating system

Windows 11

### Install method

Extract

### Bug description and reproduction

Noticed it when I jumped a few versions to v473, not sure when introduced. Basically any updated filtering conditions aren't updating on a duplicate filter page that I've had open for months with at least 10 exclude conditions. I also tried this on a new client and seems repeatable.
1. Open duplicate processing page
2. Add any filter conditions
3. Close and reopen Client
4. Change/add more filter condition
5. Close and reopen Client
6. Note that the filter conditions didn't update from the initial ones you put in

**Comment by hydrusnetwork** [comment]
Thank you for this report. This should be fixed for this week's v475. Please let me know if you have any more trouble with it!
