### ISSUE TITLE
dark theme?

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#108]
could we get a dark theme?
we can change the colors of the tags, the thumbnail squares, tag background aswell as the background of the image viewer.
but we cannot change the main management window, for example the toolbar on top (file, view and the tabs and so on).
we can't change the background behind the thumbnails either when navigating the program.

am i missing something here and its supported or isnt it there. i feel there is alot of settings here but not for the largest spaces in the program.
- reasons why darkmode is good:
- better for when its dark in the room so the screen isnt so bright.
- makes the image or whatever you want to look at pop more.
- light pollution isnt such a big thing when most of it is dark (when windows are white it pollute the eye space and makes things not as color perfect and so on).
- alot of people already use darkmode for most of their other programs aswell so it will be used.

**Comment by pokeball99** [comment]
maybe we can have an css like system for themes for it,like 4chan

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
