### ISSUE TITLE
Download support for Idol Complex?

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#109]
It is still sankaku chan
https://idol.sankakucomplex.com

**Comment by AreFinstad** [comment]
just copy over the settings from sankaku and you are good to go. 
i did just that when i saw you post and it works just fine with tags and everything (ofc you have to copy all the settings over) 

![](http://i.imgur.com/MuAbcsH.png)


on note to the dev: you could add this as an officially supported booru tho :D would make it easier for people.

**Comment by HASJ** [comment]
Thanks, I forgot about that.

**Comment by HASJ** [comment]
@AreFinstad Do you have any idea would I make Hydrus scrape the [Photo_set](https://idol.sankakucomplex.com/tag?commit=Search&name=&type=5&order=date) namespace? I tried tag-type-photo_set and it did not work (same for the [Medium](https://idol.sankakucomplex.com/tag?commit=Search&name=&type=8&order=date) and [Meta](https://idol.sankakucomplex.com/tag?commit=Search&name=&type=9&order=date) namespaces).
It feels like Hydrus is actively trying to not add them...

**Comment by AreFinstad** [comment]
did you figure it out for the series tags and so on?
i noticed you asked about that but i didnt have internet for the day.... back now tho XD

**Comment by HASJ** [comment]
I actually did get it right the first time, just had to start a new download page for it to work.

**Comment by AreFinstad** [comment]
mhm thats right. a new download tab has to be made for changes to be in effect. i dont think this should be needed tho as it doesnt allow people to change settings on the fly while downloading from that site.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
