### ISSUE TITLE
Downloading files do not obey a network pause if connection drops

### ISSUE THREAD

**Issue by Malfunktion-issues** [hydrusnetwork/hydrus#1095]
### Hydrus version

475

### Operating system

Windows other (specify in comments)

### Install method

Extract

### Install and OS comments

Windows 8.1

### Bug description and reproduction

1. Download a file (larger files or from a slow source are best to catch it)
2. Pause network activity while the file is being downloaded
3. Drop your connection (I.E. switch VPN servers)
4. The URL import status will announce it lost connection and will redownload the file as normal despite the network pause

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am sorry for the trouble. I have it set in next week's release to wait on 'all network traffic is paused' after a connection problem. It shouldn't reattempt the job as long as traffic is paused. Please let me know if you have any more trouble.
