### ISSUE TITLE
left and right arrow to move through tabs in page of page

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#1096]
Ok, I just got a tourbox and I have been playing around with if finding different uses for different programs
now I never really noticed that if I press the tabs and then left or right it cycles through them, I thought that this was useful, so I went to a page of page tab that is kind of really bloated with tabs, pressed left and right, but it only cycles top level tabs

is there any way to bring that tab cycling down to page of page, and from there whatever tab level is clicked while still letting left and right when clicking a thumb move through the thumbnails?

**Comment by hydrusnetwork** [comment]
Hey, there is no 'nice' support here, but if you hit shift+tab several times on a page you should be able to move the current widget focus backwards and up through the page tabs above your current one, and then you can use arrow keys or ctrl+tab and ctrl+shift+tab to navigate the current row.

**Comment by alidan** [comment]
> Hey, there is no 'nice' support here, but if you hit shift+tab several times on a page you should be able to move the current widget focus backwards and up through the page tabs above your current one, and then you can use arrow keys or ctrl+tab and ctrl+shift+tab to navigate the current row.

It's not perfect, it's a little laggy to switch in between tabs at least when nothing is loaded in, but its nicer when things are off screen to do it this way than needing to hold the button, once I let something get out of hand again I will be able to give it a good test to see how much of an issue anything is, but this works. 

If I could suggest an improvement for this, possibly not having the tabs, when tabbed though like this, load immediately would probably help with lagginess of moving between tabs this way.

anyway, thanks for letting me know this command existed.
