### ISSUE TITLE
Strange issue with thumbnails vanishing

### ISSUE THREAD

**Issue by ghost** [hydrusnetwork/hydrus#11]
This is not at all priority, but: I've been having some issues with thumbnails that I can't figure out.

Specifically, when viewing a large search of local files, I can scroll just fine and thumbnails will load, up to a point (said point is between a few hundred and a few thousand images, depending on factors I'm not sure of, but the length of time the client has been open is possibly involved). After that point, not only will new thumbnails not load, but old thumbnails will disappear and not show up when scrolling back, and even the other UI elements of the search grid (the pale frames, the namespace overlays) will disappear. I'm left with a blank white view, which is scrollable normally, and if I click anywhere within it the image that should be there appears in the preview pane and can be acted on, but the thumbnail for it still doesn't load.

F5ing the view resolves this temporarily, and everything appears normal until I scroll too far down again.

This doesn't seem isolated to a specific subset of images; it can happen with anything as long as there are enough search results. I've tried with "memory reserved for thumbnail cache" as low as 50 and as high as 1024 mb, and it doesn't seem to make a difference. I've also completely regenerated the thumbnails (though I'm not sure that worked, since it terminated much earlier than I thought given its rate of progress). This is all on a Win7 x64 desktop machine with 8gb of RAM and an i5-4670. Thumbnail size is set to 200x200.

Again, not a priority, but it can get irksome, so I'm more than happy to troubleshoot/fuck with stuff to try to resolve it, if you have any ideas on what I might do.

**Comment by disposablecat** [comment]
Still happens in 142. No half-cut-off row this time.

Haven't tried a big import yet. None planned for the time being, but I'll update if I do one.

**Comment by disposablecat** [comment]
Hadn't tested for a while, I've just been filtering, but after upgrading to 144 today it still happens. Sorry!

**Comment by disposablecat** [comment]
Persists across uninstall/reinstall, except now I'm getting the half-cut-off row again.

**Comment by hydrusnetwork** [comment]
I'm clearing up my old github issues, so I'm closing this, assuming it is fixed now. If not, please reopen!
