### ISSUE TITLE
AUR install of Hydrus crashes on startup, using Manjaro Linux

### ISSUE THREAD

**Issue by WilliamFakespear** [hydrusnetwork/hydrus#1101]
### Hydrus version

477-1

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Hydrus installed from AUR using pamac-manager, operating system is Manjaro Linux

### Bug description and reproduction

I attempt to open Hydrus for the first time today, but it didn't open, and I tried launching it through the terminal, and I got an error which was what showed up in my Hydrus crash log. Hydrus keeps having the same crash when attempting to start it (even after rebooting my computer, I get the same crash; tried reinstalling Hydrus from pamac-manager, still crashes; tried installing other optional dependancies for pyside 2, still crashes). If I'm not mistaken, I believe pyside, 2 or 6, I can't remember, just updated; i'm not sure if that caused it. I copypasted the contents in my hydrus_crash.log into the log output section. 

EDIT: even after hydrus update, still doesn't work. Did some research online, and I am still completely clueless as to how to fix this.

EDIT2: after some other updates on my computer, Hydrus just started working again. Sadly still don't understand what went wrong or how to get around it if the issue happens again.

### Log output

```text
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qtpy/__init__.py", line 210, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hydrus/hydrus/hydrus_client.py", line 23, in <module>
    from hydrus.client.gui import QtPorting as QP
  File "/opt/hydrus/hydrus/client/gui/QtPorting.py", line 23, in <module>
    import qtpy
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/qtpy/__init__.py", line 216, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

**Comment by Zweibach** [comment]
You should probably contact the maintainer for the AUR package.

**Comment by WilliamFakespear** [comment]
> You should probably contact the maintainer for the AUR package.

Well, after another couple programs updated, included one that had to do with python, Hydrus just mysteriously started working again. But thanks for the suggestion; I'll contacting the maintainer of the AUR package next time an issue like this pops up.
