### ISSUE TITLE
Files stay selected even when deselected

### ISSUE THREAD

**Issue by DisasterInbound** [hydrusnetwork/hydrus#1105]
### Hydrus version

477

### Operating system

Windows 10

### Install method

Extract

### Install and OS comments

Version 21H2

### Bug description and reproduction

1. Select a file and while holding the SHIFT key use the arrow keys on keyboard to select files
2. Backtrack using the opposite arrow to de-select a file
3. The files stay selected and they are still counted as selected files.

Video posted on Discord: https://discord.com/channels/207629417290268672/207631384276107264/941128888594104371

**Comment by DisasterInbound** [comment]
Also I'm not sure if its related to this same issue but I wanted to also mention another behavior that I think is weird (coming from a Windows user at least)
If there are multiple files selected but I decide to deselect all and select only 1 file, I have to select a file outside of the selected group because If I click a file from within the group, all the files stay selected.

**Comment by hydrusnetwork** [comment]
Thank you for this report. The video was helpful. The hydrus selection logic is a bit bleh, I agree. I sort of hacked it together out of nothing, and it doesn't behave like Explorer etc...

The main thing I have tuned it for is when making a selection over time, for instance scrolling down several pages of thumbs picking out one or two here and there, and I didn't want a regular click to lose the whole selection. A regular click on selected stuff just moves the preview focus.

I think the best thing I should do here is add a bunch of options so people can configure it how they prefer. As I work through some more shortcuts overhaul I expect this will happen naturally. That said, in the meantime I agree that if you are doing a shift-select and you go 'back', it should really deselect.

I have updated the selection logic to 'undo' a selection if you go back. It will also some clever 'undo' deselect, where if a shift select goes over some files here and there that were already selected, if you undo that large selection, it will remember what was previously selected and not deselect them. Please give this a go in the next version and let me know if it is confusing or helpful.
