### ISSUE TITLE
similar search from rightclick image/thumb should show the edit UI

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#111]
similar search from rightclick image/thumb should show the edit UI for editing hammer value number on the fly.
right now if you want to edit a number its a pain, you have to first search with the standard one to get the hash number (as you cant just rightclick to copy hash) and then create a new tag search with the copy of the hash code and then set the search value.
would be better to be able to have a setting to either let us have the window show up to input the search value with the hash code already in place. 
and also have an option to change the standard search value.

ofc i have seen that you plan to do a more final dupe manager later, but i think this might have some uses aswell. 

![](http://i.imgur.com/TEbjKYg.png)

**Comment by AreFinstad** [comment]
to note on this, would be also great to be able to either double click or right click the search input of a similar search to edit the hammer value right there and then. that way users can change the value on the fly without doing a new search on a new tab.

![](http://i.imgur.com/4qQOa1r.png)

adding a way to add more than one of these similar searches to a search would be perfect tho, to say search for a hash with more than one hammer value at a time as they might give different results. 

then again, nothing beats a full database similar search tho.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
