### ISSUE TITLE
Client API: CBOR for binary file import

### ISSUE THREAD

**Issue by Trivernis** [hydrusnetwork/hydrus#1110]
The current method of opting into CBOR doesn't work with the way binary files are imported.
The binary import is a POST request to `add_files/add_file` with a `Content-Type` header set to
`application/octet-stream` to differentiate it to the request providing a path for import to the same endpoint.
As CBOR can only be turned on for POST by using the `Content-Type` header, CBOR is currently only
supported for the path-based import on that endpoint.
To support CBOR for binary file import responses I could think of two solutions

- allowing opt-in via the cbor url parameter on POST requests (same as GET)
- adding an `Accept` header to signify which response content type should be served

**Comment by Trivernis** [comment]
To add more context:
I'm the author of the `hydrus-api` rust crate (library) and put JSON and CBOR support behind a feature gate. Removing all instances of JSON parsing would allow me to get rid of all JSON dependencies of this crate (when the JSON feature is not chosen) which would improve compile times and binary sizes.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I think `Accept` header is probably the right solution here. We should probably take that for any request and let you override what response you get, CBOR or JSON, while still defaulting to answering in whatever you requested in.
