### ISSUE TITLE
Nijie Parser Fails to Grab Video

### ISSUE THREAD

**Issue by FatRatCock** [hydrusnetwork/hydrus#1113]
### Hydrus version

479

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

When supplying default nijie page parser with page id or id's containing videos, the parser fails to download entirely and instead ignores the post.

This applies to both the standard nijie.info parser and the pop-up view parser. 

### Log output

```text
The parser found nothing in this document, nor did it seem to be an importable file!
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am sorry I was late getting to it. I think I have this fixed for 483 next week.

I am not familiar with the site, so while I fumbled my way through the japanese and found some mp4s to test with, I may have missed something. Please let me know if there is any more trouble.
