### ISSUE TITLE
Consider adding hydrus-api-rs to the list of hydrus api libraries

### ISSUE THREAD

**Issue by Trivernis** [hydrusnetwork/hydrus#1115]
As you are already mentioning the python and node.js wrapper in the API docs I'd like to ask if you could also add the [hydrus-api-rs](https://github.com/Trivernis/hydrus-api-rs) api wrapper for rust to the list which I am maintaining.
It currently supports direct calls to the API via the given endpoints but also operations on objects representing hydrus entities to provide some abstraction.

**Comment by Zweibach** [comment]
Dev accepts pull requests for the documents
