### ISSUE TITLE
Flatpak/appimage package

### ISSUE THREAD

**Issue by animaldaydream** [hydrusnetwork/hydrus#1117]
On the dawn of "unbreakable" Linux distros like Fedora Silverblue/Kinoite and SteamOS 3, some users of Hydrus will need a Flatpak package as it is the only way to install applications on those systems. Besides appimages, of course.

Either of those would be useful. Anybody would use those?

**Comment by Zweibach** [comment]
Anybody is free to create third-party distributions as they like.

**Comment by UAYmZy8A** [comment]
Packaged everything for Flatpak and Hydrus is now available on Flathub : https://flathub.org/apps/details/io.github.hydrusnetwork.hydrus (x86_64 only for now)

Source repo : https://github.com/flathub/io.github.hydrusnetwork.hydrus (README has info about passing args like --db_dir)

If that's fine for you I'll send a PR to update the hydrusnetwork.github.io documentation to include a link to flathub. I will wait a few days tho, to make sure everything is running fine. 

It's still fresh so if you use it, please backup everything before.
