### ISSUE TITLE
Clicking on any UI element that isn't a button in the dupliates viewer skips to the next image

### ISSUE THREAD

**Issue by Trivernis** [hydrusnetwork/hydrus#1119]
### Hydrus version

480

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Arch Linux 5.17.2-zen3-1-zen
Hydrus installed from the AUR

### Bug description and reproduction

1. Add some duplicates to your hydrus client
2. Search for duplicates and open the duplicates viewer
3. Click on the background of the duplicates menu -> Viewer skips to the next file
4. Click anywhere on the image -> Viewer skips to the next file

This makes managing duplicates harder as missing the button and clicking on the background skips to the next image. You are also unable to zoom into the image and move it to focus on details that might be different in each duplicate. If this is defined behaviour please provide a way to turn it off.

**Comment by Zweibach** [comment]
Update your Hydrus before making a bug report.
