### ISSUE TITLE
Improvement upon #94: Show query in download queue status, mockup inside

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#112]
![fileimportimprovmockup](https://cloud.githubusercontent.com/assets/9345660/11411665/66eb0aba-93b9-11e5-988f-eacc70101625.png)
Pretty self-explanatory. That would let you identify what is what when you have 40k links on your queue or just 50.
#94

**Comment by AreFinstad** [comment]
should also be combined with this IMO: https://github.com/hydrusnetwork/hydrus/issues/98
aswell as being able to remove links that we highlight, finished, failed & already in db alike.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
