### ISSUE TITLE
Tags not correctly selectable when you scroll.

### ISSUE THREAD

**Issue by schneckenschnabel** [hydrusnetwork/hydrus#1120]
### Hydrus version

481

### Operating system

Linux (specify distro and version in comments)

### Install method

Running from source

### Bug description and reproduction

Clicking On a tag in any tag window when you scrolled a bit, makes the tag selection jump, roughly the same amount. HArd to explain in words, here some images.

No scrolling, selecting the last visible tag, everything works.
![normal](https://user-images.githubusercontent.com/14168/163389290-206de9fd-edba-4c80-86a3-aec8fc50411e.png)

scrolling down by ~2 lines, selecting the exact same tag (high heel boots), the selection jumps up by two.
![jump](https://user-images.githubusercontent.com/14168/163389391-944b309e-77c6-4674-a0ed-aefc604f6ea4.png)

Seems like the amount of scrolling down determines the amount of tags jumped.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I messed up here during some routine cleanup from some old hacky wx code to Qt. It is fixed for tomorrow and I've added a test to make sure it doesn't slip through again. Sorry for the trouble!
