### ISSUE TITLE
Clicking on the image in the dupliates viewer skips to the next image

### ISSUE THREAD

**Issue by Trivernis** [hydrusnetwork/hydrus#1121]
### Hydrus version

481

### Operating system

Linux (specify distro and version in comments)

### Install method

Extract

### Install and OS comments

Arch linux 5.17.2-zen3-1-zen
Hydrus run from the latest github release

### Bug description and reproduction

1. Add some duplicates to your hydrus client
2. Search for duplicates and open the duplicates viewer
3. Click anywhere on the image -> Viewer skips to the next file

Zooming into an image and dragging it is not possible in the duplicates viewer due to this behaviour.

**Comment by Zweibach** [comment]
Hold shift before you click and drag, I don't think it's documented anywhere so it's easy to miss. Scrollwheel is intended behaviour, there's keybind options for zooming.

**Comment by Trivernis** [comment]
> Hold shift before you click and drag, I don't think it's documented anywhere so it's easy to miss. Scrollwheel is intended behaviour, there's keybind options for zooming.

@Zweibach Why is the behaviour different from the default image viewer?

**Comment by thatfuckingbird** [comment]
Probably for fast switching between images for easier comparisons? Better ask the dev if you really want to know.

**Comment by Trivernis** [comment]
@thatfuckingbird It's not switching between both images detected as duplicates but just skips to the next pair of duplicates so I don't think that's the case.

**Comment by Mengmoshu** [comment]
Actually, it sounds like you're setting the viewed image as better. The default shortcut for that in the dupe filter is left click.

Which is also why left click doesn't work for dragging the image around, since it at least partially conflicts.

**Comment by Trivernis** [comment]
> Actually, it sounds like you're setting the viewed image as better. The default shortcut for that in the dupe filter is left click.
> 
> Which is also why left click doesn't work for dragging the image around, since it at least partially conflicts.

@Mengmoshu Ah thanks that makes sense. When was this introduced?

**Comment by Mengmoshu** [comment]
As far as I know this is how the duplicate filter has always worked. That left click shortcut has been this way for the 4-5 years I've been using the program at least.

**Comment by Trivernis** [comment]
> As far as I know this is how the duplicate filter has always worked. That left click shortcut has been this way for the 4-5 years I've been using the program at least.

Probably just me being confused as it also marked the image when clicking on the background of the dialog in the previous version.
