### ISSUE TITLE
Wrong media length in media viewer

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1126]
### Hydrus version

482

### Operating system

Windows other (specify in comments)

### Install method

Installer

### Install and OS comments

Windows 7

### Bug description and reproduction

Imported file from gelbooru ( https://gelbooru.com/index.php?id=4791898&page=post&s=view )
Shows it's 160millis (2 frames, 12fps) while playing media for much longer.

putting this file in ffmpeg (version n4.4.1-20211029):

> ffmpeg -i "C:\Hydrus Network\db\client_files\ff3\f3aeccbd9fa4904bec16d25e5d81f9049503895a150c20949e4d7736a7a8e7b1.gif"
`Input #0, gif, from 'C:\Hydrus Network\db\client_files\ff3\f3aeccbd9fa4904bec16d25e5d81f9049503895a150c20949e4d7736a7a8e7b1.gif':
  Duration: 00:00:03.60, start: 0.000000, bitrate: 3224 kb/s
  Stream #0:0: Video: gif, bgra, 600x600, 12.50 fps, 12.50 tbr, 100 tbn, 100 tbc`

> ffprobe -v error -select_streams v:0 -count_packets -show_entries stream=nb_read_packets -of csv=p=0 -i "C:\Hydrus Network\db\client_files\ff3\f3aeccbd9fa4904bec16d25e5d81f9049503895a150c20949e4d7736a7a8e7b1.gif"
`45`

> ffprobe -v error -select_streams v:0 -count_frames -show_entries stream=nb_read_frames -of csv=p=0 -i "C:\Hydrus Network\db\client_files\ff3\f3aeccbd9fa4904bec16d25e5d81f9049503895a150c20949e4d7736a7a8e7b1.gif"
`45`

To clarify: I imported this file using v477 but it's still showing incorrect length in newest version (no idea if these values are cached or not)

**Comment by stysmmaker** [comment]
This was caused by a bug with Pillow that was recently fixed as of the [latest release](https://github.com/python-pillow/Pillow/releases/tag/9.1.0) which was 20 days ago (I suspect python-pillow/Pillow#6077 resolved it). The last few releases of Hydrus have had this fix, so right-clicking the file and navigating to **manage** -> **regenerate** -> **file metadata** should update the duration to the correct one.

**Comment by CatPlanet** [comment]
Regenerating metadata works so problem shouldn't occur for new files.
Thanks for your detective work @stysmmaker, it was a good read. Have a nice day!
