### ISSUE TITLE
Separate media storage location(s) based on a tag / query

### ISSUE THREAD

**Issue by Senju-vilis** [hydrusnetwork/hydrus#1128]
We can already add another storage location, however instead of adjusting weight like we do now, we could pass a tag or query and every media that fit's that query, would get moved / stored in that location.

This would be **very** useful to me for backing up the core of my Hydrus media collection, which is about 2,5TB. 
As it stands, I have to manually export them, which requires more effort, time and disk space. With query based media location it would be as simple as pointing the path to Restic or similar.

Now to decide on what to do, when a file fits multiple query based locations. 
Lets say you have set up two locations, one based on query  'clothing:none' and other one on 'shadow the hedgehog -shadow'. You have several files fitting both queries, do they get 
a) moved only to one location, or 
b) copied to both.

'A' would require some kind of hierarchy on which a certain location has higher priority and 'B' might require for exact duplicates to be allowed (in case it's a problem, I don't know how it works). 
Both options could be useful.

**Comment by Zweibach** [comment]
The planned implementation of #338 will allow something like this.
