### ISSUE TITLE
filename regex does ignore filenames with hyphenation in them. 

### ISSUE THREAD

**Issue by AreFinstad** [hydrusnetwork/hydrus#113]
filename regex does ignore filenames with hyphenation in them. 
that is the built in filename regex:
(?<=\\)[\w\s]*?(?=\..*$)

for some reason every filename that has a hyphenation - in it  will be ignored by the regex. ofc people have filenames with those in them when they import, it doesnt work at all when its in them tho for some reason.

**Comment by hydrusnetwork** [comment]
Thank you. I think \w only matches alphanumeric and underscore, so it only does simple filenames. Try:

`(?<=\\)[^\\]*?(?=\..*$)`

Which should match anything except \.

I will update this in the code for next week.
