### ISSUE TITLE
After installing the latest build (v. 482) windows defender is reporting Win32/Uwamson.A!ml and Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by re3me** [hydrusnetwork/hydrus#1134]
### Hydrus version

v482

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

After installing the latest build (v. 482) windows defender is reporting Win32/Uwamson.A!ml and Win32/Wacatac.B!ml as trojan

**Comment by hydrusnetwork** [comment]
Thank you for this report. Although I can never be certain, this is very likely a false positive. Please read more here:

https://hydrusnetwork.github.io/hydrus/getting_started_installing.html#anti_virus
