### ISSUE TITLE
Highlight Importer Criteria on the Importer Page

### ISSUE THREAD

**Issue by ytypo123** [hydrusnetwork/hydrus#1135]
When using the lots of subscriptions the title bar page name becomes unreadable due to the amount of pages.

Requesting a way to show which subscription is being presented somewhere on the left or top independent of the page title.

My first thought was to show which tags the subscription queries similar to how tags are shown in the upper left on the file page after a tag is searched for. 

Perhaps just adding the subscription name to a box above the taglist would work too.

**Comment by Zweibach** [comment]
Options > GUI pages > When there are too many tabs blablabla
Turn that option off.

**Comment by ytypo123** [comment]
Totally works!. Thanks!
