### ISSUE TITLE
Further data into a part of #96: Background/foreground issues

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#114]
#96

> EDIT: BTW, you know when you click a background window and Windows play that sound telling you that something else is on foreground? That's what that happens when the GUI does this hang and I click on it. Weirdly enough, the traceback messages are still clickable and can be closed as normal, with a right click.
> ---

It seems the client main window was indeed in the background and I do not know how that happened nor how to fix it.
![tagmaninvisibleforeground](https://cloud.githubusercontent.com/assets/9345660/11424698/85e2f9dc-9436-11e5-9056-2b932890ec74.jpg)

But this is what is actually displayed
![mainwindowbackgroundfocus](https://cloud.githubusercontent.com/assets/9345660/11424744/d3f5c3a2-9436-11e5-83d5-902523e0a5ec.jpg)

And the traceback messages aren't clickable anymore.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
