### ISSUE TITLE
Shortcut to immediately zoom to max

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1141]
I noticed that there are shortcuts to zoom in, out, and switch between 100% and canvas fit. But there does not seem to be an option to zoom to the maximum level that the client can do. I would like that as an option.

**Comment by hydrusnetwork** [comment]
Thank you, this should be in for tomorrow's release as several new actions in the shortcuts system. Let me know if you have any trouble with it!
