### ISSUE TITLE
IndexError in dupe filter after skipping a pair

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1143]
### Hydrus version

483

### Operating system

macOS 11 "Big Sur" (Intel)

### Install method

Running from source

### Install and OS comments

I recently upgraded from 480 to 483. This problem has never occurred before, so my guess is that something in 481-483 has introduced a bug.

### Bug description and reproduction

I am not sure if it has to be particularly this number of files, or this series of actions exactly, or if there's some wiggle room, but here's what happened if I recall correctly:

1. started the dupe filter, with 16 potential pairs and 12 presented in the filter
2. marked 10 files as dupes
3. skipped the 11th pair, making this screen appear:

    <img width="353" alt="hydrus_client_media_viewer" src="https://user-images.githubusercontent.com/73802796/167742897-5621b851-5112-446e-8a5f-213b6f370d0b.png">
4. marked the 12th pair as a dupe and tried to commit; nothing happened in the UI, but an IndexError was logged in the console
5. tried to close the window, which brought the commit dialog back up
6. committed, this time it worked
7. loaded up the filter again (this time with 4 potential pairs and 2 pairs shown in the filter)
8. marked the 1st pair as a dupe
9. skipped the 2nd pair
10. committed just fine

My guess is that the problem is related to where the skipped pair is in the list.

### Log output

```text
v483, 2022/05/10 16:51:52: Uncaught exception:
v483, 2022/05/10 16:51:52: IndexError
list index out of range
  File "/Users/me/hydrus/src/hydrus/client/gui/ClientGUIShortcuts.py", line 1223, in eventFilter
    shortcut_processed = self._ProcessShortcut( shortcut )
  File "/Users/me/hydrus/src/hydrus/client/gui/ClientGUIShortcuts.py", line 1163, in _ProcessShortcut
    command_processed = self._parent.ProcessApplicationCommand( command )
  File "/Users/me/hydrus/src/hydrus/client/gui/canvas/ClientGUICanvas.py", line 3540, in ProcessApplicationCommand
    self._CurrentMediaIsBetter( delete_second = True )
  File "/Users/me/hydrus/src/hydrus/client/gui/canvas/ClientGUICanvas.py", line 2874, in _CurrentMediaIsBetter
    self._ProcessPair( HC.DUPLICATE_BETTER, delete_second = delete_second )
  File "/Users/me/hydrus/src/hydrus/client/gui/canvas/ClientGUICanvas.py", line 3259, in _ProcessPair
    self._ShowNextPair()
  File "/Users/me/hydrus/src/hydrus/client/gui/canvas/ClientGUICanvas.py", line 3454, in _ShowNextPair
    self._ShowNextPair() # there are no useful decisions left in the queue, so let's reset
  File "/Users/me/hydrus/src/hydrus/client/gui/canvas/ClientGUICanvas.py", line 3432, in _ShowNextPair
    while not pair_is_good( self._batch_of_pairs_to_process[ self._current_pair_index ] ):
```

**Comment by hydrusnetwork** [comment]
Thank you for this excellent report. This is the same issue as #1139 and I think I have it fixed in tomorrow's 484. I messed up something when the filter wants to auto-skip at the end of a batch. I am sorry for the trouble, and please let me know if you still have any problems in 484.

**Comment by roachcord3** [comment]
Ok, I'll close this since it's a dupe. I definitely checked the list to make sure someone hadn't already reported this, but I guess I'm blind 😭
