### ISSUE TITLE
Nitter Downloader will miss some but not all video files

### ISSUE THREAD

**Issue by manwithakeyboard** [hydrusnetwork/hydrus#1144]
### Hydrus version

484

### Operating system

Linux (specify distro and version in comments)

### Install method

Extract

### Bug description and reproduction

Use Nitter media lookup on a twitter page with videos
Most will be grabbed but looking back over the feed shows some will not
Viewing the posts that are not grabbed in a browser has an "Enable HLS playback" button before playback begins, posts that were grabbed successfully did not

example of a not working as intended post: https://nitter.net/SkashiArts/status/1512912438206865408
example of working as intended post: https://nitter.net/SkashiArts/status/1518311873669734400

possibly relevant?: https://github.com/zedeus/nitter/issues/326
Nitter/Twitter downloaders might need a fix of some kind to automatically enable HLS playback so downloading behavior is consistent.

### Log output

```text
https://nitter.net/SkashiArts/status/1512912438206865408
Could not find a file or post URL to download!
```

**Comment by Zweibach** [comment]
The twitter parser has no issue downloading the link that does not work for you. I strongly suggest you either switch over fully or configure so the twitter parser is used in place of the nitter one.
I will attach an URL class that will simplify the process. It converts a nitter url like you would get from your subscriptions into a twitter url so the default twitter parser downloads it.
It might be possible to fix the nitter parser but there's little value in spending the time when a functional alternative already exists especially when Hydrus can't interact with websites in a manner that's required for an easy fix here.
![nitter to twitter](https://user-images.githubusercontent.com/10709426/169653783-cbb323c3-cf8a-4352-9af1-b10553536772.png)
