### ISSUE TITLE
Images have broken gamma

### ISSUE THREAD

**Issue by SlashGit** [hydrusnetwork/hydrus#1148]
### Hydrus version

470

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

Some images that I import have their gamma values completely scuffed, both in the thumbnail view and in full using native viewer
The result is that some dark colored images end up in high exposition and extremely bright
Only looks that way in the client, choosing to view the image in external program or the source folder has no issues

I'm not sure what makes it happen, maybe the client thinks the image is an incorrect gamma value and tries to correct it, but just ends up completely borking it

It's not a big issue since this only happens to a very small percentage of images, but it's a little annoying
To replicate, try to import this image (NSFW) and see what happens
https://files.catbox.moe/jio1km.png

**Comment by Zweibach** [comment]
You're fifteen versions out of date.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I have been working on improving support for images with ICC Profiles in recent months, and I _think_ this may be an instance of this. When I import that image into my dev client, it seems to render ok (or at least the same as Firefox shows it), and it reports having an ICC Profile, so I hope if you update, you will get support here.

I put in some automatic file maintenance routines in the update code to schedule all your files for a scan-and-fix, but if you want to hurry that along to check the images are fixed, find some that look incorrect, and then right-click on the thumbnails and go _manage->regenerate->file metadata_ and _->thumbnails_.

Let me know if you have any more files that show wrong!
