### ISSUE TITLE
Windows finding Trojan and Deleting Client.exe

### ISSUE THREAD

**Issue by BlubParadox** [hydrusnetwork/hydrus#1159]
### Hydrus version

v487

### Operating system

Windows 10

### Install method

Installer

### Install and OS comments

I've never had this happen with an install of hydrus before, I updated to v484 before this and it was just fine, I don't know why Windows Defender is suddenly having an issue with v487.

### Bug description and reproduction

1. Install v487 via Windows Installer
2. Attempt to let it open Client.exe
3. Windows Defender detects Wacatac.B!ml
4. Windows Defender deletes Client.exe

**Comment by Zweibach** [comment]
https://hydrusnetwork.github.io/hydrus/getting_started_installing.html#anti_virus
