### ISSUE TITLE
Improve identifier Naming and locations

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#1162]
This will be a very long lived issue, hydrus has thousands of function identifier let along other members and locals.  Generally hydrus is undergoing continuous rework, as dev modernizes it, and these are some practices which could greatly improve the quality of the structure and descriptiveness of identifiers.

### Boolean predicates
Sometimes functions that only return true/false begin with the "Is", "has", or "can" predicates, which I think is best stylistically.  Other times, not so much.

https://github.com/hydrusnetwork/hydrus/blob/a39462c4bc4d63302ce8e03bdf80441e72e503fb/hydrus/core/HydrusThreading.py#L72

https://github.com/hydrusnetwork/hydrus/blob/a39462c4bc4d63302ce8e03bdf80441e72e503fb/hydrus/core/HydrusThreading.py#L214

https://github.com/hydrusnetwork/hydrus/blob/a39462c4bc4d63302ce8e03bdf80441e72e503fb/hydrus/core/HydrusThreading.py#L338

### Event Handlers
Event handlers in Hydrus currently basically never begin with `On` as in `_OnFilterCancelled` and look like a boolean getter.
The below are called On event happened, they do not actually answer the question of whether or not a job or filter was cancelled
https://github.com/hydrusnetwork/hydrus/blob/a39462c4bc4d63302ce8e03bdf80441e72e503fb/hydrus/core/HydrusThreading.py#L619
https://github.com/hydrusnetwork/hydrus/blob/a39462c4bc4d63302ce8e03bdf80441e72e503fb/hydrus/core/HydrusThreading.py#L454

### Symbol location
Python can emulate enums using classes.  Nesting these classes in the class to which they are important allows their purpose to be understood, as opposed to just putting them all in the global namespace.
https://stackoverflow.com/questions/30376127/is-it-a-good-practice-to-nest-classes

The same can be said of simple class constants, although python cannot do static class variables (but it can bind such variables to the closure of the module) .python also just treats as object attributes as it is a [prototyping language](https://en.wikipedia.org/wiki/Prototype-based_programming) (basically ever instance is a copy of a dictionary represented by the class definition, not an uninitialized schema represented by the class definition.
https://www.digitalocean.com/community/tutorials/understanding-class-and-instance-variables-in-python-3

### Capitalization
Identifiers are pretty much inconsistent program wide.   In the same class you can have functions that are CamelCased and Pascal Cased

https://github.com/hydrusnetwork/hydrus/blob/a39462c4bc4d63302ce8e03bdf80441e72e503fb/hydrus/core/HydrusThreading.py#L167
https://github.com/hydrusnetwork/hydrus/blob/a39462c4bc4d63302ce8e03bdf80441e72e503fb/hydrus/core/HydrusThreading.py#L172

## Mitigation
The first and most obvious step to make this code easy to read for contributors is to add return type hints, and parameter type hints.  Then even if you picked names that aren't great, it is easy to establish the purpose of a function or variable without a lot of rename refactoring.

```py
def JobCancelled( self ) -> None :
```
This shows that this symbol is not a getter, and lets IDE tools like Intellisense infer purpose when there is ambiguity.  It also makes completion faster because such tools can stop at the declaration instead of trying to inspect the function's call trace to figure what it could return.

**Comment by Zweibach** [comment]
You've been told before to talk code with dev on discord, not open issues for them.

> The first and most obvious step to make this code easy to read for contributors is to add return type hints

Dev still doesn't accept PRs for code.
