### ISSUE TITLE
v487 Client.exe is detected as a virus

### ISSUE THREAD

**Issue by NdymBzyd** [hydrusnetwork/hydrus#1168]
### Hydrus version

v487

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

Windows security quarantines the file automatically after install

Trojan:Win32/Wacatac.B!ml

This never happened with previous versions.

**Comment by Zweibach** [comment]
https://hydrusnetwork.github.io/hydrus/getting_started_installing.html#anti_virus
