### ISSUE TITLE
Can't pan animated gifs when the mouse is within the image area

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#117]
When viewing animated GIFs in the internal viewer, they can't be panned with the mouse while the mouse is within the image area.

**Comment by hydrusnetwork** [comment]
Thank you. This is fixed for next week.

BTW: At the moment, holding a modifier (Shift/Ctrl/Alt) will let you drag an animation without changing its pause/play status. This is similarly true for any sort of file when filtering your inbox, where a left or right click would normally trigger keep/delete.
