### ISSUE TITLE
Font Size in Media Viewer Unchanged

### ISSUE THREAD

**Issue by Red-Bean-Soup** [hydrusnetwork/hydrus#1173]
### Hydrus version

488

### Operating system

Windows 11

### Install method

Installer

### Bug description and reproduction

I changed the font size in the QSS under QWidget.  However, the font size of the tag list in the media viewer when not hovered over is unchanged
![Animation](https://user-images.githubusercontent.com/69950720/173199536-3be70d6a-7196-4da5-bbda-56864b2cc311.gif)
![Animation](https://user-images.githubusercontent.com/69950720/173199541-5a31d723-5ca8-46f7-9415-8efa07ce85c5.gif)
.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I think I have this fixed for tomorrow's release, and the text banners on thumbnails should be fixed too. Please let me know if you have any more trouble!
