### ISSUE TITLE
Downloader for twibooru.org

### ISSUE THREAD

**Issue by dergness** [hydrusnetwork/hydrus#1180]
This would be pretty equal to derpibooru. In fact it is based and branched of an older version of the API:
[Twibooru api-docs](https://twibooru.org/pages/api)

https://twibooru.org/api/v3/search/posts?q=safe&page=1

Similarly to derpibooru there's a unfiltered Everything filter: `filter_id=2`.

The reason this one should be added is because it's less limited than derpibooru.

**Comment by floogulinc** [comment]
See the community run repo for additional downloaders. There is already one for twibooru there. 

https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts
