### ISSUE TITLE
Minor graphical glitch when closing a page

### ISSUE THREAD

**Issue by ketsuban** [hydrusnetwork/hydrus#119]
When closing the currently active page, there's no problems. When closing a page that is currently inactive, I get some junk left in the tab bar—looks like the nontext portions of the tab itself. It seems to be harmless, but it's a little scruffy-looking.

**Comment by hydrusnetwork** [comment]
Thank you for this report. If you don't mind answering:

What OS are you using? Which version?
If you have some junk in your tab bar and you minimise then restore the window, is it still there?
How about if you resize the window a bit?
How about if you go _undo->closed pages->clear all_?

**Comment by Ketsuban** [comment]
OS is Linux (Ubuntu 15.10), version is 184.
Minimising the window doesn't cause the junk to go away, but resizing the window does.
Clearing all closed pages doesn't clear the junk.

**Comment by ScoreUnder** [comment]
Can confirm this also happens to me

![animation](https://r.kyaa.sg/vwrzzo.gif)

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
