### ISSUE TITLE
flake8 found a typo

### ISSUE THREAD

**Issue by shadownetdev1** [hydrusnetwork/hydrus#1192]
### Hydrus version

490

### Operating system

Linux (specify distro and version in comments)

### Install method

Extract

### Install and OS comments

Pop OS 22.04

### Bug description and reproduction

Running "flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics"
on Hydrus returned
"./hydrus/client/db/ClientDB.py:11394:44: F821 undefined name 'e'
                HydrusData.PrintException( e )"

The reason for this error is that line 11390 is "except:" when it should be "except Exception as e:"

**Comment by hydrusnetwork** [comment]
Thank you, this is fixed for tomorrow's release!
