### ISSUE TITLE
Duplicate processing page forgets last "search immediately" setting

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1193]
### Hydrus version

v490

### Operating system

Windows other (specify in comments)

### Install method

Installer

### Install and OS comments

Windows 7

### Bug description and reproduction

"search immediately" defaults to "true" every client restart, which makes me wait extra several seconds first time I enter duplicate processing page (SAD!)

**Comment by hydrusnetwork** [comment]
Thank you for this report. This is fixed for tomorrow's release. Let me know if you have any more trouble!
