### ISSUE TITLE
Option to ignore certain tag repositories when collecting

### ISSUE THREAD

**Issue by TheCommandoChicken** [hydrusnetwork/hydrus#1195]
Currently you can blacklist certain namespaces from specific repositories so they don't appear on the files, but this has no effect on how they are collected, meaning that when "collect by title" is turned on, you'll still end up with files being collected from PTR titles like "untitled", which is very inconvenient if you're someone like me who uses titles to keep file groups organized.

**Comment by Zweibach** [comment]
Copy of #572
