### ISSUE TITLE
UnboundLocalError when trying to set 3 or more files as alternates

### ISSUE THREAD

**Issue by boobayayo** [hydrusnetwork/hydrus#1199]
### Hydrus version

492

### Operating system

Windows 11

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

scoop install

### Bug description and reproduction

When trying to set any **3 or more** files as alternates via 
_right click > manage > file relationships > set relation > set all selected as alternates_ 
the error message comes up. 
I do not get the yes/no confirmation dialog and no alternates are being set.

Doing the same thing on 15 or more files gives me the "Are you sure?" dialog and everything seems to work.

Pairs of two files also work fine.

Setting as potential duplicates or "this file as better than [...]" also works for any number of files.

### Log output

```text
v492, win32, frozen
UnboundLocalError
local variable 'message' referenced before assignment
  File "hydrus\client\gui\ClientGUIMenus.py", line 213, in event_callable
    callable( *args, **kwargs )
  File "hydrus\client\gui\pages\ClientGUIResults.py", line 2368, in ProcessApplicationCommand
    self._SetDuplicates( HC.DUPLICATE_ALTERNATE )
  File "hydrus\client\gui\pages\ClientGUIResults.py", line 1853, in _SetDuplicates
    result = ClientGUIDialogsQuick.GetYesNo( self, message, yes_label = yes_label, no_label = no_label )
```

**Comment by CatPlanet** [comment]
Windows 7, installer: same thing

**Comment by hydrusnetwork** [comment]
Thank you for this report, this was a stupid typo and is fixed for tomorrow's release. Sorry for the inconvenience!
