### ISSUE TITLE
ipfs integration

### ISSUE THREAD

**Issue by pokeball99** [hydrusnetwork/hydrus#120]
I know you have already briefly talked about this on the 8chan board, but I just want to put this as an issue on here as well. Also, how exactly would it be implemented, would it replace the whole client/server that is already in hydrus and be more p2p like how you planed it originally(based on change log),or something else

**Comment by hydrusnetwork** [comment]
Thank you for this. I will add IPFS to the soon-to-come voting list of new things to add.

I will start by adding it as a new service under manage/review services and try to run it like any other file domain. I hope to be able to get files from and send files to that domain, just like you might a file repository, although the exact details of how that file cache is populated and maintained is something I'll have to figure out once I understand IPFS better.

Anyway, it'll be an optional addition. If the client can't find a wanted file on a file repository, it'll check IPFS, that sort of thing.

**Comment by pokeball99** [comment]
will there be an option of weither it want to be in the "public" ipfs hash link or "private" ipfs link?

**Comment by ScoreUnder** [comment]
@pokeball99 does ipfs make a distinction between those? I haven't used it too extensively but I never found a way to make things public/private.

**Comment by pokeball99** [comment]
@ScoreUnder no, but i was kinda thinking about how we have the public tag repo/read old only repo, so  i was thinking of if he was going to do that as well, and since it would not take any space (unless you wanted to pin them to your own daemon) it would be implmented that way

**Comment by pokeball99** [comment]
@hydrusnetwork i assume this can be closed? or is there more you want to add? a little todo list in your first comment would be nice for that if the latter is the case

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
