### ISSUE TITLE
Changing one rating on multiple files will change all ratings.

### ISSUE THREAD

**Issue by thefloattube** [hydrusnetwork/hydrus#1207]
Whenever I change a 1 rating for multiple files, it will actually reset the other rating systems I have on those files. I will include an example to help explain.

![image](https://user-images.githubusercontent.com/96643521/182499430-ba3a4fce-e2ff-4dbb-88bc-f0742b546513.png)
So right now, these files are all a 0/4 for rating 1, they all have different values for rating 2. If I change the value for rating 1 to 1/4 and hit apply, it will set rating 2 to 0/5

![image](https://user-images.githubusercontent.com/96643521/182499515-7cb8fa41-910a-4f45-b1a2-5ad5661ffe88.png)

**Comment by bbappserver** [comment]
This is more a feature request than a bug.

The dialog represents the **absolute setting** of a rating on the selection, not the change of modified fields. 
When you have multiple elements selected hydrus believes you want to set all values in all of them to the value shown in the dialog.
I don't think that the behaviour for reading a rating from a multi-select is even defined, it probably just yoinks the value from the first one.

It sounds like you want rating to be more granular in multi-editing mode, is that correct?  And if so do you want to be able to pick between the current setting of overwriting all fields, or should there perhaps be a checkbox to indicate which fields should be overwritten?
