### ISSUE TITLE
regenerate thumbs are broken when using another client_files folder

### ISSUE THREAD

**Issue by AreFinstad** [hydrusnetwork/hydrus#121]
so the regenerate thumbs are broken when using another client_files folder than the one in the install location.

i just moved my database to my SSD and it boots up alot faster now it seems.
but when i want to regen the thumbs (might as well i thought) it looks for files inside my install location (where the client_files are not located at all ATM).

plz look into this.

Traceback: 
WindowsError
[Error 3] The system cannot find the path specified: u'D:\\Programs\\Hydrus\\db\\client_files\\ae\\*.*'
Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusThreading", line 233, in run
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUI", line 1529, in THREADRegenerateThumbnails
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientCaches", line 370, in IterateAllFilePaths
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientCaches", line 310, in _IterateAllFilePaths
WindowsError: [Error 3] The system cannot find the path specified: u'D:\\Programs\\Hydrus\\db\\client_files\\ae\\*.*'

**Comment by hydrusnetwork** [comment]
I cannot reproduce this error. If you don't mind, in what order did you do the steps to move your database to your ssd? For instance, did you go:

Move client_files to location on same/different hdd.
Move everything else to ssd.
Boot client, set up external location as location on hdd.

If you load and scroll through a few hundred files, making sure you load them in the media viewer, do they all load correctly, or do they give errors?

And if you go _file->options->file storage locations_, does it say the correct folder there? Is the drive letter correct?

If that is all correct, and you go _database->maintenance->rebalance file storage_, does it say 'All folders balanced!', or does it do some 'moving' or 'recovering' work beforehand?

**Comment by AreFinstad** [comment]
seems my database or something is really messed up ATM after doing a move of the install.
i still have my DB and my client files but they are not seen by the program at all eventho the settings for the folder is pointing to where the images are.
all i want is to have my database and install on my SSD's where i can more quickly access it and more quickly back things up while having the actual content on a slower HDD.

i dont care about loosing my Database to be fair, only important thing i dont want to loose is my download queues as i dont even recall which tags i have on queue there and i have worked down a huge list with it.
question while you are here: is the download queues and tabs saved in the main database file or somewhere else? if not, could that be split up at one point?

**Comment by AreFinstad** [comment]
seems like my small test to move things back to the folder in my edit fixes adding the files, now i have more issues with moving relocating the files are forcing it seems to only work once and every time i try after that tells me all files are moved...... yet they are not.
i suggest that doing a force move with the "rebalance file storage" button should try to do that the best it can no matter if the user did that just a few min ago. im unsure if that button will work again or not to be fair.

**Comment by AreFinstad** [comment]
im closing this issue as for me i dont have the issue anymore. i guess ill make another issue if something comes up again.

tho take note, work queue and tab states should be saved on another file IMO aswell as have multible backups made of it from time to time IMO.
the database is not that big if a loss as you always have the files anyway unless you lose the drive. the download queue and so on is a much larger problem to loose as you have no oversight over it at all ATM.
