### ISSUE TITLE
Interface too small

### ISSUE THREAD

**Issue by SU042002** [hydrusnetwork/hydrus#1211]
### Hydrus version

494

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

Is there a way I can increase the font size for this program? It's very hard to read the text. It was working fine other days but there are times when the font is just super zoomed out and unreadable.
![Screenshot 2022-08-12 200659](https://user-images.githubusercontent.com/79118184/184426811-06c58164-e352-4cf1-bead-ecc96274d832.png)

**Comment by floogulinc** [comment]
If your display scaling factor changes you may need to restart hydrus for it to scale correctly again.

**Comment by SU042002** [comment]
> If your display scaling factor changes you may need to restart hydrus for it to scale correctly again.

I don't remember changing anything for my display since yesterday and I have restarted hydra but the text is still too small.

**Comment by floogulinc** [comment]
Please update to the latest version. Looks like you use a scale greater than 100% and that was broken in 494.

**Comment by SU042002** [comment]
> Please update to the latest version. Looks like you use a scale greater than 100% and that was broken in 494 for Qt 6.

Yes, this fixed my problem. As a matter of fact, it looks even better than it did before when it was "working"! It's my first time using the software and the first version I started using was 494. The scaling is definitely better on this version, thank you for your help.
