### ISSUE TITLE
Instant favourite using shortcut

### ISSUE THREAD

**Issue by SU042002** [hydrusnetwork/hydrus#1213]
I tried looking into if this was already available but could not find it, the only thing close to it I could find was opening the manage ratings using the shortcuts. Rather than doing this, is there a way an instant favourite could be implemented? For example, if I have a file already selected, I would like to just press "f" to favourite and unfavourite it rather than opening this manage rating and clicking every time.

**Comment by bbappserver** [comment]
That already exists.
This is assignable from the shortcuts settings menu.

**Comment by SU042002** [comment]
> 

Could you check how you assigned it?

**Comment by bbappserver** [comment]
> > That already exists. This is assignable from the shortcuts settings menu. I know it is because that's exactly what my f key does.
> 
> Could you check how you assigned it?

Look under the `media viewers` category.

**Comment by SU042002** [comment]
> > > That already exists. This is assignable from the shortcuts settings menu. I know it is because that's exactly what my f key does.
> > 
> > 
> > Could you check how you assigned it?
> 
> Look under the `media viewers` category.

I am looking at the media viewers - all category and see nothing to do with favourites

**Comment by SU042002** [comment]
Ok, I have now found it. It's under "media actions, either thumbnails or the viewer". You then add your own custom shortcut. Picture for anyone using that is stuck with this later and can't figure it out.
![Screenshot 2022-08-14 060516](https://user-images.githubusercontent.com/79118184/184523317-9edcbcd5-60d8-41b3-a25b-b850b6a72c07.png)
