### ISSUE TITLE
File lookup script: IQDB Danbooru fails to run

### ISSUE THREAD

**Issue by SlashGit** [hydrusnetwork/hydrus#1221]
### Hydrus version

497

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

When I manage tags for an image and attempt to run this script to fetch tags, it gives out an TypeError
It looks like this
https://i.imgur.com/BKgZbRS.png
https://i.imgur.com/mfeAavQ.png

The other 2 scripts to fetch from MD5 works fine, but not the IQDB one
I've used this feature a lot even though it's not technically supported any more, but I'd really like a fix

Traceback information:
v497, win32, frozen
TypeError
Parse() missing 1 required positional argument: 'collapse_newlines'
Traceback (most recent call last):
  File "hydrus\core\HydrusThreading.py", line 401, in run
    callable( *args, **kwargs )
  File "hydrus\client\gui\ClientGUITagSuggestions.py", line 629, in THREADFetchTags
    parse_results = script.DoQuery( job_key, file_identifier )
  File "hydrus\client\ClientParsing.py", line 3117, in DoQuery
    parse_results = self.Parse( job_key, parsing_text )
  File "hydrus\client\ClientParsing.py", line 3140, in Parse
    parse_results = GetChildrenContent( job_key, self._children, parsing_text, self._url )
  File "hydrus\client\ClientParsing.py", line 259, in GetChildrenContent
    child_content = child.Parse( job_key, parsing_text, referral_url )
  File "hydrus\client\ClientParsing.py", line 2736, in Parse
    search_urls = self.ParseURLs( job_key, parsing_text, referral_url )
  File "hydrus\client\ClientParsing.py", line 2802, in ParseURLs
    basic_urls = self._formula.Parse( {}, parsing_text )
TypeError: Parse() missing 1 required positional argument: 'collapse_newlines'

**Comment by hydrusnetwork** [comment]
Thank you for this report. Sorry for the trouble! When I recently updated the parsing system to support multi-line parsing for notes, I basically forgot to update this method. It is a stupid typo bug. It should be fixed in v499, so please let me know if you have any more trouble!
