### ISSUE TITLE
Broken rendering in data unit dropdowns in some locations

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1222]
### Hydrus version

497

### Operating system

macOS other (specify in comments)

### Install method

Running from source

### Install and OS comments

I actually run macOS 12.4, which needs to get added to the OS options tbh

### Bug description and reproduction

Some dialogs that let you specify amounts of data/memory with a dropdown for units (e.g. MB, GB) don't render correctly. You can still select the four options and the client will act like nothing is wrong, so this is just a rendering bug.

Here in the speed and memory dialog options you can see that the unit dropdown for the thumbnail cache is messed up, but the ones for the image and image tile caches are not:

<img width="1015" alt="first example screenshot" src="https://user-images.githubusercontent.com/73802796/188515985-3d942dd3-1bfe-440f-bc88-bbef81138fb7.png">

Here in a bandwidth limit dialog you can see what it looks like when you click the dropdown. I decided to use this different dialog because it would show that this happens not just in the speed and memory dialog.

<img width="650" alt="second example screenshot" src="https://user-images.githubusercontent.com/73802796/188515569-e9af7559-5814-4335-aba8-29cb9fc1296a.png">

This also happens in the `system:filesize` search predicate's dialog. It does not happen in the "edit import options" dialog. I can't think of any other dialogs to check for this behavior.

I can't remember which version I was on first when I noticed this was broken, sorry. But I am pretty sure this happened sometime before the Qt6 stuff, because before I upgraded to 497 I was on 493 and this was also still a problem. I thought it was a known issue, but when checking for open issues before opening the next one I'm going to, I found out that this particular UI bug isn't tracked. So, here we are.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am not totally sure why this is happening, but it looks like some QSS styles are causing the comfortable minimum width of that dropdown to be calculated wrong. Seems like the space that would normally be the arrow dropdown icon is overlapping the text. I have bodged it so it gets a bit more minimum space and now see this:

![image](https://user-images.githubusercontent.com/3878678/188760223-90b73b71-3dde-4c4f-b763-fd9bc14fdac2.png)

![image](https://user-images.githubusercontent.com/3878678/188760500-b09e482d-c53a-46da-a269-15a23b9bb80f.png)

This isn't an excellent answer, but I think it will do for now. Let me know if it still looks bad in macOS!

**Comment by Zweibach** [comment]
This bug is by now almost two years old. #721
