### ISSUE TITLE
Poor wording in "speed and memory" options

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1223]
### Hydrus version

497

### Operating system

macOS other (specify in comments)

### Install method

Running from source

### Install and OS comments

macOS 12.4

### Bug description and reproduction

The option says "MB memory" but you can choose memory units. It's a good thing that you can choose units, so all that needs to change is the phrasing of the option. Example:

<img width="718" alt="manage_options" src="https://user-images.githubusercontent.com/73802796/188515238-3b354d80-80f0-4dc3-8089-803d8707e6ef.png">

Note: there's a known bug (#1222) with some of the memory unit dropdowns on where they don't render their contents. I temporarily chose GB here instead of MB so that you could see that my 2000 number was obviously producing a prediction result that wouldn't make sense if it was MB.

It's also like this for the image and image tile caches–they say "MB memory" but you can choose memory units.

While I'm here, I'd also like to complain that you can't choose memory units for the video buffer. Seems like an oversight–not sure if it's worth tracking as its own issue or not though. If it is, then I'd probably go through the other places where values are stuck in MB.

**Comment by hydrusnetwork** [comment]
Thank you for this report! These used to be fixed 'MB integer' widgets like the video buffer setting, and I must have forgotten to update the labels when I converted the option values to the more flexible system.

I have updated the video buffer option to the new system too.

**Comment by hydrusnetwork** [comment]
...and I forgot to update the label for the new video buffer setting the first time around.
