### ISSUE TITLE
Crashing to Desktop upon opening Client Media Viewer

### ISSUE THREAD

**Issue by Chirishman** [hydrusnetwork/hydrus#1234]
### Hydrus version

v499

### Qt major version

Qt 6

### Operating system

Windows other (specify in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Installed via Chocolatey, running on Windows Server 2019

### Bug description and reproduction

1. Open Hydrus Client
2. Double Click on a jpeg or other static image in a Page
3. Hydrus Client Media Viewer briefly pops up, image is not visible
4. Entire Hydrus client crashes to desktop

Also, when opening mp4 or webm videos the Hydrus Client Media Viewer comes up successfully, but video doesn't play and `MPV is not available!` error is displayed back on the main window. Such files will only open externally.

This has occurred after doing an upgrade from 433 to 499 in 10 version increments as is suggested. I can provide that section of the log if desired. I also forced shutdown maintenance after each one.

Nothing useful is visible in the main log except for this one error that happened part way through trying to import a bunch of new files where it crashed to desktop *without* me trying to view a file and some line items about the ongoing syncing with the Public Tag Repository after having not run/synced for over a year and a half.

### Log output

```text
v499, 2022/09/19 21:36:07: Found and deleted the durable temporary database on boot. The last exit was probably not clean.
v499, 2022/09/19 21:36:17: checking database
v499, 2022/09/19 21:36:18: preparing db caches
v499, 2022/09/19 21:36:18: initialising managers
v499, 2022/09/19 21:36:18: booting gui…
v499, 2022/09/19 21:37:00: Exception:
v499, 2022/09/19 21:37:00: JSONDecodeError

Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "hydrus\client\gui\importing\ClientGUIImportOptions.py", line 1769, in _PasteFileImportOptions
    file_import_options = HydrusSerialisable.CreateFromString( raw_text )
  File "hydrus\core\HydrusSerialisable.py", line 144, in CreateFromString
    obj_tuple = json.loads( obj_string )
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

v499, 2022/09/19 21:37:59: hydrus client started
v499, 2022/09/19 21:38:03: booting controller…
v499, 2022/09/19 21:38:04: booting db…
v499, 2022/09/19 21:38:04: Found and deleted the durable temporary database on boot. The last exit was probably not clean.
v499, 2022/09/19 21:38:07: checking database
v499, 2022/09/19 21:38:07: preparing db caches
v499, 2022/09/19 21:38:07: initialising managers
v499, 2022/09/19 21:38:07: booting gui…
v499, 2022/09/19 21:44:59: hydrus client started
v499, 2022/09/19 21:45:04: booting controller…
v499, 2022/09/19 21:45:04: booting db…
v499, 2022/09/19 21:45:04: Found and deleted the durable temporary database on boot. The last exit was probably not clean.
v499, 2022/09/19 21:45:07: checking database
v499, 2022/09/19 21:45:07: preparing db caches
v499, 2022/09/19 21:45:07: initialising managers
v499, 2022/09/19 21:45:07: booting gui…
v499, 2022/09/19 21:47:23: hydrus client started
v499, 2022/09/19 21:47:28: booting controller…
v499, 2022/09/19 21:47:28: booting db…
v499, 2022/09/19 21:47:28: Found and deleted the durable temporary database on boot. The last exit was probably not clean.
v499, 2022/09/19 21:47:31: checking database
v499, 2022/09/19 21:47:31: preparing db caches
```

**Comment by Chirishman** [comment]
Apparently I can also crash it by going to `Options>Media>Set a new mpv.conf on dialogue ok?` and clicking "Browse"

Same absolutely nothing in the log. Please advise.

**Comment by Chirishman** [comment]
Replacing the DLL in the v499 Hydrus install folder does appear to have resolved all of the the crash triggers that I've experienced.

Not sure how that DLL effects simply opening the "Open File" dialog or viewing non-animated images but regardless that DLL does fix things.

**Comment by hydrusnetwork** [comment]
Thank you, I am glad we got you fixed here. This better dll and two fixes for the open file dialog issue are rolled into the latest releases, so closing this now. Let me know if you have any more trouble!
