### ISSUE TITLE
Upgraded from v185 to v186 now Hydrus won't even start.

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#124]
Downgrade to v185 works fine.
There is no log output.
Yes, I'm on a x64 PC.

**Comment by AreFinstad** [comment]
got the same issue here.
try to start it and i get nothing, nothing at all. 
no logs, nothing shows up in the process in windows or anything at all it seems. 
running Win10 Pro 64bit here myself.
also tried different launch modes with compatibility for Win7 and so on aswell.

**Comment by AreFinstad** [comment]
note, seems like a fresh folder fixes this for me. now i just need to try to copy over the database and so on to it tho.

**Comment by misakitchi** [comment]
I have start error too: "pyi_rth_win32comgenpy returned -1"
Don't want to reinstall or DL all my images :(

**Comment by AreFinstad** [comment]
you can always move over the images and database TBH.
tho i have not tested it myself as im unsure what files contain what and so on. my settings and database is the main thing i guess.

**Comment by misakitchi** [comment]
I deleted all files, but db folder. reinstall v186 and now its working! :)

**Comment by HASJ** [comment]
@misakitchi Did the same thing here. Worked.
Was reluctant to doing it because I feared it was going to delete my unfinished queues.

**Comment by misakitchi** [comment]
I just find this:
http://hydrus.tumblr.com/
He say same thing... but why he don't say that in "Download" or "changelog" page?

Did Hydrus have a "config file"?
Because i want to no launch subscriptions automatically or wait 10min and launch it...

**Comment by hydrusnetwork** [comment]
Hey guys, sorry for the short notice on this, and for the bad github release text. I only discovered the 32-bit 64-bit problem when I ran my test install on Wednesday, so I tacked on instructions for the update on my 8chan and tumblr release posts, and I didn't think to mention it in my raw changelog. To make things even more fun, 8chan promptly went down for the upgrade, so tumblr was the only place with correct instructions. The tumblr post is here:

http://hydrus.tumblr.com/post/135347199104/version-186

8chan is back up for now (although their own update didn't go very well either!), and my post is here:

http://8ch.net/hydrus/res/1589.html

I will update my github release post to mention the special update needs.

If this whole thing gave you a fright, start making a backup before you update every week! Then, if the update goes wrong, you can always rollback. There are instructions at the end of this page:

http://hydrusnetwork.github.io/hydrus/help/getting_started_installing.html
