### ISSUE TITLE
Deviantart parser borked

### ISSUE THREAD

**Issue by manwithakeyboard** [hydrusnetwork/hydrus#1245]
### Hydrus version

493

### Qt major version

Qt 5

### Operating system

Linux (specify distro and version in comments)

### Install method

Extract

### Install and OS comments

Fedora 36

### Bug description and reproduction

Fill in Deviantart login details under Network> logins> manage logins
Test login
Deviantart artist lookup
Every result gets a "The parser found nothing in the document, nor did it seem to be an importable file!" and after ~200 requests starts getting 403'd
![bork](https://user-images.githubusercontent.com/87183565/193392437-3ac98be5-86a9-4490-ac43-3a59e70323c1.png)

**Comment by AngusThermo-Pyle** [comment]
This is happening on the extended fetch parser.

"DeviantArt now requires a CSRF token for every request to their Eclipse API"

The folks at gallery-dl appear to have run into the same issue:
https://github.com/mikf/gallery-dl/issues/2983

**Comment by hydrusnetwork** [comment]
Sorry for the trouble here. I had a look but couldn't immediately figure out what I needed to do here. I do not think I wrote the newer API parser, and it doesn't look like current DA uses it behind the scenes either, so I can't talk too cleverly about it. I presume you now attach that token in a header or GET param, but that's stuff the hydrus network engine would strain to dynamically figure out anyway, so I just rolled us back to my old html parser in 501 and it works ok.

Please update and then tell your DA subs to 'retry ignored' and you should be _basically_ back to normal. I think my HTML parser has some trouble in edge cases getting the max available resolution, or in stuff you need to be logged in to get, so if you discover any good examples, please send them to me and I'll see what I can do.
