### ISSUE TITLE
bdsmlr subscriptions not working (both "bdsmlr blog scraper (tags with auth cookies)" AND "bdsmlr username lookup")

### ISSUE THREAD

**Issue by JessicaHelp** [hydrusnetwork/hydrus#1247]
### Hydrus version

v449

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

1. network->manage subscriptions
2. add
3. attempt to add bdsmlr blog
4. hydrus fails. Shows as status "1 working" and last new file time "n/a". hydrus briefly appears to start working in bottom-right after OK dialogue, but downloads no files and shuts down after ~3 seconds

**Comment by Zweibach** [comment]
Third party parser, not a Hydrus issue.
