### ISSUE TITLE
option to delete folder if empty on imports

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#126]
i think Hydrus is missing an option to delete folders on import, we already have options to delete files on import.... why not folders aswell to clear out those empty folders (ofc only an option for those that want to use it)

**Comment by hydrusnetwork** [comment]
That's a great idea, thank you. I will add it to my to-do list.

**Comment by ScoreUnder** [comment]
For this one you can probably just use os.rmdir after doing the deletions: https://docs.python.org/2/library/os.html#os.rmdir

If you didn't delete the last thing in the directory it will throw an OSError, so no need even to check if the directory has anything in it.

I'm thinking something like this after all the deletes are done:

```python
def delete_dirs_of_files(files):
    dirs_to_delete = (os.path.dirname(file) for file in files)  # Cut files down to directory names
    dirs_to_delete = set(dirs_to_delete)  # Remove duplicate dirs
    dirs_to_delete = sorted(dirs_to_delete, key=len, reverse=True)  # Put longer dirs first (so parent dirs get removed after their children)
    for dir in dirs_to_delete:
        try:
            os.rmdir(dir)
        except OSError as err:
            if err.errno != errno.ENOTEMPTY:
                pass  # Put some error here because we failed for some reason other than the directory not being empty
```

I hope that helps - probably didn't, knowing programming and its intricacies but it's worth a shot.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
