### ISSUE TITLE
Twitter syndication api tweet parser recently stopped working, 404

### ISSUE THREAD

**Issue by sockpuppetclock** [hydrusnetwork/hydrus#1268]
### Hydrus version

504

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Installer

### Bug description and reproduction

Starting sometime yesterday (last known success was on Nov 3), the API for the tweet downloader included with the install is 404ing.

Example:
https://twitter.com/takaharashin/status/1588727816400404480 (live)
-> https://cdn.syndication.twimg.com/tweet?id=1588727816400404480 (404 error)

All the example URLs in the twitter syndication api tweet parser 404 now
https://cdn.syndication.twimg.com/tweet?id=1357511772102615045
https://cdn.syndication.twimg.com/tweet?id=1355712967812075522
https://cdn.syndication.twimg.com/tweet?id=1358129751546765313

**Comment by Zweibach** [comment]
Fix to defaults will be rolled out in next version

https://cdn.discordapp.com/attachments/471400633237241906/1038131241708425246/twitter_update_2022-11-04.png

> floogulinc: literally the endpoint changed from https://cdn.syndication.twimg.com/tweet?id=1357511772102615045 to https://cdn.syndication.twimg.com/tweet-result?id=1357511772102615045

**Comment by EttOrm** [comment]
The one with the fix seems to break videos on download
They play for a few frames and then loop back to the beginning

**Comment by Zweibach** [comment]
Most likely unrelated since people have been having trouble with twitter videos for a long time. Some times they work, some times they don't. We just don't know why.
