### ISSUE TITLE
Tool windows (toolbar, tags box) pop into place after being shown in the wrong position

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#127]
![animation](http://i.imgur.com/JTSzu3P.gif)

Arch linux + i3 window manager

**Comment by hydrusnetwork** [comment]
Thank you for this report. Ubuntu (no idea the window manager--whatever is default) was unreliably giving me complete garbage coordinates while trying to arrange hover windows, so they randomly would fly off to (0,0) and stay there. Perhaps you got something like that as well.

In any case, I fixed that bug a few weeks ago with some cleverer positioning logic, but it looks like you are getting a single frame of bad coordinates still. I will look at it.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
