### ISSUE TITLE
Hydrus on Windows spawns new taskbar icon instead of using shortcut

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#1271]
### Hydrus version

v505

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Installer

### Bug description and reproduction

When installed with the installer it creates a start menu shortcut for Hydrus
![explorer_bKEwlOHUAg](https://user-images.githubusercontent.com/1300395/200969941-7e58c937-7fa9-465d-9c0a-8bc61716b243.png)

When you had this pinned to the task bar in previous versions Hydrus would use it when launched. Now it spawns a new taskbar icon instead of reusing the pinned shortcut. 
![r37az9cjZ0](https://user-images.githubusercontent.com/1300395/200970154-38b124e8-5c81-4d7d-ae82-0b8d314d2723.png)

**Comment by hydrusnetwork** [comment]
Thanks, yeah, fixed by #1273 fix. There's probably a magic regex or manifest way of telling windows or the executable what the App Model ID is or whatever to make this all line up correctly, but that's beyond me atm. Turn off for now, since default exe behaviour is fine.
