### ISSUE TITLE
client_running file on split db paths

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1272]
This is a pretty simple request. In addition to the `client_running` file that gets created alongside the main db when the client is running, I would like for a similar file to be created in the root of every path in split db situations.

The user story here is ensuring that the client is not running before performing any automated backups (in my case, `borgmatic`), in a split db using network shares. Checking for the client running helps to prevent any backups from containing corrupt data if they just so happen to be performed at the same time as media is shifting around; this ensures that every backup that passes integrity checks can be assumed to be a valid, usable restore point. In a split db using network shares, the hosts that contain the media but not the client would normally not have an easy, universal way of telling if the client is running. I currently work around this by `ssh`ing to the client machine to check for the `client_running` file, but this is obviously less secure and reliable than simply checking for the file locally.

Not a high priority request, but should also be pretty easy to implement, no?

**Comment by hydrusnetwork** [comment]
I recommend you use the Client API to do this test. Make sure your client is running the API, and then hit up any request, including just the base URL `http(s)://host:port/`, to see if it gives you a response. Also, if you are feeling clever, the Client API actually lets you lock your db while it is running so you can do backups like this:

https://hydrusnetwork.github.io/hydrus/developer_api.html#manage_database_lock_on
