### ISSUE TITLE
MacOS binary: No module named PyQt5

### ISSUE THREAD

**Issue by docchaoswizard** [hydrusnetwork/hydrus#1280]
### Hydrus version

v505

### Qt major version

Qt 6

### Operating system

macOS 12 "Monterey" (Apple silicon)

### Install method

Extract

### Bug description and reproduction

When launching Hydrus via the Bundle (Not CLI) it simply doesn't start, just silently dies. When running via the shell we get the error-messages below. The last known working Version is 504. The `hydrus_crash.log` pretty much contains the same informations. Let me know if you need anything else.

### Log output

```text
/Applications/Hydrus\ Network.app/Contents/MacOS/client
PySide6/__init__.py: Unable to import Shiboken from /Applications/Hydrus Network.app/Contents/MacOS, /Applications/Hydrus Network.app/Contents/MacOS/lib
PySide6/__init__.py: Unable to import Shiboken from /Applications/Hydrus Network.app/Contents/MacOS, /Applications/Hydrus Network.app/Contents/MacOS/lib
Traceback (most recent call last):
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/hydrus_client.py", line 24, in <module>
    from hydrus.client.gui import QtInit
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/gui/QtInit.py", line 45, in <module>
    from qtpy import QtCore as QC
  File "/Applications/Hydrus Network.app/Contents/MacOS/lib/qtpy/QtCore.py", line 15, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'

Critical boot error occurred! Details written to hydrus_crash.log in either db dir or user dir!
```

**Comment by docchaoswizard** [comment]
Just a quick heads up: v506 fixed this issue. Thanks :-)

**Comment by docchaoswizard** [comment]
I was a bit confused yesterday sorry, the issue still persists with v506:

```
PySide6/__init__.py: Unable to import Shiboken from /Users/xxx/Downloads/Hydrus Network.app/Contents/MacOS, /Users/nwinnwa/Downloads/Hydrus Network.app/Contents/MacOS/lib
PySide6/__init__.py: Unable to import Shiboken from /Users/xxx/Downloads/Hydrus Network.app/Contents/MacOS, /Users/nwinnwa/Downloads/Hydrus Network.app/Contents/MacOS/lib
Traceback (most recent call last):
  File "/Users/nwinnwa/Downloads/Hydrus Network.app/Contents/MacOS/hydrus/hydrus_client.py", line 24, in <module>
    from hydrus.client.gui import QtInit
  File "/Users/nwinnwa/Downloads/Hydrus Network.app/Contents/MacOS/hydrus/client/gui/QtInit.py", line 45, in <module>
    from qtpy import QtCore as QC
  File "/Users/nwinnwa/Downloads/Hydrus Network.app/Contents/MacOS/lib/qtpy/QtCore.py", line 15, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'
```

**Comment by hydrusnetwork** [comment]
Thank you for this report, and sorry for the trouble. I have been working on the same issue with another macOS user and have updated the client to report more information for this in tomorrow's release. Please try that and let me know what different message you get, if any!

This is an odd one. Not only is it selecting the wrong Qt library to use, the exact line it is throwing an error on is supposed to be _after_ it found a good Qt to use. Furthermore, there's no obvious difference between v505 and v504's built Qt (PySide6).

If you know how to set such things, you _might_ have luck setting this environment variable:
`QT_API=pyside6`

**Comment by Michael-Bell** [comment]
Running 13.0.1 on an Intel Mac. 

v507 binary crashes with the same error. Running from source works fine when I select 5 or 6 from the `setup_venv.command `

**Comment by docchaoswizard** [comment]
Yep, still crashes. Here are the details:

```
╰─$ /Applications/Hydrus\ Network.app/Contents/MacOS/client
PySide6/__init__.py: Unable to import Shiboken from /Applications/Hydrus Network.app/Contents/MacOS, /Applications/Hydrus Network.app/Contents/MacOS/lib
PySide6/__init__.py: Unable to import Shiboken from /Applications/Hydrus Network.app/Contents/MacOS, /Applications/Hydrus Network.app/Contents/MacOS/lib
Traceback (most recent call last):
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/gui/QtInit.py", line 120, in <module>
    from qtpy import QtCore as QC
  File "/Applications/Hydrus Network.app/Contents/MacOS/lib/qtpy/QtCore.py", line 15, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/hydrus_client.py", line 24, in <module>
    from hydrus.client.gui import QtInit
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/gui/QtInit.py", line 156, in <module>
    raise Exception( message )
Exception: One of the Qt modules could not be loaded! Error was: No module named 'PyQt5'

Of the different Qts, qtpy selected: PySide2 (not selected), PySide6 (not selected), PyQt5 (selected), PyQt6 (not selected). Here is info on QT_API: No QT_API set.

If you are running from a built release, please let hydev know!

Critical boot error occurred! Details written to hydrus_crash.log in either db dir or user dir!
```

The same happens when i set `QT_API=pyside6` (Or any other Qts). My python Version is `Python 3.10.8`, but that shouldn't matter.

Do you need any more informations? Oh by the way, it doesn't matter if i start the client through Rosetta on Apple Silicon or natively on an Intel Mac.

**Comment by KamillaPup** [comment]
I'm having the same issue. Shouldn't it make a call to PyQt6?

**Comment by livyathan** [comment]
This is the crash log using 508:

[hydrus_crash.log](https://github.com/hydrusnetwork/hydrus/files/10135382/hydrus_crash.log)

**Comment by KamillaPup** [comment]
Here is the crash from the 508 fix
[hydrus_crash.log](https://github.com/hydrusnetwork/hydrus/files/10157359/hydrus_crash.log)

**Comment by KamillaPup** [comment]
I just want to confirm that 509 fixed this <3
