### ISSUE TITLE
Requesting feature auto generate tags.

### ISSUE THREAD

**Issue by Yuki-Soul** [hydrusnetwork/hydrus#1287]
Hi i'm new to hydrus,
I just want to request feature to use DeepDanbooru (https://github.com/KichangKim/DeepDanbooru) with hydrus. it is an AI based auto tagging tool to find related tag to images. 

So i think it would be great if in hydrus i can do like,  right-click image, choose 'auto generate tags from selected image', then a menu of generated tags appears, in that menu we can choose to use or edit the generated tags, and select OK to apply the tags. 

I don't know if system like this has already used in hydrus. if there is fell free to tell me :)

**Comment by Zweibach** [comment]
https://gitgud.io/koto/hydrus-dd

**Comment by Yuki-Soul** [comment]
hi thanks for replaying me. after looking at your link i cant figure out how to use it. i had follow installation guide but after it telling me to 'Run pip install . --user in folder.' i dont understand what it is and where i should do it. is it installation is using cmd? also that mean every time i want to generate image, i should run this command?
