### ISSUE TITLE
Store files at multiple locations by balancing the files instead of folders

### ISSUE THREAD

**Issue by trashcand69** [hydrusnetwork/hydrus#1292]
I'm not entirely sure if this would be a good idea or not, but thought I'd make the request anyway to check if it could be done.

Currently Hydrus stores files by splitting up all files into 256 folders depending on the first two numbers of the hash (folders f00-fff).
When using multiple locations it then moves some of those folders to the other locations, meaning there are 256 folders across multiple locations.
This works well enough. However, this also causes a greater chance of a location running out of disk space if you are unlucky and get a lot of hashes that begin with the same numbers.

I'd like it if it was possible to have those 256 folders in each location and then when a new file is imported it is saved to the location with the most amount of free disk space. This would decrease the likelyhood of running out of disk space.

One thing I'm worried about is if there would be a performance hit to check the available disk space. Maybe storing it in-memory and updating it in the background would be a possible solution.
I'm sure this might also cause a performance hit to certain tasks that iterate through the file folders as well.

**Comment by floogulinc** [comment]
This adds a lot of complication to accessing files as well since you either have to keep track of which location each file is in or check each location everytime it's accessed. With a sufficient number of files the hashes should be evenly distributed so I don't think this is really a major issue unless you have a small library.

**Comment by hydrusnetwork** [comment]
Thanks for this thought. It is a good idea, but I don't think I need to do it.

You are right that the reason why I address files by their hash at the moment is for speed and convenience. If I started placing them based on additional metadata like size, I'd have to have a more complicated file storage system. I do plan to have this support in future, in a broader sense, so users can store archive on one drive and inbox in another etc..., but I will keep the basic idea of allocating files according to hashes (I'll just have multiple possible 'f05' style folders a file could go into at that point).

You are also correct that assigning files pseudorandomly to a folder can cause size spikes. If two 500MB files have the same hash prefix, they'll make a bigger folder. However, the pseudorandom assignment of hashes is a very flat distribution (file size has no relation to resulting hash), so as the number of files in your collection increases, the likelihood of large files collecting in one place over another goes _down_. If you have <=256 files, the folder-size distribution is super spiky, but once you have a million files, you have 4,000 files per folder, and things flatten--a large client softens the statistical noise in almost all situations.

Although I sound like a scold, I have to say a healthy computer means keeping a hard drive with a bit of free space. Drives that are 99.8% full are going to lead to all sorts of problems, not just with hydrus. Every drive should ideally be 10% free, with a 5% hard limit. Given the size of hydrus typical files, usually a handful of megs, but even some crazy 3.6GB video or something, we should never be worried that that pushes a hard drive limit now that we regularly have multi-TB drives.

On a side issue, a bigger problem I want to deal with is having those thousands of files per folder. Many OSes start to get slow (access latency) when a folder has 10k+ files in it, so my more pressing issue is to move to a system that can dynamically split the 256 folders into 4096. A new client then might start with 16 folders and bump up automatically. We'll see how it shakes out.

**Comment by floogulinc** [comment]
If you want better control over how disk usage is split between multiple disks I highly recommend [[StableBit DrivePool](https://stablebit.com/) if you're on Windows. It will let you make a virtual drive that stores files on multiple disks and allows more control over how its balanced.
