### ISSUE TITLE
Store file metadata on import

### ISSUE THREAD

**Issue by jamesWalker55** [hydrusnetwork/hydrus#1294]
**Feature request:** When importing files, provide some way of storing that file's metadata in the database, including filename, date modified and date created. E.g. store these in the notes?

This kind of goes against hydrus' philosophy of no filenames, but my files usually contain a lot of useful metadata before importing. This includes filename, date modified, date created.

I'm a new user trying to import an existing folder of images. My existing folder has about 30,000 images (!!!) and each file has their own naming scheme dating back many years, it's impossible to use regex to cover all possible filename structures. I'd like to retain the filenames somewhere so that I can review these in the future and information isn't lost.

**Rationale:**

**Filenames:** A file named `d:\pictures\organised\cat\12357498_p0.jpg` tells me that image is from Pixiv. `d:\pictures\organised\cat\12357498_p0 edited.png` tells me I have edited the image, and it is not the original unedited image.

**Date modified/created:** Related images usually have similar dates, since I download images related to a concept in batches. For example:

```
2022-12-01 cat/01.png
2022-12-01 Persian.jpg
2022-12-01 cat/__original_cat.jpeg
2022-11-30 dog/01.png
2022-11-30 shiba inu.jpg
2022-11-30 dog/3217672_p0.png
2022-11-30 terrier.jpg
```

- From that list, you can deduce there's 2 groups of images, `cat` images and `dog` images
- It's hard to tag these using the filename alone - some `cat` images may not have the text "cat" in the name

**Comment by jamesWalker55** [comment]
> You can already parse filenames and paths into tags. Modified dates are also already added to the db.

Thanks, does having a huge amount of tags (>30,000 tags, 1 per file) affect performance? I'm currently importing files and using the file's full path as a tag, so with this many files it would generate many tags in total.

**Comment by floogulinc** [comment]
Nah, hydrus handles millions of tags no problem. Though it is not ideal to be saving the full path as a tag, it shouldn't cause an issue. You may be able to use regex to get some more useful tags out of your paths and filenames as well.

**Comment by thatfuckingbird** [comment]
> You can already parse filenames and paths into tags. Modified dates are also already added to the db.

That doesn't work in general, since its not case sensitive and filenames/paths can contain characters that tags can't. I'm pretty sure I had an issue open about saving filenames and paths on import but I can't find it now... Maybe I only wanted to open one.

**Comment by jamesWalker55** [comment]
Should I reopen this issue?

**Comment by thatfuckingbird** [comment]
Can't find another issue about this so I think this is a valid request, yeah.
Btw. the modified time is saved (but not the created time for some reason...).

**Comment by Zweibach** [comment]
Hydrus already tracks modified time and full file path saving is already a feature request, see #676. Make a new one for just time created.
