### ISSUE TITLE
save tags from what booru files are from when downloading.

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#130]
i think we need hydrus to add tags to where the file comes from, ofc alot of files will have more than one of these.... but i think its worth it.

so we need two new official namespaces:
site: (or website:) where it would say [booru name here] or something like that.
url: a direct url tag to where the file comes from, you can then build this into the navigation menu where people can rightclick to open a file page in the browser on the site it came from.

this is really useful for sites like ibsearch.xxx talked about here: https://github.com/hydrusnetwork/hydrus/issues/129
that site also got those links contained in its image pages that you can pull from. 

there is many reasons why its good to know where a file comes from and to see what site has what file.
logging something like this in the tags can also be used to update tags at a later date where you can re-add your collection for download/update.
it also might be handy to share this way instead of doing a transfer or look for the file in question again, you could just share the link instead. 

i think this should be added pretty early as more people download to their collection the more links people miss out on and have to go back to get those.

**Comment by HASJ** [comment]
This is something I've been meaning to ask for. I already use the site: namespace but I added it in using the explicit tag feature in the default tag import option menu for every booru. Kind of a chore but can be done quickly, if the user cares enough. It of course is useless if you don't use 'get tags even if file is already on db', which a higher level of this that bypass that would be appreciated.

url: is also very wanted.

**Comment by AreFinstad** [comment]
the tread downloader should also have a thread namespace for the thread name.
like [4chan Thread:[random thread name here]]

that way people can more easily sort the content..... ofc people can always do this manually tho, might be handy tho IMO.

**Comment by HASJ** [comment]
I just had a crazy idea if the url: namespace is ever implemented.
Basically you'd have a backup of the tagged file for as long as the source is online and you're connected to the internet.
You could virtually lose your HD but stil have your files if you had a backup of your database, you could just tell the client to download everything again.

**Comment by AreFinstad** [comment]
yeah, that is what i meant by the line: "logging something like this in the tags can also be used to update tags at a later date where you can re-add your collection for download/update."
in my OP, there would always be an backup of the tags on the booru aswell as being able to update the tags (for when tags are added after the last download you did) at a later date once an url is saved.

**Comment by AreFinstad** [comment]
this is pretty much half done by the looks of it. Hydrus does save the url it gets its files from (only one now tho sadly and not all links) 

well we need is an official URL namespace that auto uses these in someway somehow. we can export the url now. but thats about it. so much more that can be done with having the url saved. 

not gonna close this one just yet.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
