### ISSUE TITLE
Support path expansions (e.g. `~`) in ipfs nocopy path mapping

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1320]
I was trying to use this feature, which I _thought_ was working earlier, but after booting my client today and trying to pin some files, I got this error:

```
v511, 2023/01/06 09:10:05: File could not be pinned: 500: {"Message":"cannot add filestore references outside ipfs root (/Users/me)","Code":0,"Type":"error"}
```

My mapping was like this:

`/Volumes/hydrus/client_files` -> `~/.ipfs/ipfs_maps/hydrus_client_files`

Changing it to the following made the error go away:

`/Volumes/hydrus/client_files` -> `/Users/me/.ipfs/ipfs_maps/hydrus_client_files`

Again, I'm pretty sure this was working just fine before, but my memory could be wrong. This error definitely happened, and using an absolute path with no expansions made the error go away. I won't claim it's a bug, since the help message never says explicitly that path expansions are supported, so I'm filing this as a feature request instead.

(In case it is a bug, debugging info is: v511, macOS 13, running from source.)

**Comment by bbappserver** [comment]
Path expansion is a feature of the shell, and does not actually exist at the program level.  If it ever worked it is because IPFS was doing the expansion or hydrus was invoking IPFS using `subprocess.Popen([args], shell=True)`, and now it is not.
