### ISSUE TITLE
Deviantart.com Tag Search Subscription Still Missing

### ISSUE THREAD

**Issue by JessicaHelp** [hydrusnetwork/hydrus#1321]
Deviantart.com tag search was removed in v504, on October 26, 2022. Deviantart is the #1 highest frequented art and visual design website in the world. It would be nice to see a fix, at least temporary, to plug this gap in Hydrus and once again allow Deviantart.com tag search for users.

**Comment by Zweibach** [comment]
You will have to either fix it yourself or hope somebody else does and submits a fix.
