### ISSUE TITLE
[Request] WMV is a piece of trash container, is there anyway to convert it to MKV and maintain tags?

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#133]
I've been learning some really basic coding and came up with this script:

```
FOR /r %%i in ("*.wmv") DO ffmpeg -y -i "%%~fi" -c copy "%%~dpni.mkv"
pause
for /r %%i in ("*.wmv") do del "%%i"
pause
```

It finds every .wmv file in the directory and sub-directory the script is being executed from, then demux the video into a .mkv container. No video or audio is changed. This allows the files to use matroska's much more advanced skipping features.

So the thing is, if I do this, the .wmv files will be deleted as soon as the script finishes it's job. I could just remove the **del** line and it maintain both files (with same file name, different extensions) and Hydrus would display to me which to keep) How would Hydrus treat these files?
I expect it to give me a bunch of missing files and lose all those tags.

At first, the mkv will have the same file names as their wmv originals, could Hydrus use it as means to attach the old tags to the new files?

Yesterday also did basically the same thing for a giant gif collection I had, transforming them into webms, reducing the damn thing from 40gbs to 11gbs.

```
for %%a in ("*.gif") do ffmpeg -y -i "%%a" -c:v libvpx -crf 19 "%%~na.webm"
pause
for %%a in ("*.gif") do del "%%a"
pause
```

I know it might be asking too much but, is it possible?

---

Break down:
- Detect same file name files
- Mirror the tags (if any)
- Rename the new ones with their actual sha-256 hash and delete the old ones.
- Prevent files that have the old file's hash to be added.

**Comment by HASJ** [comment]
I'm not for video encoding options to be included within the program (although they already are, in the form of ffmpeg).

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
