### ISSUE TITLE
cant import tag.txt

### ISSUE THREAD

**Issue by volatilaq** [hydrusnetwork/hydrus#1335]
### Hydrus version

v516

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

cant import picture and sidecar(tag.txt) on hydrus, tags are not imported properly.

i have a picture with name c08af083a2ad124077122d9645f76868.jpg
and a tag named c08af083a2ad124077122d9645f76868.jpg.txt

when imported, the tag does not appear
![1](https://user-images.githubusercontent.com/122660998/218952416-6dcf4f43-52ec-4691-ab0d-a624ae6605b5.PNG)
![2](https://user-images.githubusercontent.com/122660998/218952427-06b77800-30a8-4fad-b2d4-e60495ebc2d3.PNG)

**Comment by schneckenschnabel** [comment]
And did you tell hydrus to use sidecards (add tags/urls button)? Or did you just hit the import now button?

**Comment by volatilaq** [comment]
> And did you tell hydrus to use sidecards (add tags/urls button)? Or did you just hit the import now button?

thanks for the answer, I quite understand. forgive me who is still new to using this hydrus network application
