### ISSUE TITLE
[API] /add_urls/associate_url doesn't work with API key in URL

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1336]
### Hydrus version

v517

### Qt major version

Qt 5

### Operating system

Windows other (specify in comments)

### Install method

Running from source

### Install and OS comments

Windows 7, from source + fresh setup_venv

### Bug description and reproduction

Endpoint doesn't work when `Hydrus-Client-API-Access-Key` is provided in URL parameter.

![](https://i.imgur.com/ZFi5ZLV.png)
![](https://i.imgur.com/H0eiHQY.png)

Using [https://hydrusnetwork.github.io/hydrus/developer_api.html](https://hydrusnetwork.github.io/hydrus/developer_api.html#add_urls_associate_url) documentation.

**Comment by CatPlanet** [comment]
Also, when I use `Hydrus-Client-API-Access-Key` parameter in URL I get `401 Unauthorized`, funny.

**Comment by thatfuckingbird** [comment]
You are sending a GET request instead of a POST.

**Comment by floogulinc** [comment]
I don't think including the API key in the query params was meant to work with POST requests.

**Comment by CatPlanet** [comment]
Except [documentation](https://hydrusnetwork.github.io/hydrus/developer_api.html#access_and_permissions) says, that

>Access is required for every request. You can provide this as an http header, like so:
>> `Hydrus-Client-API-Access-Key : 0150d9c4f6a6d2082534a997f4588dcf0c56dffe1d03ffbf98472236112236ae`
>
>Or you can include it as a GET or POST parameter on any request (except POST /add_files/add_file, which uses the entire POST body for the file's bytes). Use the same name for your GET or POST argument, such as:
>> `/get_files/thumbnail?file_id=452158&Hydrus-Client-API-Access-
Key=0150d9c4f6a6d2082534a997f4588dcf0c56dffe1d03ffbf98472236112236ae`

**Comment by floogulinc** [comment]
Yeah if its a POST that takes its parameters in the body as JSON then you include it there.

**Comment by CatPlanet** [comment]
POST takes its paremeters in headers AND body, documentation states that, with exception of [`/add_files/add_file`](https://hydrusnetwork.github.io/hydrus/developer_api.html#add_files_add_file) while sending image in raw bytes, you can use both approaches - that is using acces key in header or url argument.

**Comment by CatPlanet** [comment]
And no, you can't use `Hydrus-Client-API-Access-Key` in POST body.

**Comment by floogulinc** [comment]
Alright then I suggest just including it in the headers. I think it's safe to assume that if you can send a POST request you can control the headers too. The ability to include the access key in the URL query params was mainly for allowing embedding files in the browser where you can't control the headers used.

**Comment by thatfuckingbird** [comment]
In any case the docs are wrong then, or at least misleading and should be updated.

**Comment by hydrusnetwork** [comment]
Thanks, sorry for the confusion here. I'll check out what is going on. My intention was you could put `Hydrus-Client-API-Access-Key` in the 'POST' args as in the JSON dict you normally post in the body. Sounds like that isn't working. I'll fix it, add some unit tests, and make the docs are clearer on how to do this.

**Comment by hydrusnetwork** [comment]
Hey, I updated the help here today to be clearer, with examples. If it is a GET, you can put `Hydrus-Client-API-Access-Key` in the URL arguments, but if it is a POST, you put it in the JSON body Object like the other parameters. I am afraid I could not reproduce this:

> And no, you can't use `Hydrus-Client-API-Access-Key` in POST body.

For instance, if I do a test line like this:

`r = requests.post( 'http://127.0.0.1:45869/manage_pages/refresh_page', headers = { "content-type" : "application/json" }, data = json.dumps( { 'page_key' : 'a53fee606a93dd0e0bfdecdcd58653674864f8ed4217751e89d25aca51262226', 'Hydrus-Client-API-Access-Key' : '6b97e4b591c324059d2d157855f0aa8bd7820ed0356b7f17eae8fd61d2dadace' } ) )`

It works ok for me! @CatPlanet can you give an example of how `Hydrus-Client-API-Access-Key` doesn't work for you in a request body? Maybe there's a special request somewhere with weird permission checking I am missing.

If this was just a misunderstanding of how this should work due to bad help, no worries.

**Comment by CatPlanet** [comment]
> It works ok for me! @CatPlanet can you give an example of how Hydrus-Client-API-Access-Key doesn't work for you in a request body?

Now that I check endpoints again it works, I don't know how I managed to get it to fail. Perhabs I changed my test lines one too many times and it got polluted.
With this all misunderstandings are cleared and hopes for better world restored. Thank you for your time and sorry for causing fuss.

**Comment by hydrusnetwork** [comment]
No worries, thanks for the report!
