### ISSUE TITLE
windows mpv test v518

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1338]
### Hydrus version

v518

### Qt major version

Qt 5

### Operating system

Windows other (specify in comments)

### Install method

Running from source

### Install and OS comments

[MPV API 2.1](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20230212-git-a40958c.7z/download) and following instructions from [latest release patchnotes](https://github.com/hydrusnetwork/hydrus/releases/tag/v518)
Windows 7, from source + fresh setup_venv

### Test results

Tested almost all files that could possibly fail with mpv.

- [x] regular gifs
- [x] huge gifs
- [x] webms vp8
- [x] webms vp9
- [x] mp4s (all kinds of profiles and codecs you can find on web including:)
- [x] hevc (yuv420p10le)
- [x] av1 (mostly yuv420p10le)
- [x] apngs (some [still won't](https://github.com/hydrusnetwork/hydrus/issues/1153) and can't be looped by "rewinding"/hitting play, only by closing and opening them again)

I haven't tested any videos with alpha channel or exotic pixel formats, but it this mpv works with my ancient machine and setup it should work for everyone with no problems.
That concludes my report. Feel free to close this issue.

**Comment by CatPlanet** [comment]
All test cases include zooming in/out + fiddling with seek bar back and forth, in both paused/playing state alike.

**Comment by hydrusnetwork** [comment]
Thank you for testing! The dll is now integrated into the Windows build, and we haven't had any big issues afaik, so I'll close this to tidy up. Interesting and neat that it all works in Qt5 and Win 7--I'll update the 'running from source' help to talk about that.
