### ISSUE TITLE
ImportError: /usr/lib/libopencv_viz.so.407: undefined symbol

### ISSUE THREAD

**Issue by Garakusi** [hydrusnetwork/hydrus#1339]
### Hydrus version

518

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Arch Linux

### Bug description and reproduction

1. Update hydrus with pikaur
2. Launch hydrus

### Log output

```text
v518, 2023/02/25 14:58:58: hydrus client started
v518, 2023/02/25 14:58:58: hydrus client failed
v518, 2023/02/25 14:58:58: Traceback (most recent call last):
  File "/opt/hydrus/hydrus/hydrus_client.py", line 240, in boot
    from hydrus.client import ClientController
  File "/opt/hydrus/hydrus/client/ClientController.py", line 27, in <module>
    from hydrus.client import ClientCaches
  File "/opt/hydrus/hydrus/client/ClientCaches.py", line 16, in <module>
    from hydrus.client import ClientFiles
  File "/opt/hydrus/hydrus/client/ClientFiles.py", line 19, in <module>
    from hydrus.client import ClientImageHandling
  File "/opt/hydrus/hydrus/client/ClientImageHandling.py", line 6, in <module>
    import cv2
ImportError: /usr/lib/libopencv_viz.so.407: undefined symbol: _ZN12vtkAlgorithm8RegisterEP13vtkObjectBase

v518, 2023/02/25 14:58:58: hydrus client shut down
```

**Comment by Garakusi** [comment]
`pip install opencv-python` solved for me.

**Comment by GunnerGuyven** [comment]
I had the same issue, identical error, using `paru` to install from https://aur.archlinux.org/packages/hydrus

The solution was the same, using pip to install `opencv-python`.  I had to add pip to my system to do this, which was pretty annoying.  There must be some dependency issue with this package at some level.
