### ISSUE TITLE
[Request] Zoom/float thumbnail on hover

### ISSUE THREAD

**Issue by AeliusSaionji** [hydrusnetwork/hydrus#134]
This is just an idea for "sometime down the road maybe".

Have thumbnails zoom by 30% or so when under the mouse cursor. If you have used any dock launching software, you know the effect I'm talking about.
Here's an example
http://www.stardock.com/products/objectdock/videos/AddEffects.ogv

The zoomed size is the true size of the generated thumbnail, so the rest pf the visible thumbnails are scaled down.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
