### ISSUE TITLE
[API] /get_files/file_metadata doesn't work with file_id parameter

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1341]
### Hydrus version

v518

### Qt major version

Qt 5

### Operating system

Windows other (specify in comments)

### Install method

Running from source

### Install and OS comments

Windows 7, from source + fresh setup_venv

### Bug description and reproduction

Endpoint doesn't work when `file_id` is provided in URL parameter.
According to [files parameter documentation](https://hydrusnetwork.github.io/hydrus/developer_api.html#parameters_files) "you can use any of the following" but in this case you cannot.

Using `file_id` with Integer:
![](https://i.imgur.com/MtHNixA.png)
Using `file_id` with something other, like an array:
![](https://i.imgur.com/kVA6ViI.png)
Using `file_ids` with just one element works just fine, though:
![](https://i.imgur.com/u3SzAme.png)

Using [https://hydrusnetwork.github.io/hydrus/developer_api.html](https://hydrusnetwork.github.io/hydrus/developer_api.html#get_files_file_metadata) documentation.

**Comment by CatPlanet** [comment]
Can't assing "bug" label using custom github templates, feels_bad_man.

**Comment by hydrusnetwork** [comment]
Hey, thanks for this report! Sorry I am only clearing it now. I believe this was fixed in v536. I assume you are updated now, but if not, please give it a go and let me know if you have any more trouble.
