### ISSUE TITLE
Client not booting up after failed update - Migration Possible?

### ISSUE THREAD

**Issue by AsaTyr2018** [hydrusnetwork/hydrus#1342]
### Hydrus version

443

### Qt major version

Qt 5

### Operating system

Windows 11

### Install method

Installer

### Install and OS comments

Tried Upgrading from 443 to 453 (As suggested)
it delivered a error on startup. so i removed everything (Except the db files) and loaded back in the 443. not its not starting up anymore. It stays as a process but no windows is showing up. (Yes i checked if its on a nother monitor or out of the viewing angle)

I red this files to "repair" it without a result:
help my db is not booting.txt
help my db is broke.txt
help my client will not boot.txt

Its not even Producing an errorlog (crash file)

I installed the latest version on a different drive and its working.

**Now the question:**
Can i use the migration tool to move the old database to the new client?

Hope you can help me. Its a 17tb large database. (Yes i know allways create a backup. its hosted on a raid drive. disk failor might happen. but can be rescued due to its nature)

### Bug description and reproduction

1. Updated from 443 to 453
2. started up client -> Delivered Error message (Sadly no screenshot taken)
3. Removed all Files except the db Folder
4. Reinserted the old Client 443 (Except the DB folder)
5. client not booting up. Stays as dead process.
6. tried database check. just mentioned "OK"

### Log output

```text
No crashlog created
```

**Comment by floogulinc** [comment]
You should always create a backup of the DB files (the files ending in `.db`) before updating and especially before such updating through so many versions. You say it's a 17tb database but presumably that's including the actual files and the size of the db itself is much less.

So to start trying to fix this make a backup of your DB files NOW. Then you might want to try identifying which version of the db the migrations got to, there should be a version identification script in the hydrus install. If that version is between 443 and 453 you may be able to get running with that hydrus version. Otherwise maybe try 454 or some version slightly newer, again only once you've backed up the DB files.

**Comment by AsaTyr2018** [comment]
> 

yes i know about the backup. currently i don´t have enough storage to backup everything and yes its the db files and the images together.

and i allready tried to load ip up with a different version. its not booting up neither. just stays as a dead client.exe in the proccess manager.

the db version is 443.

as asked. is it possible to use the migration tool from hydrus itself to drag the files to a different version?

**Comment by floogulinc** [comment]
Your DB files shouldn't be more than like 100gb. I can't believe that if you manage to store 17tb of files you can't keep another 100gb for a backup... Also if you compress it with 7zip for example it's more like 20-30gb.

What migration tool are you talking about?

**Comment by AsaTyr2018** [comment]
i`m doing AI Training for Stable Diffusion and use hydrus to sort all the training images. thats why its so huge.
but to be stright forward. the "Database" i ment is the whole DB folder.
the db file itself (client.db) is currently at 86gb. 
But whats the point in backing up this file without all other files?

And the Migration Tool.
Open Hydrus. click in the Menu on Database -> Migration Database.

So far it can just migrate from one folder to a nother. but can it do this reverse?

**Comment by AsaTyr2018** [comment]
Update:
i managed to rescue the whole database. don´t ask me how. i just tried it again with a clean install of version 455. draged the whole database into it. (db file and the client files) and bang its working again.

Got the notice about update. but its converted the database and its running again... hell that was nightmare stuff x_x no update for me anymore.

**Comment by floogulinc** [comment]
> the db file itself (client.db) is currently at 86gb.

There should be 4 files ending in `.db`, those are the hydrus database files.

> But whats the point in backing up this file without all other files?

Because that's the actual hydrus database that is modified when you update so its good to back it up before so if something goes wrong **like what you just had happen** you can restore it.
