### ISSUE TITLE
[Request] Alternative views

### ISSUE THREAD

**Issue by AeliusSaionji** [hydrusnetwork/hydrus#135]
This is but one suggestion, but I'm envisioning a "Details" view. This has the added benefit of making hydrus's interface a little more standard-

Imagine Windows Explorer's details view- Details introduces the concept of "columns"
| Name | Date Modified | Type.. | Size |
| 12.jpg | ....2015-12-10 | image | 5MB |

In hydrus, allow the user to create columns based on namespaces, and hide/create as many as they want. This allows you to sort by each column, too. The image preview box should be movable, too: perhaps a verical split down the main portion of the window?
| Hash | Date Imported | Size | Page | Character || %%%%%%%%%Image Preview%%%%%%%%%%|
| 13.... | .....3 days ago | 5MB | ....5... | .....Miku... || .......................... :) ......................................................|

With this, you can remove the sorting drop down box, and rethink how you display the collections filter.
I also think the search box needs to be rethought. The floating box that pops up in the search box is... unique. So unique in fact, that it's basically incompatible with most window managers (https://github.com/hydrusnetwork/hydrus/issues/49).

**Comment by Link-Satonaka** [comment]
A mock up of what it might look like, lazily made with excel. Each column is a pre-configured namespace.

![image](https://cloud.githubusercontent.com/assets/4342746/14595634/ce46e456-050e-11e6-82e9-f12c55681c5f.png)

**Comment by Link-Satonaka** [comment]
Something that goes hand in hand with pre-configured namespace columns: layout profiles. 
The ability to save different selected namespaces for each view type.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
