### ISSUE TITLE
Twitter downloader not working on age restricted content

### ISSUE THREAD

**Issue by Perfect-Ciel** [hydrusnetwork/hydrus#1354]
### Hydrus version

523

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Extract

### Install and OS comments

Ubuntu 22.10

### Bug description and reproduction

Whenever I try to download an image from a twitter URL that is age restricted content, the downloader results in "Ignored" with a 404. I have not noticed this issue before and the earliest it has been occurring for me is five days ago (april 8th). It happens with any post from any account where the post says "Age-restricted adult content. This content might not be appropriate for people under 18 years old. To view this media, you’ll need to log in to Twitter."
![Screenshot_2023-04-13_16-07-55](https://user-images.githubusercontent.com/115500437/231883249-60aaf72c-e32a-490d-8f63-7fc9b4fcbb39.png)

**Comment by Zweibach** [comment]
Twitter killed the API endpoint for age gated content. Fixed parser in the discord server.

**Comment by hydrusnetwork** [comment]
Hey, I have been saying in some other places, and I'll say it here too, that twitter clearly don't want to make it easy to download their content, so I just don't think hydrus's simple booru-tuned downloader can properly handle it any more. I tested twitter, including nsfw content, out with gallery-dl, and it worked well. I recommend trying to find the artists you like on other sites as much as possible, and then using gallery-dl on the remainder.

If you try this out, please let me know how it goes and what works for you.

In the longer-term future I expect to roll gallery-dl and yt-dlp support into hydrus itself so we can solve many of these problems without the hassle of setting up external import workflows.
