### ISSUE TITLE
Locked out of my database

### ISSUE THREAD

**Issue by Icing-weaponry** [hydrusnetwork/hydrus#1371]
Hi there,

I'm currently locked out of my database.
I had set up the password and I was sure I had noted it down in my password manager but I guess I didn't click save because now the password is set and my manager doesn't have the password.

I had read before on the help section that the password is saved in plain text somewhere, could I get the steps on how to find it?

Thank you for your help!

**Comment by thatfuckingbird** [comment]
It's in client.db, in the options table. If you don't know how to query it, then sqlitebrowser is a GUI app that can open it ( make sure to not change anything in there).

**Comment by Icing-weaponry** [comment]
nvm I just changed it to null and it worked.
thanks again for your help!
