### ISSUE TITLE
Add download query parameter for get_files API endpoint

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#1375]
Currently the `get_files/file` endpoint returns the file with the `Content-Disposition` header set to `inline`. There should be a query parameter, maybe `download=true` or `dl=true` to change from `inline` to `attachment`. This will allow providing the user with a link that immediately downloads the file and allow for downloading in third-party web apps.

**Comment by hydrusnetwork** [comment]
Thanks again, this is a great idea. I've done it for v532, exactly like this with `download=true` on `/get_files/file`, so let me know if there are any problems with it!
