### ISSUE TITLE
Question: Splitting Tags

### ISSUE THREAD

**Issue by AsaTyr2018** [hydrusnetwork/hydrus#1378]
Good day, 
this is more a question. Maby a Fearute Request. Depend on the viewing angle.

I had the issue that i Imported a fairly large ammount of images created by my ai. Every image was served with a sidecar txt that contained the tags. Normaly they are sorted so every tag can be read out correctly.
But currently i have the problem that the sidecar files wasn´t correctly alligned and now i have for every image a tag like "tag1, tag2, tag3, tag4....." and not "tag1", "tag2", "tag3"..... (Seperated)

Is there a feature that i overlooked to seperate them all in once? (The syntax is the same for all images. the tags are just fused in 1 tag)

Hope you can help me. Otherways i have a long and rocky way to do this by hand xD

**Comment by AsaTyr2018** [comment]
> You might get faster support on discord. But IIRC, txt sidecars expect tags to be delineated by newlines, while you seem to have used commas to delineate them, so maybe your problem is in how you're generating your sidecars. It's tough to tell because you don't give a concrete example. Again, I suggest that you try using the discord server for support questions, as you're likely to get help way faster that way.

Its nothing that i would state as time essential. So i don‘t habe a problem waiting. 

What do you mean by not a „concret example“?

i statet:
tag like "tag1, tag2, tag3, tag4....." and not "tag1", "tag2", "tag3"..... (Seperated)

the problem was that the initial import of the sidecar files was without spaces and it didn‘t recognize the seperation by coma.

**Comment by Zweibach** [comment]
Redo the import with correct settings.

**Comment by AsaTyr2018** [comment]
Erm i can´t. Its deleted after import. Thank you for this "unpersonal" reply and simply closing the thread.....

**Comment by Zweibach** [comment]
Export the tags then import with proper settings.

**Comment by AsaTyr2018** [comment]
> > What do you mean by not a „concret example“?
> 
> Like, we'd want to see your actual file and your actual settings. Or, a simplified version that reproduces the issue consistently would also suffice. While we're not dealing with the actual material world (since this is software,) a concrete example generally means [a real-world example rather than an abstract one](https://socratic.org/questions/what-is-a-concrete-example). What you gave was highly abstract, forcing me to hazard a guess as to what you had done that had led to you getting your undesired result.
> 
> To use a metaphor: if I am a grocer and you are a customer, and you tell me "I bought a bunch of rotten apples from you earlier today and I want my money back," and I ask you for evidence, a concrete example would be to show me one of the apples. What you did instead was the equivalent of vaguely describing what a rotten apple looks like: "they were kinda soft and squishy." While those certainly sound like they could be rotten apples to me, for all I know, you might just be a deeply confused person who baked his apples and then mistook their softness and squishiness after being baked for them being rotten.
> 
> Hopefully that makes sense. I'm being overly descriptive because it seems like English is not your primary language, but I realize that it could come across as being a bit patronizing to explain a common phrase like that, so you'll have to forgive me. I mean well.
> 
> > Erm i can´t. Its deleted after import.
> 
> You mean your sidecar file was deleted after import? I'm almost certain that's something you can change in the settings to have it not happen. Or rather, I'm pretty sure that's not the default behavior in the first place... regardless, I recommend you never delete source files or sidecars or anything upon import, because you don't know if something will go wrong and you'll need to redo the import, like in this case.
> 
> > Thank you for this "unpersonal" reply and simply closing the thread.....
> 
> Yeah I can understand why Zwei did that, after all we generally don't like it when people use Github issues for support requests, especially if they're requests that are almost certainly not stemming from an underlying bug or gap in functionality. We couldn't tell because you didn't make your request clear, and while I'm just a normal user who's semi-active in trying to help other users, Zwei's a mod who also takes care of most of the janitorial work of cleaning up issues that the developer needn't concern himself over. To him you're just one of many problems; hopefully you didn't take it too personally. After all, at one point, the issues were disabled because the developer couldn't keep up with the traffic. Thanks to volunteers, particularly Zwei who does most of the issue labeling, we're able to have the issue tracker here open again; but the collateral damage is the occasional situation like this one. I sympathize with your frustration, but I agree with Zwei's decision to close this issue since you didn't provide a repro case or any more concrete details.
> 
> So, let me suggest some next steps. First, have a look again at [the sidecar documentation](https://hydrusnetwork.github.io/hydrus/advanced_sidecars.html), and if your question doesn't get answered that way, I still think you should head to the community discord server for support questions; or, if you don't like discord, there's also a [bunch of other ways to seek support](https://hydrusnetwork.github.io/hydrus/contact.html), but please be courteous by creating a repro case _first_ should you choose to end up asking the developer for support; he's the one we're all volunteering our time for in order to save his, after all.

Thank you for the Reply. And i´m Sorry for the missunderstanding. I Usually perfer Github Issues because of documentary. Discord is a gamer communication tool. And i hate it. And yes. English isn´t my native Language.

The Sidecars and Images are created using Stable Diffusion/Auto1111. They usualy contain a lot of informations like Prompt, Negative Prompt, creation details (Model, hash, seed, etc....)
Every Inforamtion is stored as single lined text, seperated by coma.

I use a Powershell Script to filter out unrequired Inforamtions and just keep the Prompt.
Next step in the Script is removing the Seperations and write every word in a seperat line. (Usualy works with Hydrus)

Example:
Original Prompt Line: Mondstadt, landscape, masterpiece, best quality, highly detailed, cinematic lighting, sharp focus, realistic 

Once Converted:
Mondstadt
landscape
masterpiece
best quality
highly detailed
cinematic lighting
sharp focus
realistic 

But the script failed to launch befor the import from hydrus started. Now i have thousends of images with the one lined Prompt as 1 tag. and not as seperated tags. (Like the converted version)

But i think its not possible so i gonna delete the images and try to recreate them. i´m pretty tired of the support way of hydrus.
Nothing against you [roachcord3](https://github.com/roachcord3). you explained at last =) Thank you.

**Comment by AsaTyr2018** [comment]
> Gotcha. Once you had imported them like that and deleted the original sidecar sources, you were kind of screwed. Your best bet at that point would have been to use Hydrus' own API to extract those nasty tags and turn them into good ones, then retag your images that way. I'd do what you're doing if I was in your place. In the future, make sure you don't delete your imported files until after you're sure you got them in the client the way you want.

yea but hydrus can´t extract the tags from the png files. and the pure raw sidecars from A1111 has to much things in it to use as tags. so i need to filter them beforhand. (if the powershell script is working as planed ofcause xD) Since i´m using a own trained model i don´t need the model details in hydrus. Just the Prompt and the "Input/Output" Tags that i add manually. 

Anyway. Thank you for your understanding =) Have a nice day.
