### ISSUE TITLE
[v187/Issue] Client still working but completely irresponsive.

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#139]
It's just like one of the errors I reported in #96, this part in specific:

> GUI "irresponsiveness": It keeps on running normally but I can't do anything, not even normally close it. This is the second time this happened. Around line 50000+- on the log.
> I suppose the "Unknown Caller, probably GUI" caller traceback has something to do with it.
> EDIT: BTW, you know when you click a background window and Windows play that sound telling you that something else is on foreground? That's what that happens when the GUI does this hang and I click on it. Weirdly enough, the traceback messages are still clickable and can be closed as normal, with a right click.
> EDIT 2:This time, I did not kill the program, went to sleep and a new thing has happened. The GUI stopped altogether, the rest of the program seems to have frozen as well, even the previously working traceback messages went to shit.
> Clicked around the window and eventually Windows gave me the "stopped responding, kill or wait" message. Chose to kill it and even then Hydrus did not die. Windows has never done that. Waited for 5 minutes and Hydrus' icon was still on the taskbar, activated the window, clicked on it and it vanished. WTF. Seriously, What the fuck?

Which is continued in #114

Except it did not crash like in #96 and the thing in common with #114 was that it happened after managing tag and the parent tag manager inside it and this time I managed to click on it, so there's no window in the background, just the client's main window that is unusable.
The log is reporting nothing different (it locked while still downloading and it is still creating new files), there's no way to close it normally (alt+f4, close button, etc.)... Any kind of interaction with the GUI just gives me that irresponsive window sound

![clipboard01](https://cloud.githubusercontent.com/assets/9345660/12008442/71f68b9c-ac22-11e5-9846-7b9cce0df512.jpg)

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
