### ISSUE TITLE
Custom thumbnails for all file types

### ISSUE THREAD

**Issue by ngoomie** [hydrusnetwork/hydrus#1393]
This is related to #595 so I don't know if this should've maybe just been a reply to that one, but it'd be nice to be able to set custom thumbnails for all types of files, or at the very least for anything that isn't just a singular static image. I have knitting/etc patterns saved into Hydrus, all of which are in PDF format, and even if Hydrus were to already have PDF thumbnail generation, it'd be nice to be able to set thumbnails for these files that show what the finished item will look like. It's good for skimming for patterns, since the thumbnails for some of them in other software can potentially only have [very small](https://files.catbox.moe/n2p3s2.png) images showing what the finished item looks like, or (less frequently) [none at all](https://files.catbox.moe/xf6le4.png).

**Comment by Zweibach** [comment]
Expand on existing, related issues instead of opening new ones.
