### ISSUE TITLE
FR: merge records

### ISSUE THREAD

**Issue by ghost** [hydrusnetwork/hydrus#14]
Small thing: I would love to be able to tell Hydrus to merge duplicate records, having found them by using the "find similar files" option. This way if the inferior version of a file is the one that's got tons of tags, I don't have to copy them over - I just merge them and the system keeps one copy of the file, with all the metadata from both.

You'd probably want to have a "merge records" submenu that allows the user to pick "highest resolution kept / highest filesize kept / lowest resolution kept / lowest filesize kept / pick kept file manually", to encompass the majority of use cases.

I sort of feel as though the merged record should keep both sets of hashes associated with/aliased to it, for future duplicate and tag matching purposes, but I don't know a) if that's technically possible and b) if it would cause any problems elsewhere. If this isn't possible, maybe "most tags kept" could be an option when merging.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
