### ISSUE TITLE
Installer housekeeping

### ISSUE THREAD

**Issue by AeliusSaionji** [hydrusnetwork/hydrus#140]
Now that hydrus is 64 bit, the registry keys shouldn't be in WOW64 :)

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
