### ISSUE TITLE
High DPI Text Scaling

### ISSUE THREAD

**Issue by Myles-Trevino** [hydrusnetwork/hydrus#1400]
### Hydrus version

534

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Installer

### Install and OS comments

Fresh install with no settings changed.
Qt 6.4.1
Python 3.9.13

### Bug description and reproduction

On Windows 11 with display scaling above 100%, the text in the menu bar and certain windows scales disproportionately. At 200%, which is what I use on 4K monitors, the interface becomes almost unusable. I can force the program back to 100% scaling with 2x nearest neighbor upscaling to make it usable, but it would be nice to take advantage of having a high DPI display, especially since this is showing art. Other Qt 6 programs I use, such as qBittorrent (using Qt 6.4.3), work fine.

Menu bar:
![1](https://github.com/hydrusnetwork/hydrus/assets/11729491/d38e051f-4074-4773-bedc-6e1e216c0097)

Settings:
![2](https://github.com/hydrusnetwork/hydrus/assets/11729491/01857f95-11ee-4fdb-84ab-fbdc64b397ca)

**Comment by floogulinc** [comment]
This is a bug with Qt 6.4.1 and is fixed in later versions.

**Comment by hydrusnetwork** [comment]
Just pasting here from another convo so I don't forget--on PySide 6.4.2 and 6.4.3, opening an mpv window spams this to console:

`QWindowsWindow::setDarkBorderToWindow: Unable to set dark window border.`

Which seems to be mostly harmless, but I'd want more testing before deploying it to the builds.

PyQt6 doesn't have that problem, but it doesn't have a 6.4.3 version either, and it seems we need that to fix this text issue. So we are probably looking at accelerating testing and moving up to 6.5.0, which flickers more severely on loading any mpv window. Can't go to 6.5.1 though, or every menu in the program breaks!

I'm a hair's breadth away from reverting to 6.3.1, but still thinking about it all.

**Comment by hydrusnetwork** [comment]
Hey I forgot to mention this, but please try out the future-release I put out last week here:

https://github.com/hydrusnetwork/hydrus/releases/tag/v536-future-2

Make a backup before you try, but it shouldn't have any special install instructions--when I did a test install/update, it all went fine, no 'clean install' needed. This release has PySide6 6.5.2, and, fingers crossed, will sort you out! Let me know what you get. If everything looks good, I'd love to roll 6.5.2 into the normal release in a couple weeks (assuming no problems for other users--and so far there haven't been) and finally expel this Qt version-problem merry-go-round to the shadow realm.

**Comment by Myles-Trevino** [comment]
Installing over the previous version worked fine, and text scaling looks good now, thanks!

![Screenshot 2023-08-01 161517](https://github.com/hydrusnetwork/hydrus/assets/11729491/257b1fa5-3d07-47f5-89a2-ece6aa81af7e)
