### ISSUE TITLE
rule34hentai subscriptions just dont work.

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#141]
it seems that the subscriptions to rule34hentai tags does not download anything and just gets an error.
it looks for new files alright but gets an error when it starts to download the new files.

the traceback is long and contains a html page, it will just be easier to test for yourself TBH.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
