### ISSUE TITLE
Export Dialog takes a long time to open/process files

### ISSUE THREAD

**Issue by Mpegger** [hydrusnetwork/hydrus#1413]
### Hydrus version

v535

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Extract

### Install and OS comments

Hyrus installed on NVME

### Bug description and reproduction

Ever since around v464 (I'm not 100% of the exact last version affected, might has been v474), exporting files results in a long wait time before "Export Files" window opens. The more files choosen to export, the longer the wait before the window opens. Choosing a folder to export to under the "Browse" dialog window results in the same amount of wait time. During this wait time, Hydrus is unresponsive/locked (hour glass icon is displayed if you click on any Hydrus window element), and the hard drive activity light shows constant access (writing?) untill the export window finally opens. A 4000 file export, took almost 7 minutes before the "Export Files" window opened, and another almost 7 minutes after selecting a folder to export to.

Exporting files prior to this issue, regardless of how many files was being exported at a time, used to be almost instant.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am afraid on my machine a 5,000-file export dialog takes about 2 seconds to open, so this must be something specific to your situation. Please hit up _help->debug->profiling_ and run a profile while you do this. Email me the profile or pastebin it here or whatever is convenient. Please do scan its contents, but it shouldn't have any private info.

Also, what is your export filename pattern? If you swap it to `{#}`, does everything suddenly get very fast?

For the issue with the 'browse' dialog, is the delay before the dialog opens, or after you click ok? If it is taking a long time to open, you might like to try the 'ANTI-CRASH BUGFIX: Use Qt file/directory...' setting under _options->gui_. That's for a macOS issue, but if you can browse for a folder quick using the native dialog, then we know there's a weird Windows folder-access issue here. Secondarily, if you open up _file->import files_ and click the 'add folder' button there, does it similarly take a long time to open?

If it takes a long time to recalculate paths after you 'ok' the browse dialog, then it sounds like these are both the same problem and for whatever reason your export dialog is taking a huge amount of time to calculate export paths.

**Comment by Mpegger** [comment]
I've run a profiling log and attached it to a message on Discord to you.

Filename pattern is {hash}, and it's always been hash, I've never changed it from that. I tried using file numbering #, but that made no difference.

I did try the 'ANTI-CRASH BUGFIX: Use Qt file/directory...'. Opening the export dialog window did not appear to have any difference in speed, however, when choosing a folder to export to and clicking ok, it did appear to be slightly faster to go back to the export window, but not by much.

I ran a export of 99 files, and 198 files for the profiling. I also tried changing the export file name option as well to different options (hash, #, file_id, etc) while profiling, but they were all the same slow speed.

**Comment by hydrusnetwork** [comment]
Thanks again. I believe I have figured it out: I request the file system type when I prepare paths for export, NTFS or whatever--so I know which characters in an export path are invalid--and in your case this was taking 50ms each time. I was doing it for every export path, which was adding up to crazy numbers.

That file system type call is now cached, so with luck your problem is completely fixed in tomorrow's release! Let me know if you have any more trouble.
