### ISSUE TITLE
Whole Booru Download

### ISSUE THREAD

**Issue by 8ullyMaguire** [hydrusnetwork/hydrus#1416]
I would like to request a feature for the Hydrus Network that allows users to download an entire booru without having to subscribe to each individual tag. This would be particularly useful for smaller boorus where users may want to subscribe to the entire content rather than specific tags.

Currently, Hydrus Network supports various downloader types such as URL download, Gallery, Subscriptions, Watcher, and Simple downloader. However, none of these options allow for downloading an entire booru in a single action.

**Proposed Solution:**
Allow users to set up a subscription for the whole booru, so they can keep their collection updated with new content as it is added to the booru.

This feature would greatly enhance the user experience for those who want to download and subscribe to entire boorus without having to manage individual tags. It would also save time and effort for users who are interested in smaller boorus with a limited number of tags.

Thank you for considering this feature request.

**Comment by Zweibach** [comment]
Already possible, find out what query produces all result. For example, on danbooru it's `*`.
