### ISSUE TITLE
No Limit Subscription

### ISSUE THREAD

**Issue by 8ullyMaguire** [hydrusnetwork/hydrus#1417]
Currently, when adding many tags, the process of using the gallery downloader to fetch all content and then setting up a subscription to keep updated is quite cumbersome. It would be beneficial to have an option for no limit in the subscription when it runs for the first time, allowing users to download all content without having to use the gallery downloader initially. Additionally, when a gap is found in the downloads, it would be helpful to have the no limit option set as the default for the gallery downloader. This would streamline the process and make it more user-friendly for those who want to download and keep their content updated efficiently.

**Comment by floogulinc** [comment]
You can generally set a very high limit for the first run of a sub, at least 10,000, but the reason using a gallery downloader first is recommend is that very large subscription objects are a performance issue since they're literally serialized as giant JSON strings.

**Comment by Zweibach** [comment]
Dev has at various points spoken out against this for reasons I don't quite remember, probably mostly about how subscriptions are stored like floo said. You can copy+paste multiple queries in both gallery downloader and subscriptions so doing a lot of them at once is not really any more bothersome than one.
