### ISSUE TITLE
Minimize client to tray

### ISSUE THREAD

**Issue by iSplasher** [hydrusnetwork/hydrus#142]
Hi, could you implement minimizing the client to tray?
The reason should be obvious.
Thank you for your hard work~

**Comment by AreFinstad** [comment]
would also be great if the program could offload its resources so it can work smoother with what its working on in the background like imports or downloads for example. might speed things up if its all minimized and uses less resources for other things.

**Comment by iSplasher** [comment]
@AreFinstad 
Yes exactly. That was part of what i meant with
>The reason should be obvious.

Additionally, if you could extend the notification system to show those text ballons instead when minimized to tray, that would be great!

**Comment by AreFinstad** [comment]
well notifications like that would be limited to non-error message if that is the case i would think as you would have no option to open it and check the traceback.

**Comment by HASJ** [comment]
@AreFinstad hydrus can just his internal notification system. I don't think many changes are needed to display them when the client is out of focus/in the tray.

**Comment by AreFinstad** [comment]
i guess that is true...

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
