### ISSUE TITLE
Importing Twitter Links Not Working

### ISSUE THREAD

**Issue by zachjord** [hydrusnetwork/hydrus#1424]
### Hydrus version

539

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Arch Linux

### Bug description and reproduction

Twitter links fail to import. This has been happening for at least 2 days now and was also happening with v538. Maybe related to some sort of API change?

### Log output

```text
The parser found nothing in the document, nor did it seem to be an importable file!
```

**Comment by floogulinc** [comment]
Twitter parsers are no longer included in the Hydrus client and haven't worked properly in a while. Check the Discord for the current solution if there is any.
