### ISSUE TITLE
enable search for missing tags 

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#143]
i think we should be able to search for missing tags.
like files that dont have tags at all, files that dont have a creator tag and so on.
something simple like this would help out people filling out missing tags in our collections. 

li also think we should be able to search for file with a certain number of tags or less.
say if i want to search for files with 10 or less tags it would show me all of those files but not files with 11 tags or more.
this number should be able to be set by the user when searching so we can go as low or high as we want.

this is also handy for those files that lack alot of tags or only have creator tags and such, would also make it easier to find those files that you have added some tags to but not everything it contains.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
