### ISSUE TITLE
Extracting source time doesn't work (Inkbunny, maybe others)

### ISSUE THREAD

**Issue by brachna** [hydrusnetwork/hydrus#1431]
### Hydrus version

v540

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

Noticed that Inkbunny parser doesn't extract source time, tried to fix it.
There's something wrong with datetime.strptime step:
ERROR: Could not apply "datestring to timestamp: ('%d %b %Y %H:%M', 2, 7200)" to string "04 Feb 2014 17:07": time data '04 Feb 2014 17:07' does not match format '%d %b %Y %H:%M'

In Python this works:
import datetime
datetime.datetime.strptime("04 Feb 2014 17:07", "%d %b %Y %H:%M")
#datetime.datetime(2014, 2, 4, 17, 7)

**Comment by floogulinc** [comment]
What is your system locale set to?

**Comment by brachna** [comment]
Russian. Is this what causes the issue?

**Comment by floogulinc** [comment]
Yes. Until hydrus switches to a more flexible date parsing system it is dependant on your system locale and won't work properly for many sites when it's not English.

**Comment by brachna** [comment]
Bummer. Thanks for pointing it out, replacing month names with their month numbers using regex works as a fix for now.

**Comment by floogulinc** [comment]
That's a good workaround yeah. It looks like Hydrus might switch to using a better library for parsing dates soon as well.

**Comment by floogulinc** [comment]
Hydrus now has a new date parsing library added that should fix this issue for you. Update to https://github.com/hydrusnetwork/hydrus/releases/tag/v543 and use this updated inkbunny parser:
![inkbunny file page parser updated date](https://github.com/hydrusnetwork/hydrus/assets/1300395/0d03a9ad-8575-492e-bba2-77fbe503f5f0)
