### ISSUE TITLE
The login for "chan.sankakucomplex.com" failed!  Missing cookie "pass_hash"!

### ISSUE THREAD

**Issue by slaithe** [hydrusnetwork/hydrus#1435]
### Hydrus version

v542

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Install and OS comments

The login for "chan.sankakucomplex.com" failed!  It will not be reattempted until the problem is fixed.  The failure reason was:

Missing cookie "pass_hash"!
![hydrus sankaku error](https://github.com/hydrusnetwork/hydrus/assets/6773371/e7a832e0-e863-4c44-87ae-3e2cc3d3c1bf)

### Bug description and reproduction

1. my chan.sankakucomplex.com login was no longer working.
2. I deleted the entry from "manage logins"
3. hit apply and that window closed
4. using web browser, ensured my login credentials still worked properly by logging out and back into chan.sankakucomplex.com
5. create the entry anew in "manage logins" with the confirmed correct login credentials.
6. same error

### Log output

```text
The login for "chan.sankakucomplex.com" failed!  It will not be reattempted until the problem is fixed.  The failure reason was:

Missing cookie "pass_hash"!
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am not up on the site's latest news, but I heard they have been changing their layout and so on recently. My login system only works well for sites that use the common booru engines that rarely change, so I am generally encouraging people to move to [Hydrus Companion](https://gitgud.io/prkc/hydrus-companion) browser add-on as the better login solution for anything tricky. It copies your logged in cookies straight from your browser to to your hydrus using the Client API.

I will remove the sankaku login script for new users.

**Comment by slaithe** [comment]
Ok, I've installed Hydrus Companion, appropriately configuring it and Hydrus Network, verifying HN has successfully received the cookies from HC.
