### ISSUE TITLE
put wiki up

### ISSUE THREAD

**Issue by pokeball99** [hydrusnetwork/hydrus#144]
how about you open up the wiki and just dump the help pages into there? (converted to markdown of course)

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
