### ISSUE TITLE
How to set path for sidecars (tags, metadata)?

### ISSUE THREAD

**Issue by Fuwiz** [hydrusnetwork/hydrus#1445]
I have folder, this folder stored folders with images. Each folder with images contain images and another folder "metadata, tags". In this folder i have .txt and .json files. How to set path to this folder? 
I tried my_image\metadata, tags\my_image.jpg,  my_image.jpg\metadata, tags\my_image.jpg, metadata, tags\my_image.jpg and it not works. It only works when my json and txt files in the same folder as images.
Please help
![изображение](https://github.com/hydrusnetwork/hydrus/assets/62134155/b68544b6-c12e-4801-b5bf-331d8eb5f130)
![изображение](https://github.com/hydrusnetwork/hydrus/assets/62134155/7a39e6fb-44e1-4d08-961f-c7ee3cd6c053)

**Comment by floogulinc** [comment]
Yes it only works for files and metadata in the same folder. Just move the metadata files into the folder with the images.
