### ISSUE TITLE
PSD thumbnails generated by v545 have wrong colors: the blue channel and red channel seem to be swapped

### ISSUE THREAD

**Issue by Yukai-Qian** [hydrusnetwork/hydrus#1448]
### Hydrus version

v545

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Running from source

### Install and OS comments

The problem exists in the portable version too.

Tried replacing the 6.0 build of ffmpeg.exe with a 5.0 build, but the problem persists.

### Bug description and reproduction

Reproduction:
1. Install hydrus v545;
2. Import a PSD file;
3. The thumbnail has wrong colors.

Example:
Left: thumbnail with correct colors, generated from a PNG picture;
Right: thumbnail generated from a PSD of the same picture.
![image](https://github.com/hydrusnetwork/hydrus/assets/100383998/2951088f-652b-4333-b223-26502ddc87b0)

It appears that the blue and red channels are swapped in the PSD thumbnail.

The two files used in this example are attached below.
[RGB.zip](https://github.com/hydrusnetwork/hydrus/files/12761913/RGB.zip)

**Comment by Yukai-Qian** [comment]
People who use the installer or portable versions might need to stick to v544 to avoid this issue.

For those who run hydrus from source, below is a quick fix before the bug gets officially patched:

1. Open `install_dir/hydrus/core/HydrusPSDHandling.py` in a text editor;
2. Find line 53 `numpy_image = HydrusImageHandling.DequantizeNumPyImage( numpy_image )`
3. Replace line 53 with the following lines (be careful about the indentations):
```py
    shape = numpy_image.shape
    
    if len( shape ) == 2:
        
        # monochrome image
        
        numpy_image = HydrusImageHandling.DequantizeNumPyImage( numpy_image )
```

**Comment by floogulinc** [comment]
This is a better fix: https://github.com/hydrusnetwork/hydrus/pull/1449

**Comment by hydrusnetwork** [comment]
Thank you for this report. I've got the proper fix in for tomorrow, with retroactive thumb regen to fix existing bad thumbs. I tried to fix something at the last minute last week and screwed it up because of a badly named method!
