### ISSUE TITLE
adding too many namespaces can cause ok button to not be clickable

### ISSUE THREAD

**Issue by pokeball99** [hydrusnetwork/hydrus#145]
i was importing the tag archive http://www.mediafire.com/download/d2j6prlr7ov5840/PTR_HTA_up_to_update_1212.7z to my client and chose to add all the namespaces that popped up, when i did so, i could not select ok as shown here
![tag archive screwup](http://snag.gy/e4YdH.jpg)

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
