### ISSUE TITLE
manual facetagging as a part of the tag share?

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#146]
one thing i feel is missing and can be handy is to manually facetag (not automatic as it works bad with 2D images 40% of the time (works fairly in picasa)) 
it could also be shared like the tags are ATM with the hashes of the images as the location of the tag square/circle will always be the same for the same image.

this is handy for images with loads of characters and so on, shouldn't take up more space than any normal tag either really.

ofc this can still be miss used by tagging non-face areas and so on... but then again so can tags aswell. 

it can also be used to translate things like how sankaku does it for some of its images. 
like this: https://chan.sankakucomplex.com/post/show/5034045

it shouldnt have a shade tho IMO, unless its for text translation. 
might want to try to pull these translation boxes aswell.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
