### ISSUE TITLE
Redirect https://hydrusnetwork.github.io/ to https://hydrusnetwork.github.io/hydrus

### ISSUE THREAD

**Issue by PreciselyPixels** [hydrusnetwork/hydrus#1465]
Title. 
My web browser autofills any mention of hydrus to `https://hydrusnetwork.github.io/`, leading me directly to a 404 page. A redirection should be added to `https://hydrusnetwork.github.io/hydrus` for ease of use.

**Comment by floogulinc** [comment]
This would require dev creating a new repo called `hydrusnetwork.github.io` with an index.html file containing a redirect.

**Comment by Zweibach** [comment]
I haven't found any other solution than what floo said soooo... deal with it.

**Comment by floogulinc** [comment]
Something that may help, I have registered https://hydrus.dev/ which redirects to https://hydrusnetwork.github.io/hydrus
