### ISSUE TITLE
system:duration ~ and = search is extremely clonky

### ISSUE THREAD

**Issue by Suika** [hydrusnetwork/hydrus#1468]
system:duration allows to search videos by length. Yet the `~` search is a `+-15%` search which is waaaaay to broad. Optimally there would be an option(float) to set the distance for ~.
And the `=` search is too precise, what monster knows the length of some videos up to millisecond. The current `=` s and ms search window can stay, but maybe do not populate the ms field?
That way one would be able to search only for seconds, and if one really knows what one does, then they could fill out the ms field.

**Comment by Suika** [comment]
![image](https://github.com/hydrusnetwork/hydrus/assets/2320837/210ce306-166a-48b2-9cf6-f2500db5ee79)
This field should be kept empty to force the seconds only search.

**Comment by dergness** [comment]
Yeah, minutes:seconds is probably a better input.
