### ISSUE TITLE
make html help files w3 valid (and unicode ? symbol rendering bug in html files)

### ISSUE THREAD

**Issue by pokeball99** [hydrusnetwork/hydrus#147]
yea.... like most of the images don't have a alt tag and such, and there are several unicode ? symbols where spaces should be

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
