### ISSUE TITLE
Ability to manage / remove downloaders

### ISSUE THREAD

**Issue by sodamouse** [hydrusnetwork/hydrus#1471]
Hi thanks for the great program. I have one feature request: the ability to remove downloaders from the database. Since websites update their APIs and downloaders break, you end up with a lot of broken downloaders in the list. It would be great if you could clean the list up.

If this feature is already implemented, I have not managed to find it. I may be blind, but i really don't think it's there.

**Comment by Zweibach** [comment]
![image](https://github.com/hydrusnetwork/hydrus/assets/10709426/0bb005f8-d111-4d5b-b061-de964a653a0c)

**Comment by sodamouse** [comment]
oh thanks. i was not looking in that menu.
