### ISSUE TITLE
delete lock: Add checkbox to ignore for duplication deletes.

### ISSUE THREAD

**Issue by dergness** [hydrusnetwork/hydrus#1478]
When deleting duplicates, the delete lock also triggers.
 
So, I have to turn it off.

Still, for normal operation, browsing images and such, I find it a good feature to not allow it to be deleted while already marked as a good archived pic.

I'd like to have the protection outside of deduplication.

Setting is at <kbd>files and trash</kbd> in the options:
![image](https://github.com/hydrusnetwork/hydrus/assets/100443007/98b46d03-8982-4605-ba0a-465f3930d3ae)

**Comment by Zweibach** [comment]
> Hydrus Developer — 16.04.2022 22:37
if there's a delete lock on archived files, there's a delete lock
