### ISSUE TITLE
check last edit date of each file? or timer to not download again within a certain number of days.

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#148]
i have been thinking, its it possible to either check the last date of an edit of a file to see if it has been updated since last time it was checked by Hydrus.

in worst case there could be a timer tho, that tags and file will not be downloaded if its already in the database and is within a certain number of days since last download (user setting).
this should be contained on a per borru/site as a user might want to download tags of the same file from more than one site. 

just looking up the files when downloading for when they are already in the database takes up too much time i think esp if you have a "be nice timer" on and get like 10k dupes in the database when downloading.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
