### ISSUE TITLE
Client reports false positive "serious I/O Error"

### ISSUE THREAD

**Issue by pozieuto** [hydrusnetwork/hydrus#1485]
### Hydrus version

552

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

When the client runs its new "determine if the file has transparency" maintenance job and runs into a truncated image file, it will tell the user to check their hard drive health. This warning is incorrect here though - not only does my client not use a hard drive in this case, but the client itself downloaded and stored this truncated image file as-is under version 544 just days prior (as this is how it is being delivered by the online server it was downloaded from).

Now I'm also stuck in an awkward spot because the client will inevitably run into this error and stop performing file maintenance jobs for as long as this image file remains in the database. However, I want to keep this file for archival purposes for the time being (it is the highest-quality version of this image on the internet for the part that is not truncated).

### Log output

```text
v552, 2023/11/20 05:58:48: Hey, while performing file maintenance task "determine if the file has transparency" on file 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, the client ran into a serious I/O Error! This is a significant hard drive problem, and as such you should shut the client down and check your hard drive health immediately. No more file maintenance jobs will be run this boot, and a full traceback has been written to the log.



image file is truncated
```

**Comment by thatfuckingbird** [comment]
Quoting the dev:

> Hey, if you got any 'serious I/O error' sounding problems during the new 'has transparency' maintenance work, and if they talk about image truncation or 'broken data stream', you can ignore them, it is a false positive. I'll silence them this week.

> It looks like one of our image libraries is giving off way too serious errors on unusual files, and it is being escalated to the maintenance handler, which is then panicking. I'll figure out better error handling here, sorry for the trouble!

The best course of action is probably pausing that job now and resuming when the next version releases.
