### ISSUE TITLE
right click add tag to highlighted/selected files

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#149]
to speed up tagging in general. i think we need two ways to quickly tag the highlighted files with a tag that is already in use.

i think we should be able to right click on a tag to add it to the files selected in the manage tags menu (the one you get if you highlight more than one file then manage>tags)

but also in the normal file browser when the tags are on the side menu of the window. so if you highlight many files and some does not have a tag in question but one do you can rightclick it and add it to everything highlighted.

its a small thing but with loads of tags to manage its faster than what we have now.... pointing to either right clicking to copy then pasting in the selected space.... or even worse start typing, a simple one click solution can be done and have been done by other image managers like Picasa for example.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
