### ISSUE TITLE
How do I "pin" the info bar at the top of the media viewer?

### ISSUE THREAD

**Issue by dudeman108** [hydrusnetwork/hydrus#1490]
If I want to view the information in the info bar (e.g file type, resolution, file size), I need to mouse over the top of the screen. This is annoying when filtering duplicates, because I need to move my mouse to the top to compare the two files and then move it back to the right of the screen to make my decision. That doesn't sound like a lot of effort, but with 1,000+ duplicates it really adds up.

Is there a way to "pin" the info bar so that it's always visible, without requiring mouse-over?

**Comment by Zweibach** [comment]
No.
