### ISSUE TITLE
Can't delete a parent tag while tagging an image

### ISSUE THREAD

**Issue by jpfurriel** [hydrusnetwork/hydrus#1492]
### Hydrus version

556

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Installer

### Bug description and reproduction

I updated to 556. Before, when I parented two tags, I could remove the child while tagging an image. In some new update this has changed. I don't know if it's a bug, if there's a way to activate it again, but in this version, I can't select the tags separately in the image, It selects the whole family making it impossible to tag properly.

**Comment by Mengmoshu** [comment]
Not a bug. Parent tags are virtual now, which is an important feature to prevent stupid parents from causing nearly impossible to fix problems. We've still got `garrison cap` on pictures with `green eyes` where it shouldn't be in the PTR, even though the system changed a couple years ago.

You're supposed to manually tag the parent tag that you want if the child tag doesn't actually apply. The system isn't designed for workflows like applying a batch of tags with a temporary child tag.
