### ISSUE TITLE
FR: full boolean tag implications

### ISSUE THREAD

**Issue by ghost** [hydrusnetwork/hydrus#15]
I'm insane and you may well have already decided this is not worth the amount of effort it would require, but: It would be really cool to expand the already-useful tag parent system to include boolean logic. For example, I have given some thought to a really complicated series of automatic tags that would allow me only to tag genders and actions and get sexuality and explicit-ness automatically. A lot of this can be done with tag parents, but some of it requires constructions such as:

(okay writing this out suggests I don't actually have it specified as well as I think I do...)

`male AND NOT (female OR SFW) >> gay`
`male AND female AND NOT SFW >> straight`

The only problem I can see with this is that you could relatively easily create cascades - Rule 1 triggers and makes changes that trigger Rule 2, which makes changes that trigger Rule 3... and so on. I'd expect that this could cause the entire client to choke and die in a horrible processing loop, if not handled as some kind of exception.

You could also expand this to allow exclusive implications like `tag a NOT tag b` - which would force `tag a` and `tag b` to not be allowed to exist on the same image. I have no idea why you'd want to do this, but it's possible someone could find a use for it. The downside is that this not only exacerbates the cascade problem, but probably allows for conflicts to be created as well - just set the rule above, then set rules that set `tag a` and `tag b` individually, then tag an image with the tags that will activate those two rules. You'd need an order of priority defined, probably? I suspect that exclusive tags are more trouble than they're worth.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
