### ISSUE TITLE
sort namespaces on top if tag amount is the same

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#150]
i find that if i have say only a few files on tab ATM and most files got the same number of tags then namespace tags will be placed in alphabetical order or what ever order you set it to.
i think we should be able to set namespace type tags (anything that uses : as a category) to be on top if there is a tag with the same amount of uses on it.

that way all namespace tags no matter how many will atleast gather on the top the best it can, being artist tags aswell as series, volumes and so on. all that will just make it easier to get to the tags the user want faster.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
