### ISSUE TITLE
hide-able tags from taglist? 

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#151]
as much as i love the namespace page: and many others like it, i dont think its needed to have them in the taglist on the side menu all the time just taking up a ton of space.

i think we should be able to set namespaces aswell as tags to hidden in the user settings. that way people can for example hide the page: namespace. if possible there could also be a checkbox close to the taglist side menu that will activate the hide and deactivate it making easier to move back and forth when you need the hidden tags.

this shouldnt be limited by any tags for formats tho IMO, should be user set.

note, for example the page/series/volume/issue tags should not be hidden from the image thumbnail so users will still view them on the thumbnail itself.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
