### ISSUE TITLE
MissingCredentialsException('401: {"success":false,"code":"unsupported_auth_scheme","error":"unsupported_auth_scheme","errorId":...}')

### ISSUE THREAD

**Issue by Wallyking** [hydrusnetwork/hydrus#1533]
### Hydrus version

556

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Installer

### Bug description and reproduction

I am trying to download galleries from chan.sankakucomplex.com. I've added the necessary downloader and set http header by approving authorization for _capi-v2.sankakucomplex.com_ suggested in https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/tree/master/Downloaders/Sankaku

![image](https://github.com/hydrusnetwork/hydrus/assets/164578909/46ec5a6c-ff58-4fe9-be38-d73446cf2cbf)
![image](https://github.com/hydrusnetwork/hydrus/assets/164578909/5ec0185d-418e-48de-8c50-418245fda394)

I've added cookies after signing in chan.sankakucomplex.com:
![image](https://github.com/hydrusnetwork/hydrus/assets/164578909/039c2bad-9418-4022-9e4e-a3a343ad3330)

Added my login information 
Network > Logins >Manage logins. And Network > Logins >Manage login scripts
![image](https://github.com/hydrusnetwork/hydrus/assets/164578909/48fd2129-2e91-446d-9f0b-6ea0ee953db0)

I use default settings for login steps under this script except for the post login form. I noticed that _chan.sankakucomplex.com_ has a post of "/login?auth_type=oidc&reject_unverified=false&payments_integration_enabled=true&service_name=Sankaku%20Web%20App&submit_url=%2Foidc%2Finteraction%2F89a3754a-81f7-4eee-a870-32de40312292%2Flogin&entry_query=Y2xpZW50X2lkPXNhbmtha3Utd2ViLWFwcCZsYW5nPWVuJnJlZGlyZWN0X3VyaT1odHRwcyUzQSUyRiUyRnNhbmtha3UuYXBwJTJGc3NvJTJGY2FsbGJhY2smcmVzcG9uc2VfdHlwZT1jb2RlJnJvdXRlPWxvZ2luJnNjb3BlPW9wZW5pZCZzdGF0ZT1yZXR1cm5fdXJpJTNEaHR0cHMlM0ElMkYlMkZzYW5rYWt1LmFwcCUyRmF1dGgmdGhlbWU9d2hpdGUmdG9fcGF5bWVudHM9ZmFsc2U&lang=en&route=login&theme=white" - which returns the length error. However _login.sankakucomplex.com_ gives login success but when I try to download a tag from the gallery, I get an error saying "MissingCredentialsException('401: {"success":false,"code":"unsupported_auth_scheme","error":"unsupported_auth_scheme","errorId":...}')". The same occurs for the _chan.sankakucomplex.com_ domain.

![image](https://github.com/hydrusnetwork/hydrus/assets/164578909/92857dc6-1d0b-4b08-8e70-a0c578e62876)
![image](https://github.com/hydrusnetwork/hydrus/assets/164578909/028a0e21-5f6f-40a5-82b9-790b377338b8)
![image](https://github.com/hydrusnetwork/hydrus/assets/164578909/0e369b4b-3906-4128-a2c7-f48db00c62f7)

I might be doing this completely wrong and I understand that. I tried looking almost everywhere I could but couldn't find anything. Any assistance is most welcome.

**Comment by floogulinc** [comment]
The sankaku login script hasn't worked in years. When using the API based parser you don't use the login script.
