### ISSUE TITLE
Add tags from import folders names? [Possible new bug]

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#155]
A simple option like "Add sub-folder name as tags when importing" when creating a new import folder entry.
For example, I have an automatic import set up in D:\Hydrus Import and I want Hydrus to automatically add D:\Hydrus Import\**4chan**\**YLYL** as tags.
Possible?

**Comment by AreFinstad** [comment]
well you can technically do this with regexes but im unsure how to set those up for that.... nothing built-in works for the folders like you want.

what i would do is to import one folder at a time with the tags you need, thats for the best i think.
other then that you can try to learn regexes to set this up semi-automatically.

**Comment by HASJ** [comment]
Damn regex is really hard.
Can't find a proper way to exclude commas from the filenames.
e.g.Trying to parse everything separated by a comma and a space and removing possible Windows duplicate numbers:
>leilani leeane, brazzers, doctor adventures
>kelsi monroe, bangbros (3)

>\w+\s?(\w+[^,])[^\s\(\d\)]

In the results, the commas are always selected and I don't know why.

I may even found a new bug, because of my non-existant regex skills (paging @hydrusnetwork)

```
Exception
Was unable to parse the tag: (u' ', u'lexis,')

'tuple' object has no attribute 'lower'
  File "C:\code\Hydrus\include\ClientGUIDialogs.py", line 3394, in EventAddRegex
  File "C:\code\Hydrus\include\ClientGUIDialogs.py", line 3294, in _RefreshFileList
  File "C:\code\Hydrus\include\ClientGUIDialogs.py", line 3279, in _GetTags
  File "C:\code\Hydrus\include\HydrusTags.py", line 149, in CleanTags
  File "C:\code\Hydrus\include\HydrusTags.py", line 138, in CleanTag
```
The cause was this regex on this file name (I was just trying stuff out, I knew this wouldn't work): 
>([^\w+:\\?])(\w+[\,])
>D:\Imagens\Hydrus Import\Anal\lea lexis, anal, sideways, evil angel.webm

**Comment by HASJ** [comment]
I'm so dumb.
>([a-z0-9]\s?)+)
Does the trick. Trying to exclude directories on the other hand is hard

**Comment by ScoreUnder** [comment]
`[\w\s]+`

Source: worked a year full time somewhere where we did the nastiest hacks with regular expressions, daily.

**Comment by HASJ** [comment]
@ScoreUnder Thanks, that kinda works.
I can't modify it to remove the `(#)`, the extensions and use the commas as tag separators.

Will keep reading to see if I can fit this to do exactly what I want, thanks.
Starting to think I wasn't made for this coding stuff, however.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
