### ISSUE TITLE
manage tag siblings dialog is slow

### ISSUE THREAD

**Issue by lc-guy** [hydrusnetwork/hydrus#1553]
### Hydrus version

v575

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

right clicking on a tag > add siblings to:
with roughly ~270k pairs of siblings in my database (mostly imported from the PTR), the window takes about 5 to 7 seconds to become responsive.

Add parents, with ~25k pairs, is a lot faster.

**Comment by Zweibach** [comment]
This is just how it is.

**Comment by lc-guy** [comment]
> This is just how it is.

... this is honestly the first time I've gotten such a reply to a bugtracker listing.

Yes, it obviously is how it is. Maybe something should be done about it? ~270k entries in a database is not something that should take several seconds to process on every load of the popup, at least not on any modern machine. The size of an index for this doesn't mean outrageous either.
