### ISSUE TITLE
Pintrest image support

### ISSUE THREAD

**Issue by RealFX-Code** [hydrusnetwork/hydrus#1559]
i tried adding images to hydrus from my pintrest's homepage and it seems hydrus doesn't recognize the link to a pintrest post.

Examples:
```
https://no.pinterest.com/pin/188166090674112240/
https://no.pinterest.com/pin/40743571623302106/
https://no.pinterest.com/pin/4151824650816827/
https://no.pinterest.com/pin/12384967721493216/
```

trying to import these links to Hydrus seems to just error out.
The message I get is: `Looks like HTML -- maybe the client needs to be taught how to parse this?`
which indicates a parser has to be written for it.

Thanks in advance

**Comment by KJNeko** [comment]
You've already deduced that a parser has to be written for that page. You can find out how to make them in the [docs](https://hydrusnetwork.github.io/hydrus/downloader_parsers.html).

**Comment by RealFX-Code** [comment]
@Zweibach Why did you close this issue as completed? The issue isn’t resolved.

**Comment by floogulinc** [comment]
Because @Zweibach doesn't close them with the right status.
