### ISSUE TITLE
small stutter when loading webm's 

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#156]
im having small stutters every time i load a webm file (happens in mp4 files aswell)
the stutter happens every time between fram 9-15 mostly at 10 or 15 frames tho.

its just sad that playback is so smooth after that first stutter that the stutter takes away from the experience IMO. 
it ofc gets even worse when you are moving between webm files alot.

these stutters seems to happen without fail no matter what.

**Comment by HASJ** [comment]
I should add that those happen no matter how powerful your PC is. Happens on my i7 3.4 as well as in my Athlon 64

**Comment by AreFinstad** [comment]
sadly yes, sitting on a hexacore here and it happens all the time. yet no other program that opens these files have such issues. 
the webm's are small after all.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
