### ISSUE TITLE
Windows Defender flagged Hydrus Client as a trojan

### ISSUE THREAD

**Issue by PuszekChan** [hydrusnetwork/hydrus#1564]
### Hydrus version

v577

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Installer

### Bug description and reproduction

Three days after updating from v574 to v577, Windows Defender suddenly moved hydrus_client.exe into the quarantine as a Trojan:Win32/Wacatac.B!ml when opening the application. The workaround is just to allow the "threat", but I'll leave an issue here as it may happen to other people.

![Screenshot 2024-06-04 183135](https://github.com/hydrusnetwork/hydrus/assets/171718580/5f1572d0-aefa-431a-9ffd-8898b6adf71e)

**Comment by SaturyUnreal** [comment]
i have the same issue, i tested o virustotal, and this make a little uncomfortable. But i don't have much knowlement about these stuffs

**Comment by floogulinc** [comment]
If you downloaded Hydrus from GitHub it's definitely a false positive. We added some additional integration for Windows in this last version and that's probably why it's picking it up.

**Comment by SaturyUnreal** [comment]
> If you downloaded Hydrus from GitHub it's definitely a false positive. We added some additional integration for Windows in this last version and that's probably why it's picking it up.

I downloaded from github, So do you think is best to wait? because windows don't stop blocking as virus...

**Comment by floogulinc** [comment]
You can add an exception for it

**Comment by NatoSkato** [comment]
This issue seems to be fixed on V578. Had the issue on 577 but reinstalling with 578 presented no issues with windows defender

**Comment by hydrusnetwork** [comment]
Hey, sorry for the trouble here, and thank you for the report. Unfortunately, I do not have much control over this, but we can be fairly confident that these are false positives. Thanks to those who submitted it as such. More info here: https://hydrusnetwork.github.io/hydrus/getting_started_installing.html#anti_virus
