### ISSUE TITLE
Import video file metadata?

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#157]
And possibly get already imported files' metadata?
Many webms have info where the source is from in the title metadata.

**Comment by AreFinstad** [comment]
codecs, file formats, framerate and if it has audio would be really nice to pull from this aswell :D

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
