### ISSUE TITLE
Add option to sort items in collection by their page number

### ISSUE THREAD

**Issue by JohnDevlopment** [hydrusnetwork/hydrus#1573]
Let's say I have a single chapter of a manga as a collection. But the pages are not necessarily imported or archived in the same order as they appear in the source. That is to say, sorting collections by import/archive time will not always place them in the correct order, page-wise For example, I have one collection where, if sorted by archive time, goes from page 4 to 1, while the other collections are ordered from page 1 to _x_.

All of this is to say that I want the option to explicitly sort images according to their page number, since the client does not seem to do factor in page number when it sorts items.

**Comment by DralinZero** [comment]
Don't sort by archive time then, sort by namespaces. Your feature is literally already in hydrus.

Feel free to ask in the discord support channel first, if you don't know how to do something. (Better yet search the discord first before asking)

**Comment by floogulinc** [comment]
There is already namespace sorting in hydrus.
