### ISSUE TITLE
 Considerations for Open Contributions for the Wiki

### ISSUE THREAD

**Issue by uwidev** [hydrusnetwork/hydrus#1586]
There doesn't seem to have been any substantial updates to the wiki for a long time. Would you be willing to open up to the community contributions for the wiki? And if so, the process on how to do so?

There are many things I have yet to understand about Hydrus, and would like to learn more. What I do know, I would like to share it with others without repeating myself over and over again (which sometimes occurs on the Discord support).

There's also times when I'm reluctant to ask because something seems trivial but I just couldn't figure it out, and asking support makes me feel dumb or wastes the time of others. This kind of gets in the way of me learning more about how to use Hydrus.

Maybe move the documentation to it's own repository to separate the two? I'm not too sure how you want to proceed with this, if any.

**Comment by Zweibach** [comment]
This isn't a feature request for Hydrus the program.
If you want to contribute to the documentation make a pull request.
