### ISSUE TITLE
Tag: Previously Deleted

### ISSUE THREAD

**Issue by AeliusSaionji** [hydrusnetwork/hydrus#159]
Implement an option whereby a previously deleted image gets the tag "previously deleted".

This could be in the form of another checkbox next to the
"exclude already deleted files"
"tag already deleted files"

**Comment by AreFinstad** [comment]
tags like these should be blocked from uploading to the repo tho. we dont want other people tags like that.

**Comment by Link-Satonaka** [comment]
Good point. Maybe this would be better as an internal marker (similar to archive/inbox markers).

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
