### ISSUE TITLE
Edit predicates dialog for hashes doesn't scale the contents horizontally correctly

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1590]
### Hydrus version

588

### Qt major version

Qt 6

### Operating system

macOS other (specify in comments)

### Install method

Running from source

### Install and OS comments

macOS 14.6.1

### Bug description and reproduction

1. Do a search and add the `system:hash` predicate
2. Yoink the right-hand side of the dialog window and scale it out
3. Behold, it looks like the screenshot

![edit_predicates](https://github.com/user-attachments/assets/4ca17802-bb86-4014-88dd-afa3423b758b)

I would expect that the radio menu on the right would cling to the right side of the dialog, and the text input box in the middle would resize to fill the width of the window. That would be a better UX (would allow you to see the whole hashes without wrapping.)

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am sorry for getting to it late. I think I have it fixed for v594!

![image](https://github.com/user-attachments/assets/3b491432-fb0a-4b1b-b2db-06db64e1afa2)
