### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [hydrusnetwork/hydrus#1591]
### Hydrus version

*

### Qt major version

Qt 6

### Operating system

Other (aka none of the above, specify in the comments)

### Install method

Installer

### Install and OS comments

Dear @hydrusnetwork team, @floogulinc, @Zweibach, @Suika,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

### Bug description and reproduction

Currently there is a personal account for this important project instead of an organization.

**Comment by Zweibach** [comment]
This is not a bug report and this project is a personal project for dev.

**Comment by Neustradamus** [comment]
@Zweibach: I have created a feature request because for you it is not a bug:
- https://github.com/hydrusnetwork/hydrus/issues/1592

You can see here, it is not an human, a person, it is "Hydrus Network":
- https://hydrusnetwork.github.io/hydrus/
- https://hydrus.tumblr.com/
- ...

**Comment by Neustradamus** [comment]
@Zweibach: You have confirmed that it is a project, a project is not a physical person, a human.
- https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts

**Comment by floogulinc** [comment]
The hydrusnetwork account represents the developer of this project, the person. I'm locking this now.
