### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [hydrusnetwork/hydrus#1592]
Dear Hydrus Network (@hydrusnetwork) team, @floogulinc, @Zweibach, @Suika,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

PS : It is a Feature request if it is not a bug:
- https://github.com/hydrusnetwork/hydrus/issues/1591

**Comment by Zweibach** [comment]
That was not a request to open the same issue under a different label. Get lost.
