### ISSUE TITLE
Corrupted files after import

### ISSUE THREAD

**Issue by Shinkir0** [hydrusnetwork/hydrus#1593]
### Hydrus version

v588

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

During the import there was a failure because of which the hdd was disconnected, the client suspended the import but several files were damaged ![image](https://github.com/user-attachments/assets/82dc5e0b-50d5-4149-9824-23c894ede8ab).
there was an error in the log

> Exception('Copying the file from "C:\\Users\\User\\AppData\\Local\\Temp\\hydrus3pss65wu\\hydrusjpld50nj" to "S:\\Hydrus Network\\f61\\619c6275dd122a4b23f0a6e8cdb9ac7e4e57aed74de61aab13c25198740946d5.jpg" failed! Details should be shown and other import queues should be paused. You should shut the client down now and fix this!')… (Copy note to see full error)
> Traceback (most recent call last):
>   File "hydrus\client\ClientFiles.py", line 409, in _AddFile
>   File "hydrus\core\HydrusPaths.py", line 840, in MirrorFile
>   File "hydrus\core\HydrusPaths.py", line 656, in safe_copy2
>   File "shutil.py", line 448, in copy2
>   File "shutil.py", line 258, in copyfile
> OSError: [Errno 22] Invalid argument: 'S:\\Hydrus Network\\f61\\619c6275dd122a4b23f0a6e8cdb9ac7e4e57aed74de61aab13c25198740946d5.jpg'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "hydrus\client\importing\ClientImportFileSeeds.py", line 1106, in ImportPath
>   File "hydrus\client\importing\ClientImportFileSeeds.py", line 1071, in Import
>   File "hydrus\client\importing\ClientImportFiles.py", line 192, in DoWork
>   File "hydrus\client\ClientFiles.py", line 1240, in AddFile
>   File "hydrus\client\ClientFiles.py", line 419, in _AddFile
> Exception: Copying the file from "C:\Users\User\AppData\Local\Temp\hydrus3pss65wu\hydrusjpld50nj" to "S:\Hydrus Network\f61\619c6275dd122a4b23f0a6e8cdb9ac7e4e57aed74de61aab13c25198740946d5.jpg" failed! Details should be shown and other import queues should be paused. You should shut the client down now and fix this!

I tried re-importing the corrupted files, but the client thinks they are already in the database.
file recognised by database: 

>log: Imported at 2024-09-08 22:49:39, which was 29 minutes 20 seconds ago before this check.

I deleted the corrupted files from the database and tried to import these files again, but the client automatically deletes them itself
log: file 

> recognised: Currently in trash (Deleted from Media Page.). Sent there at 2024-09-09 00:11:41, which was 40 seconds ago before this check.

Based on the above, the question arises as to how I can replace the corrupted files?

**Comment by Zweibach** [comment]
options -> files and trash
Turn on advanced deletion and use the delete without deletion record option when deleting the files.
You can also open the file log in the import page, right-click the recognized files and pick try again.

**Comment by Shinkir0** [comment]
it worked, thanks for the quick response
