### ISSUE TITLE
(really minor) FR: Rotate!

### ISSUE THREAD

**Issue by ghost** [hydrusnetwork/hydrus#16]
It'd be convenient to be able to rotate an image (90 CW/90 CCW/180/flip horiz/flip vert) within Hydrus, causing Hydrus to overwrite the existing image with its rotated version and recalculate the hashes accordingly. This would prevent having to export badly-rotated images, rotate them externally, reimport, and retag.

(As with the merge idea, keeping the old hashes somehow associated with the edited image would be nifty for future matching purposes, but like I said there, I don't know if that's feasible.)

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
