### ISSUE TITLE
hydrus_client.exe (590) gets flagged as trojan by Windows Defender

### ISSUE THREAD

**Issue by trollusk** [hydrusnetwork/hydrus#1605]
### Hydrus version

590

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Extract

### Bug description and reproduction

Windows Defender flagged hydrus_client.exe as a trojan.

```
Detected: Trojan:Win32/Bearfoos.A!ml
Status: Quarantined

```

**Comment by floogulinc** [comment]
This is a fairly common occurrence and out of our hands. You should add an exception for hydrus and/or submit it to Microsoft so they can determine it's not malicious.
