### ISSUE TITLE
importing a Windows database to Linux breaks the client

### ISSUE THREAD

**Issue by bclindner** [hydrusnetwork/hydrus#161]
Importing a database backed up from a Windows version of hydrus into a Linux version renders the Linux version unusable; the use of backslashes in a Windows-created database makes hydrus think the directories where the files are stored don't exist. All entries in the `location` column of the `client_files_locations` table have to be updated to use slashes when this is the case.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
