### ISSUE TITLE
[API] system:tag as number does not work for namespaces that contain underscores

### ISSUE THREAD

**Issue by GreenLandisaLie** [hydrusnetwork/hydrus#1610]
### Hydrus version

589

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

Self explanatory title.

Following the API doc, I can search for `system:tag as number imdbvotes > 2000` and obtain results but searching for `system:tag as number release_date > 2000` returns an empty array even though I'm certain I have such tagged files in the database.

It works fine on the client UI - just not the API.

It is possible this issue extends beyond the 'tag as number' predicate.

Btw, using '>=' and '<=' should be acceptable but currently those aren't supported yet.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I have fixed this for v594. It seems the system predicate parser was replacing all underscores with spaces in the first step of parsing. There might be some cases where that is useful, but I think the cases that it prohibits are more obviously valuable, so I have undone it. Let me know if you have any more trouble with it!

Unfortunately I can't add '>=' to the Client API just yet. Most of my system pred internal variable storage is a hacky mess, and I need to overhaul the operator/comparison component into a cleaner object first that all runs on the same construction and storage pipeline, and broadly add '>=' awareness to the normal client support, and then it will be a much easier job to add it to the Client API too.

**Comment by GreenLandisaLie** [comment]
@hydrusnetwork Thank you for the fast fix! Since this should be solved by the next version I'll close the issue right away.

About the >= / <= operators its usually something very easy to implement but since I haven't checked that code I won't dare make assumptions. Its a minor thing so seriously take your time with that.
