### ISSUE TITLE
Inconsistent keyboard focus on panels when switching/closing tabs

### ISSUE THREAD

**Issue by uwidev** [hydrusnetwork/hydrus#1616]
### Hydrus version

v592

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Arch Linux, rolling latest release, on Wayland running Hyprland.

### Bug description and reproduction

I'm under the impression that keyboard focus is remembered on a per-tab basis. Closing a tab makes you change your tab, and the focus seems to be reset to the Search panel. I am calling the left panel with search, tags, collections, etc. as the "Search panel." I don't know it's official name.

## Scenario
Let's assume I have tabs A, B, and C.

A is focused on Search.
B is focused on Thumbnails.
I am currently on tab A.

From tab A, I switch to tab B, then back to A.

On A, I am still focused on Search.
Switching back to B, it is still focused on Thumbnails.
Focus is remembered per-tab. Working as intended(?).

Now I switch to C. I close the tab.
As a result of closing the tab, I am now on B.
I try to navigate thumbnails with keyboard as I expect I am on Thumbnail. I am unable to.
Pressing tab, it seems that focus has changed to Search.

## Impact
Not too sure if this is intended, but when [opening collections from a search in a new tab](https://github.com/hydrusnetwork/hydrus/issues/1615), making adjustments to it, and then closing the tab, I have to constantly hotkey to change my focus back to thumbnails.

Please consider making this more consistent by not changing panel focus when closing a tab, staying on the remembered focused panel for the tab that we return to when closing a tab.

**Comment by hydrusnetwork** [comment]
Please uncheck _options->gui pages->When switching to a page, focus its text input field (if any)_. It is tucked away at the bottom of the options page, I had to search around a bit to find it, so I'll see if I can make it more obvious/clear what it does.

**Comment by uwidev** [comment]
It is already unchecked. It works correctly when navigating normally. This specific problem happens **when closing a tab.**
