### ISSUE TITLE
Common resolution swap still applied in duplicates filter

### ISSUE THREAD

**Issue by VampirkoOrus** [hydrusnetwork/hydrus#1621]
### Hydrus version

597

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

Option "Swap in common resolution labels" is not applied in every context. In duplicates filter I still get common labels.

1. Check off "Swap in common resolution labels";
2. Launch duplicates filter containing an image with such common resolution (e.g. 720x1280);
3. See that resolution is still swapped to common label (e.g. vertical 720p).
![hydrus_client_MNE1iUxarh](https://github.com/user-attachments/assets/af939d01-2644-4cd6-a53d-fa575ef39317)

Also, I'd suggest moving this option from "media viewer" category to "gui", since it applies in other places, like bottom bar with metadata of a selected file.

**Comment by hydrusnetwork** [comment]
Damn, thank you, I will check this!
