### ISSUE TITLE
Feature request: copy tag from any menu with mouse-over and ctr+c

### ISSUE THREAD

**Issue by NyaaTell** [hydrusnetwork/hydrus#1622]
That's 10x faster than current workflow of "right click -> copy -> namespace:foobar". 
Would save me a lot of time since I end up copying a ton of tags per browsing/tagging session.

**Comment by Zweibach** [comment]
You can do this now.

**Comment by NyaaTell** [comment]
Incorrect, I can ctrl+c selected tag(s) without going through menus, which is an improvement I had missed, but it's not the same as `mouse-over -> ctrl+c` I'm requesting.

**Comment by Mengmoshu** [comment]
I don't know what anybody else will think about it, but hover + hotkey controls are almost always trouble in my experience. Especially if you're already talking about a context with full multi-selection support. What entry should be copied if you select Tag A then hover over Tag B before pressing Ctrl + C? Or for that matter, what if some other part of the UI that supports Ctrl + C is focused?

Clicking *once* is a pretty trivial cost to avoid ambiguity, and has the advantage of conforming to the vastly more common interaction model.

**Comment by NyaaTell** [comment]
I don't see how hover-copy could possibly mess up anything crucial, as it only concerns clipboard.

Selection-copy should override hover-copy, which would be a simple solution to avoid unintended behavior in your example - this way `Tag A` would be copied... or whichever multi-selection was made, for example.

At this point I'm considering moving this request to the 'shortcuts' compilation issue, since it would be convenient if all right-click menu options could be assigned to mouse-over / hover based shortcuts. This should ease any concerns, because assigning these shortcuts would be optional.
