### ISSUE TITLE
Duplicates filter page's UI has a width independent of the sidebar, making half of it invisible without horizontal scrolling

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1625]
### Hydrus version

v598

### Qt major version

Qt 6

### Operating system

macOS other (specify in comments)

### Install method

Running from source

### Install and OS comments

macOS 14.7.1

### Bug description and reproduction

The screenshot says it all tbh. Regression as of this latest release (v597 did not have this problem)

![girthy](https://github.com/user-attachments/assets/60d2bb17-a8db-44c3-bb05-5005504fae19)

**Comment by hydrusnetwork** [comment]
Thanks--I had a couple reports on this. Do you have a 'auto-resolution' tab on that page? It has some new placeholder UI I have been trying out. If you cannot see it, please hit `help->advanced mode` and then restart the client. There should be a multi-column list on that page, and I think it has some crazy widths causing the big panel size. Right-click on the header and say 'reset default column widths', and then you may need to restart the client again to re-layout the panel here--does that fix you?

![image](https://github.com/user-attachments/assets/73f602a5-493d-4a09-8c19-02a0148830e4)

**Comment by hydrusnetwork** [comment]
Great. This will be fixed for everyone automatically in tomorrow's release.
