### ISSUE TITLE
Issues with the download parser

### ISSUE THREAD

**Issue by DianoxDragon** [hydrusnetwork/hydrus#1628]
### Hydrus version

598

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Installer

### Bug description and reproduction

Hi, 

I've been trying to download other content from the e621 site for a while now, but nothing downloads. It used to work, so it's true that I'm touching up the bandwidth settings a bit, yet it seemed to work before. With others it works, but not for e621.

I either get "successful", 0 new url founds, or 'ignored" The parser found nothing in the document!

Maybe it's an API problem? It seems very strange to me, and it appeared randomly.

Thank you again

**Comment by KraatCat** [comment]
Can confirm, having the same issue.

**Comment by gabriel-cmf** [comment]
Same for me, when the bug started, I update from version 578v to 588v, and then to 598v, so it is not exclusive to just v598

**Comment by hydrusnetwork** [comment]
Thank you for this report. Yeah, it looks like they renamed some stuff in their html, which we parse. Should be fixed for tomorrow's v599. Let me know if you still have any trouble.

**Comment by KraatCat** [comment]
Thank you!

By the looks of their forum it seems they'll be updating their page to fix other problems this update caused.

**Comment by hydrusnetwork** [comment]
Great. This issue will close tomorrow, but if their further updates break things again, please re-open it or make a new one so I don't miss it!
