### ISSUE TITLE
Duplicate page sidebar so wide, yo

### ISSUE THREAD

**Issue by chaskayote** [hydrusnetwork/hydrus#1629]
### Hydrus version

598

### Qt major version

Qt 6

### Operating system

macOS 12 "Monterey" (Apple silicon)

### Install method

Installer

### Bug description and reproduction

1. Open new special -> duplicates page
2. Look at wide sidebar D:

![CleanShot 2024-11-19-000622](https://github.com/user-attachments/assets/f67973b0-6b85-4de3-8f80-b991c2c0fcf5)

I don't see a way to shrink it and I have to scroll horizontal to use it at all. I don't remember it being like this in v596. (I skipped v597)

**Comment by Zweibach** [comment]
Closed with https://github.com/hydrusnetwork/hydrus/commit/425d0d22cb3f192e1b67d37bcf0e40c7f602cd67
