### ISSUE TITLE
Support decimals in aspect ratio

### ISSUE THREAD

**Issue by AeliusSaionji** [hydrusnetwork/hydrus#163]
Currently, the system:dimensions , system:ratio only accepts whole numbers. Many standard ratios are decimal, too!

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
