### ISSUE TITLE
"edit metadata migration router" dialog cuts off UI text when importing to a file's notes

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1634]
### Hydrus version

v599

### Qt major version

Qt 6

### Operating system

macOS other (specify in comments)

### Install method

Running from source

### Install and OS comments

macOS 14.7.1

### Bug description and reproduction

Here's how I got to this point:

1. Dragged-and-dropped some files into the client for manual import
2. Opened the dialog to add tags before import
3. Selected the `sidecars` tab
4. Changed the destination field from `a file's tags` to `a file's notes`.

![edit_metadata_migration_router](https://github.com/user-attachments/assets/20dbbcc4-66d2-433a-88e6-93063f54a7f2)

As you can see, the checkbox that says `use "name: text" format` is cut off. Furthermore, the text input field is super tiny. Scaling the dialog to be wider helps somewhat, but it'd be nice to not have to fiddle with that. I rarely use this dialog window, so it's definitely not a high priority issue for me; I figured I should report it nonetheless.

**Comment by hydrusnetwork** [comment]
Thank you for this report! I have removed the unhelpful scrollbar behaviour and made the text box at least 20 characters wide for v601.

![image](https://github.com/user-attachments/assets/a345064e-7a65-496f-b821-03be8b1d1458)

As it happens, I did some other sidecar note stuff today, fixing multiline importing from .txt files and improving some other multiline display in the text panel and stuff.

Please let me know if you have any more trouble.
