### ISSUE TITLE
Cant update PTR (Quicksync)

### ISSUE THREAD

**Issue by IlluminatiWave** [hydrusnetwork/hydrus#1636]
### Hydrus version

600

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Extract

### Install and OS comments

Fresh install (extract)
Quicksync [hydrus-db-plus-ptr-2024-11-14.7z](https://huggingface.co/awcccc/hydr/blob/main/hydrus-db-plus-ptr-2024-11-14.7z).
HDD (I don't have space on the SSD, but I doubt this is the problem).

### Bug description and reproduction

The Public tag repository does not seem to be available, the program is stuck on “next account sync in 13 hours XX minutes”.

1. Download Quicksync and Hydrus Network (zip).
2. Extract both files and place them as explained in the guide (Quicksync in the Hydrus db folder).
3. Open Hydrus Client > Services > Review services > Remote > Public tag repository.
![image](https://github.com/user-attachments/assets/8b41649d-d612-4337-99b8-aac46ff4c7f3)
4. Try to refresh the account (not allowed, grayed out).
5. Wait for the indicated time (does not work, the time does not go below 13 hours).
6. Test the access keys |  Services > Manage services (everything is OK).
![image](https://github.com/user-attachments/assets/c1701210-2314-4e22-955c-55b31f98c426)
7. Repeat the process (doesn't seem to work).
![image](https://github.com/user-attachments/assets/024eb782-8f26-48ca-acf3-5df009a441c9)
(go back to 52 minutes?)

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am afraid I have never used the quicksync, so I don't know exactly what situation it initialises in. What does the panel just above that one on `review services` say?

![image](https://github.com/user-attachments/assets/f91a770c-eee8-458b-a9b9-604aefc67cf2)

Does it have a nice error message there like 'all repositories are paused'? I _think_ that if the 'refresh account' button is not available, the specific reason for that will percolate up to that panel, but let me know if it says like 'hey everything looks great'.

If it is that all repos are paused, hit up `services->pause->repository synchronisation` and I think after a bit of jiggling it'll all catch up with itself and get you syncing again.

EDIT: Yep, looking here https://breadthread.duckdns.org/ it says:
```
REPOSITORY SYNCING IS PAUSED BEFORE COMPRESSING THESE ARCHIVES
UNPAUSE WITH services->pause->all repository synchronisation
```

I think hit that unpause and you'll all be set. I'm closing this now, but please re-open if it is more complicated!

**Comment by IlluminatiWave** [comment]
Fixed, apparently the default PTR is paused synchronization (I guess for optimization issues). Something they never mention, thanks for the fix.
