### ISSUE TITLE
help with tags

### ISSUE THREAD

**Issue by timeg7100** [hydrusnetwork/hydrus#1637]
Hi
I don’t know where I can ask these questions

I want to ask is there a way I can see all of my tags at once?
I don’t want to start searching for a tag name and then have it appear
I want all my tags to show up so I can choose from them or search a specific one
I don’t want to use the recent tab
The same problem happens in the manage tags section

and how can I change a tag color?

thank you

**Comment by timeg7100** [comment]
and one more question
how can i edit a tag name?
how to manage tags? (deleting, editing, viewing of all of my tags)

**Comment by Zweibach** [comment]
The issue tracker is for feature request and bug reports.

Read the manual. For questions see https://hydrusnetwork.github.io/hydrus/contact.html
