### ISSUE TITLE
Database upgrade to v197 takes several days to complete

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#164]
Screenshot: https://r.kyaa.sg/nyvqvz.png

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
