### ISSUE TITLE
mpv playback stutters with post 600 version

### ISSUE THREAD

**Issue by Zeronthe** [hydrusnetwork/hydrus#1643]
### Hydrus version

601

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Extract

### Install and OS comments

23H2, PC used is the 13900H version of the Minisforum MS-01. Connected via USB to displayport using the integrated GPU. Resolution 3440x1440 165hz, single monitor.

Database is on the internal SSD, thumbs/media is on a NAS network share via SMB.

### Bug description and reproduction

Attempting fullscreen video playback using mpv will frequently have microstutters, causing small interruptions in sound and video. Particularly noticeable when subscriptions are downloading items at the same time.

Using the mpv-2.dll file from before version 600(i used the one from 596 for example) seems to fix these microstutters.

[client - 2024-12.log](https://github.com/user-attachments/files/18092054/client.-.2024-12.log)

**Comment by Zeronthe** [comment]
Seems to be resolved if you update to the latest version of the Intel Arc drivers (not the stock ones that come with windows.)

**Comment by Zeronthe** [comment]
Reopening this because it seems i was premature in closing, updating the drivers merely made stutters go away when subscriptions weren't running. While subs run, stutters seem to return. Old MPV still seems fine.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I saw something like this in my IRL client a couple times, but I couldn't tell you if subs were going on at the same time. It was when I was archive/deleting, and the vids were unusual anyway so I figured they were broken. It was like the video was playing at half or a quarter speed, with many gaps in audio. Is that what you experienced?

It only happened that one session, so if this is the same problem, I wonder if I had some other heavy system task going on like ffmpeg encoding or something.

It sounds like the new mpv is waiting on the python UI thread before moving on, so when subs are choking your python with heavy jobs, it is pausing a lot. I will experiment with this. It might be the solution is to move to another mpv dll, or, longer term, fix my heaviest code to be less rude on the UI thread.

You might like to test setting 'max number of subs that can run simultaneously' under _options->downloading_ to 1 temporarily, to see if that relieves your whole UI in general. I've been working on making subs load faster in the past few months, but it seems they now hammer the CPU all the harder as a result.

Also, I won't ask you do hit this up and do tests for me, but if you are ever interested in trying different dlls, the ones we use for mpv are from here: https://sourceforge.net/projects/mpv-player-windows/files/libmpv/

Get the 'x86_64', without the 'v3', and you may need to rename the dll to 'mpv-2.dll'. As you've been doing, you can just swap it in.

**Comment by Zeronthe** [comment]
Wasn't getting any video slowdown in terms of it feeling like half/quarter speed, just largely felt like hitching. It'd play fineish visually but have frequent stutters that disrupted the audio, when stutters happened it'd look like a micropause sometimes, but not always. I only ever seemed to be able to reliably replicate it during sub work(actively downloading and comitting to the db, not the initial getting gallery phase.) So i'm guessing it must be when it's committing or deleting things from the db.

My max number of subs is already 1 apparently (believe that is the default) so for now i just took to using the old mpv which doesn't seem to have the issue.

When i get some spare time i might play around and see if i can get any different results out of the other dlls you linked.

**Comment by hydrusnetwork** [comment]
Thanks. I'll see if I can induce some really bad UI pauses and see if the mpv player stutters.

**Comment by Zeronthe** [comment]
Using the latest version of mpv from your link i also get where you're coming from with the seemingly slowed video, it's a bit subtle at first glance but definitely noticeable if you're looking for it.

**Comment by hydrusnetwork** [comment]
Unfortunately I tried this out a bit today and could not get mpv to stutter with UI pauses on my dev machine. Playback was smooth no matter what the main gui was doing. MPV renders on its own thread in C++ land, afaik, so this is typically what one would expect. I interact with it via events back and forth, so any stutter caused from my end is probably related to a click that changes seek/volume/etc... or some pile-up of 'hey lets update where the seek bar is based on where mpv says it is' style update events.

I'm afraid I am off until the new year, but let's see if we can learn any more over the break. Since new GPU drivers relieved(?) your problem, I wonder if this is particular to your machine. I'll try and isolate one of these apparently slow webms on my IRL machine and see if that was down to the file, the mpv dll, or what.

If you happen to discover any files that are particularly aggravated, and you are ok to share them, please send them to me or link them to me. If they are in any way private, you can DM me on discord and we can set up a secure transfer.

Since the old mpv dll seems to work better for you, I think you are good to keep using that for now.

**Comment by Zeronthe** [comment]
Can't seem to replicate this anymore. I have a feeling it was something to do with process lasso(which i was originally using to keep the 13900h stable, as it'd crash hydrus ocasionally without it.) But seemingly ever since the MS-01 1.26 BIOS updated the intel microcode i haven't had any issues with crashing and completely uninstalling process lasso seemed to have fixed the stutters.

**Comment by hydrusnetwork** [comment]
Thanks. I am glad you are working better. I made the decision over Christmas to roll back to the older dll for v604 anyway, as it seems it causes crazy high CPU on certain APNGs and on older Windows in particular. I think those newer dlls were too fresh out of the oven for our purposes. Let me know how you get on here in general and in particular when I roll out the next 'future build' that has a new test mpv dll.
