### ISSUE TITLE
"system:media views = 0" does not work

### ISSUE THREAD

**Issue by sam-the-enby** [hydrusnetwork/hydrus#1644]
### Hydrus version

v600

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### Install and OS comments

Installed on its own SSD

### Bug description and reproduction

I use "system:media views" to sort through things i haven't seen before, but it is showing me things I've viewed before. I checked for duplicates and none of the things I see repeatedly have duplicate files.

**Comment by hydrusnetwork** [comment]
Thank you for this report. Unfortunately things seem to be working ok here and I cannot reproduce this. In your _options->file viewing statistics_, can you tell me what you have this option set to?
![image](https://github.com/user-attachments/assets/abec5b0b-fe4c-494e-83ae-8af97a3d6c25)

I have a setting there that is 'show media and preview combined' (which I never really liked tbh), are you set to that? If you do a 'system:all views = 0' (i.e. selecting both media and preview views), do things line up with how you expect?

If you still have the problem, what do you see if you right-click on a problem file and check its view settings on its menu, like this?
![image](https://github.com/user-attachments/assets/2db56a03-5df7-45ca-8cb1-1552674bd523)

Does it say 'no views', or does it have a view count?

There are thresholds for a file to count as 'viewed', also on that options page. If you have seen these files before, is there any chance you only saw them for a second or so? The default, I think, to count as a 'media view' is two seconds in the media viewer.

**Comment by sam-the-enby** [comment]
I think I may have figured out the issue, and it's my fault. Even with the media view timer set to one second, I'm flicking through things too fast for it to get counted as viewed.
Is it possible to have a fractional value for the min view timer? If I set it to zero will it mark everything in the database as viewed? Will things be counted as viewed instantly if I have "no limit" checked?

**Comment by sam-the-enby** [comment]
Sorry for closing this briefly. Clicked the wrong button.

**Comment by hydrusnetwork** [comment]
Yeah, if you set it to 'no limit', it will count a really short 50ms view as countable. I will reword the label in the UI since it isn't clear what 'no limit' means here.

Making this work on fractional time is a good idea. Looking at it, I think this system is all still working on second-resolution, and rounding down for viewtime, so if you do view a file for <1s, it'll record that as an increase of 0s (i.e. no) additional viewtime. This system wasn't swept up in the 'convert to millisecond' work earlier this year. I will make a job to review it all next year and upgrade it.

**Comment by sam-the-enby** [comment]
I'll set it to "no limit" and call it good. Thank you for the help!
