### ISSUE TITLE
can't verify db integrity or writing tags to db

### ISSUE THREAD

**Issue by lc-guy** [hydrusnetwork/hydrus#165]
I can't apply the public repository tags. It's stuck at "content row 0/100,164: writing".

Specifically, it seems hydrus locks up when doing this (according to the db logs):
`2016/03/27 14:08:34: Profiling write content_update_package`

I tried verifying the integrity of the db, but it locked up for a while and then crashed. I got this error message:

```
2016/03/28 18:38:36: Profiling write db_integrity
The program 'client.pyw' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 42195 error_code 11 request_code 53 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
