### ISSUE TITLE
Add tantabus.ai

### ISSUE THREAD

**Issue by VX8054** [hydrusnetwork/hydrus#1651]
Hello!

I want to add a gallery downloader for the tantabus.ai website

I tried to add it myself by copying all the elements from derpibooru, but it doesn't work, or rather it works, but not correctly. The images are parsed in the wrong order, not from new to old, but in general it's not clear how. Although if you open the page with search in the browser, then everything is correct there. Hydrus takes the image IDs from an unknown source, there are no such images on the page.

I don't understand what the problem is, the sites have the same engine. In the copied elements I only changed the address, nothing else.

**Comment by VX8054** [comment]
Разобрался, проблема была в фильтре сайта, у этого сайта он другой

**Comment by Zweibach** [comment]
Downloader requests here: https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/issues

Downloader docs here: https://hydrusnetwork.github.io/hydrus/downloader_intro.html
