### ISSUE TITLE
Issue with video import

### ISSUE THREAD

**Issue by Agrijb** [hydrusnetwork/hydrus#166]
When i try an import (.mp4) i get this error : 
raise HydrusExceptions.DBException( text, caller_traceback, db_traceback )
[error-hydrus.txt](https://github.com/hydrusnetwork/hydrus/files/211555/error-hydrus.txt)

**Comment by Link-Satonaka** [comment]
Hydrus is generally bad about handling dirty/imperfect videos.

You usually fix them easily by running them through ffmpeg first:

`ffmpeg -i video.mp4 -c copy fixedvideo.mp4`

**Comment by Agrijb** [comment]
Thank you for your advice, apprently the error came from the filename. i removed special character from it and it finally worked ^^

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
