### ISSUE TITLE
easy way to replace files

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#167]
i think we should have a simple way to replace files. after all files isnt always in the right format when there is better around.

unsure how to handle this other than filenames really, if a new file is added that has the same hash filename as a file already in DB then it should copy over the tags it has to the new imported file and then tag them both with a dupe tag of some sort. maybe even tagging them with which one is the original file or not.

there is many programs that can convert gif's to webm files and jpg to jpf files and so on.
im also guessing alot of people want to do that aswell as the files will be smaller for long storage without loss of quality. 

we need a simple way to import these new files that has unchanged filenames so its easier to make batch converts with programs like Adobe Media Encoder (supports webm with plugins)

ofc the hash should be calculated again and uploaded to the repo while renaming the file to the new hash value.

building on this, we should also have a simple way to remove original files that we have already converted, under certain tags if possible.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
