### ISSUE TITLE
[Request] Video management enhancements

### ISSUE THREAD

**Issue by AeliusSaionji** [hydrusnetwork/hydrus#168]
Someone on the board mentioned they use hydrus to store their video collection, and it intrigued me enough to try it.

I'm not exactly sure what the scope of hydrus is- if the dev never intends to support using hydrus for general traditional videos, then we can close this issue right now.

Otherwise, I have some suggestions.

**Playlists**
Open multiple selected files with an external player. Most programs should be fine with a list of files appended to the spawn command. (This actually should probably be a feature request in of itself, since it applies to using any format with any external viewer.)
`mpv file1.mkv file2.mkv`
`honeyview.exe file1.png file2.jpg`
edit- created seperate feature request https://github.com/hydrusnetwork/hydrus/issues/170

**Larger Thumbnails**
The current maximum size is too small. This is another general request.

**Animated Thumbnails**
Generate 20 or so thumbnails for each video, cycle through those thumbnails on mouseover.

**Detailed list view**
https://github.com/hydrusnetwork/hydrus/issues/135
Not all videos are going to have meaningful thumbnails. A list view with columns of tags for the rows of items. The current layout only allows you to see the tags of the currently selected item, which makes for slow work in a sea of black thumbnails.

**Detailed thumbnail view**
Each items in its own row, horizontally display all generated thumbnails for each item.
Here's a mock up of what it should look like (lazily created using excel)
![image](https://cloud.githubusercontent.com/assets/4342746/14595408/e9cd51bc-050c-11e6-8f7f-b48c9d1b8aa8.png)

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
