### ISSUE TITLE
[Request] OR searches

### ISSUE THREAD

**Issue by Beligertint** [hydrusnetwork/hydrus#169]
An example of an OR search would be such as:
1girl
solo
brown hair OR blonde hair

And would return both brown and blonde hair results mixed.

**Comment by xandershelley** [comment]
I think hydrus supports regular expressions, but I agree user friendly basic keywords would be nice.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
