### ISSUE TITLE
[Request] Open multiple files externally

### ISSUE THREAD

**Issue by AeliusSaionji** [hydrusnetwork/hydrus#170]
Open multiple selected files with an external player. Most programs should be fine with a list of files appended to the spawn command; eg, one would run the following in a terminal:
`mpv file1.mkv file2.mkv`
`honeyview.exe file1.png file2.jpg`

**Comment by eva7sk** [comment]
Same Request Here

**Comment by eva7sk** [comment]
By the way please support drag file and drop to player

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
