### ISSUE TITLE
[Request] Skip the first N urls

### ISSUE THREAD

**Issue by HailHydrus** [hydrusnetwork/hydrus#172]
On booru pages, it would be nice to have a feature to skip the first N urls detected and not process them at all.

**Comment by HailHydrus** [comment]
Or a "check url starting at page N" would actually be even better.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
