### ISSUE TITLE
[Request] simple api to import and tag files

### ISSUE THREAD

**Issue by sttollgrin** [hydrusnetwork/hydrus#173]
As title says, we (I and I'm pretty sure some other people too) could really use some really simple (POST /file, POST /tags) API to import files and tag them from outside of the application. One of the use-case scenarios I see for such API is creating set of userscripts for all major imageboards that would add "Import to Hydrus" button on sites like sankaku/gelbooru/etc.

I've tried writing it myself however I'm not Python dev and I don't really understand how hydrus works, tried calling

```
    def _threadDoPOSTJob(self, request):
        # TODO: do whatever magic is needed to import file from request
        db = HydrusGlobals.client_controller.GetDB()
        db._ImportFile(request.hydrus_args['path'])
        # TODO: return file_hash to client
        response_context = HydrusServerResources.ResponseContext(200, mime=HC.APPLICATION_JSON, body=json.dumps([]))
        return response_context
```

but it was no dice
`sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 10844 and this is thread id 11028`.

So I'm guessing DB access from service worker thread is not that simple...

I'm currently writing similar API in Java/Groovy, operating directly on DB, however with the DB structure being changed with pretty much every release it's really hard to maintain the code, API built-in within hydrus would be much better.

Alternatively, if you cba to write this and/or do not see how it could be useful, please provide us (again me, and I'm sure some other people too) with insight on how to access db object from service threads...

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
