### ISSUE TITLE
MD5 tagging

### ISSUE THREAD

**Issue by Cotihero** [hydrusnetwork/hydrus#176]
Is there anyway to read MD5's against a Booru database and grabbing all the tags on those images?

**Comment by AreFinstad** [comment]
sadly there is no way to do this today. BUT a patch or 3 ago added links from where its downloaded. that COULD add a simple tag reimport/update on the sites in general. 

tho it could technically do the hash searches for the files aswell. tho that needs to be added aswell to function.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
