### ISSUE TITLE
redownload file on failed file integrity with saved url.

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#178]
now that Hydrus saves the url it downloaded the file from, it could auto redownload files you have that failes file integrity for whatever reason. files that dont open and dont work properly.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
