### ISSUE TITLE
easier/faster retries of failed downloads

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#181]
right now we have to open the file import status (the download list) to change our failed downloads so it will be tried again.
depending on how large your list is that list can take a while to load, or even crash the program esp when you have a download or two going already.

i think we should atleast have one of two things:
1: a button that just says retry failed (which will automatically change the state of those downloads so it will try again)
2: have a setting that will auto try all failed downloads on a timer (say every hour or every 2 hours for example).

small things, but its a HUGE QOL improvement, esp when the list loads slowly.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
