### ISSUE TITLE
No thumbnails work at all

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#183]
In the latest update (211), no thumbnails work at all. Here is a patch to fix it:

``` diff
diff --git a/include/ClientCaches.py b/include/ClientCaches.py
index 19cb427..d8a2334 100644
--- a/include/ClientCaches.py
+++ b/include/ClientCaches.py
@@ -765,6 +765,8 @@ class ClientFilesManager( object ):

         thumbnail_dimensions = options[ 'thumbnail_dimensions' ]

+        resized_path = self._GenerateExpectedThumbnailPath( location, hash, False )
+        
         try:

             thumbnail_resized = HydrusFileHandling.GenerateThumbnail( full_size_path, thumbnail_dimensions )
@@ -773,7 +775,7 @@ class ClientFilesManager( object ):

             try:

-                HydrusPaths.DeletePath( path )
+                HydrusPaths.DeletePath( resized_path )

             except:

@@ -785,8 +787,6 @@ class ClientFilesManager( object ):
             thumbnail_resized = HydrusFileHandling.GenerateThumbnail( full_size_path, thumbnail_dimensions )


-        resized_path = self._GenerateExpectedThumbnailPath( location, hash, False )
-        
         try:

             with open( resized_path, 'wb' ) as f:
```

A variable called `path` is being used, but it hasn't been defined anywhere.

I hate to have to hammer the point home again, but **if you were using a linter this would never have happened**, and same goes for using an IDE like PyCharm. Please install pylint and check your code with it regularly, because it can find problems like this. (You may want to use the `--disable=C` argument to turn off python style checking)

**Comment by hydrusnetwork** [comment]
Thank you for this report. I use PyLint, which plugs into WingIDE nicely, and make sure to scan before I put the release together, but it unfortunately did not catch this problem. I updated to PyLint 1.5.6 and then it did, so I suppose that was a bug in PyLint. I've made a note to regularly update it in future.

I appreciate your advice. I feel the code is generally in a much better state than it was a year ago, but I am aware that it and my ability remain imperfect. I hope to improve it further in future while continuing work on the rest of my to-do list.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
