### ISSUE TITLE
manual thumbnail replacement for videos and flash files.

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#184]
i think we should be able to use another image for a thumbnail for those files that dont generate correctly, like Flash games/animation and longer videos (not gifs and webms).

really handy for flash games that have official splash screens (Meet & Fuck anyone?) and longer videos like StudioFOW, Fap Heroes and other long videos that people might use that might have official art connected to it.

the thumbnail should have hashed and have a hash value and be a part of the database like normal. but it should be tied to the file its thumbnailing for (linking them) 
also, you could use the URL save function for the thumbnail so IF someone dont have the thumbnail but have downloaded the info about it then they should be able to rightclick and download thumbnail if the url is saved. 

this overall will help with the final look of everything and also will enable easier and better viewing of content where the auto thumbnailer failes (sadly it always does for longer files)

small thing that would be great aswell (but not needed) is dual sided cover support (like ComicRack does it) where you have an image with the hole cover and the program will view it as a "3D" cover and you would be able to view the back of it aswell. user choice is key on that one tho. 
but main cover support is much more important!

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
