### ISSUE TITLE
mouse buttons on shortcuts! or remove with single mouse button.

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#185]
i was thinking about binding the middle mouse button to remove (sadly it wont remove what im hovering over but whats highlighted (maybe another issue)) then i found out that the shortcut menu ignores all mouse input so i cant tie a mouse button to this. 
this is also an issue if you have alot of mouse buttons i would think.

i atleast want to be able to quickly and easily remove files from the page with middle mouse button (while hovering over it, like a chrome tab)

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
