### ISSUE TITLE
Do you have any guides for compiling Hydrus into w32?

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#186]
I'm heavily interested in a updated w32 version of Hydrus but I honestly have no idea how to compile programs. I just need some tips to how it'd work with hydrus, I can find the rest on the internet.

**Comment by Link-Satonaka** [comment]
32bit support was dropped because several of the used libraries dropped 32bit. The latest version you will ever get is the latest official 32bit release.
