### ISSUE TITLE
dynamic page tagging (change, edit and add Incremental tags) 

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#187]
while adding tags the first time can easily be done wth regexs like \d\d\d with spaced numbers on filenames.
its a huge pain to correct and/or edit numbered/Incremental tags, like pages and volumes for example.

why not have a gui that enables drag and drop of the files in order. let us perview the order in the normal viewer would also be great.

something like that could remove the old tags for us and add new tags in the order the user set.

while this would be a huge undertaking, i think a gui to handle something like this would speed up the page tagging.

like how ComicRack handles this with dragging and dropping while seeing the thumbnails. [screenshot bellow]

![](http://i.imgur.com/f2k3kR1.png)

the gui should let us either open a namespace tag to manage or let us drag and drop from the main client window onto the "page manager".

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
