### ISSUE TITLE
[New Feature] View Last xx Images?!

### ISSUE THREAD

**Issue by misakitchi** [hydrusnetwork/hydrus#190]
I want to view my last xx images
so i open a new search and add filter "system: limit is 10" and "system:everything"
But everytime i press refresh i have random images...

Can you add a new feature to see last xx images please? Thanks! :)

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
