### ISSUE TITLE
Popup menus appear offscreen in 1366x768 resolution

### ISSUE THREAD

**Issue by xandershelley** [hydrusnetwork/hydrus#202]
There is no check to ensure that menus dont appear partially offscreen for low resolutions. Its not a huge issue, but using these menus frequently is slowed by having to drag the buttons back into a useable screen area.
![capture](https://cloud.githubusercontent.com/assets/13305268/18209206/99ba1970-70e7-11e6-80c3-78d0bcd0f4e7.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13305268/18209207/99bf2212-70e7-11e6-97ac-33e71a1c998a.PNG)
![capture3](https://cloud.githubusercontent.com/assets/13305268/18209208/99c122a6-70e7-11e6-82b9-754a917c0b29.PNG)

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
