### ISSUE TITLE
Inverted UI font issue

### ISSUE THREAD

**Issue by oba2cat3** [hydrusnetwork/hydrus#203]
I have the most odd issue I ever saw. Some of the GUI has mirrored Text, and the location of the controls is RTL instead of LTR. issue is similar to the stackoverflow question here:
http://stackoverflow.com/questions/7800143/wxpython-program-mirrors-individual-letters-horizontally-how
solution is from here:
https://groups.google.com/forum/#!topic/wxpython-users/pA3zXKjbgi4
changing the relevant line in the source code solved it for me, but modifying the official release did not.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).

**Comment by yonixw** [comment]
For future ref, the solution suggested is:
Find:
`wx.LANGUAGE_DEFAULT`

And Replace with:
`wx.LANGUAGE_ENGLISH_US`
