### ISSUE TITLE
Improvements wishlist

### ISSUE THREAD

**Issue by Bozunee** [hydrusnetwork/hydrus#204]
Right click menu could use "Show in folder" similar to how newly downloaded files in Google Chrome work.
Option to allow an external image viewer instead of the built-in viewer
Options to change mouse button controls for the built-in viewer (only can change keyboard keys for some reason)

**Comment by ipatrol** [comment]
Option \# 2 is already implemented.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
