### ISSUE TITLE
HC.DB_DIR undefined in except in client.pyw

### ISSUE THREAD

**Issue by CirnoT** [hydrusnetwork/hydrus#205]
`dest_path = os.path.join( HC.DB_DIR, 'crash.log' )`

HC is undefined in except block (missing import HydrusConstants as HC) causing block "except NameError, IOError" to take over and never deliver proper traceback.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
