### ISSUE TITLE
[Enhancement] Textfile support

### ISSUE THREAD

**Issue by filterop** [hydrusnetwork/hydrus#206]
I'm sure plenty of people have or would like to swap copypastas or even actual discourse.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
