### ISSUE TITLE
[Request] Tag Descriptions

### ISSUE THREAD

**Issue by xandershelley** [hydrusnetwork/hydrus#207]
Menu to add a description for a tag. Some tags are nessesarily vague for length, it would be nice if in the tag options menu we could describe how a tag should be used, and have that description appear as hovertext for that tag.
Thanks!

**Comment by KriPet** [comment]
This, or a wiki, like what exists on many boorus would be nice. It's not always obvious what a tag means, and, for the public tag repo, to have a community edited tag wiki would be useful.

**Comment by xandershelley** [comment]
Maybe. Having to go lookup what a tag means externally could be a drag while tagging many things. Integrated hover-over-text seems like a good solution. Could that be done with a wiki (I cant think of how that would work).

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
