### ISSUE TITLE
Please provide standard-sized icons and .desktop file

### ISSUE THREAD

**Issue by yurivict** [hydrusnetwork/hydrus#208]
In order for the app to behave well on a desktop, it needs to provide icons and desktop file. For example, qTox provides these:
```
        /usr/local/share/icons/hicolor/128x128/apps/qtox.png
        /usr/local/share/icons/hicolor/14x14/apps/qtox.png
        /usr/local/share/icons/hicolor/16x16/apps/qtox.png
        /usr/local/share/icons/hicolor/192x192/apps/qtox.png
        /usr/local/share/icons/hicolor/22x22/apps/qtox.png
        /usr/local/share/icons/hicolor/24x24/apps/qtox.png
        /usr/local/share/icons/hicolor/256x256/apps/qtox.png
        /usr/local/share/icons/hicolor/32x32/apps/qtox.png
        /usr/local/share/icons/hicolor/36x36/apps/qtox.png
        /usr/local/share/icons/hicolor/48x48/apps/qtox.png
        /usr/local/share/icons/hicolor/512x512/apps/qtox.png
        /usr/local/share/icons/hicolor/64x64/apps/qtox.png
        /usr/local/share/icons/hicolor/72x72/apps/qtox.png
        /usr/local/share/icons/hicolor/96x96/apps/qtox.png
        /usr/local/share/icons/hicolor/scalable/apps/qtox.svgz
```
You only have hydrus_non-transparent.png with the non-standard size 200x200.

.desktop file in Arch Linux is currently supplied by the port. You should provide it.

**Comment by ipatrol** [comment]
I think only the scalable version is strictly necessary, since all the other sizes can be rendered from it by the system. Correct me if I'm wrong.

**Comment by yurivict** [comment]
I agree.

**Comment by ipatrol** [comment]
If that's the case, there's already a suitable icon [here](../blob/master/static/Icons.svg).

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
