### ISSUE TITLE
Missing 'import numpy.core.multiarray' in ClientConstants.py

### ISSUE THREAD

**Issue by yurivict** [hydrusnetwork/hydrus#209]
```
--- include/ClientConstants.py.orig     2016-11-14 02:56:34 UTC
+++ include/ClientConstants.py
@@ -1,4 +1,5 @@
 import collections
+import numpy.core.multiarray
 import cv2
 import HydrusConstants as HC
 import HydrusExceptions
```

**Comment by ipatrol** [comment]
I take it this is a patch. Can you explain the bug that prompted it?

**Comment by yurivict** [comment]
hydrus-client fails: ImportError: numpy.core.multiarray failed to import

I think this is the same as this bug: https://github.com/opencv/opencv/issues/8139

**Comment by ipatrol** [comment]
Well it appears that cv2 was removed in a later commit: 3859d7ff83661618f8c52c543d283ed2ee7ea2c3

So... close as invalid?
