### ISSUE TITLE
Importing Past First Page of Search Results

### ISSUE THREAD

**Issue by HaikenEdge** [hydrusnetwork/hydrus#213]
Not sure if it is actually a problem, because the manual is fairly poorly formatted so I can't tell if it's actually addressed in there, but I'm having trouble importing images from certain booru where Hydrus can't seem to get past the first page of results even though the search on the site shows there are multiple page of results.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
