### ISSUE TITLE
[New Feature] Subscriptions Boorus POPULAR (Yande.re Popular Recent)

### ISSUE THREAD

**Issue by misakitchi** [hydrusnetwork/hydrus#214]
Hello!
I want to check every 6hours this URL:
https://yande.re/post/popular_recent

Its the 40 most popular posts of the last 24hours.
So posts change very often! Some are the same (top left corner) but new posts are coming too (bottom right corner).

So i create a custom booru with only this URL
I created a subscription who check every 6hours. But sometimes its working and sometimes not...
I don't know why...

When its not working, if i clear the "URL cache status" its working...

So can we have an option to not check the cache or always download all the posts?

Thanks! ^_^

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
