### ISSUE TITLE
auto mass tag adding for many images

### ISSUE THREAD

**Issue by MasterPetrik** [hydrusnetwork/hydrus#215]
I see in current version only ability to fetch tags for image from boorus manually. 
![2017-01-28_223057 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22399399/bc90f2ea-e5ac-11e6-9473-bff80675a96f.png)

It is cool option, but its crazy to fetch and add tags for each one of thousands of images in my db.
Is there are some way to do it automaticly for all my images?

**For example I need to use "md5 gelbooru" fetching script on all my images and auto add founded tags to them. 
Is there any way how I can do it?** 
And if not, maybe you should add this function to your programm?

**Comment by vbessari** [comment]
I do have the same question, however it's related to e621. Is there a way do put the script to run for all the files?

**Comment by nonamethanks** [comment]
The dev said he doesn't want to implement mass-tag lookup to prevent users from accidentally DDoSing the servers of the boorus in question - think of hundreds of users all doing the same request continuously.

You can work around this if the pictures come from the same batch by re-downloading them with the booru downloader - just tick this cogwheel https://a.uguu.se/xmAIlK1NTo8E_tmp.Zoo0yN9RNX.png and check the first option (or second if you want it on always). It won't redownload files if they already exist, it'll just update their tags. It doesn't work for groups of different files, but it can help.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
