### ISSUE TITLE
Suggestion: mouse actions for mini-preview window

### ISSUE THREAD

**Issue by MasterPetrik** [hydrusnetwork/hydrus#216]
![2017-01-28_230604 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22399488/84b68324-e5ae-11e6-8457-3763b1a9a627.png)
Some useful functions for mini-preview window:
1. DoubleClick on preview image should open it as it works when you DoubleClick on the same image in the list view.
2. Rolling mouse wheel when cursor is on mini-preview window should change selected image in the listview to next/previous as it works in full-preview window.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
