### ISSUE TITLE
Gelbooru Subscription broken, new url system

### ISSUE THREAD

**Issue by Scrxtchy** [hydrusnetwork/hydrus#218]
As talked about in the bug thread on 8ch.
Hydrus now is given redirect urls, which are base64 encoded of the entire url, minus protocol

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
