### ISSUE TITLE
Scrolling leaves weird unpainted regions and can cause crashing

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#22]
Probably related to #12 (which is now fixed for me)

When I scroll I often get stuff like this:
![Screenshot](http://a.pomf.se/eenwpv.png)
The text it's pasted comes from the terminal behind it.

I think it might also be connected to a crash that happens when scrolling:
```
The program 'client.pyw' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 21728 error_code 11 request_code 53 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
Unfortunately I have no idea on how to debug that.

**Comment by hydrusnetwork** [comment]
Wow, that looks horrible!

I am hoping to completely rewrite the way the thumbnail canvas works this week (chiefly to reduce memory usage, which may be part of your BadAlloc problem), so please let me know if you still get the problem after next version.

**Comment by hydrusnetwork** [comment]
I'm clearing up my old github issues, so I'm closing this, assuming it is fixed now. If not, please reopen!
