### ISSUE TITLE
Any way to make speed this up?

### ISSUE THREAD

**Issue by Zekken01** [hydrusnetwork/hydrus#220]
Is there any way to speed up adding images? It gets really slow when you're adding around 200,000k images.

**Comment by nonamethanks** [comment]
Try importing batches of fewer files at once. Hydrus doesn't act nicely when you import more than a couple tens of thousands files at once.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
