### ISSUE TITLE
Tags being deleted on their own

### ISSUE THREAD

**Issue by Sparklepaws** [hydrusnetwork/hydrus#221]
Every so-often random tags will be deleted from my recently-tagged images. I am not connected to a repository and my database is set to synchronize with my export folder every 3 minutes.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
