### ISSUE TITLE
Subscription support on more art galleries

### ISSUE THREAD

**Issue by theredmanor** [hydrusnetwork/hydrus#222]
There's a lot of artist I'm following that mainly uploads on sites not supported by the Hydrus subscription service
It'd be amazing if this software can support subscription on those sites:
1. [Facebook](Facebook.com)
2. [Twitter](Twitter.com)
3. [Instagram](Instagram.com)
4. [Artstation](Artstation.com)
5. [DrawCrowd](Drawcrowd.com)

Thank you so much for developing this wonderful soft!

**Comment by nonamethanks** [comment]
It's a planned feature for the downloading engine refactoring, which is currently in progress. Wait a couple of months and the program should be able to support all of those once the dev finishes it.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
