### ISSUE TITLE
[Request] Login options for the boorus

### ISSUE THREAD

**Issue by Phooh** [hydrusnetwork/hydrus#223]
I noticed some of the boorus hide images if you don't use an account and Hydrus just skips over them. I know rule34hentai you need an account to see everything, I think danbooru might as well, haven't tried. I'm not sure which others need one since I don't browse them regularly but hopefully someone else can name them if there are any.

**Comment by nonamethanks** [comment]
The dev's currently in the middle of a refactoring for the downloading engine, which will include session cookies and ref headers. Once he's done (which will take around 3-4 months probably, but some of these features will be available sooner), you'll be able to use your various accounts to fetch all kinds of hidden pictures from these boorus with hydrus, as long as it's possible to do so through a regular browser.

**Comment by Phooh** [comment]
I see now, I guess Hydrus has everything covered. Thanks for the reply, closing this issue
