### ISSUE TITLE
DBException error

### ISSUE THREAD

**Issue by zeftony** [hydrusnetwork/hydrus#225]
UnicodeEncodeError
and
Daemon SaveDirtyObjects encountered an error

**Comment by nonamethanks** [comment]
See: https://8ch.net/hydrus/res/6398.html#6409
It will be fixed for next week's release.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
