### ISSUE TITLE
Gelbooru exception

### ISSUE THREAD

**Issue by Zekken01** [hydrusnetwork/hydrus#226]
Exception
The subscription Gelbooru - kasuga39 encountered several errors when downloading files, so it abandoned its sync.
Traceback (most recent call last):
  File "include\ClientImporting.py", line 3506, in Sync
    self._WorkOnFiles( job_key )
  File "include\ClientImporting.py", line 3187, in _WorkOnFiles
    raise Exception( 'The subscription ' + self._name + ' encountered several errors when downloading files, so it abandoned its sync.' )
Exception: The subscription Gelbooru - kasuga39 encountered several errors when downloading files, so it abandoned its sync.

This keeps happening on all my gelbooru subscriptions after a few images.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
