### ISSUE TITLE
The dropdown window can be closed, and causes issues when it is.

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#23]
The autocomplete dropdown window can be closed using the keyboard, and hydrus really does not like this. It disables typing in the tag box and causes errors when the scroll wheel is used:
```
TypeError
object of type '_wxPyDeadObject' has no len()
  File "/home/score/src/hydrus/include/ClientGUICommon.py", line 278, in EventMouseWheel
    if self._text_ctrl.GetValue() == '' and len( self._dropdown_list ) == 0:
```

I know this is more of a "Doctor, it hurts when I do this" type of issue, but it is strange nonetheless.

**Comment by hydrusnetwork** [comment]
That's neat--how are you closing it with the keyboard? Is there a 'close frame' shortcut in Linux?

I never considered it, but I can probably put a 'ignore close events' handler into the dropdown class.

**Comment by ScoreUnder** [comment]
Yes please! In i3 the close shortcut is Win+Shift+Q, but I have tried in openbox and it can be closed with alt+f4. For some reason i3 gives preference to that window in a way, so by default the dropdown window comes focused, and if a dialog gets closed (in any program) the dropdown is usually the thing that gets focus again.

**Comment by hydrusnetwork** [comment]
I'm assuming this is no longer a problem since I embedded the dropdown. Please reopen if you still get any problems!
