### ISSUE TITLE
Include URL type in file metadata API response

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#235]
Currently the known URLs section of an `/get_files/file_metadata` API response looks like this:
```json
"known_urls" : [
				"https://gelbooru.com/index.php?page=post&s=view&id=4841557",
				"https://img2.gelbooru.com//images/80/c8/80c8646b4a49395fb36c805f316c49a9.jpg",
				"http://origin-orig.deviantart.net/ed31/f/2019/210/7/8/beachqueen_samus_by_dandonfuga-ddcu1xg.jpg"
			],
```

It would be nice if it could also include the URL type from the parser, eg "twitter tweet" and "booru post"

It could look like this, perhaps with different key names:

```json
"known_urls" : [
				{
				  "url_name": "gelbooru post page",
				  "url": "https://gelbooru.com/index.php?page=post&s=view&id=4841557"
				},
			],
```

The "url type" may also be included as in `/add_urls/get_url_info`.

**Comment by floogulinc** [comment]
Original from Discord:
![image](https://user-images.githubusercontent.com/1300395/84580430-85d42e00-ad9c-11ea-85b8-ed538b1e8434.png)

**Comment by hydrusnetwork** [comment]
Thank you. For tomorrow's release, I have added a parameter to /get_files/file_metadata, 'detailed_url_information' true/false, which will add 'detailed_known_urls' to the file metadata row with a list of the same info you get from /add_urls/get_url_info. The help is updated with an example. The Client API version is now 13.

Note that the type of an url is not cached and has to be computed on the fly by consulting the current url class structure, so I believe this could add significant lag when asking about hundreds or thousands of files at once, a bit like when you right-click in the client on a huge ctrl+a file selection.

I thought about suggesting just using /add_urls/get_url_info to look up URLs as needed, but this would be annoying and inefficient to do n times for every file.

Let me know how this works for you!

**Comment by floogulinc** [comment]
Hmm that's interesting. I didn't realize it would be inefficient like that. What would you think about allowing the get_url_info endpoint to take an array of URLs like many of the others do. Then I could just query all the URLs for a file on demand.
