### ISSUE TITLE
Sorting in API search

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#236]
It would be nice to be able to specify a sort parameter for the `/get_files/search_files` API endpoint along with ascending/descending. This could be implemented with additional query parameters.

**Comment by grravity** [comment]
Unsure if this is the same thing, but the client api doesn't return tag results in alphabetical order and that's a bit annoying. Would hope to see that.

**Comment by hydrusnetwork** [comment]
> Unsure if this is the same thing, but the client api doesn't return tag results in alphabetical order and that's a bit annoying. Would hope to see that.

Thank you, just noticed this, it is done for this week's release.

**Comment by hydrusnetwork** [comment]
Ok, this should be done now!

https://hydrusnetwork.github.io/hydrus/help/client_api.html#get_files_search_files

I will give this another pass to improve the help, specifying exactly what asc/desc is for each type!

**Comment by prof-m** [comment]
@hydrusnetwork Was just testing this out on the new version 450. Good news: the `file_sort_type` parameter seems to be working as intended! Bad news: At least as far as I can tell, the `file_sort_asc` parameter doesn't seem to be respected. Whether I pass it true or false, the returned list of file_ids comes back in the exact same order. 

I tried this for all sorting types 0-9, but the `file_sort_asc` parameter didn't seem to affect the results of any of them.

Here's an example of one of the GET URLs I was trying with:
`http://localhost:45869/get_files/search_files?file_sort_type=9&file_sort_asc=false&tags=["system:duration < 2 seconds"]`

**Comment by floogulinc** [comment]
@prof-m would you be able to make a new separate issue for this so we can track it better?

**Comment by prof-m** [comment]
@floogulinc Issue #959 is up! Let me know if you think it could use any additional details and I'll see what I can do. I'd definitely be curious to know if others can reproduce it.
