### ISSUE TITLE
Feature: Shebangs on *.pyw

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#24]
Please add this comment to the very top of those files (client.pyw and server.pyw):

```python
#!/usr/bin/env python2
```

This will enable running them easily from the console (./client.pyw) or file manager (with a double click) on Linux.

**Comment by hydrusnetwork** [comment]
I'll do this, thank you.

**Comment by hydrusnetwork** [comment]
Finally getting around to actioning this stuff. This is done for v183, thank you for suggesting it.
