### ISSUE TITLE
Feature:API:Search URLs by prefix

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#240]
I for a variety of reasons need to get a list of URLs with a certain prefix from the known URL table.

I would like to be able to do this via the API and I want a list of URLs out, then I want to be able to get hashes associated to said URLs, so I can operate on the attached files.

It appears that the `system:known url` predicate can already do this with a regex, maybe you can just hijack that.

**Comment by floogulinc** [comment]
This has been added in https://github.com/hydrusnetwork/hydrus/releases/tag/v448 with the addition of system predicates in the API (#351).
