### ISSUE TITLE
Linux package for v147 is corrupt

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#26]
```
score@kirisame ~/src/hydrus-prebuilt % tar zxf Hydrus.Network.147.-.Linux.-.Executable.tar.gz

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
2 score@kirisame ~/src/hydrus-prebuilt % cd hydrus\ network                                                                                                            :(
score@kirisame ~/src/hydrus-prebuilt/hydrus network % ./client
zsh: no such file or directory: ./client
```
The package for v146 is okay.

**Comment by hydrusnetwork** [comment]
Thank you for this!

I think my ftp client must have cut it off when I was collecting the release and didn't tell me. I have reuploaded the file. The link should be the same, so please try it again.

I will ping my posts to let other Linux users know.

**Comment by ScoreUnder** [comment]
I should probably have closed this earlier: the v147 download is working now (and the newer ones work too).
