### ISSUE TITLE
Store post time for sorting chronologically.

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#263]
For lots of things like grabbing from a booru, post time both doesn't matter and is inaccurate.  However when using hydrus for various photostreams or OG gallery services which present post time it would be nice to be able to sort on that.

**Comment by Zweibach** [comment]
> For lots of things like grabbing from a booru, post time both doesn't matter and is inaccurate.

Comics are usually posted in order and it even has potential use in deduplication since the better version is usually posted after the inferior version, especially with revisions. So in my opinion it's quite useful for boorus too.

**Comment by walramb** [comment]
There's some real wrinkles to doing chronology in hydrus. If you end up importing the same thing from multiple sources or merging duplicates, you often get conflicting information.

Single-value fields (like "file modified") will only hold whatever it saw first, and if it's stored in tags, they'll get lumped together unless you give each separate source of timestamps an absurdly specific namespace or something.

**Comment by CuddleBear92** [comment]
Source time is already parsed on many of the parsers. 
The only issue is that it doesn't get saved atm.

There also needs to be an update mechanic for it so it only has one date.
It would need to update its date if there is a new earlier date parsed.
That way it will dynamically update if you get the original source parsed.

**Comment by Zweibach** [comment]
Could store it with URLs so you only have one time per URL but still allow you to have multiple per file. Then a system predicate for sorting, allowing you to specify stuff like "Show only first/last" or per domain/parser.

**Comment by CuddleBear92** [comment]
Hmmm connecting it to the URL would make perfect sense. This might be the right move.

**Comment by bbappserver** [comment]
I don't like the idea of overloading the URL system, you're not supposed to add artificial things to the URL, it's supposed to uniformly locate an external resource, if you go changing it it can't do its job.  Just introduce a seperate table, and jam a unix_timestamp integer into it.  That should be good enough.  If you encounter the same hash and its (HTTP `Last-Modified` is less than the current or parsed value is less than current) and parse value is not unreasonable (say before 1990 since the public web came out in 1993, then choose lower value.

**Comment by Zweibach** [comment]
My point was to connect an URL with time. I certainly don't know enough about how stuff is handled internally to say whether literally storing URL and post time together is a good idea. That's for dev to work out.

**Comment by bbappserver** [comment]
Chronology is also useful for manual alternate detection.

**Comment by hydrusnetwork** [comment]
First version of this rolls out today in v476. Let me know how it works out for you, there are several ways to expand on this.
