### ISSUE TITLE
Display overall progress when running file maintenance jobs

### ISSUE THREAD

**Issue by imtbl** [hydrusnetwork/hydrus#264]
When running certain file maintenance jobs, Hydrus only displays the progress for 256 files at once (see screenshot). This makes it hard to gauge how much longer the job will take approximately. In my opinion, displaying the overall progress for all files processed in the job would make more sense here.

![image](https://user-images.githubusercontent.com/28833155/85048501-ae409b80-b193-11ea-96e7-8775779a66c3.png)

**Comment by hydrusnetwork** [comment]
Thank you, I agree. I had forgotten that it did this. This should be updated to do x/y for total count for v402 tomorrow. Let me know if you get any borked numbers.
