### ISSUE TITLE
pyconfig.h

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#27]
What is pyconfig.h for? It's under "include" but is not included by the software itself. It looks like part of the build process for a python interpreter.

**Comment by hydrusnetwork** [comment]
I think my Linux release script is misfiring. Include is supposed to have the source files, in case someone wants to run from source despite it being the frozen exe release. Maybe PyInstaller changed cwd or something and my script broke. I'll look into it, thank you.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
