### ISSUE TITLE
Static context menu items being cut off

### ISSUE THREAD

**Issue by pozieuto** [hydrusnetwork/hydrus#276]
Some context menu items have predefined strings that are so long they're being cut off, making them difficult to read. Two examples:

![duplicates > preparation tab > gear menu](https://user-images.githubusercontent.com/67081751/85152346-6b8acc00-b244-11ea-89c8-0d6752538427.png)

![animated media](https://user-images.githubusercontent.com/67081751/85152349-6b8acc00-b244-11ea-9c3d-511fac0e6beb.png)

Hydrus version: 401
Platform: Windows 10 version 1909

**Comment by hydrusnetwork** [comment]
Thank you for this report. A little while ago, I instituted a menu-wide limit to 64 characters, as some very long dynamically generated strings here (such as the namespace file sort entries when you have a whole bunch of namespaces) were for some users going wider than monitor widths and causing unusual problems.

I was going to do a clever thing here, but I think the simpler better solution is to just double the limit up to 128 for v402 and see how we do. It should fix most of my hardcoded texts, like in your examples. Please let me know if you discover any more elided menus that looks like they shouldn't be in v402.
