### ISSUE TITLE
"No results" indicator

### ISSUE THREAD

**Issue by pozieuto** [hydrusnetwork/hydrus#277]
This request is for some kind of visual indicator that a search has completed and not returned any files. Presently, the thumbnail grid remains empty, so it's not immediately obvious to the user that a search has been performed at all, since it looks exactly as it did before they searched.

This could simply be some low-contrast text like "No results found" in the centre of the thumbnail area, Ideally, this text would fade in for a brief moment, like how the thumbnails do; this would cause a visual change when consecutive searches with no results are performed. It also seems intuitive that it would disappear as soon as a new search predicate is entered, which would make it obvious that the current search predicates have not actually been searched for yet, especially for when immediate search is turned off.

**Comment by ShadowJonathan** [comment]
Maybe something akin to the "How boned am I?" menu entry, in spirit? Something like an in-joke to appear in the background if no results are found, something really dumb and outdated like the lamp moth meme or something, but yeah.

**Comment by ShadowJonathan** [comment]
![](https://i.imgur.com/TqW4P2v.png)

**Comment by hydrusnetwork** [comment]
Thank you. Doing something fun, or simply adding a new results page with custom text/animation takes a little time, but I have set it for tomorrow's 402 to display a variety of 'no search done yet' and 'search cancelled!' and 'no results for this search' and 'no files for this highlighted query' type phrases into the status bar, where it would currently say '0 files' for most of these situations. I will close this issue with that, but if you find that is insufficient, please reopen this issue and I will plan something longer.
