### ISSUE TITLE
Downloader whitelist

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#279]
Creating this issue mostly to ensure it is not forgotten about.  
As per the changelog of v400:
> to reduce blacklist confusion, when you launch the edit blacklist dialog from an edit tag import options panel, now only the 'blacklist' tab shows, the summary text is blacklist-specific, and the top intro message is improved. a separate 'whitelist' filter will be added in the near future to allow downloading of files only if they have certain tags

I have a few Pixiv queries that catch way too much irrelevant stuff and adding to the blacklist all the time gets tiresome quick. Pixiv artists are not very good at tagging their work properly so I don't want to tighten the query either and risk missing things. Whitelist will allow me to add all the various series tags for the character I want, thereby letting me avoid having to delete boatloads of images of characters with the same name but from other series.

Creating a query for each unique tag combination is more effort than it's worth.

**Comment by hydrusnetwork** [comment]
Thank you. I did not manage to get to this this week, but I hope to have it done for 403.

**Comment by hydrusnetwork** [comment]
This should be done for tomorrow's release. It is a simple list off of tag import options, and if a to-be-imported-file has _any_ of the tags in the list, it is allowed. If the list is empty, it does nothing.
