### ISSUE TITLE
Build process is not open source

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#28]
This is probably the last issue in my spree :smile: 

Packages are provided at https://github.com/hydrusnetwork/hydrus/releases, but there is no indication of how to build them. There's a lot of .so files in the linux package and the "client" binary is cryptic in origin - I don't see any compilable code in the tree but it must have come from somewhere. It's not clear whether it's a launcher for system python, a python interpreter itself, or anything else.

In the interests of letting us contribute community fixes to issues like #7 I think it would be great to open source the scripts (or instructions) used to package the releases.

**Comment by hydrusnetwork** [comment]
The build process is currently a few scripts I hacked together that'll only work on my directory structure for each of the platforms I make releases on. It is basically a bunch of 'copy's and 'mkdir's with something like:

python "C:\code\pyinstaller-dev\pyinstaller.py" --windowed --icon="C:\code\Hydrus\static\hydrus.ico" --name="client" "C:\code\Hydrus\client.pyw"

Stuck on the front.

Generalising these scripts for any user's platform is a good idea. I will make a note to do it, for when I have the time.

I don't have much experience making releases for Linux, so I'll ask: Is there a way of making a release that'll run from source, where running a setup.py or makefile or _whatever_ will download and install all the required libraries, essentially automating what I have here:

http://hydrusnetwork.github.io/hydrus/help/running_from_source.html

?

**Comment by ScoreUnder** [comment]
I've had a stab at a wrapper script. It's not quite a package, but it's a different approach. It still requires, to some extent, manual installation of dependencies but I think most people would have the required things already. I've tested it on arch and torn my hair out trying to test it on ubuntu and eventually failed.
https://github.com/ScoreUnder/hydrus-from-source
It creates a virtualenv to run hydrus in, and ensures that anything else (wxpython, opencv) which can't run in the virtualenv is installed.

Ubuntu 14.04 really got on my bad side. I couldn't test because the freeglut3-dev package doesn't install, and apparently there's no way around that. Installing gentoo was less painful :|

**Comment by ScoreUnder** [comment]
For Arch Linux I've created an AUR package: https://aur.archlinux.org/packages/hydrus/

Note that it bundles with this patch to better support installation in a read-only /opt:

```diff
diff --git a/include/ClientConstants.py b/include/ClientConstants.py
index b73c44c..a446f94 100755
--- a/include/ClientConstants.py
+++ b/include/ClientConstants.py
@@ -2651,7 +2651,7 @@ class ThumbnailCache( object ):
             
             thumbnail = HydrusFileHandling.GenerateThumbnail( path, HC.options[ 'thumbnail_dimensions' ] )
             
-            resized_path = HC.STATIC_DIR + os.path.sep + name + '_resized.png'
+            resized_path = HC.TEMP_DIR + os.path.sep + name + '_resized.png'
             
             with open( resized_path, 'wb' ) as f: f.write( thumbnail )
             
@@ -3018,4 +3018,4 @@ class VPTreeNodeEmpty( object ):
     def __len__( self ): return 0
     
     def GetMatches( self, phash, max_hamming ): return []
-    
\ No newline at end of file
+    
diff --git a/include/ClientGUI.py b/include/ClientGUI.py
index 5e5bc87..0c7e2e2 100755
--- a/include/ClientGUI.py
+++ b/include/ClientGUI.py
@@ -1828,7 +1828,7 @@ The password is cleartext here but obscured in the entry dialog. Enter a blank p
             elif command == 'fetch_ip': self._FetchIP( data )
             elif command == '8chan_board': webbrowser.open( 'http://8ch.net/hydrus/index.html' )
             elif command == 'file_integrity': self._CheckFileIntegrity()
-            elif command == 'help': webbrowser.open( 'file://' + HC.BASE_DIR + '/help/index.html' )
+            elif command == 'help': webbrowser.open( 'file:///opt/hydrus/help/index.html' )
             elif command == 'help_about': self._AboutWindow()
             elif command == 'help_shortcuts': wx.MessageBox( CC.SHORTCUT_HELP )
             elif command == 'import_files': self._ImportFiles()
@@ -3148,4 +3148,4 @@ class FrameSplash( ClientGUICommon.Frame ):
         
         dc.DrawText( text, x, 200 )
         
-    
\ No newline at end of file
+    
diff --git a/include/ClientGUIDialogs.py b/include/ClientGUIDialogs.py
index 0ae986f..a492f32 100755
--- a/include/ClientGUIDialogs.py
+++ b/include/ClientGUIDialogs.py
@@ -632,7 +632,7 @@ class DialogFirstStart( Dialog ):
         def ArrangeControls():
             
             message1 = 'Hi, this looks like the first time you have started the hydrus client. Don\'t forget to check out the'
-            link = wx.HyperlinkCtrl( self, id = -1, label = 'help', url = 'file://' + HC.BASE_DIR + '/help/index.html' )
+            link = wx.HyperlinkCtrl( self, id = -1, label = 'help', url = 'file:///opt/hydrus/help/index.html' )
             message2 = 'if you haven\'t already.'
             message3 = 'When you close this dialog, the client will start its local http server. You will probably get a firewall warning.'
             message4 = 'You can block it if you like, or you can allow it. It doesn\'t phone home, or expose your files to your network; it just provides another way to locally export your files.'
@@ -5911,4 +5911,4 @@ class DialogYesNo( Dialog ):
         if event.KeyCode == wx.WXK_ESCAPE: self.EndModal( wx.ID_NO )
         else: event.Skip()
         
-    
\ No newline at end of file
+    
diff --git a/include/HydrusConstants.py b/include/HydrusConstants.py
index 0d3c649..ba72da8 100755
--- a/include/HydrusConstants.py
+++ b/include/HydrusConstants.py
@@ -3,9 +3,9 @@ import sys
 
 # dirs
 
-BASE_DIR = sys.path[0]
+BASE_DIR = os.path.expanduser("~/.local/share/hydrus")
 
-BIN_DIR = BASE_DIR + os.path.sep + 'bin'
+BIN_DIR = "/opt/hydrus/bin"
 DB_DIR = BASE_DIR + os.path.sep + 'db'
 CLIENT_ARCHIVES_DIR = DB_DIR + os.path.sep + 'client_archives'
 CLIENT_FILES_DIR = DB_DIR + os.path.sep + 'client_files'
@@ -16,9 +16,14 @@ SERVER_MESSAGES_DIR = DB_DIR + os.path.sep + 'server_messages'
 CLIENT_UPDATES_DIR = DB_DIR + os.path.sep + 'client_updates'
 SERVER_UPDATES_DIR = DB_DIR + os.path.sep + 'server_updates'
 LOGS_DIR = BASE_DIR + os.path.sep + 'logs'
-STATIC_DIR = BASE_DIR + os.path.sep + 'static'
+STATIC_DIR = "/opt/hydrus/static"
 TEMP_DIR = BASE_DIR + os.path.sep + 'temp'
 
+for dirs in [LOGS_DIR, TEMP_DIR, DB_DIR]:
+    try:
+        os.makedirs(dirs)
+    except os.error:
+        pass
 #
 
 PLATFORM_WINDOWS = False
@@ -2810,4 +2815,4 @@ sqlite3.register_adapter( ServerToClientUpdate, yaml.safe_dump )
 
 sqlite3.register_converter( 'BLOB_BYTES', str )
 sqlite3.register_converter( 'INTEGER_BOOLEAN', integer_boolean_to_bool )
-sqlite3.register_converter( 'TEXT_YAML', yaml.safe_load )
\ No newline at end of file
+sqlite3.register_converter( 'TEXT_YAML', yaml.safe_load )
diff --git a/include/HydrusServerResources.py b/include/HydrusServerResources.py
index 37f4388..a4dec1d 100644
--- a/include/HydrusServerResources.py
+++ b/include/HydrusServerResources.py
@@ -762,11 +762,11 @@ class HydrusResourceCommandBooruThumbnail( HydrusResourceCommandBooru ):
         mime = media_result.GetMime()
         
         if mime in HC.MIMES_WITH_THUMBNAILS: path = CC.GetThumbnailPath( hash, full_size = False )
-        elif mime in HC.AUDIO: path = HC.STATIC_DIR + os.path.sep + 'audio_resized.png'
-        elif mime in HC.VIDEO: path = HC.STATIC_DIR + os.path.sep + 'video_resized.png'
-        elif mime == HC.APPLICATION_FLASH: path = HC.STATIC_DIR + os.path.sep + 'flash_resized.png'
-        elif mime == HC.APPLICATION_PDF: path = HC.STATIC_DIR + os.path.sep + 'pdf_resized.png'
-        else: path = HC.STATIC_DIR + os.path.sep + 'hydrus_resized.png'
+        elif mime in HC.AUDIO: path = HC.TEMP_DIR + os.path.sep + 'audio_resized.png'
+        elif mime in HC.VIDEO: path = HC.TEMP_DIR + os.path.sep + 'video_resized.png'
+        elif mime == HC.APPLICATION_FLASH: path = HC.TEMP_DIR + os.path.sep + 'flash_resized.png'
+        elif mime == HC.APPLICATION_PDF: path = HC.TEMP_DIR + os.path.sep + 'pdf_resized.png'
+        else: path = HC.TEMP_DIR + os.path.sep + 'hydrus_resized.png'
         
         response_context = HC.ResponseContext( 200, path = path )
         
@@ -1238,4 +1238,4 @@ class HydrusResourceCommandRestrictedUpdate( HydrusResourceCommandRestricted ):
         
         return response_context
         
-    
\ No newline at end of file
+    
```

The "no newline at end of file" stuff is due to my choice in text editor - vim automatically ensures that files end in a newline character, since every line must end in a newline according to posix standards (http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206)

**Comment by eider-i128** [comment]
Here's simple script for building Hydrus on Windows: https://gist.github.com/eider-i128/f5e3ee221eb4669dffad

Hydrus requires:
-Python 2.7 x86
-PyInstaller
-Visual Studio C++ Compiler for building some modules (MinGW can work too)

And these modules:
-pysqlite
-pycrypto
-pyaml
-wxpython
-beautifulsoup4
-lz4
-psutil
-send2trash
-socks
-pafy
-hsaudiotag
-mp3play
-PyPDF2
-numpy
-cv2 (OpenCV)
-PIL (Pillow fork)
-flvlib
-twisted
-python-potr

SQLite should be built from sources to include support for FTS3/FTS4, or you can just copy-paste sqlite.dll from latest Hydrus Release.

OpenCV can be either fully installed or just copy-paste cv2.pyd (~20MB) from package http://sourceforge.net/projects/opencvlibrary/files/ (it's under build/python/2.7/x86) to your Python/Lib/site-packages. If you do this, you'll need to copy cv2.pyd (5MB) and opencv_*.dll from latest Hydrus Release to your directory.

Given you installed all required tools and modules, you should be able to download Hydrus source, put build.bat i created inside and execute it from CMD. Results will be saved to /dist and should be copied to main directory.

**Comment by eider-i128** [comment]
Hey again. I decided to make it even easier to build Hydrus on Windows, so i prepared complete environment - http://i32.pl/hydrus-win.rar

The source code goes to */source*. build.bat should be executed from cmd to see result, clean.bat does housekeeping if you want to compiler another version or upgraded source. To work, it requires Python 2.7 x86 with modules i listed in comment above. PySQLite can be skipped as my environment contains correct sqlite3.dll. OpenVC should be installed by copy-paste of http://i32.pl/cv2.pyd (i just extracted file from http://sourceforge.net/projects/opencvlibrary/files/ since it's quite big) to Python/Lib/site-packages. Again, no need to think about opencv_*.dll as my env also contains correct versions and will copy them.

And here's my Python2.7 installation made for Hydrus - it contains all requires modules: http://i32.pl/Python27.rar (refer to it in case you have problems with your installation or any modules)

**Comment by eider-i128** [comment]
And it's me again. This time i'll just leave this link here: https://github.com/eider-i128/hydrus-win

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
