### ISSUE TITLE
Make tag parents virtual to prevent parent cascades

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#283]
Currently (according to the PTR janitors), a parent is applied directly to items, rather than being derived when needed.  This has a really regrettable consequence with bad siblings.

If there is a sibling relationship
`a=b=c=d`

Let there exist a tag e, which is too ambiguous to be a sibling of d, but for whatever reason 
`d=e`
gets accepted in the PTR

Let there exist foo and there is the parent relationship
`e->foo`

Now even though we know e is not sufficiently unambiguous to equal d and its siblings, it is now true that.
```
a->foo
b->foo
c->foo
d->foo
e->foo
```
And this cannot be automatically undone, because foo is literally applied to all items tagged with a through e, instead of being a virtual tag.

Ideally when foo is searched for it should expend its ancestors and just search for them or itself, instead of all items actually taking on the tag of foo.  This way the sibling correction also corrects the erroneous parent cascade, because the tag foo is not actually applied to works with all the other siblings.

**Comment by bbappserver** [comment]
Compounding this issue if `foo->bar` then [a-e] also gets `bar`.

**Comment by DonaldTsang** [comment]
In this case how bad can things go?
