### ISSUE TITLE
Client Can Disappear When Toggling From Remote Desktop [Windows 10]

### ISSUE THREAD

**Issue by GoAwayNow** [hydrusnetwork/hydrus#284]
## Environment

Hydrus version: 401
Platform: Windows
OS specifics: Windows 10 Pro Build 18362

## Steps to reproduce

1. Connect to PC via remote desktop
2. Leave client visible in tablet mode
3. Access desktop on PC

## Describe what you expected to happen
Client should appear on main desktop

## What actually happens
The client is still running, but is inaccessible. By holding shift and right-clicking the icon in the taskbar, it can be interacted with in limited fashions. I can toggle between maximized and restored, and the preview that pops up shows the difference between these modes without problem. By choosing to move the client while restored, it can be shown that the client does still have a location and size.
In this situation, the client can be recovered by accessing it in tablet mode and minimizing it to the toolbar.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I do not have much experience with remote desktop, but I will do some research into why this could be happening. If I can fix it my end, I will.

**Comment by GoAwayNow** [comment]
No longer occurs v431.
