### ISSUE TITLE
Show most recently viewed files

### ISSUE THREAD

**Issue by arisune** [hydrusnetwork/hydrus#286]
Having the option to show the X number of most recent viewed files would be quite nice, maybe including being able to sort them by last viewed

**Comment by LustWolf** [comment]
Should this be closed out since it looks like this can be accomplished from the main window by:

**Sort:**
- sort by views -> views -> media views
- choose ascending or descending

**Populate:**
- system:file viewing statistics

**Comment by imtbl** [comment]
@LustWolf 

That doesn't seem to do quite the same thing. With `system:file viewing statistics`, you can limit the search to files with views/viewtime > x. And combined with sorting by views, you could then, for example, _show all files with more than 100 viewes and sort them ascending_.

But this doesn't touch on the _most recently viewed_ aspect of this feature request.

**Comment by LustWolf** [comment]
@imtbl Ah, I misread.
Reading through all of the open issues in one sitting must have made my eyes play tricks on me.

**Comment by hydrusnetwork** [comment]
Hey, this should now be possible. The client now tracks the last time you saw a particular file, and you can search (system:time) and sort by this value.
