### ISSUE TITLE
Duplicate 'eff both files' option

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#290]
Ok, I am running duplicate filters, everything's going fine, till I get to a file that is just 'eff them both' so my only option is to full stop the parsing and go though deleting both files. I feel this a bit cumbersome

One work around I have found was make a rating and call it "z Hide Duplicates" and make a macro that would rate, go to next image, rate, go to next pair. 

This works but I think it could be done with one button, in fact I think if this was just an option in the duplicate finder to apply to both, this would greatly help parsing

My thought is
1) a remove from duplicates action that can be associated with what it does next, applied at the end of a parse chunk
2) make the removed from duplicates surchargeable and resettable with ease (getting duplicates I already did to show up as duplicates, something I did as a test, was a pain in the ass to do)
3) With this custom action to apply to both files allow the ability to rate or tag, my work around example above is remove from dup is a pool of CYOA games that I want to parse later on not though dup filters but easily able to bring them into dup filters once I have done the initial parse without the need to rely on a macro to hit both files, and it would also allow me to have, let's give an example, a stomp fetish snuff image tagged 'completely appealing' while also having it completely removed from the duplicate pool. 

I think this would be a useful tool for everyone given it would allow you to do more with less clicks

**Comment by pozieuto** [comment]
I'm not sure that I follow. What do you need that you can't accomplish by deleting the files when they appear in the filter, or by narrowing down the duplicate filter search before launching the filter?

**Comment by alidan** [comment]
more or less, I see deleting them as flow breaking, because instead of just pressing 1 button to make a decision, I have to delete, delete both, permanently delete, pick my reason, ok it, wait for it to go though and then go back to filtering, in the case of my example image, it was 3 images back to back that I would have loved to just say 'eff both files' and marked them so I could get rid of them in bulk later then doing the same action 3 times

to rate both files

I need to hotkey, next file, hotkey, skip file and hope the program did not have a hiccup

what im saying is instead of that, a hotkey that applies a rating/tag/and or removes it from dup filters with 1 button

the rating/tag applies to both and moves on, an in program single hotkey action, and or, a remove from dup filter system tag like thing, this would remove the need to go out of the dup filter and add whatever tag to assigned it each time you start the filter, and by having it a searchable flag, you would be able to deal with all of the files in one go.

like I said above, it would be nice to be able to get rid of the files faster, and a side effect of it would be other scenarios like the cyoa's that I don't want to put through duplicate filters yet can also be handled the same way. 

I assume the hotkey would go something like this
[what is the hotkey] [is there a tag or rating?] [remove from dup?]

**Comment by Zweibach** [comment]
I feel like this suggestions suffers a bit from going away from the title. You start with deletion, goes into ratings and macroes and custom actions. Restructure and split this into multiple suggestions or rename the issue to reflect your desires better.

You can do some pre-dupe work by specifically tagging things you don't want to dupe check with everything else and then exclude that tag from the dupe filter search. In your case, tag all CYOAs with `cyoa` or whatever and then just enter `-cyoa` in the dupe filter to avoid dupe checking them or `cyoa` to dupe check CYOAs.

> I have to delete, delete both, permanently delete, pick my reason, ok it, wait for it to go though and then go back to filtering

A configurable quick delete button would definitively be appreciated.

**Comment by pozieuto** [comment]
Yes, the deletion workflow in the duplicates filter could be sped up a bit with duplicate_filter_delete_this and duplicate_filter_delete_both shortcuts.

The rest of this seems like it would be best addressed with richer duplicate filter action customization, which is more generally useful. It would enable this workflow if you could combine "skip" and "apply these tags on this service for these files" in a custom action, for instance.

**Comment by alidan** [comment]
@Zweibach not really, I think it sticks with it, my examples are 
1) I want both gone
2) I dont want to filter these files this way
In both cases a button that does X (where x being tag, rate, or a searchable 'removed from duplicates' system setting) that hits both files, my use case however ends up with me telling telling both files to get the hell out of duplicates, i'll deal with you a different way, one though a hard 'im deleting you later on' and the other though a rating that I would exclude from dups searches because I will deal with it a different way. 

the Problem with tagging assumes that every file is properly tagged or rating up front. part of the reason im doing dups is to hard cull files in a way that makes subsequent culls FAR easier on me because its kind of a mind eff to be awake for 20+ hours, culling files if you like something or not, but see the same file pop up over and over again, but when you check its rating (I use a star system from 0-10 with a +1 rank button so I know if that file has gone through a cull more than once) only to see this is the first time you saw the files. 

more or less, I cant see a reason for this function besides to remove the files from duplicates, however I can think of several reasons to exclude from duplicates. 
1) hard deletion of files, which would be easier to do all at once rather then a case by case basis
2) my cyoa example, some of these things are 70+ files long, but when they are posted to threads they are in order, or if not in order, grouped together in a tagable way where I could tag them (cyoa) and (cyoa name) and (cyoa version), if I deal with these files in duplicates then there is no way I am going to be able to tag or group just due to how spread out everything is and it would be more of a nightmare than it already is. 

Those are 2 reasons I can think of for wanting to exclude from duplicates, and a reason for a tag/rate for both to also be applied. you could remove the system flag/tag/whatever for removing from duplicates and instead go through the tag system and have a delete file flagged with a (System:Pending Deletion) tag that would be searchable. with that, it would also probably be a good idea to have duplicate windows come with some pre filled out filters, just because 99.9% of the time you will be adding those filters anyway, may as well have them pre added. 

I think this way with tags and ratings you would cut out some of the harder stuff and if there was a pre applied filters it should be easy for user customization. 

@pozieuto personally I like the idea of deletions as a batch and user confirmable, when culling I have several rating that are dedicated to deletion and reasons for it, this allows me to easily give a quick once over and apply the deletion reason to several hundred files at a time.
