### ISSUE TITLE
DeviantArt extended_fetch Parser Fails on Some Deviations

### ISSUE THREAD

**Issue by GoAwayNow** [hydrusnetwork/hydrus#295]
I originally submitted the extended_fetch parser, and when I was making it, a lot of the different url-grabbing methods were there just to bandage strange things that the DA backend does. Well, Hecko on Discord found some that I'd missed.

The pieces that are missed use the media/baseUri element alone to provide a functional url, while this url alone on any other work would cause a 403, so it has to be placed at the bottom of the order to keep the parser from erroring-out on valid works.

This content parser fixes the issue.
https://cdn.discordapp.com/attachments/471400633237241906/724838716715171870/Deviantart-extended-fetch-media-url-no-token-content-parser.png

**Comment by hydrusnetwork** [comment]
Thank you, I will roll this in tomorrow morning for 403.
