### ISSUE TITLE
Menu sub-items not triggered when you start holding left mouse button on their parent

### ISSUE THREAD

**Issue by AlexCSDev** [hydrusnetwork/hydrus#296]
## Environment

Hydrus version: 401
Platform: Windows
OS specifics: Windows 10 x64 version 1909

## Steps to reproduce

1. Choose any menu item with sub-items (top menu, right-click menu on files)
2. Hold your left mouse button while hovering on this menu item
3. Move your mouse cursor on any sub-item and stop holding left mouse button. Nothing will happen.

## Describe what you expected to happen
Starting with version 402 Hydrus overrides default OS behavior. Highlighted menu item should be triggered regardless of when you have started holding left mouse button.

## Error message / Log file
None

**Comment by imtbl** [comment]
I assume it's either a bug or a change in a recent Qt release (HyDev bumped the bundled Qt in the prebuilt Hydrus versions from `5.13.2` to `5.15` in `402`).

If that's the case, HyDev would have have to check if it's possible to restore the previous behavior.

In any case, I'll label this with `upstream` for now as it's likely not a Hydrus-related issue per se.

**Comment by thatfuckingbird** [comment]
It's a regression in Qt 5.15.0, see https://bugreports.qt.io/browse/QTBUG-85166
5.15.1 will have the fix

**Comment by hydrusnetwork** [comment]
Thank you, Windows and Linux builds are moving up to 5.15.1 tomorrow. Seems to fix the menu thing!
