### ISSUE TITLE
Tiered Inbox/Archive/Trash Boxes

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#298]
I often find myself wanting multiple levels of archive/delete filter.

For example 
```
...
trash2=-3
trash1=-2
trash0=-1
Inbox=0
archive0=1
archive2=2
archive3=3
...
```
Where I consider which are more archived to have better tags or to be by a favourite author, and things in deeper levels of trash to be candidates for deletion sooner, because I am very sure I meant to put them there, whereas in trash0 it may have been in accident.

Implementation wise this seems simple, encode the archive inbox trash status as a single tinyint.  Change the behaviour of the archive button to
```py
def event_archive():
 for x in selection:
  if x.status<0: x.status=1 else: x+=1
  x.save()
```
and trash to
```py
def event_archive():
 for x in selection:
  if x.status>0: x.status=-1 else: x-=1
  x.save()
```

**Comment by DonaldTsang** [comment]
Going from Inbox => short term => long term archive instead of Inbox => archive?

**Comment by Zweibach** [comment]
> Hydrus Developer: I'm happy with inbox/archive as it is. anything more complicated, I recommend setting up your own tag/rating workflow. better I spend my time on adding custom archive/delete filters so you can filter according to your own shit, rather than hardcoding new archive/inbox states

**Comment by hydrusnetwork** [comment]
For now, if you want more complicated processing workflows, please set up tags or starred ratings to emulate the behaviour you want. I think ratings may do very close to what you want here. You can set up some shortcuts too, to make it faster.

I plan to 'generalise' the archive/delete filter in the future, letting you set your own rules for what happens on your 'action and move on' clicks, at which point you could set up something like 'increment archive rating and move on'.
