### ISSUE TITLE
Infinite loop when processing parent posts in galleries

### ISSUE THREAD

**Issue by Suika** [hydrusnetwork/hydrus#302]
## Environment

Hydrus version: 402
Platform: all
OS specifics: none

## What happens

The newly addes sub-gallery type url allows to work with galleries that create gallery urls.
In this case specific case, the parser fetches a parten ID from a post, creates a sub-gallery url and sends it to the gallery downloader.
And that creates an infinite loop of endless queries: process post > get parent > process parent > get post > process post > get parent > back to the beginning

And the urls generated are... always chaning. See Screenshots.

## Steps to reproduce

1. Import the downloaded down below
2. open gallery download and select "sankaku chan beta tag search"
3. query this "parent:20924245"

![sankaku705](https://user-images.githubusercontent.com/2320837/85933378-e481c780-b8c5-11ea-8124-2603fe6f3097.png)

## Desired outcome
Finite process.

## Error message / Log file / Screenshots
![client_KrgrWjxlDC](https://user-images.githubusercontent.com/2320837/85933413-39bdd900-b8c6-11ea-97da-929df71b4c88.png)

**Comment by hydrusnetwork** [comment]
Info: We have been talking about this issue in discord. I have a solution in mind involving adding a token to gallery runs to break loops but still allow duplicate entries in gallery logs.

**Comment by hydrusnetwork** [comment]
Should be fixed for 403. As we discussed elsewhere, each new gallery run now creates a unique token id, which is passed down to new URLs in the same run. The deduplication hash of items in the gallery log is now (url, token), so repeat URLs in a single run shouldn't be added. Let me know how it works for you.
