### ISSUE TITLE
Feature: Summary/description/transcript field

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#31]
For things like this: http://a.pomf.se/olcgdt.jpg
They are probably easier to remember by their text than any defining characteristic about them, and it just seems wrong to tag something with its text. I would like a larger field (searchable via the normal means) where I can just dump text like that so that I can find images by their text.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
