### ISSUE TITLE
Double Middle-clicking page title(to close two pages) asks to rename instead

### ISSUE THREAD

**Issue by Aegis43615** [hydrusnetwork/hydrus#314]
##  Environment

Hydrus version: 402
Platform: Windows
OS specifics: Win x64 10 Pro 1909

## What happens

The first page is closed, however on the second middle-click, the second page will instead give a pop-up asking if you would like to rename it. Likely from the feature added a few versions ago to allow quick renaming when page title is double-clicked.
## Steps to reproduce

1.Open multiple pages
2.Middle-click the title of the page to close two pages very quickly in succession without moving mouse location (aka close the page under mouse then the second one that slides to the left)

## Desired outcome

Close both pages normally

## Error message / Log file / Screenshots

![image](https://user-images.githubusercontent.com/67392701/85963075-06408480-b982-11ea-8f70-0b0adf92f1db.png)

**Comment by hydrusnetwork** [comment]
Thank you for this report. I will fix this.

**Comment by hydrusnetwork** [comment]
This should be fixed for tomorrow. Rename will no longer be triggered, and I _think_ middle-clicks are registering as singles even if spammed fast enough to be detected as double-clicks.

**Comment by hydrusnetwork** [comment]
I messed this up, will fix in 405. Sorry for the inconvenience!

**Comment by Aegis43615** [comment]
No problem at all, like I said its just QoL so not very important. Just for What currently happens now is that the first page will close, then the second will stay open and then a few seconds later throw the following error:

UnboundLocalError
local variable 'index' referenced before assignment
  File "hydrus\client\gui\QtPorting.py", line 437, in mouseDoubleClickEvent
    self.tabMiddleClicked.emit( index )

**Comment by hydrusnetwork** [comment]
As always:

- Test this problem, figure it out
- Implement a solution
- Test it, it works, great
- Ah, that code looks bad, I'll just 'neaten' it before I move on
- Completely mess it up
- Wednesday, looking at my todo, which says 'test everything again, just in case'
- Nah, it is fine, I tested it just last night

Every time, ha ha

**Comment by hydrusnetwork** [comment]
Ok, legit fixed for 405. Thank you for your patience.
