### ISSUE TITLE
Configurable sync time for Hydrus server

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#318]
Make sync time configurable instead of being harcoded. Also remove it from the client and rely on the server telling the client when sync will take place.

An option for repo update file creation/sync.
To not do the 24hours or something for each sync.
This is mostly for self-hosted repos.

**Comment by hjri** [comment]
I'm trying to use hydrus across several machines (laptop+desktop), so I'm experimenting with hosting it on LAN on a FreeNAS Linux VM and syncing clients to it (bonus points for storing DB in a ZFS dataset in RAID10 + snapshots).

At the very least it would be nice to have a "manual sync" option or something like that.

**Comment by Xlaits** [comment]
> I'm trying to use hydrus across several machines (laptop+desktop), so I'm experimenting with hosting it on LAN on a FreeNAS Linux VM and syncing clients to it (bonus points for storing DB in a ZFS dataset in RAID10 + snapshots).
> 
> At the very least it would be nice to have a "manual sync" option or something like that.

There's a button for it if you enable Advanced Features, but it doesn't seem to function. (grayed out)

**Comment by Zweibach** [comment]
> There's a button for it if you enable Advanced Features, but it doesn't seem to function. (grayed out)

I presume you're talking about "download now" or whatever it's named and no, it doesn't do what you think it does. Nothing can happen until the server generates an update to download.

**Comment by Xlaits** [comment]
> > There's a button for it if you enable Advanced Features, but it doesn't seem to function. (grayed out)
> 
> I presume you're talking about "download now" or whatever it's named and no, it doesn't do what you think it does. Nothing can happen until the server generates an update to download.

Fair enough.

**Comment by Zweibach** [comment]
Added in v435.
