### ISSUE TITLE
System like archive/delete filter for quick like/dislike tagging.

### ISSUE THREAD

**Issue by PurpleAzurite** [hydrusnetwork/hydrus#322]
Quite self-explanatory. I'd like to see a system similar to the way archive/delete filter works. Left click would tag liked and right click would tag disliked. Ducks rule the world.

**Comment by vickyorlo** [comment]
Already possible by using the hilariously underdocumented and hidden shortcuts feature (there's a shortcut button in the top panel of the media viewer).

**Comment by PurpleAzurite** [comment]
I'm aware of the shortcuts in media view. That's still not fast enough for my workflow, and tbh honest all these floating UI elements are a real pain to use in a tiling window manager setup in linux. But that requires it's own ~~rant~~ issue. I will get around to writing it later.

**Comment by rachmadaniHaryono** [comment]
i kinda want it

my current workflow is:

- to return all images to inbox, 
- run archive/delete filter, 
- tag on archived image
- archive all image once again

this is not possible if some image are mixed between archived and in inbox

**Comment by Zweibach** [comment]
Folded this into issue #262 since it seems I didn't state the intent included ratings and this was almost a duplicate issue.

**Comment by bbappserver** [comment]
> I'm aware of the shortcuts in media view. That's still not fast enough for my workflow, and tbh all these floating UI elements are a real pain to use in a tiling window manager setup in linux. But that requires it's own ~rant~ issue. I will get around to writing it later.

You can make a selection, and then use the context menu to select manage>ratings, and apply the star all at once.
