### ISSUE TITLE
Inconsistent behavior based on selections in selection tags

### ISSUE THREAD

**Issue by Trizkat** [hydrusnetwork/hydrus#325]
## Environment

Hydrus version: 402 - Extract Only
Platform: Windows
OS specifics: Windows 10 Pro 1803

## What happens

When selecting fewer than all tags in the selection tags box. There appears to be four options in the copy submenu: selected, selected subtags, all tags, and all tags with counts.

When selecting all tags, the last two options disappear.

This was done without any images being selected.

## Steps to reproduce

1. Select one or more tags, but fewer than all, inside the selection tags box.
2. Right click and look in the copy submenu
3. Repeat step 2, but with all the tags selected
4. There should be a difference of 2 options missing.

## Desired outcome

That all the options appear regardless if only one, all or anything between that, number of tags are selected.

**Comment by hydrusnetwork** [comment]
Thank you. When all the tags are selected, 'copy selected' and 'copy all' are the same, so I think that is why it is hiding the 'all' entries in this case. I try not to show duplicate menu entries.

Would you rather in this special case that it was the 'selected' labelling that was hidden, to let you know that your selection is indeed everything?

Shall I also add a 'copy selected (with counts)' option, so you can always get tags with counts?

Now I look at it, I think it should be easy to also add a little 'copy n selected tags' number, just so you have a feeling of how many are selected.

**Comment by Trizkat** [comment]
Copy n selected tags would be neat!

**Comment by hydrusnetwork** [comment]
Ok, this should be sorted for tomorrow's 407. You can now basically do any combination of selected/all, tags/subtags, no_count/with_counts. A couple of situations, like copying subtags with counts, doesn't do a nice count merge, but it should generally work. Let me know if you have any trouble with it.
