### ISSUE TITLE
Move "<file type>_resized" images out of STATIC_DIR

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#33]
Since these images get overwritten every startup and whenever the thumbnail size option changes (I think - I haven't checked that), I think these should be in TEMP_DIR. More to the point, when packaging this software it's necessary to separate files that should be read-only and files that should be writable, and having the "static" directory contain both complicates things. See #28.

**Comment by hydrusnetwork** [comment]
Thank you for this. I am not sure when I removed this stuff, but there doesn't seem to be anywhere left that writes to static_dir. I have also now removed the resized stuff from the local booru's thumbnail server, which seems to be the last place it was (incorrectly) referenced.
