### ISSUE TITLE
Shortcut to cycle between tag repositories in the manage tags window

### ISSUE THREAD

**Issue by thatfuckingbird** [hydrusnetwork/hydrus#330]
Many times I want to add some local and some PTR tags too. Would be much faster if I didn't have to use the mouse to switch between the tag repo tabs.

**Comment by pozieuto** [comment]
If ctrl [+ shift] + tab doesn't already switch between those tabs, maybe it could just use those, at least for when the related / recent tags area isn't in focus.

**Comment by thatfuckingbird** [comment]
It does. Thank you, I didn't know about this.
