### ISSUE TITLE
Being able to filter by tags when opening files in new page.

### ISSUE THREAD

**Issue by PurpleAzurite** [hydrusnetwork/hydrus#334]
In the current implementation, when you select a bunch of files and have them opened in a new page, you are not able to filter by tags. Having tag selection available would open up more workflow options.

**Comment by Mengmoshu** [comment]
I literally wished for that within the last 24 hours.

**Comment by pozieuto** [comment]
Perhaps a good solution would be to just make these actions create a normal files page that has a pre-populated `system:hash=` predicate.

**Comment by walramb** [comment]
One way this could be solved is if users could filter the existing contents of any page on the fly based on what's already there, without doing a "fresh" database lookup. I think that would be useful for speedy workflows inside watchers and search pages too. Not sure if my suggestion is different enough to warrant a new wish

**Comment by Zweibach** [comment]
We have this since some versions ago.
