### ISSUE TITLE
Client API: more file metadata

### ISSUE THREAD

**Issue by thatfuckingbird** [hydrusnetwork/hydrus#345]
* Time imported and whatever other metadata is not currently returned by the file_metadata endpoint
* ~~API endpoints to get duplicate/alternate group info~~ Also see #347

**Comment by rachmadaniHaryono** [comment]
> API endpoints to set duplicate/alternate group info

i wish this was also included

i have script to rotate image but i have to manually set original image and rotated image as possible pair manually to merge metadata

**Comment by thatfuckingbird** [comment]
I've split out the alternate/dupe part into a separate issue since these would have to be separate API endpoints. See #347

**Comment by thatfuckingbird** [comment]
Time imported is returned now, not sure what else is missing if anything.
Closing for now.
