### ISSUE TITLE
Feature: Option to open in an external viewer by default

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#35]
I like viewing images in feh, but as of yet there isn't a way to just double click an image tile and have it open in feh. Currently I need to right click and click the button that opens it in an external viewer, while I would like to be able to set an option to just double click and have that work.

**Comment by hydrusnetwork** [comment]
I think you can set this now in _options->media->mime->do not show in the media viewer. on thumbnail activation, open externally_. Let me know if it doesn't work for you!

**Comment by ScoreUnder** [comment]
This works for showing the image externally, but it also removes the thumbnail.
