### ISSUE TITLE
Microsoft Office document formats treated as plain .zip files

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#362]
To reproduce:

Import any new Office Document format file (e.g. .docx for Word, .pptx for PowerPoint, .xlsx) into Hydrus.

**Expected**

.docx, .pptx and the like get imported and recognized as a document format, or rejected for not being one of the supported file types.

**Actual**

Hydrus treats these as ordinary ZIPS, and the association is lost.  (technically they **are** ZIPs with XML and other files, I don't know if they have a MIME type)

**Notes**

- I don't know if the same thing happens for old school .doc, .ppt, .xls, and so on.   
- It might do this for other formats that are technically ZIP, like Adobe Animate or Captivate source files, but I don't have any to try.

.pdfs do work as expected.

For reference, some Office MIME types may be found here: https://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc

**Comment by imtbl** [comment]
> I don't know if the same thing happens for old school .doc, .ppt, .xls, and so on.

Shouldn't happen for those as they are not Office Open XML documents.

**Comment by bbappserver** [comment]
Not a bug for .docx .pptx .xlsx etc files (note trailing x)
> Office Open XML documents are stored in Open Packaging Convention (OPC) packages, which are **ZIP files** containing XML and other data files, along with a specification of the relationships between them.[2] Depending on the type of the document, the packages have different internal directory structures and names. An application will use the relationships files to locate individual sections (files), with each having accompanying metadata, in particular MIME metadata.
https://en.wikipedia.org/wiki/Office_Open_XML_file_formats
> I don't know if the same thing happens for old school .doc, .ppt, .xls
 It shouldn't

**Comment by Zweibach** [comment]
Not actually a bug. Added request for Open Office XML document support to the filetype issue #261.
