### ISSUE TITLE
ISO time hyphen/slash inconsistency

### ISSUE THREAD

**Issue by walramb** [hydrusnetwork/hydrus#369]
The setting for absolute time stamps claims to use the ``YYYY-MM-DD`` ISO date format, but it's apparently actually using the slash-separated, slightly incompatible ``YYYY/MM/DD`` format.
I checked the code to make sure it's not related to my locale and it looks like the ``ConvertTimestampToPrettyTime`` function is hardcoded to use slashes.

This could lead to some minor mishaps if a user tries to copy-paste a stamp into a place that wants real ISO.

**Comment by bbappserver** [comment]
ISO 8601 for reference

**Comment by hydrusnetwork** [comment]
Thank you, this is fixed for tomorrow's 407.
