### ISSUE TITLE
allow exporting/importing urls as tags/to tag text file

### ISSUE THREAD

**Issue by puphime** [hydrusnetwork/hydrus#377]
My process involves exporting, editing and reimporting a lot of content and while I am able to keep the tags by exporting with a sidecar text file, the source URLs are lost forever in the process
I would like for hydrus to enable me to export the file URLs along with the tags and later be able to read them back in (preferably from the same file as the tags, or from the filename, like tags).

**Comment by bbappserver** [comment]
If you have modified the file you have changed its identity and its URL is no longer appropriate for identifying it, only its tags remain valid.  If you mean that you change the tags, then provided you do not delete the origional entry, the known urls should remian.

**Comment by thatfuckingbird** [comment]
This would be nice. Besides URLs, it should be possible to export/import other metadata too (as a json file or similar).

**Comment by puphime** [comment]
> 
> 
> If you have modified the file you have changed its identity and its URL is no longer appropriate for identifying it, only its tags remain valid. If you mean that you change the tags, then provided you do not delete the origional entry, the known urls should remian.

I don't want to keep the original file but I want to have a link to where i can find the original again

**Comment by DonaldTsang** [comment]
Another metadata issue.

**Comment by Zweibach** [comment]
This has been possible for a while now.
