### ISSUE TITLE
Add tag .txt file export functionality to "edit export folder"

### ISSUE THREAD

**Issue by puphime** [hydrusnetwork/hydrus#378]
Currently the "edit export folder" (file -> import and export folders -> manage export folders -> add) dialog does not have an option to export tags in .txt files, unlike the manual export dialog (right click, share, export, file).

I would like for this to be added, perhaps in a new section under the filename pattern

**Comment by bbappserver** [comment]
@puphime 
That is not sufficient information to constitute a real issue.  Please specify in exactly what way it is currently, what you need changed, and how you would test that this had been changed.

**Comment by Zweibach** [comment]
This is already possible for import folders. When you add a service under "filename tagging" you get the same window as when you pick `add tags before import >>` in the manual import window. Sidecar .txt tag file, folder name tags, regex, all of it.

Change title and comment to reflect that it's desired for export folders.

**Comment by puphime** [comment]
> 
> 
> This is already possible for import folders. When you add a service under "filename tagging" you get the same window as when you pick `add tags before import >>` in the manual import window. Sidecar .txt tag file, folder name tags, regex, all of it.
> 
> Change title and comment to reflect that it's desired for export folders.

I hope this is better! Sorry for the hassle.

**Comment by prof-m** [comment]
Would also love to see this! I regularly do manual exports of .webps and big .gifs so that I can convert them to mp4s, and the addition of tag exports to the export folder functionality would let me fully automate that process.

**Comment by hydrusnetwork** [comment]
This is ready in v491, please check it out!
