### ISSUE TITLE
API: Rating service

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#379]
It would be nice to be able to do get and set the favourite status of items associated to a URL so things like hydrus companion could show favourite status and set favourite status from the browser.

**Comment by thatfuckingbird** [comment]
Duplicate of #343

**Comment by bbappserver** [comment]
Ah, whoops, I searched for favourites, and didn't see that cause it was under ratings, which is weird given that I subsequently though enough about the issue request to call it the rating service.
