### ISSUE TITLE
Clearing the last duplicate pair available using quick and dirty processing gives error popup

### ISSUE THREAD

**Issue by Aegis43615** [hydrusnetwork/hydrus#383]
## Environment

Hydrus version: 403 executable
Platform: Windows
OS specifics: Win x64 10 Pro 1909

## What happens

If one of the three buttons in the 'quick and dirty processing' option on the duplicate page is used to clear the last remaining potential duplicate pair; an error pop-up will appear saying "No files were found. Try refreshing the count, and if this keeps happening, please let hydrus_dev know."

## Steps to reproduce

1.Have 1 potential pair remaining to be filtered.
2. Click "show some random potential pairs' so that the last pair is shown
3. Click one of the three options to set the current media as either duplicate, related alts, or not related
4. Note the error pop-up and that the last 

## Desired outcome

Apply the last selected relationship (which works as intended). Then **remove the images from that previous pair from the page.** Then unless you want to keep it as a notice that it was the last pair, I'd say **remove the pop-up** or change it to say "Last pair of duplicates filtered"

## Error message / Log file / Screenshots
<img width="256" alt="NoFilesWereFound" src="https://user-images.githubusercontent.com/67392701/87363100-6b79a580-c53e-11ea-8570-340738c71a6b.png">

**Comment by hydrusnetwork** [comment]
This appears to have been fixed, thank you for the report. Please re-open if you still have trouble.
