### ISSUE TITLE
Linux - can't launch - "SyntaxError: Non-ASCII character '\xe8' in file client on line 2, but no encoding declared"

### ISSUE THREAD

**Issue by Lasefo** [hydrusnetwork/hydrus#385]
Hello,
I have been using hydrus on linux (mint debian cindy) until version 367, which i can still use.

A few month ago i downloaded the lastest version at that time : 385, which i was unable to use, as the program would not launch. I had an error message that leads to python, and after trying to install other version of python 2 and 3, it still did not worked and i gave up trying to update.

I tried again with 396 and same problem.

Today i tried again with 403. I do not have the same error message as before. But i still can not launch "client" or "server". clicking on it does not do anything.

Using console command to launch either client or server, i get this error message :
"File "client", line 1
SyntaxError: Non-ASCII character '\xe8' in file client on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details"

Not sure if this is an issue with my setup or hydrus.
Thank you.

**Comment by imtbl** [comment]
Hey, please provide some further details:

- Are you trying to run Hydrus from source or using the prebuilt executable version?
- When launching from the command line, what's the command you are using?
- What's the output of `python --version` on your system?

**Comment by Lasefo** [comment]
-I am using the executable version.
-The command is "python client" / "python server"
-Python 2.7.13

I tried using some other command and got this:

- "python2 client.py"  or "python client.py" >>> 
"Traceback (most recent call last):
  File "client.py", line 120, in <module>
    from hydrus.core import HydrusData
  File "/media/smoi/stock21/Nouveau dossier 2/hydrus network/hydrus/core/HydrusData.py", line 93
    def ConvertIndexToPrettyOrdinalString( index: int ):                                                ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "client.py", line 152, in <module>
    with open( dest_path, 'w', encoding = 'utf-8' ) as f:
TypeError: 'encoding' is an invalid keyword argument for this **function"

- "python3 client.py" >>>
"Traceback (most recent call last):
  File "client.py", line 18, in <module>
    from hydrus.core import HydrusBoot
  File "/media/smoi/stock21/Nouveau dossier 2/hydrus network/hydrus/core/HydrusBoot.py", line 3, in <module>
    from hydrus.core import HydrusConstants as HC
  File "/media/smoi/stock21/Nouveau dossier 2/hydrus network/hydrus/core/HydrusConstants.py", line 69, in <module>
    import yaml
ImportError: No module named 'yaml'
Critical boot error occurred! Details written to hydrus_crash.log in either db dir or user dir!
"

**Comment by imtbl** [comment]
> -The command is "python client" / "python server"

There is your issue. The executable version has to be run just as `./client`, not by calling Python manually.

**Comment by Lasefo** [comment]
- Alright so i installed python 3 pip, which i though include yaml, but still got the same error message so probably not. I will look into it if i can't find a way to launch from the executable.

- with the command "./client", i get this error : "[12147] Error loading Python lib '/media/smoi/stock21/Nouveau dossier 2/hydrus network/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /media/smoi/stock21/Nouveau dossier 2/hydrus network/libpython3.6m.so.1.0)"

Which now i remember, is the error i used to get before.
After a quick search, glibc is a C runtime used in unbuntu, my distro (mint debian cindy) might use something else, and i remember reading in the faq or somewhere that hydrus on linux is mainly made with unbuntu in mind.

Thank you for you answer, at least i know where to search now.

**Comment by imtbl** [comment]
> Alright so i installed python 3 pip, which i though include yaml, but still got the same error message so probably not. I will look into it if i can't find a way to launch from the executable.

No, you'll need to install other dependencies like python-yaml manually (either via pip or your distro's package manager). See the aforementioned https://hydrusnetwork.github.io/hydrus/help/running_from_source.html or also https://aur.archlinux.org/packages/hydrus/; the latter is obviously for Arch, but you need basically the same packages (though they might be named differently in your distro's repositories).

> `GLIBC_2.25' not found (required by /media/smoi/stock21/Nouveau dossier 2/hydrus network/libpython3.6m.so.1.0)

Yeah, in this case you'd need to update to 2.25; the executable version bundles all the Python dependencies, but there are still dynamic links to native libraries like this one in there.

> i remember reading in the faq or somewhere that hydrus on linux is mainly made with unbuntu in mind.

I know the developer put this somewhere into the docs because that's what he tests on, but I wouldn't necessarily say that this is true. The native libraries used will be the same in virtually any Linux distro and the Python dependencies are platform-independent. The largest userbase of Hydrus is probably on Arch (or Arch-based distros like Manjaro).

**Comment by Lasefo** [comment]
I just noticed my distro (mint debian 3) is not supported since july 1st.
I will upgrade to mint debian 4, which i did not know existed, and hopefully it will work.
Thanks again, i guess we can close this topic.
