### ISSUE TITLE
Client API: Apply siblings on retrieved tags

### ISSUE THREAD

**Issue by walramb** [hydrusnetwork/hydrus#389]
For some use cases I want a "normalized" tag list where it applies siblings like it does in the main tag sidebar, but right now the API only returns the literal stored tags.

My use cases mostly involve counting and comparing tags between different files where I, for example, don't want `female` and `gender:female` to be counted separately.

I imagine this would either be a boolean argument on `GET /get_files/file_metadata` to have it apply siblings before sending,
or a command similar to `GET /add_tags/clean_tags` where you can pass in a batch of tags, this would be more flexible but probably slow since it needs a lot more back-and-forth through the API.

**Comment by floogulinc** [comment]
This would also be nice for Hydrus Web to be able to display the same tags the client does.

**Comment by DonaldTsang** [comment]
Clear tags = less load.

**Comment by floogulinc** [comment]
Added in 193cfce4ad8585348032de47b25afeb6b3e9387f
