### ISSUE TITLE
Client API: Change Archive/Inbox and Trash state for files

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#393]
It would be nice to have an API endpoint to change the archive/inbox and trash states for files. This would allow for many nice things in third party client applications like mobile archive/delete filters and such. Currently such functionality requires the third party app to set a special tag on the files to archive/inbox/delete and the user has to go and manually apply those operations.

**Comment by hydrusnetwork** [comment]
I am running super late on the week, but I have added basic commands for these for 415. I don't have documentation or proper unit tests ready, but feel free to play with them:

/add_files/delete_files
/add_files/undelete_files
/add_files/archive_files
/add_files/unarchive_files

All take 'hash' or 'hashes' parameters. Delete only works to send from my files to trash atm, it doesn't do physical delete (delete from trash).
