### ISSUE TITLE
Use BlurHash in Hydrus

### ISSUE THREAD

**Issue by thatfuckingbird** [hydrusnetwork/hydrus#394]
What is BlurHash?

![blurhash](https://user-images.githubusercontent.com/67429906/87882235-0e2e9a00-c9ff-11ea-9829-c7284b095861.png)

> In short, BlurHash takes an image, and gives you a short string (only 20-30 characters!) that represents the placeholder for this image. You do this on the backend of your service, and store the string along with the image. When you send data to your client, you send both the URL to the image, and the BlurHash string. Your client then takes the string, and decodes it into an image that it shows while the real image is loading over the network. The string is short enough that it comfortably fits into whatever data format you use. For instance, it can easily be added as a field in a JSON object.

See the website https://blurha.sh/ for images and further explanation. There is also a Python implementation available.

This can be used in the Hydrus UI itself as placeholders until thumbnails load. It would also be very useful to make it accessible through the API so clients can display the blurhash until the thumbnail loads.

**Comment by pozieuto** [comment]
This could also have limited applications for blurring "objectionable" media that you do not normally want to see if they happen to come up in searches (eg. "cannot be unseen" content types), but that you still want to store and tag for archiving or rare usage.

**Comment by hydrusnetwork** [comment]
This is very interesting, thank you. I like the idea a lot. I will make a job to mock up a test for this, so we can see how much CPU it takes to render that blur IRL.

**Comment by thatfuckingbird** [comment]
Found a pure Python impl that has both the encoder and decoder: https://github.com/halcy/blurhash-python

**Comment by DonaldTsang** [comment]
1. What about https://axe312ger.github.io/sqip/ ?
2. Is it possible to apply the same principle to GIFs?

**Comment by floogulinc** [comment]
> 2. Is it possible to apply the same principle to GIF/APNG/WebP?

I would expect the blurhash to be calculated from existing Hydrus thumbnail images so anything Hydrus can make a thumbnail for would get a blurhash.

**Comment by DonaldTsang** [comment]
@floogulinc notice how all the formats I listed are animated, I was asking an animated equivalent of blurhash.

**Comment by floogulinc** [comment]
> @floogulinc notice how all the formats I listed are animated, I was asking an animated equivalent of blurhash.

Hydrus doesn't provide animated thumbnails for animated files either and a blurhash is really just supposed to be a very small amount of data to load an approximation of the thumbnails before the real thumbnail is loaded. It would only be shown for a couple of seconds at most. Animating a blurhash would be excessive, increasing the size by a lot, and useless since it would just be replaced by a static thumbnail as soon as that loads.

**Comment by Senju-vilis** [comment]
If you do implement it - make it optional. It's hard on my eyes.

**Comment by DonaldTsang** [comment]
@floogulinc it does not have to show the full animation either. A video or animated image can be "summarized" into just a small collection of images, which can reduce size while maintaining some information (assuming such placeholders can be used to help confirm the existence of files by memory).

**Comment by floogulinc** [comment]
> @floogulinc it does not have to show the full animation either. A video or animated image can be "summarized" into just a small collection of images, which can reduce size while maintaining some information (assuming such placeholders can be used to help confirm the existence of files by memory).
> For context https://github.com/Breakthrough/PySceneDetect

This is irrelevant to the use of blurhash. If you want animated thumbnails that should be a separate issue.
