### ISSUE TITLE
Negated wildcard namespace searches yield tags with namespaced items, when search term is a result of sibling

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#396]
## Environment

Hydrus version:404
Platform: OSX
OS specifics: 10.13

## What happens
Negating a wildcarded namespace yields **both** items tagged and not tagged in that namespace.

## Steps to reproduce

Search for `-creator:*anything*` or `-title:*anything*` whichever is likely to produce a good mix of positive and negative in our dataset.

## Desired outcome
Exclude all works having creator tags from search results (useful for workflows where creators haven't been tagged by the parser, or were not present in the booru.)

**Comment by bbappserver** [comment]
> Hydrus Dev: it doesn't work with siblings yet

**Comment by hydrusnetwork** [comment]
Thank you. With luck, this situation should improve with the db siblings cache in v408, as I'll be able to quickly search pre-computed siblings at the db level.

**Comment by hydrusnetwork** [comment]
With the new cache, I believe this situation is now fixed. Let me know if you still have any trouble!
