### ISSUE TITLE
Apply sequential page tags: from selection order

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#403]
Often times hydrus perfectly imports a bunch of files in order but not with page numbers.  It would be nice to have a context menu action, and shortcut action for assigning these based on the order in which they were selected, so if you have two spans [0,5], [8,10] then it should number
```
0 1 2 3 4 5 6 7 8 9 10 11
1 2 3 4 5 6 - - 7 8  9 -
```
In the page namespace

And if you select
[8,10] and then [0,5]
It should number
```
0 1 2 3 4 5 6 7 8 9 10 11
4 5 6 7 8 9 - - 1 2  3 -
```

----
Edit:Nov 2020
If you select [5,0] assign numbering in reversed order (I'm really hoping that Qt just guarantees to give you selection spans in the order they were made), unless that would be difficult to make work, but this would be useful if a collection is in reverse which can happen if it's source is sorted by release date latest first.  Otherwise please also provide an action which applies page numbers in **descending** order in the thumbnail "list".
```
0 1 2 3 4 5 6 7 8 9 10 11
6 5 4 3 2 1 - - - -  -  -
```

Also please bind the entire thing to an **undo action** so that if you catastrophically __accidentally number 500 images, you don't have to manually go remove 500 different page tags to reverse this error.__ 

There should also be a separate action to apply the tags either locally or to the PTR.

**Comment by Zweibach** [comment]
Adding this from wishlist so this issue pops up when you search sequential.
> Sequential tagging for page: among others. Based on selection order.

**Comment by Zweibach** [comment]
This feature is currently possible to achieve outside of Hydrus using existing API functionality. It is one of the features available in [Hydrus Companion](https://gitgud.io/prkc/hydrus-companion) under Utilities as an example.

**Comment by hydrusnetwork** [comment]
Hey, I think this is done now, as of ~v567! Let me know if you have any trouble with it.
