### ISSUE TITLE
ClientGUIMessages line 994 references an unassigned variable

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#41]
Caught this one automatically when messing around with some python tools on the Hydrus codebase.

The variable "ip" is used, but it hasn't been set inside that specific elif branch (ID_LINK_BREAK).

**Comment by hydrusnetwork** [comment]
Any 'Messages' code is old stuff I haven't touched in ages. I've left it lying around for when I eventually get back to it, but there is a lot of bitrot. None of the code will run, so any problems are not a high priority. I'm slowly excising this stuff from live code (including a big db refactor this week), and now I've removed ClientGUIMessages from the import tree. Thank you for pointing this out.
