### ISSUE TITLE
Would doing hamming distance in sqlite instead of Python improve performance?

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#410]
I came across this: https://github.com/droe/sqlite-hexhammdist 

Can this be added to Hydrus, and would it have any difference on the performance of duplicate searches? (I don't know much about SQLite modules or integrating with Python, I just came across this while researching something else and it looked promising)

**Comment by bbappserver** [comment]
No, it would just tie up the DB.

**Comment by QueenHek** [comment]
>I don't know much about SQLite modules or integrating with Python

based

**Comment by imtbl** [comment]
Please don't use the issue tracker for vague suggestions like this that would need long discussions; it is meant for actionable feature requests and bug reports, not as a forum.

If you want to discuss a potential feature, join the Discord server or talk to HyDev directly through one of the other channels. Once an actual feature request has been formulated it can be posted here.
