### ISSUE TITLE
e621 Account Blacklist Seems Amiss

### ISSUE THREAD

**Issue by Mr-53918** [hydrusnetwork/hydrus#414]
## Environment

Hydrus version: 405 Executable
Platform: Windows
OS specifics: Windows 10

## What happens

I have an account on e621 with a rather extensive blacklist. I have noticed that some of the images that get downloaded have tags that should result in them not getting downloaded. The images in question do not show on the site without me disabling the blacklist, so the blacklist on the site's end works. The blacklisted terms that seem to be at fault are those with multiple tags to them, more specifically those with -tags.
For example the following term blocks all images that have the male tag AND are **missing** the female and/or the rating:safe tags on the site, but does not block their download through Hydrus.
`male -female -rating:safe`
While I suspect it to be that Hydrus is having trouble with the complex blacklist terms, it is also possible that my Hydrus blacklist is getting the more basic tags while letting the more complex terms that can't be replicated through Hydrus through.

## Steps to reproduce

1. Add a blacklist term with multiple tags (done by putting multiple tags on a single line, separated by spaces, in the settings menu).
2. Try to download a file that should be stopped due to that blacklist term.

## Desired outcome

The desired outcome is for the blacklist to function as it does on the site.

**Comment by bbappserver** [comment]
**Not a bug in hydrus**, the parser is using the e621.net API which is apparently not blacklist aware, and simply serves all matching posts.
https://e621.net/help/api#list

@Mr-53918 If you would like to use your blacklist terms specify your query string followed by subtracting every item on your blacklist, or use the builtin hydrus blacklist to exclude items after their metadata has been retrieved.

**Comment by Zweibach** [comment]
Not a bug. E621 blacklist is done clientside via a javascript according to their forums. Hydrus does not deal with javascript. Use Hydrus' tag blacklist if you need to blacklist terms.

**Comment by Mr-53918** [comment]
> 
> 
> Not a bug. E621 blacklist is done clientside via a javascript according to their forums. Hydrus does not deal with javascript. Use Hydrus' tag blacklist if you need to blacklist terms.

I see, I apologize for the misunderstanding. Is Hydrus' blacklist able to handle multi-tag terms in a similar manner as e621? I was under the impression that it was unable to, but I'd be happy to be wrong.

**Comment by Zweibach** [comment]
I don't think Hydrus filter is quite as good as what some boorus seem to have. Correct me if I'm wrong but on e621 you can format blacklist in a manner like this:

`musles male -female` which would exclude all images of muscly guys unless they also have women in them.  
`female car` which would exclude all images with women and cars.

Hydrus blacklist from what I understand are all or nothing. If a post has **ANY** of the blacklisted tags it is discarded. There's a whitelist where anything without a listed tags is discarded and an advanced mode that combines them. All posts with blacklisted tags are discarded unless they also have a whitelisted tag.

Unfortunately it's as I said, all or nothing. You just have two lists of tags that posts are checked against and if they have any black and no white it gets thrown out, no advanced multi-tag queries. Hydrus' filter is generally meant to be used on a per-query basis I think, based on how it's constructed. So you'd make a query for `muscle`, blacklist `male`, whitelist `female` and you'd get what the first blacklist term would present to you.

**Comment by Mr-53918** [comment]
> 
> 
> I don't think Hydrus filter is quite as good as what some boorus seem to have. Correct me if I'm wrong but on e621 you can format blacklist in a manner like this:
> 
> `musles male -female` which would exclude all images of muscly guys unless they also have women in them.
> `female car` which would exclude all images with women and cars.

That is correct.

> Hydrus blacklist from what I understand are all or nothing. If a post has **ANY** of the blacklisted tags it is discarded. There's a whitelist where anything without a listed tags is discarded and an advanced mode that combines them. All posts with blacklisted tags are discarded unless they also have a whitelisted tag.
> 
> Unfortunately it's as I said, all or nothing. You just have two lists of tags that posts are checked against and if they have any black and no white it gets thrown out, no advanced multi-tag queries. Hydrus' filter is generally meant to be used on a per-query basis I think, based on how it's constructed. So you'd make a query for `muscle`, blacklist `male`, whitelist `female` and you'd get what the first blacklist term would present to you.

I forgot all about the whitelist to be honest. It's probably sufficient as is (if it works as I expect it to) in this role (if missing a tag then discard), but I can see how it is comparatively limited in that you can't make conditional statements or exceptions within each rule.

Guess I'm good to go, thank you for your assistance!
