### ISSUE TITLE
Old files not getting deleted in git

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#42]
HydrusDownloading and ClientParsers both have a bunch of code in them, but later versions have removed all references to them. They have probably not been "git rm"'d. ("git add --all" might come in handy if you have a clean enough working tree)

Checking all unused files:
```
% for f in *.py; do grep -qe "${f%.py}" *.py ../*.py{,w} || echo "$f"; done         
ClientGUIMixins.py
ClientParsers.py
ClientVPTree.py
HydrusBooru.py
HydrusDownloading.py
HydrusSerialisableFactory.py
TestHydrusDownloading.py
TestObjects.py
```
This has some false negatives, being a really naive script, so here are some it missed:
* Puncher.py
* TestServer.py
* magic (the whole directory)

Given this list you probably know what does or doesn't need deleting.

**Comment by hydrusnetwork** [comment]
Thanks for this!

The way I was syncing my code wasn't clearing out orphans. I've changed my build workflow, so these should be cleared out next Wednesday when I put v154 together.
