### ISSUE TITLE
Manage ratings dialog has wrong active areas with large star ranges

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#420]
**To reproduce:**

Create ratings services with the following properties:

- one with like/dislike only
- another with a numerical rating, with 5 star range, NOT allowing a zero rating
- another with numerical rating, with a 20 star range, but do allow a zero [rating](url)

Select any file(s) and open the manage ratings dialog.

![Capture](https://user-images.githubusercontent.com/1312650/89250040-a82e3f00-d5c8-11ea-84b7-aa2410257069.PNG)

**Expected:**

Clicking any of the icons in the 5 star rating sets that value directly (e.g. clicking on the fifth square in this screenshot would set rating=5 and so on)

**Observed:**

- Only the first and fourth icons respond to clicks
- On further testing, it acts as if the icons are evenly spread across the width of the dialog:
  - Clicking on the rightmost area of the dialog does set rating 5
  - clicking in the middle sets rating 3 (though there is no icon there)
  - .. and so on, e.g. around 40% from the left sets rating 2, 80% rating 4
  - you can also click on the first icon and drag to the right

Verified in v405, but I've noticed it earlier than this.

Platform: Windows 10 Home

**Comment by Zweibach** [comment]
Current version is 406 but I see nothing in the changelog about this being fixed so it likely persists there too. 407 should drop tomorrow.

**Comment by novakda** [comment]
Verified fixed in v407.
