### ISSUE TITLE
quick way to merge artist's alternative names into one tag

### ISSUE THREAD

**Issue by gin9980** [hydrusnetwork/hydrus#421]
Artists have different names across websites, danbooru/gelbooru/pixiv/nijie so a tag for a single picture fetched into hydrus ends up as having "creator:name1 (240)", "creator:name2 (240)", "creator:name3 (103)".
The problem is that if you search for "creator:name3" you will only get the the 103 results and if you search for "creator:name1" you might not get all the result from "creator:name3".
I am highlighting tags > add sibilings to selection > copy each of the artist's name individually one by one and putting the "|" between them.

Could there be a way to quickly merge them into one tag as siblings into "creator:name1 | name2 | name3" when you highlight the tags and press a button?

**Comment by bbappserver** [comment]
Creators are merged down using a sibling tree, to merge them quickly select multiple items on the LHS in the sibling management panel.  If you perform a search with any siblings term it will return all results with the king for that sibling group, if it does not that is a bug.

It is possible for a work to be tagged with multiple creator names, and it being tagged with a tag that has been siblinged into a noter does not remove the original tag only alias it.   This is the intended behaviour, it does not signify that your siblinged creator name has only been partially resolved.

**Comment by gin9980** [comment]
> 
> 
> Creators are merged down using a sibling tree, to merge them quickly select multiple items on the LHS in the sibling management panel. If you perform a search with any siblings term it will return all results with the king for that sibling group, if it does not that is a bug.
> 
> It is possible for a work to be tagged with multiple creator names, and it being tagged with a tag that has been siblinged into a noter does not remove the original tag only alias it. This is the intended behaviour, it does not signify that your siblinged creator name has only been partially resolved.

I'm requesting for a way to quickly set multiple tags as siblings turning "creator:name1", "creator:name2", "creator:name3" into "creator:name1 | name2 | name3" as the top, instead of doing it manually in the manage tag siblings window.

most artist on pixiv/booru have multiple names so having a quick way of creating siblings into that format seems like a idea.

**Comment by bbappserver** [comment]
You aren't required to do a single creator sibling at a time when you open the siblings window.  You can add as many sibling pairs without clicking OK and then click when you are done. This may help you for now

----
It may be somewhat inconvenient to do this  by comparison to selecting a group of sibling tags in the sidebar and saying "make these the same", but I'm not sure that's desirable.

Maybe doing this could launch a wizard that makes sure that's what you intended to do, but I don't think making a sibling should ever be characterized as quick.

We already have a problem of users absentmindedly submitting things like
`shadow == character:shadow the hedgehog`

Making a sibling being a little inconvenient might actually be a good thing to prevent users from easily accidentally doing such things.  

There are also some benefits to using the siblings dialog:
- The siblings dialog shows you what the final sibling name would be, after the transitiveness
- The siblings dialog shows whether there are any cycles or conflicts.
- By typing into the sibling dialog you can also see many other variants and misspellings of naming that creator, which may not have returned from your search results.

---- 
Misidentification in a certain booru or parsing errors, as well as artist names and character names that overlap with non namespaced tags could result.

Consider the case where you got a work from 3 different boorus
- Booru1 says `creator:a`
- Booru2 says `creator:b` `b`
- Booru3 says `creator:c` `c`

`b` is a correct alias for `a` and  the work was created by `a` but `c` is not a correct alias for `a` and `b`, but `c` is an artist that exists.

If you were tired one day while doing drive by tagging and just lazily said "unify these creator tags`.  You have now erroneously tagged all of `creator:c`'s work also with `creator:a` and `creator:b`

----
Those are my two cents, but maybe the rest of the user base thinks having such a feature outweighs the risks, and again, it could launch a wizard, I only object to it being possible to do such a thing without being easily able to observe the side effects.

**Comment by gin9980** [comment]
Maybe if you can highlight multiple artist tags > press button then the manage tab siblings gets brought up with it is already as "creator:name1 | name2 | name3" added, where you can review and apply instead so you can see any errors that arent meant to be.
I have made a macro for this but would be nice to have this sort of feature implmented.

**Comment by Zweibach** [comment]
To start: Your usecase sounds bonkers. I don't want to think about how long some creator tags will eventually get for some people that change name a lot. I am unsure as to why you want it since all siblings in a chain are searchable and will produce the same results. You will eventually also get a lot of superfluous tags unless you actually go back and move over sibling relations and delete/replace tags. As for display, only the most common name or two are really useful as I see it, example `creator:thatguy (bbappserver)`.

I most definitively don't want a feature like this implemented because somebody is going to be stupid and push tags like those to PTR.

A more sensible feature is tag display options that's been discussed when the topic of tag meta information gets brought up wherein the tag is not changed in any way, just how Hydrus presents it.

> The problem is that if you search for "creator:name3" you will only get the the 103 results and if you search for "creator:name1" you might not get all the result from "creator:name3".

The answer to this problem is to just sibling two of the names to the remaining one. Which is how most people use the sibling feature.

**Comment by gin9980** [comment]
> The answer to this problem is to just sibling two of the names to the remaining one. Which is how most people use the sibling feature.
you're right, didn't know it could be used like this

**Comment by Zweibach** [comment]
Requisite RTFM moment:  
https://hydrusnetwork.github.io/hydrus/help/advanced_siblings.html
