### ISSUE TITLE
Sort/group collections in results by count

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#422]
When working with large results sets and collecting by namespaces, I frequently want to work only with groups that contain more than one member.

It would be useful to be able to sort or filter the resulting groups by the count of items in each group.

**Comment by Zweibach** [comment]
For somebody making a lot of suggestion you seem to oddly enough not like any of them. Take a moment to read #260

**Comment by novakda** [comment]
> For somebody making a lot of suggestion you seem to oddly enough not like any of them. Take a moment to read #260

Do you mean the "Remember to upvote your own suggestion since that is not done automatically" bit?  If so, thanks - I must have missed that.

**Comment by thatfuckingbird** [comment]
Sorting by number of files in collection was implemented in v413. Closing this issue for now.
Feel free to reopen or create a new one if more is wanted.
