### ISSUE TITLE
Opening a file externally leaves a zombie process (linux)

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#43]
Opening a file externally leaves a zombie xdg-open process, which is only reaped when you open another file externally (which of course leaves a zombie again).

I reported this in https://github.com/hydrusnetwork/hydrus/issues/39 but I think it is unrelated.

**Comment by hydrusnetwork** [comment]
I have improved my 'running external programs' pipeline in today's release. I think this will stop the zombie processes, but let me know if you still get them!

**Comment by ScoreUnder** [comment]
I'm still getting the zombie process unfortunately (sorry for taking so long to respond here). I've looked a little into how this happens and it seems to happen if you keep a leftover process object from Popen lying around.

**Comment by hydrusnetwork** [comment]
Thank you for this. I have added .wait() and .communicate() calls to my linux/osx code that launches files and directories. As I understand, this fetches the return code and allows the process to terminate properly. I've tested it on Linux, and I don't see any zombies being created any more when I run 'top'.

My other Popen calls either already did a wait/communicate call because they wanted to read stdout or I explicitly .terminate() them, so I think I am fine on this front now. Again, please let me know if you still see any in v166.

**Comment by ScoreUnder** [comment]
In the current Hydrus version 177, I no longer get the issue of zombie processes.

On the other hand, the Hydrus client freezes when I open an image in an external viewer, and then resumes responding once the viewer is closed.

**Comment by hydrusnetwork** [comment]
That's interesting! If you go file->open->installation directory, do you get a similar effect?

My Linux (Ubuntu 14.04) works fine, so perhaps there is some terminal/process setting or something in your Linux that means the 'xdg-open' call that I rely on isn't completing quickly.

I will throw the call into a temporary separate thread for v178, which stop the gui locking up for you. Let me know if you still get the problem, or if this gives rise to anything new!

**Comment by ScoreUnder** [comment]
>My Linux (Ubuntu 14.04) works fine, so perhaps there is some terminal/process setting or something in your Linux that means the 'xdg-open' call that I rely on isn't completing quickly.

Is it opening in a program that's already running? For me I have my image viewer set to `feh`, which launches anew each time.

`xdg-open` on my machine does not exit until the application closes. If it behaves differently under ubuntu it could be because it uses `gvfs-open` under gnome-like desktop environments, and that might have different behaviour (I don't use it so I'm not sure about that).

>If you go file->open->installation directory, do you get a similar effect?

Yes, my file manager launches and hydrus freezes until I close it. I am using `thunar` as my file manager.
If I run `thunar --daemon`, I don't get the same effect. Presumably this is because the thunar instance launched by Hydrus just hands the task over to the daemon then exits.

**Comment by hydrusnetwork** [comment]
I think this is fixed now--and the thread that the client launches to wait on the external process is a daemon, so it won't hold up shutdown if you close the client before the external process. Let me know if you still have any problems.
