### ISSUE TITLE
Filter/sort by last viewed timestamp

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#432]
Please allow sorting/searching by the date/time a file was last viewed in the media viewer.

This eases knowing which file(s) you have or have not reviewed yet.

Currently to accomplish this I clear the viewing statistics and search by view count.   This gets unwieldy with large numbers of files.

**Comment by Zweibach** [comment]
Not sure when it was added but it is now possible to search and sort by time viewed.
