### ISSUE TITLE
Feature: import from favourites

### ISSUE THREAD

**Issue by Ketsuban** [hydrusnetwork/hydrus#45]
I'd like to import my favourites from Gelbooru into Hydrus, but Gelbooru doesn't allow filtering them through the search interface. (People have been [ask](http://gelbooru.com/index.php?page=tracker&s=view&id=303)[ing](http://gelbooru.com/index.php?page=tracker&s=view&id=515) for that feature since 2011, and I doubt there's much chance of it happening anytime soon.)

**Comment by hydrusnetwork** [comment]
I am generally in favour of adding this, but it is slightly tricky as it'll require hydrus to log in to pretend to be you, and the current downloader doesn't support that. Currently, hydrus just browses results like someone who is logged out.

I don't have a gelbooru account, so I don't know much about it--what link would you usually go to to see your favourites? Does the page look and navigate like normal search results?

**Comment by Ketsuban** [comment]
Viewing someone's favourites doesn't require logging in, but it does require knowing their user ID which isn't too hard to find. The link looks like `http://gelbooru.com/index.php?page=favorites&s=view&id=21394`; pagination uses the same `pid` parameter as search results, but the layout itself is slightly different because there's no tag interface.

**Comment by hydrusnetwork** [comment]
Thank you for this--this is good news. I tried creating a pretend booru
that would download these, but I couldn't get my current system to work.
Let me think about it a bit, and I will try to get something out for next
week.

**Comment by hydrusnetwork** [comment]
I tried a different method and got it to work!

Open up* services->manage boorus* dialog and then drag and drop this yaml
file onto the dialog. It should create a new booru, booru_favourites.

Try to download from this booru and use your id, 21394 or whatever, as the
'tags'. Everything should parse and import ok, but please let me know if it
doesn't!

On Tue, Jun 2, 2015 at 8:15 PM, Hydrus Administrator <hydrus.admin@gmail.com

**Comment by hydrusnetwork** [comment]
Damn, I forgot this was github and not a normal email chain. I expect github ate the attachment. Here you are:

http://www.mediafire.com/download/q3tnjwvtmdzkejf/gelbooru_favourites.zip

**Comment by Ketsuban** [comment]
I'm a little unclear what you mean by "use your id […] as the 'tags'". I see `%tags%` in the search URL, and a "tags" list populated with some stuff from the YAML file. Everything I try gets me another traceback dialog box I can't dismiss telling me `NoneType` objects aren't iterable.

```
TypeError
'NoneType' object is not iterable
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientGUIDialogsManage", line 497, in EventOK
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientGUIDialogsManage", line 790, in HasChanges
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientGUIDialogsManage", line 741, in _GetInfo
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientGUIDialogsManage", line 741, in <dictcomp>
```

**Comment by hydrusnetwork** [comment]
Sorry, I meant save that booru as I gave it to you, and then open a new download page for the new booru and where it says 'search tags', where you would usually put blue_eyes or whatever, just put your user id.
![like_this](https://cloud.githubusercontent.com/assets/3878678/8072570/48122df0-0edd-11e5-943c-19520ee81585.png)

**Comment by Ketsuban** [comment]
Yeah, no dice. I get the NoneType traceback on clicking Save and gelbooru_favorites isn't added to the list of boorus I can open a download page for.

**Comment by hydrusnetwork** [comment]
That's strange. I'm sorry this is being such a pain. I am not sure what is going on, other than yaml breaking like usual!

Please try just editing the normal gelbooru entry in the dialog. Replace the search url with this:

http://gelbooru.com/index.php?page=favorites&s=view&id=%tags%&pid=%index%

And hit OK. Other than the name, that's the only difference between gelbooru and gelbooru_favourites.

If you get an error just from editing that, then we have a bigger problem.

If it works, then please try downloading your favourites, and when they are done, set your gelbooru's search url back to the default, which is:

http://gelbooru.com/index.php?page=post&s=list&tags=%tags%&pid=%index%

**Comment by Ketsuban** [comment]
Same error, no changes made to boorus (search URL was still the default you provided).

**Comment by hydrusnetwork** [comment]
Ok, there is something seriously wrong going on here with the dialog, then. I will think about it a bit and work on it first thing next week.

If you don't mind answering:

Which version of hydrus are you using?
Which OS are you using?

**Comment by Ketsuban** [comment]
I downloaded version 159 from Github, and I'm using Ubuntu Linux 15.04.

**Comment by hydrusnetwork** [comment]
I am making an effort to catch up on github issues I have been neglecting. I apologise for the delay. I have made several changes to the manage boorus dialog since June 9th, and I think I set up gelbooru favourites for someone else somewhere else. Is this still a problem for you, or did I fix it for you elsewhere, or did you figure something out?

**Comment by Ketsuban** [comment]
I hadn't tried to use Hydrus since. I'll give it a shot now and see how it shakes loose.

**Comment by Ketsuban** [comment]
It's started downloading my favourites correctly. Thanks very much!

**Comment by hydrusnetwork** [comment]
Great!
