### ISSUE TITLE
Installer Detected as Presenoker Virus

### ISSUE THREAD

**Issue by kin-patsu** [hydrusnetwork/hydrus#452]
## Environment

Hydrus version: 407 (installer)
Platform: Windows
OS specifics: Windows 10 2004

## What happens
As soon as the installer is started, Windows Defender stops it detecting as a virus (PUA:Win32/Presenoker)

## Steps to reproduce

1. Download the installer for WIndows
2. Try to launch it with Windows Defender active

## Desired outcome
The program gets installed correctly

## Error message / Log file / Screenshots
PUA:Win32/Presenoker

**Comment by imtbl** [comment]
This is a false positive. This happens from time to time, HyDev can't really do anything about it. It's because PyInstaller is popular to bundle stand alone Python based malware.

Use the extract version instead of the installer to work around it.

**Comment by bbappserver** [comment]
This particular form of malware appears to be a trojan.  If you did not download the installer from the [official page](https://github.com/hydrusnetwork/hydrus/releases/tag/v407), it probably just that, an installer masquerading as hydrus.  If you did download it from the official page, then it may be a windows defender problem you need to whitelist.

Before whitelisting anything you may want to verify that the presence of other malware on your machine or in your browser did not maliciously alter the installer.

The SHA256 for this release (Hydrus.Network.407.-.Windows.-.Installer.exe) is
```
5b3eca1a6f7c07760be5caab798df9fca8161d982927826bef5571a603c4852c
```

Verify that this matches the hash of the file you are trying to install from by uploading it here.

https://emn178.github.io/online-tools/sha256_checksum.html
