### ISSUE TITLE
Search for numerical predicate causes AttributeError

### ISSUE THREAD

**Issue by Mooninaut** [hydrusnetwork/hydrus#46]
Hydrus Version: 158
Platform: Windows 7 x64

Steps to Reproduce:

1. Ensure that there is at least one local numerical predicate in the database.
2. Open a fresh local search tab.
3. Click in the search box to open the tag search dropdown.
4. Double-click on system:rating in the tag search dropdown to open the "enter predicate" window.
5. Select any one of the ">", "<", "=" or "≈" options from the middle dropdown selector.
6. Click the "Ok" button on the right side of the "enter predicate" window.

The following error occurs:

> AttributeError
> 'Service' object has no attribute 'GetLowerUpper'
> File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUIDialogs", line 1318, in EventOK
> File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUIPredicates", line 18, in GetPredicate
> File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUIPredicates", line 622, in GetInfo

This error does not occur when searching for any of the "=rated", "=unrated", or "=uncertain" predicates.
This error does not occur when searching for "like/dislike" ratings.
This error occurs whether or not there are any images that have been rated with the rating in question.
This error occurs with a freshly created, empty database, after adding a numerical rating.
This error occurs with a mature database containing thousands of rated and tagged images.

**Comment by hydrusnetwork** [comment]
Thank you for this thorough report.

I missed some old numerical rating code when I recently updated to the new control. Thanks to your report, I have fixed this bug and several other places with the same line of old code. They should be out in next Wednesday's release. Please let me know if the fix does not work for you or if you spot anything else like this.
