### ISSUE TITLE
Tag name not showing up till further info is input

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#460]
Not 100% sure if this is a bug, I use the letter z to typically push something further down an alphabetical list, be it folders, files, or in this program ratings.
I tried to do this with tags, a 'Z ' I figured would bring up tags that I create
![client_2020-08-16_23-32-42](https://user-images.githubusercontent.com/2681758/90357499-d116f100-e018-11ea-945d-c9e1cfbe4208.png)
see this image for the tag I made and 
![client_2020-08-16_23-33-20](https://user-images.githubusercontent.com/2681758/90357523-e25ffd80-e018-11ea-918c-6859fdd18be8.png)
is what comes up with 'z '
even 'zz ' still had the program shortlisting the results to 
zz
creater:zz
title:zz

due to my need to close the tab i'm working on i will have to create a temp tag that does fall in line with what will show up on the auto complete, but i'm not sure if this is a bug or not or if there is a setting that I had no idea existed that fixes this problem for me

--edit--
I have found that 'z z' is needed to have the desired effect, just in case anyone is interested in doing a method like this themselves.

**Comment by rachmadaniHaryono** [comment]
this depend on option -> speed and memory -> tag autocomplete

**Comment by alidan** [comment]
ok, just tried limiting the character to 1 letter, same results, I told it to always do a full search, the result is everything, ok, let's add the space the result stays the same. 

so the issue is that space isn't taken into consideration at all in searching 

going though about half of what must have been several thousand tags just to see what tags I could expect with a "z " search, and i saw 2, "dragon ball z" and "atilla z"
these I don't believe would show up

so with a search distance of >=1 character with a search of 'z ' i should see what I tagged, but I don't. is space being excluded from characters bug ot design?

I should note that / ( and - seem to also be excluded from character searches if the results are looked at
![client_2020-08-17_13-16-49](https://user-images.githubusercontent.com/2681758/90429788-f1cc5e80-e08b-11ea-99ec-292590da316b.png)

assuming this isn't a bug should I make a seperate thread about a feature request 'include all characters as characters' option?

**Comment by Zweibach** [comment]
I'll bring it up with Hydev when he appears for the update talk tomorrow.

**Comment by alidan** [comment]
-adding this after the rest was made incase it got lost in my ramble, the characters ()[]{}-_'"/ seem to be the only ones on a normal keyboard that are ignored.-

sounds good, if how it would be implemented comes up, I think a toggle in the drop down when you are in this area
![client_2020-08-18_21-41-28](https://user-images.githubusercontent.com/2681758/90585921-96899180-e19b-11ea-8445-6868cdf369c1.png)

would be the best option, that creator in my above image post, that one is obnoxious, however in making this post I concluded this, special characters are treated as spaces. note my above image with the creator, if I search 'z z' or 'z-z' the exact same results show up, however 'baz' which if the character was 100% ignored doesnt bring up 'b-a-z-z-z-i-n-g-a' 

I can think of 3 modes
1) the current mode where it ignores context, this may be the best for general use
2) where characters like ()[]{}-_'"/ are taken into account
![client_2020-08-18_21-54-02](https://user-images.githubusercontent.com/2681758/90586691-69d67980-e19d-11ea-85c5-dde82df50daa.png)
3) where any "special" character is bypassed, as in if, and lets use my tag that started this as an example "z z drawthread collage image harvest" being the search term, "zzdrawthreadcollageimageharvest" would get me the same result. 

number 3, is there specifically due to 'b-a-z-z-z-i-n-g-a' and the knowledge that if there is one tag that comes up like that for my 'z z' tag, then there is likely going to be quite a lot of tags like this, a mode where it ignores non letter/number characters may be useful. 

probably went on a bit longer then I should, thanks for bringing it up
