### ISSUE TITLE
You need to wait half a second before pressing enter in the tag box

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#48]
This one has annoyed me for some time but I never thought to report it until now.

When you type in the tag box, you have to wait before pressing enter. If you accidentally press it too early, either the box closes or you add a wrong tag.

**Comment by hydrusnetwork** [comment]
This annoys me too. I sometimes hit system:everything and blow my cpu up for a moment. I have made a note somewhere to change the behaviour to automatically enter whatever is in the textbox if results aren't yet loaded, but haven't got round to it yet. I'll bump it up the list.

**Comment by hydrusnetwork** [comment]
This is actual behaviour now, although it may be causing different problems as in your #32 . As I said for that, let's put this aside for now and revisit it when the new system is in place.
