### ISSUE TITLE
Hydrus has shaky behaviour in many window managers

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#49]
So that you know what to test on if you want to hit some bugs on the head:
# Common window managers
## For OOTB linux users
- metacity (GNOME legacy)
  - (1) The splash has the wrong vertical size, so the text isn't visible:
    ![screenshot](http://a.pomf.se/neegty.png)
  - (2) Clicking the tag auto-complete window closes it. This also means the buttons don't work.
- xfwm4 (XFCE)
  - 1, 2 (edit: 2 seems to affect 4.12.3 but not 4.10.1)
  - (3) The splash has a titlebar
  - (4) The auto-complete window has a visible border and starts in a strange position, and requires that you click in and out of the tag box a few times to correct it. It also never fully disappears, and the borders make this conspicuous.
  - (5) When the window is maximized, the toolbar in the builtin image viewer displays at the wrong size at the very top of the screen.
- openbox (LXDE and others)
  - 1, 2

kwin, mutter and unity are harder to test quickly and in isolation so I have not tested them
## For /tech/
- i3
  - 4
  - (6) The toolbar in the builtin image viewer shows correctly first time, in the middle of the screen second time, and doesn't show after that.
  - (7) When focus-follows-mouse is on, hovering over the auto-complete window closes it too
- dwm
  - 2, 4, 7
  - (8) The toolbar in the builtin image viewer is always too small
- spectrwm
  - (9) The splash is fullscreen
  - (10) The tag dropdown does not ever move or resize (starting as a 1x1 window), and the tag search box cannot be typed into. This makes Hydrus unusable.
- bspwm
  - 8 (props to bspwm for uncovering the fewest bugs)
- fluxbox
  - 1, 4 (somewhat)
  - (11) The toolbar in the image viewer still appears even if the window is shaded (rolled up)
# Uncommon window managers
- twm
  - (12) The splash screen requires placement
  - 2, to a lesser extent 4, 7, and 8
- mwm (openmotif window manager)
  - 2, 4
- matchbox-window-manager
  - 9, 10
- xmonad
  - 4, 7, 8
- evilwm
  - (13) tag autocomplete window is hidden behind main window
  - (14) the toolbar in the image viewer appears in a different place every time
- blackbox
  - 4 (somewhat), 7, 11
- fvwm
  - 1 (on exit only), 4, 7 (interacting with each other in the most horrible way)
- fvwm-crystal
  - 1 (on exit only), 3, 4, 7 (the interaction here between 4 and 7 is even worse, you _can not_ click the tag box with the mouse without triggering a nasty bug!)
  - (15) the toolbar in the image viewer has a title bar
- notion
  - 10
- ratpoison
  - 6
  - (16) autocomplete window is not visible; "ctrl+t, n" must be pressed once before the tag box becomes usable.

At least in my manual tests, XFCE comes out "on top" in an obvious way: it uncovers a lot of bugs and is a popular window manager, coming bundled with xubuntu.

Of course, I'm rooting for the bugs affecting i3 to be fixed... ;)

**Comment by hydrusnetwork** [comment]
This is fantastic, thank you!

**Comment by Link-Satonaka** [comment]
This fixes a lot of focus-follows-mouse issues for me in dwm:
https://wiki.archlinux.org/index.php/GTK%2B#Wrong_focus_events_with_tiling_window_managers

Most notably, keyboard shortcuts now work all the time as expected. Maybe now that I've identified a hack to fix it, hydrus dev can better track down why it happens in the first place.

**Comment by Link-Satonaka** [comment]
Saving exact command for posterity
`$ GDK_CORE_DEVICE_EVENTS=1 /path/to/hydrus/client`

**Comment by Link-Satonaka** [comment]
@ScoreUnder how many of these are still bugs? I think this list needs to be revisited. In particular, the recent changes to floating window logic has vastly improved my experience under dwm

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
