### ISSUE TITLE
Since v160, can't search with system: tags

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#50]
To bring up a system tag (usually inbox or everything), my usual process is:

1. Bring up the tag box (affected by #49)
2. Navigate to a system tag with the arrow keys
3. Press enter to add the tag

Since v160, when I press enter it doesn't add the tag. The dropdown stays there but nothing happens, as if I didn't press enter in the first place.

I know it's registering *something*, because this appears in the console:

> (client.pyw:7653): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x7f5a1a954440' has no handler with id '2320'

Interestingly, that kind of message appears once for pressing enter on a tag that doesn't work, twice for a tag that works and gets inserted into the tag search box, and doesn't appear at all if a nonexistent tag name is typed.

**Comment by ScoreUnder** [comment]
With a little cheeky trickiness I can actually do a system:everything or system:inbox search. I need to make the autocomplete disappear, then resize the window from 1x1 to something usable, then use the mouse to select the tag. It's strange but it works.

**Comment by hydrusnetwork** [comment]
Thank you, I will look into this. If you double-click the system tag, does that work?

**Comment by ScoreUnder** [comment]
It does but due to something I mentioned in #49 (I'm using i3) the autocomplete box resets to 1x1 when I move my mouse over it.

This is what it looks like trying to click the tag:
![Animation](http://a.loveisover.me/puwxtg.gif)
Excuse the poor quality, it's a gif.

I haven't recorded pressing enter on one of those tags here because there isn't much to see - nothing happens.

**Comment by ScoreUnder** [comment]
It looks like this is fixed in v161
