### ISSUE TITLE
'Copy external share link' in local booru menu

### ISSUE THREAD

**Issue by spirithntr** [hydrusnetwork/hydrus#54]
I get an error 
TypeError
cannot concatenate 'str' and 'NoneType' objects
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUI", line 2964, in EventCopyExternalShareURL
while trying to 'copy external share link' in local booru menu 
The solve for me now is putting a share key from ‘internal share link’ to my external ip. This way local booru works fine. But I hope there is some easier way this feature to work.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I will make sure to fix it tomorrow.

**Comment by hydrusnetwork** [comment]
This is fixed for tomorrow's release. Let me know if you still have any problems!
