### ISSUE TITLE
Feature: Timestamp all log entries / prints where possible

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#55]
When an error happens I'm not always there to see it, a timestamp would greatly help in determining when it actually happened and thus if it's relevant to any issue I'm investigating.

**Comment by ScoreUnder** [comment]
Also, sort of related in a "helps debugging" sense: I think after an error, stdout/stderr should be flushed. At the moment client.log and server.log can be several minutes behind due to buffering, which can make error diagnoses a pain.

**Comment by hydrusnetwork** [comment]
Thanks, these are great ideas. I've added them both for tomorrow.
