### ISSUE TITLE
API: Change page contents

### ISSUE THREAD

**Issue by walramb** [hydrusnetwork/hydrus#570]
An API call to feed a list of file ids or hashes to replace or append to the contents of a named page.
Currently, the only way to alter page content through the API seems to be `POST /add_urls/add_url`.

My use case: I experiment with some basic image analysis for sorting/filtering files, it would be very useful if I could just have a hydrus page with my results in a specific order, without making an external UI or managing temporary tags.

**Comment by floogulinc** [comment]
Support for adding files to a page has been added in https://github.com/hydrusnetwork/hydrus/releases/tag/v448. See https://hydrusnetwork.github.io/hydrus/help/client_api.html#manage_pages_add_files

I will close this but please reopen it if you need more than this functionality (eg replacing or removing files from a page).
