### ISSUE TITLE
If tag siblings A->C and B->C and you remove both A+B from an image at same time, will leave C virtually on image

### ISSUE THREAD

**Issue by Aegis43615** [hydrusnetwork/hydrus#571]
## Environment

Hydrus version:408
Platform: Windows
OS specifics: Win x64 10 Pro 1909

## What happens

Bug with new virtual siblings, I've tried this with both local and PTR tags, but if you remove two siblinged tags at the same time, it will leave it's sibling visible in the tag display, even if the tag manager is completely empty. Images are searchable with these tags too so I imagine they're valid mappings.

## Steps to reproduce

1. Find a tag with two siblings (i.e. samus -> character:samus aran; and samus_aran -> character:samus aran) (Note:I apply PTR siblings to my local tags)
2. Open tag manager and add both tags to an image, then close the tag manager so they apply
3. Note that the image tag display shows 'character:samus aran' as expected due to siblings.
4. Open tag manager and remove both of those siblings ('samus' and 'samus_aran') at the same time, and close tag manager so it applys.
5. Note that while both have been removed (and the tag manager is showing empty) that the image is still displaying 'character:samus aran'
6. You can now add 'character:samus aran' to the tag manager, close the tag manager to apply, then remove 'character:samus aran' to make it correctly disappear.

## Desired outcome

Removing siblinged tags clears the tag and their sibling normally (both local and PTR)

## Screenshots/ Video
<img width="410" alt="issue1" src="https://user-images.githubusercontent.com/67392701/91120134-f3d18700-e662-11ea-9c63-a2217c2ab250.png">
<img width="397" alt="issue2" src="https://user-images.githubusercontent.com/67392701/91120135-f3d18700-e662-11ea-8c92-224ab0204621.png">

[Webm video showing the issue on local tags](https://github.com/hydrusnetwork/hydrus/files/5121236/Bug.zip)

**Comment by hydrusnetwork** [comment]
Thank you for this excellent report. I was having trouble reproducing this. I can now create it and will have it fixed for 414.

**Comment by hydrusnetwork** [comment]
I have fixed this for 414, which is due for October 14. Let me know if you have any more trouble!

**Comment by hydrusnetwork** [comment]
If you had this issue and now see files with tags they shouldn't, there are a couple of solutions to fix them:

- Add a 'bad' sibling tag ('samus') to the files, hit apply, and then open up again and remove. The new calculation code should clear out the surplus tag correct.
- Run 'database->regeneration->tag display mappings cache'. This recomputes all display tags in your database, and is the nuclear, fix-all solution.
- Wait for me to write the per-file version of 'regen display mappings' maintenance routine, and then queue that job up in 'database->maintenance->files'.

Let me know if you try one of those and it does not work!
