### ISSUE TITLE
Setting for which services are used to sort and/or collect

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#572]
Option to exclude tag services when collecting by tags. Current collection functionality can make it so collections get messed up if, for example, you have good tags on local but a few of the files you want to collect have bad tags on PTR. Being able to disregard PTR tags when collecting would be desirable, instead of having to deal with creating unique namespaces to collect by instead.

**Comment by hydrusnetwork** [comment]
Thanks. I agree with this. As we talked about in discord, I think I will take this opportunity to write a proper tag service selection menu, like we now have for file service selection, including multiple location selection, in the tag autocomplete dropdown. I'll figure out a menu icon button or something beside the collect dropdown and upgrade the collect-by messaging system to include service selection and obviously the actual collect-by code. There's plenty of old code in there that can do with updating.

Depending on how well it goes, I'll see if I can do the same for sort-by. Both systems are tangled up and it would be nice to update them both at the same time.
