### ISSUE TITLE
Downloading pixiv manga not implemented

### ISSUE THREAD

**Issue by KriPet** [hydrusnetwork/hydrus#58]
From what I can tell, the pixiv manga pages are not implemented yet. 

I'll probably take a shot at it when I get the time.

This is related to #57, and it doesn't seem too hard to fix.

**Comment by hydrusnetwork** [comment]
This is in my to-do list. I have been saving these parsing improvement jobs for after my big gallery downloader and subscription rewrite, which I completed just recently. If you discover anything helpful about the html parsing for this before I get round to it, let me know!

**Comment by Phooh** [comment]
If and when it does get implanted though, will it be able to group them in same order as they are in pixiv? Being stripped of the name also kind of sucks for those who already had a bunch of pixiv manga images before using hydrus. So I was thinking when you go to search for the artist id to download from pixiv, have an option to automatically group manga images if they are already in the data base.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
