### ISSUE TITLE
Feature: Adding, editing tags and viewing collection via WWW

### ISSUE THREAD

**Issue by bigretromike** [hydrusnetwork/hydrus#62]
That would essentially make hydrus booru a fully working booru.
Would make it to posible to enjoy collection from various devices.
Adding API to it would also open path for (un)official clients or adding support for already existing one.

The look of www-page could be customize inside browser already

**Comment by hydrusnetwork** [comment]
This is something I hope to expand on in the future. I've been talking a bit about this here as well:

https://github.com/hydrusnetwork/hydrus/issues/60

I haven't touched the local booru in a long while, but I would really like to make it do a lot more, and open up all the commands to a general API so anyone can write a script to automatically do what you normally do in the client.

**Comment by bigretromike** [comment]
Do that and I could try to make client for android :+1: always new challenges are great !

**Comment by Scrxtchy** [comment]
Would like to bring this post back up
Putting my hand up for interest in a REST api or something.

Even if it's just fetching images / read only as a starting point

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
