### ISSUE TITLE
Send API key in URL query

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#626]
Send API key in URL query.

**Comment by bbappserver** [comment]
@Zweibach Available via
https://hydrusnetwork.github.io/hydrus/help/client_api.html#request_new_permissions
```
GET /session_key
GET /request_new_permissions
```

Close the issue.

**Comment by bbappserver** [comment]
Sending a credential in a URL query parameters is generally bad security practice because it on the request line, and thus is in the clear.  It is prefered under the HTTP `Authentication` header in the post body, because if the connection is over HTTPs then the token is protected from  eavesdropping, because the body has been encrypted.

**Comment by floogulinc** [comment]
> Send API key in URL query.

This is already a feature of the API. See this part of the [API docs](https://hydrusnetwork.github.io/hydrus/help/client_api.html):

<blockquote>
<p>Or you can include it as a GET or POST parameter on any request (except <i>POST /add_files/add_file</i>, which uses the entire POST body for the file's bytes). Use the same name for your GET or POST argument, such as:</p>
<ul>
				<li><p>/get_files/thumbnail?file_id=452158&amp;Hydrus-Client-API-Access-Key=0150d9c4f6a6d2082534a997f4588dcf0c56dffe1d03ffbf98472236112236ae</p></li>
			</ul>
</blockquote>

---

> Sending a credential in a URL query parameters is generally bad security practice because it on the request line, and thus is in the clear. It is prefered under the HTTP `Authentication` header in the post body, because if the connection is over HTTPs then the token is protected from eavesdropping, because the body has been encrypted.

With HTTPS, the entire URL, including the query string, is encrypted. Thus there is practically no difference between putting it in the query string versus a header.

**Comment by thatfuckingbird** [comment]
Closing as per the above comment.
If something else was meant, then feel free to reopen.
