### ISSUE TITLE
add support to rule34hentai.net ?

### ISSUE THREAD

**Issue by AreFinstad** [hydrusnetwork/hydrus#65]
having some issues adding this site ( http://rule34hentai.net/ ) to the program to download from aswell as grab tags from.
could someone help me get this set up right or add official support in the next update maybe? both maybe?
found that the wiki page you have is a bit lacking for this one, i really just want to add that one site.

i went to the "manage boorus" page and then added the info to the site so it looks like the others that do it the same way.
i have managed to make the gallery parser to work and it now find files..... but every download i try just fails. 

as of now it looks like this:
![](http://i.imgur.com/TroBdek.png)

its only the "image" plane and the image text that is wrong i think..... but i just cant get it to download at all.

**Comment by hydrusnetwork** [comment]
I had a quick look, and what you have put in looks generally ok. I am not sure why it wouldn't work, so I will check it out on my end.

I will have a look at this on Tuesday. If I can get it to work, I will add it as a default booru for v181.

**Comment by AreFinstad** [comment]
thanks! <3
yeah, it finds files alright but spits out errors when actually downloading.
the thing with that site is that it got the best collection of SFM content with all the Webms and so on. the others doesnt even get close IMO.

**Comment by AreFinstad** [comment]
thanks for adding support to this site :D yay!

**Comment by AreFinstad** [comment]
after finally testing this, it fails on all accounts when trying to download WebM files.
images and gifs are fine, but the other downloaders handles webm's aswell.

webm's are kinda that site's thing IMO.

**Comment by hydrusnetwork** [comment]
Thank you for letting me know. I will fix the parser for webm links for next week.

**Comment by AreFinstad** [comment]
its now functioning fully with webm and gifs. will reopen if i have problems with flash aswell tho that isnt in my queue just yet.
