### ISSUE TITLE
Client API: Search wildcards

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#654]
It would be nice to be able to use wildcards (`*`) in the file search API. This would especially simplify the logic in the Hydrus Web comics feature.

**Comment by professor-mesmerize** [comment]
Just as an FYI, the help docs for the client API currently say:

> Wildcards and namespace searches are now supported, so if you search for 'character:sam*' or 'series:*', this will be handled correctly clientside.

However, at least from my quick testing of it, wildcards **don't** actually work in the client API, so this issue is still outstanding - just clarifying here to save anyone from going down the same rabbit hole I did.

**Comment by floogulinc** [comment]
Looks like this is working in 440
