### ISSUE TITLE
Imported Files Ignore Sort Method

### ISSUE THREAD

**Issue by Unknow0059** [hydrusnetwork/hydrus#666]
## Environment

**Hydrus version:** 400, Source, Pip
**OS:** Windows 10 Pro 2004 10.0.19041.508 64-bit

## Steps to reproduce

1. Sort by 'newest first'. Or any option, really.
2. Import or download a file.

## What happens / Desired outcome

The newly imported file will show up on the bottom of the file list instead of at the top, which is what it should be doing if one is sorting by "newest first".

It ignores the sorting method altogether.

**Comment by Mengmoshu** [comment]
This is a side effect of sorts not being auto-refreshing. It's also desirable for some workflows, so the "fix" is probably to add a new feature.

Import time isn't especially precise, and may not reflect the time from the current import job if the file has been imported previously. The existing behavior of putting the newest files added to a page at the end is predictable with little disruption to work a user might be doing while an import is ongoing.

The workaround for now is to either refresh the page (F5 by default) or to look for new files at the bottom of a page.

**Comment by Zweibach** [comment]
First off what Mengmoshu said, secondly you're thirteen versions out of date, thirdly it's not a bug. See #534 for a feature request to have tabs auto-refresh.
