### ISSUE TITLE
potential duplicate preparation ram limit

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#669]
![client_2020-09-30_13-31-33](https://user-images.githubusercontent.com/2681758/94773172-db027280-0380-11eb-8bec-3af52e061ca3.png)

This process seemingly eats ram infinitely (it has gotten upto 31gb when I forgot about it), so I have to timeout 20 minute intervals which sees ram hit 14-16gb for me. and while yes, I do have a lot of ram, and I could just let this eat everything up, its pushing things to page, which at least for me isn't great for stability, and if this does scale infinitely, I don't have a ssd large enough for how big that page file would bloat. 

I would like to see either a ram limit for the operation, the operation split into smaller chunks then the whole thing at once so it doesnt eat all the ram, effectively the program cycling like I'm doing currently, or cycling from on and off on its own at a user definable image count. while i'm sure a feature like this won't make it in for very similar, it would be helpful going forward with other distances.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I have had this from a couple of users. It seems like my recent round of database optimisations is failing here, or perhaps some related code cleanup is not giving the client time to free up memory. I have a small change in for 414 that may just fix this, or it may need more work. Please let me know how 414 works for you.

**Comment by alidan** [comment]
I'll try it when i'm on 414 and will have to do a test to see if it cleans up a 4 distance search or not, fingers crossed the issue is fixed for 414

**Comment by hydrusnetwork** [comment]
Ok, seems to be fixed. The new optimisations involve some in-memory work, and it turns out this is not cleaned up regularly, so in the remaining long-running maintenance jobs like this, memory was bloating until the final commit. I'll make a job to address other areas of the program where this may be happening as well. Thanks again for reporting.
