### ISSUE TITLE
Possible reproducible UnicodeEncodeError

### ISSUE THREAD

**Issue by KriPet** [hydrusnetwork/hydrus#67]
When I try download->new gallery->pixiv->artist id and downloading 36751331, I get a unicode encode error. Can anyone try reproducing this?

Edit:
Just realized this is an invalid id, so that explains the error. Would be nice with a more friendly error though.

**Comment by hydrusnetwork** [comment]
Thank you for this report. When I run that query in v179, I get a neater "Gallery 404" message, which is something I happened to add last week. Are you running pre-179?

Semi-related, I have improved a lot of my unicode handling for next week, so I hope this generally bad error catching should improve across the board.

**Comment by KriPet** [comment]
Yeah, I was running 178, updated and got the better error.
