### ISSUE TITLE
Add tolowercase / touppercase string converters for content parsing

### ISSUE THREAD

**Issue by OptoCloud** [hydrusnetwork/hydrus#679]
Under
Content parser
Edit formula
Edit string processor
Edit processing step
Edit conversion
field: "conversion type"

**Comment by Zweibach** [comment]
> All tags are automatically converted to lower case. 'Sunset Drive' becomes 'sunset drive'. Why?

>    Although it is more beautiful to have 'The Lord of the Rings' rather than 'the lord of the rings', there are many, many special cases where style guides differ on which words to capitalise.
    As 'The Lord of the Rings' and 'the lord of the rings' are semantically identical, it is natural to search in a case insensitive way. When case does not matter, what point is there in recording it?
https://hydrusnetwork.github.io/hydrus/help/faq.html

So my question is: Why? I cannot see a purpose for this "feature request".

**Comment by OptoCloud** [comment]
Nevermind, i realized this is a useless feature 😅
