### ISSUE TITLE
auto add tags on server as regexes on import?

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#68]
would be nice to be able to add all known tags on our servers as regexes to be used on mass imports.
eventho i think this might take up too much processing power im import i do think it would make things alot simpler in may ways as it would look for every word that tags contain in the filename and auto add them as tags for the server on import.

**Comment by hydrusnetwork** [comment]
There was a discussion about this a while ago. I think it would be difficult to get right, and it would still require a human step to select "yes, this is a good tag for this file" or "no, this is a bad tag" that would need additional gui elements to support.

I will be adding a tag cloud/tag suggestions to the manage tags dialog in the future, which will need the same workflow, so perhaps that would be a good time to try this.

**Comment by AreFinstad** [comment]
i dont think it needs to be accepted at all. it could have a list of all the tags and use it like the standard regexes where it looks for the word in the filename and so on.
then again the regexe w\+ (or what it was) does mostly this anyway but also reads the folder name and other errors on the side..... even the file format.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
