### ISSUE TITLE
gallery import tab only processing batch import jobs when in focus

### ISSUE THREAD

**Issue by micnorian14** [hydrusnetwork/hydrus#684]
While trying to process multiple imports from multiple websites at once (ie artist's gallery from pixiv, danbooru, etc) the gallery parser and import queue appear to function normally in the gallery tab. The problem occurs when changing focus; to either another tab within Hyrdus, or minimizing Hydrus. The counter in the tab name "gallery (69/420)" will not process any more imports until focus is restored. Returning to the tab, the active process will send request and download normally. 

Still present on v413, present since about v368. Can not confirm if it was introduced in v368
![hydrus import bug](https://user-images.githubusercontent.com/11713661/95671077-b8324400-0b60-11eb-9948-4b00ba686306.jpg)

## Environment
Hydrus version: 413
Platform: Ryzen 2600/RX580
OS specifics: Win10x64Pro

Basic installation as windows executable
 
Not consistently reproducible. Annoying enough to start leaving the window in focus overnight. Takes a lot longer to process galleries. 

Nothing suspicious or erroneous in logs. The gallery import queue just...doesn't process. No reportable error.

**Comment by hydrusnetwork** [comment]
Thank you for this report. Is there any chance this download is only working because you are forcing the bandwidth to be overridden using the little 'cog' icon on the network job control? I know that that needs page focus to keep refreshing the bandwidth override (it is a bit of a hack).

**Comment by micnorian14** [comment]
Ah I am using the force bandwidth override function. A hack you say? I wasn't aware that page required focus to process :( 

Hmm if I can tweak the regular bandwidth rules for select pixiv/boorus I can avoid the force override bandwidth function. Is that possible on a per domain basis? If not, can you recommend a workaround better than leaving the main window in focus for hours to process one tag on one domain at a time? It's eh.. an incredibly utility-limiting "feature" I've gotten used to -_-

**Comment by hydrusnetwork** [comment]
Closing to tidy up, thank you for the report!
