### ISSUE TITLE
Gelbooru fringe results

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#685]
## Environment

Hydrus version: 412
Platform: Windows 7
OS specifics: 64bit

## What happens

Gallery download from Gelbooru doesn't download all content

## Steps to reproduce

1. Set up login script (description and gelbooru say you don't actually have to)
2. Make gallery download page and enter some fringe tag for gelbooru
3. Wait, wait some more
4. No fringe results are downloaded

## Desired outcome

Having actually whole tag downloaded.

**Comment by CatPlanet** [comment]
I logged into this account in web browser and set "display all content" checkbox.
After logging in private window the appropriate settings were cleared. It seems they're stored only in client side cookie

**Comment by imtbl** [comment]
Not a bug, Hydrus just doesn't come with the required cookie. The fringe benefits settings is not stored with your account, but just as a cooki.

In general, downloader-related issues are not considered bugs (unless it's actually some error coming up).

See [here](https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/tree/master/Downloaders/Gelbooru) for the required header that sets to cookie to download all the content).
