### ISSUE TITLE
Ability to add separate database locations for a specific tag or query

### ISSUE THREAD

**Issue by Senju-vilis** [hydrusnetwork/hydrus#690]
Only media with specified tag/query would be stored in that database location.
In other words - the specified tag/query would have 1.0 weight, while anything else - 0 weight to go into the designated location.

Unlike in #251, I want these files to be accessed, viewed and sorted together with the rest of database.
While #338 and #298 together could offer a workaround, I don't use archive/delete filter - 
and I definitely don't want to deal with 3 layers of them.

Instead I use my personal name-spaced tags to mark files of varied importance - 
anything with a personal namespace becomes a part of outer core and then certain tags make them middle or inner core.

These tag/query specific database locations would make backup process much easier -
I would simply pass these locations to something like restic.

Current workaround is share->export->file + tags.txt, but its is:
  a) more time consuming,
  b) requires extra free space.

**Comment by Zweibach** [comment]
The planned implementation of #338 would achive this.
