### ISSUE TITLE
Image Viewer: Keyboard Shortcut Action: Favourite Service Add Favourite.

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#691]
It would be nice if I could just tap a key like `f` to mark the currently viewed image as  favourite in any image viewing context.

**Comment by TheElo** [comment]
how does it differ from tag shortcuts?

you can setup "f" to add/remove "favourite" as tag

**Comment by Zweibach** [comment]
You can already bind ratings to shortcuts.

**Comment by bbappserver** [comment]
Ah indeed.  I found the problem.
By default `f` is bound in the media viewer to an action (bordered vs unbordered fullscreen) which seems to do nothing under MacOS, so you first need to rebind that, before using f as a `like/dislike` media action takes precedence.  

So yet another reason to warn of conflicting keybindings.
https://github.com/hydrusnetwork/hydrus/issues/491
