### ISSUE TITLE
support aPNG files (Animated Portable Network Graphics)

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#70]
aPNG's is a thing but is named as a .png file format while still being animated.
plz support this format, its used but not as much. but it supports much higher quality than gifs ever will.

example for apng gallery: http://g.e-hentai.org/g/804620/b299d602ef/
sorry for the H content as it was the quickest one i could find on a short notice. 
note that there is a chrome plugin in the comments or it can be viewed offline by some image viewers.

**Comment by hydrusnetwork** [comment]
I am all for this, but I use PIL and OpenCV for my image rendering. I had a look, but I don't think either support aPNG. I might be able to botch something together with ffmpeg, but I am not sure.

Since aPNG never got popular, adding full support would probably be too much work. I might be able to auto-convert to mp4 using ffmpeg--maybe that's a better solution?

**Comment by AreFinstad** [comment]
i know its not a popular format at all, dont really have much files at all. but yeah, atleast let it detect a difference between those and normal png's so it can open in an external program atleast..... but im not sure how that would work.

**Comment by ScoreUnder** [comment]
It's a format I appreciate: http://littlesvr.ca/apng/gif_apng_webp.html

If the worst came to the worst you could use apngdis to break them apart

**Comment by Link-Satonaka** [comment]
I think converting to webm/mp4 on import would be the best way to handle this. There are lossless mp4 profiles.

**Comment by KriPet** [comment]
I just read how in https://8ch.net/hydrus/res/2040.html you asked for a way of getting duration information from apngs, so I put this together for you to use as you want:

```
import struct
import re

def get_apng_duration(apng_filename):
    """Returns the duration of an apng in seconds"""
    patt = re.compile(b"fcTL.{20}(.{4})")
    with open(apng_filename, "rb") as f:
        c = f.read()
    fctls = [struct.unpack(">HH",frame) for frame in patt.findall(c)]
    frame_durations = [float(num)/(den or 100) for num, den in fctls]
    return sum(frame_durations)
```
If you just want the number of frames, you can do a `c.count(b"fcTL")` and be done.

To quickly explain how it works:
Every frame in an apng has a frame control chunk consisting of "fcTL" + 26 bytes as documented on https://wiki.mozilla.org/APNG_Specification#.60fcTL.60:_The_Frame_Control_Chunk

The regex skips the first 5 unsigned ints, and captures the next two unsigned shorts.

These two numbers, num and den are parsed to python numbers with struct.unpack.

The length of each frame is num/den, given in seconds.

The `(den or 100)` will swap out a `den = 0` with 100, as documented on the linked page.

I've tried it out myself, but it could probably stand some independent testing. Use it as you like.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
