### ISSUE TITLE
Gallery URL class: Gallery is group flag

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#704]
If https://github.com/hydrusnetwork/hydrus/issues/310 ever gets implemented, then the parse should be updated to tag a group rather than individual elements of some galleries.

In particular pixiv mangas, or ExH tend to pollute tagespace by tagging every single element of a collection with tags that apply to the group, even if only a single element of the group actually contains things to which that tag would apply.

This can get really egregious for example if someone posts a collection of various characters, causing every element of the collection to get every character.

----
The gallery is group flag would be set in the gallery url class component editor.  Setting this flag would cause content parsers on the gallery page to add tags to the group (and create the group as necessary), rather than to each hash in the collection.

**Comment by Zweibach** [comment]
Not sure what point there is in opening this issue instead of just adding it onto 310 like other, related suggestion dependent on that feature have been. Including some of your own.

**Comment by bbappserver** [comment]
That makes sense if you believe hash groups should not exist in isolation from parsers for them.  But I'm operating under the assumption that since they are completely different subsystems.  It is perfectly possible to create a group without it having been done programmatically by such a gallery parser.

In other words since updating the parser would be a different checklist item, not a sub item of hash groups it is a different ticket.

**Comment by Zweibach** [comment]
Since this is useless without image groups and really should be part of that issue I'm closing this.
