### ISSUE TITLE
Twitter Username Lookup Issue (Bug? User error?)

### ISSUE THREAD

**Issue by Mr-53918** [hydrusnetwork/hydrus#707]
I have never gotten Twitter Username Lookup to successfully sync.

## Environment

Hydrus version: 414 Executable
Platform: Windows
OS specifics: Windows 10

## What happens

Twitter Username Lookup doesn't seem to be working for me. Upon attempting to sync for the first time, I get the message provided below in the specified location on the form.

I have tried their username, display name, username with \@ preceding it, display name with \@ preceding it, and the URL in full to no success. I have tried it with multiple accounts as well, again unsuccessfully.

## Steps to reproduce

1. Set Twitter subscription.
2. Wait for sync.
3. Get message.

## Desired outcome

The desired outcome is for the files to be downloaded as they are for other subscriptions.

## Error message / Log file / Screenshots

> The query "A" for subscription "B" did not find any files on its first sync! Could the query text have a typo, like a missing underscore?

**Comment by bbappserver** [comment]
@Mr-53918
Works on my machine.

Are you using the dead twitter backed username lookup, or the working nitter backed lookup?

**Comment by Mr-53918** [comment]
> 
> 
> @Mr-53918
> Works on my machine.
> 
> Are you using the dead twitter backed username lookup, or the working nitter backed lookup?

I didn't realize the twitter username lookup was dead. I am trying the nitter lookup now.
