### ISSUE TITLE
add tags based on ocr results

### ISSUE THREAD

**Issue by pokeball99** [hydrusnetwork/hydrus#71]
have an option like "rightclick,"do you want to add tags based on the text in this image?" of course this won't be perfect,but still
https://github.com/tmbdev/ocropy seems like a good thing to impletement,but you might find something better

**Comment by pokeball99** [comment]
have i gotten overlooked?

**Comment by antonizoon** [comment]
What we would need to accomplish this is a decent OCR engine. Like, something really good. Currently the best one that is open for everyone to use is the [Microsoft OCR engine](http://blog.a9t9.com/2015/09/ocr-api.html), which beats even the best proprietary systems. 

[It can be tested out here.](https://ocr.a9t9.com/)

That's just for grabbing text though. How would we heuteristically determine what elements are worth tagging out of the text? Maybe search for existing tags within the text and then add it based on that? Such as `greentext`?

**Comment by hydrusnetwork** [comment]
Sorry about the delay, I'm trying to catch up on my github now. I've been both swamped and short on time just recently!

OCR is a nice idea. I don't like tag-harvesting without human approval, though (to stop 'hosted by 9gag' and 'copyright blah corporation 2014' and other crap being auto-added when we OCR), so before I add anything ocr-like (or harvest-tags-from-filename, which is a not dissimilar idea), I think I need a 'tag suggestion' system in the gui. Something like a checkbox list in the manage tags dialog so people can select what is an appropriate tag and ignore what is garbage. I am already planning this sort of thing to suggest tags based on already existing tags e.g. if a file already has character:ikari shinji, the suggestion control will suggest character:ayanami rei and other characters that tend to come together. Perhaps we could add a module/button to further populate this suggestion control with ocr results then.

So, I don't think I have time to work on this now, but it is certainly something that could happen in the future.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
