### ISSUE TITLE
Hydracula.qss: system:filesize data unit cut off

### ISSUE THREAD

**Issue by pozieuto** [hydrusnetwork/hydrus#721]
When using the Hydracula.qss style, in the dialogue for the system:filesize input predicate, the dropdown does not show the entire data unit (for those that are two letters long):

![example a](https://user-images.githubusercontent.com/67081751/98897985-87696580-24a4-11eb-82ea-1bf85ca7a8f5.png)

![example b](https://user-images.githubusercontent.com/67081751/98897986-87696580-24a4-11eb-982a-740a561e5369.png)

This may be indicative of further issues with this or other styles, but I haven't yet noticed any.

Hydrus version: 417
Platform: Windows 10 x64 version 1909

**Comment by Zweibach** [comment]
As of v429 this is still an issue for all non-default themes shipped with Hydrus.

**Comment by Zweibach** [comment]
After some testing I have figured out the problem. This code block, specifically the last two lines, are what causes the cutoff, removing them leaves things looking more or less the same except with no more cutoff.
```
QComboBox
{
    selection-background-color: #bd93f9;
    background-color: #6272a4;
    border-style: solid;
    border: 1.0px solid #000000;
}
```

**Comment by hydrusnetwork** [comment]
Closing this--sorry for being so late to it. There's a hack for this style problem now, in v499, as in the above referenced issue. I'll see about updating the style that comes with hydrus itself too, if that's a nicer fix.
