### ISSUE TITLE
Only one level of virtual parents being applied

### ISSUE THREAD

**Issue by Aegis43615** [hydrusnetwork/hydrus#725]
## Environment

Hydrus version:417
Platform: Extract on Windows
OS specifics: Windows 10 20H2

## What happens

Only one level of parents being applied. So lets say 'character:samus' has 'series:metroid' as a parent and likewise 'series:metroid' has 'studio:nintendo' as a parent. Currently if you add 'character:samus aran' it will only virtually add 'series:metroid'.

## Steps to reproduce

1. Give image a tag whose parent has a parent (ex: character:samus aran)
2. See that the image contains the character:samus aran and virtually has only series:metroid

## Desired outcome

The tag should get all parents of parents, etc up the whole chain of relations. So in this case a file with the tag 'character:samus aran' would virtually get 'series:metroid' and 'studio:nintendo'.

**Comment by hydrusnetwork** [comment]
Thanks again for this report. I will look into this carefully.

**Comment by hydrusnetwork** [comment]
I reviewed this today, and I discovered a way to reproduce this problem when updating existing sibling and parent multi-level chains. I have fixed bugs in chain regen and parent id lookups and scheduled a complete ideal cache regen on v420 update. That will only take a couple of seconds, and should fill in the several thousand missing rows (my test db went from 189,000 to 192,000 rows), which will fill in with normal display background maintenance processing. I also sped up a bunch of related code.

This may have also fixed the repository processing problems some users have had, or it may not. It may not have fixed your issue completely, but I feel good about it. Please let me know how you get on!
