### ISSUE TITLE
Launching the server should use the correct version of python

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#73]
When launched from menus in the hydrus client, the server currently launches in whatever the "python" executable points to. However, since python 3 is default in arch linux this doesn't work. Currently this is patched out in the AUR package but it would be nice to get rid of the patch.

`sys.executable` might be worth looking at here.

**Comment by hydrusnetwork** [comment]
Thank you for this, and the note about sys.executable. This is fixed for next week.
