### ISSUE TITLE
Tag Definition Search Cache Maintenance 'Done' Popup Unexitable

### ISSUE THREAD

**Issue by Aegis43615** [hydrusnetwork/hydrus#735]
## Environment

Hydrus version: 418 Extract
Platform: Win 10 Pro
OS specifics: Version 10.0.19042

## What happens

Pop up that appears when 'database -> regenerate -> tag definition search cache' is done cannot be closed

## Steps to reproduce

1. Run the tag definition search cache regeneration
2. Wait for it to finish and say 'Done'
3. Note that you cannot click anywhere but the modal window and when you click the 'X', its just an informational popup.
4. Use task manager to kill client

## Desired outcome

For the popup that says 'Done' to be closable. Or for it to just be one of those corner notifications, just some way to finish the process.

## Error message / Log file / Screenshots

<img width="275" alt="TagDefSearchCache" src="https://user-images.githubusercontent.com/67392701/99864623-5eb33100-2b72-11eb-8071-e1aad7e49f21.png">

**Comment by hydrusnetwork** [comment]
Thank you, sorry for this! I will check it out.

**Comment by hydrusnetwork** [comment]
Sorry for the trouble here. I believe this was fixed last month.

As it happens, this routine is replaced with a different system in tomorrow's release. That seems to be fine here, but let me know if you have any trouble with it.
