### ISSUE TITLE
Notifications API

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#743]
It would be nice to have access to the current stack of popup notifications through an API endpoint.

Additionally, the ability to have Hydrus send webhooks (hit another endpoint with a POST) for notifications could also be useful.

**Comment by dergness** [comment]
With the broad headline of "Notifications API", I also see creation of notifications from the API.

**Comment by floogulinc** [comment]
Completed with #1474 but that didn't close this issue for some reason.
