### ISSUE TITLE
Commiting Virtual Parents add un-removable (+1) to existing Parent tags

### ISSUE THREAD

**Issue by Aegis43615** [hydrusnetwork/hydrus#755]
## Environment

Hydrus version:420
Platform: Win 10
OS specifics: Win 10 Build 19042

## What happens

Okay lets say an image already has `character:samus` on its PTR mapping. That would give it `series:metroid` and `studio:nintendo` as virtual tags. Alternatively, you can even start with an image that has `series:metroid` or 'studio:nintendo' as a PTR tag

Then lets say in add `character:dark samus` as a PTR tag which also has `series:metroid` and `studio:nintendo` as it's parents. So now all three of those tags currently have a (+1) in tag display. When you commit this character tag, it will remove the (+1) for the `character:dark samus` but will leave the (+1) on the parent mappings that already (normally and virtually) existed on the image.

## Steps to reproduce

1.Add character:samus as pending to a PTR image
2.Commit tag to PTR
3. Add character:dark samus as pending to a PTR image
4. Commit tag to PTR
5. See that a (+1) still exists next to the parents that already existed on image

## Desired outcome

For parents to not have a non-removable (+1) after committing. Consider making virtual parents not get a (+1) at all when pending? Could go either way since technically you're not adding that tag but also you are technically that tag will be

**Comment by hydrusnetwork** [comment]
Thank you, I will check this out.

**Comment by hydrusnetwork** [comment]
Catching up on older open issues. This should have been fixed in the rounds of ghost tag logic fixes. I _believe_ parents and siblings now have good logic in situations where several tags imply the same thing.
