### ISSUE TITLE
Remote engagements ("likes" / ratings) from Hydrus

### ISSUE THREAD

**Issue by pozieuto** [hydrusnetwork/hydrus#757]
An unfortunate consequence of living in a reality where media consumption is dominated by closed platforms powered by obtuse content promotion algorithms is that one of the most reliable ways to help creators gain exposure is to "engage" with their works through those services - as the aforementioned promotion metrics are based on assumptions like that the more that people engage with a work, the better it must be, right? But when using Hydrus for aggregating media from across a variety of services for personal consumption, it becomes cumbersome to switch from using Hydrus to interfacing with the source platform in order to engage with the media there. Because of this, I rarely end up engaging with works simply because it is too inconvenient, even though I would like to.

Being able to have Hydrus perform these engagement actions on those services on your behalf would make these engagement actions incredibly easy to perform, to the point of being seamless if they are automated using actions already in your workflow.

Let's consider what engagement actions are commonly available:

- Like/Favorite
  - Retrievable values: true, _false_
  - Actions: set(), unset()
    Examples would include both likes and generic retweets on Twitter.
- Rate
  - Retrievable values: discrete value within range, _unrated_
  - Actions: rate(\<value>), unrate()
    Examples include five-star rating and upvote/downvote systems.
- Share
  - Actions: share([comment string])
    Examples include reblogs and "comment retweets" (ie. tweets with a link to another tweet).
    Most services just consider this to be making a new post, and so it's rarely possible to directly query whether or not you've already shared a given post.

- Comment
  - Actions: comment(\<string>)
    Some services only let you comment once on a post, but otherwise it's similarly rarely possible to directly query whether or not you've already commented on a post.

Likes/favorites and ratings would be the easiest to implement and automate. Rather than adding new control types for these, you would simply link local rating services to remote engagement types. For instance, a user with a simple local five-star rating service could use it to:
- for a booru service with an upvote/downvote system, have 0-1 stars correlate to a downvote, 2-3 stars and unrated correlate to no vote, and 4-5 stars correlate to an upvote;
- for Twitter, have 3-5 stars correlate to a like, and 5 stars correlate to a retweet.

Users adding engagement actions to an existing rating service should need to go out of their way to have it apply retroactively to already-rated files, if that capability is even given at all.

On the implementation side of things, while many sites for which a downloader can be defined also have engagement actions available, it would probably be better to keep downloader definitions and "engager" definitions separate.

**Comment by floogulinc** [comment]
This seems fairly out of scope for Hydrus. It's unlikely to even work with many of the platforms you would want, namely Twitter, which Hydrus can't even actually parse right now.

**Comment by pozieuto** [comment]
This is not like Hydrus' other functions at all, no, but I would think this would be relevant and useful to a lot of the people who use Hydrus for media consumption. It's also not all that different technologically from the stuff Hydrus is already capable of.

Hydrus would certainly need more functionality added before this becomes feasible to do with some platforms, yes. It was just useful as an example here.

**Comment by hydrusnetwork** [comment]
I would like hydrus to do some site rating stuff, particularly parsing ratings to feed them into hydrus ratings, but posting ratings from hydrus to other sites is not my thing, I'm afraid. I did have an imageboard dumper a million years ago, with even a captcha solver, but I retired it because it was a pain and I couldn't keep the maintenance up. We are a sucker, not a blower, ha ha ha.

I think this sort of project would work great in the Client API. You could search the files that had a 'like this' metadata, be that tag, archived status, or rating, and then import and call a site's API with your own credentials and send the 'favourite this' command or whatever you like.

If you do something like this, let me know and I'll stick it on the Client API page so other users can try it out too!
