### ISSUE TITLE
new option to skip image search if more than 5 pages are already downloaded?

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#76]
new option to skip image search if more than 5 pages are already downloaded?
would be nice to have an small checkbox option to stop the tag search of the booru downloader if a certain number of pages already have been downloaded.
nice for those time you download everything from one artist and/or tag and dont want it to finish looking over all the pages every time.

a checkbox on the downloading tab would be nice as it gives the user options to turn it on and off as they like/need it. 

and since the downloader gets the newest uploaded files first it would always download those before it comes to the old stuff that the user might already have.

**Comment by hydrusnetwork** [comment]
Thank you, this is a great idea. I have added it to my to-do list.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
