### ISSUE TITLE
Default setting for the "search immediately"-button in file search

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#761]
Since a lot of searches are done using more than one tag it would be good to have a setting to have default on opening a new file search page set to "search paused", or for Hydrus to remember the last set state.

![example of search](https://cdn.discordapp.com/attachments/207631384276107264/793182267693596682/unknown.png)
On a similar note it would also be nice to have a button to run a search on the current tags without changing the state, maybe change it to a pause button when a search is running.

**Comment by hydrusnetwork** [comment]
This is done for tomorrow's release, let me know if you have any trouble with it!
