### ISSUE TITLE
Petition dialog - setFocus() to the text entry field

### ISSUE THREAD

**Issue by PhuriousGeorge** [hydrusnetwork/hydrus#765]
Pretty self-explanatory, when petitioning tag(s)/parents/siblings/etc, it would be nice to immediately be able to start typing rationale rather than having to navigate to the text entry field first.

Not normally an issue, but recently fixed page numbers on a ton of comic images one at a time.  Would have been nice to save some extra clicks on an already manual curation process.

**Comment by Chad90b** [comment]
this is also known as setFocus() in Qt, just so there is confusion.

**Comment by hydrusnetwork** [comment]
Thank you for this report. It should be fixed for tomorrow's 424. Sorry for the trouble!
