### ISSUE TITLE
Livelock: Subscriptions hanging indefinitely and cannot be cancelled after prolonged slowdown

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#766]
Under load recent version of hydrus seem to lock up.  The GUI is responsive but the importing system comes to a screeching halt and cannot be cancelled.  Leading up to this issue several types of processing were slow including importing and writing repository updates.

## Environment

Hydrus version:422 (Source)
Platform:  OSX 10.13
OS specifics:

## What happened
- Network job notifications show some jobs stuck downloading and some stuck updating db.
- Subscriptions will not cancel when pause subscriptions activated.
- Network main menu will not respond to click, other menus are fine.
- Write lock (write_maintain_similar_files_search_for_potential_duplicates)
- Client will not perform normal shutdown (waited 10 minutes)
- Client will not perform emergency shutdown

#### Profiles of the client slowing down
[client profile - 2020-12-30 11-05-56.log.zip](https://github.com/hydrusnetwork/hydrus/files/5756528/client.profile.-.2020-12-30.11-05-56.log.zip)
[client profile - 2020-12-29 23-36-05.log.zip](https://github.com/hydrusnetwork/hydrus/files/5756529/client.profile.-.2020-12-29.23-36-05.log.zip)

#### Profiles and job schedule dump on hang
[logs.zip](https://github.com/hydrusnetwork/hydrus/files/5756530/logs.zip)

**Comment by hydrusnetwork** [comment]
Thank you, I have some ideas about this. I will be working on splitting up some network objects this week and reducing related CPU overhead, please let me know how 425 works for you.

**Comment by hydrusnetwork** [comment]
Ok, catching up with open issues, this should have been fixed with the network breakup. There are still some issues with limited thread resources when dozens of downloaders work at once, but the lockup stuff _should_ be clear.
