### ISSUE TITLE
Hydrus does not convert uppercase to lowercase when importing tag blacklists.

### ISSUE THREAD

**Issue by crimsonraes** [hydrusnetwork/hydrus#768]
When using the import/export function of blacklists in the 'Manage Subscriptions' > 'Edit Subscriptions' > 'Edit Tag Import Options' window, Hydrus does not convert any uppercase letters in the imported blacklist to lowercase and adds it as-is.

## Environment

Hydrus version: 423
Platform: Windows 10 Pro
OS specifics: Build 19042.685

## What happens

![image](https://user-images.githubusercontent.com/46853454/103452661-b7acd380-4c9f-11eb-907f-995b5cdf6224.png)

In the image above, I copied `[44, 1, [["character:ganyu (genshin impact)", 1], ["character:Zdrada (helltaker)", 1]]]` to my clipboard and imported it into Hydrus as a blacklist. Note the capital 'Z' in 'Zdrada'. As shown in the image, the blacklist also shows Zdrada capitalized. Typing "Zdrada" into the blacklist manually adds 'zdrada', all lowercase. Exporting the blacklist and pasting it in a notepad shows that the uppercase letters are preserved.

When downloading subscriptions, `character:Zdrada (helltaker)` does not block `character:zdrada (helltaker)`, presumably because the blacklist is case-sensitive.

## Steps to reproduce

1. In a subscription, edit the tag import options and add/edit the file blacklist by importing `[44, 1, [["character:ganyu (genshin impact)", 1], ["character:Zdrada (helltaker)", 1]]]` from the clipboard. Typing directly into the text field does not work because Hydrus converts that to lowercase.
2. Try downloading "character:zdrada (helltaker)" from danbooru (or whatever tag/site combo is being used).
3. The "blocked" zdrada tag is still downloaded.

## Desired outcome

Hydrus should convert the imported blacklist to all lowercase.

**Comment by Zweibach** [comment]
Bug still present in v429. Furthermore, the uppercased tag is not removable. Marking it and hitting delete does not remove it, double-clicking it adds and removes a lowercased version. The lowercased tag given in the example behaves as expected.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I apologise for the inconvenience and delay. This should be fixed in tomorrow's release--please let me know if you have any more trouble.
