### ISSUE TITLE
audio playback on video and flash?

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#78]
hmmm one thing i feel missing is a way to have audio playback for videos and flash files in general.
you have this kickass player that handles mp4's webm's gif's and flash files with smooth playback and even with next/previous navigation.
the main thing im missing for the viewer is audio tho.
something like this also needs a global setting the user easily can turn on and off with a button or keybinding

**Comment by hydrusnetwork** [comment]
This is planned, thank you. I need to write an audio buffer that links to ffmpeg and then figure out how to broadcast that in sync with the current video, probably with PyGame or PyMedia. I'll also add global mute options. This will be a fairly big job, but one I definitely want to do.

**Comment by AreFinstad** [comment]
good to know you are thinking about it for sure :D 
audio is needed more than ever IMO because of how webm's gets more and more mainstream nowadays, audio would also be great for those flash games/videos people have aswell.
it would just open up how people could use hydrus more than ever.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
