### ISSUE TITLE
Api /request_access_permissions 404

### ISSUE THREAD

**Issue by NO-ob** [hydrusnetwork/hydrus#780]
## Environment

Hydrus version: 424
Platform: Linux
OS specifics: Arch Linux - using github release not aur

## Steps to reproduce

1. Enable api and then open > services > review services > clinet api > add > from api request
2. Http get on urls mentioned above
3. Getting 404, also tried in the browser with same result

## Desired outcome
An acess key to be returned

## Error message / Log file / Screenshots

Not seeing any output in terminal from hydrus, output from my app printing response is 

```
I/flutter (19584): <html>
I/flutter (19584):   <head><title>404 - No Such Resource</title></head>
I/flutter (19584):   <body>
I/flutter (19584):     <h1>No Such Resource</h1>
I/flutter (19584):     <p>No such child resource.</p>
I/flutter (19584):   </body>
I/flutter (19584): </html>
```

**Comment by kotonbu** [comment]
Seems the API help documentation has some incorrect information for the example, the endpoint is /request_new_permissions.

**Comment by NO-ob** [comment]
Oh that worked lel thankyou

**Comment by hydrusnetwork** [comment]
Thank you for this report! Sorry for the trouble, I will fix this documentation.
