### ISSUE TITLE
program wont release my buttons..

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#79]
hydrus seems to not release my buttons when used.
for example i use TeamSpeak or Discord as a chat program with voice chat and push to talk enabled then my button wont work at all.
this is kinda an issue as i dont have issues with other programs like this so if i return to hydrus for a min or two to manage a few small things while having time for whatever reason the button just wont work at all....ofc i forget that it doesnt work and then ill just sit there talking to my self i guess. 

just for notes sake i use this button for my talking: <
(prob not needed tho)

it just all points to that hydrus doesnt release the button for whatever reason, other programs doesnt work if you have a hotkey like that it seems.

**Comment by ScoreUnder** [comment]
Just in case it makes it easier to work out: what button(s) are you using that get absorbed by hydrus?

**Comment by AreFinstad** [comment]
like i said in the first post its : < and >
its right next to the Z button on the European keyboards :D

**Comment by hydrusnetwork** [comment]
I am not sure what is going on here. I do not think hydrus tries to capture those specific keys on purpose anywhere, so I think I must not be releasing a certain kind of key event.

Just to be certain: does the hotkey only not work when you are doing things with hydrus, or does focusing hydrus permanently break the hotkey, even when you move back to a different program?

On my keyboard, '<' and '>' are normally ',' and '.' . I have to put shift+',' or shift+'.' to get '<' or '>'. Is this the same for you? Are you hitting shift+',' to trigger your hotkey, or can you get '<' with a single keypress?

If you open the 'review services' frame at _services->review services_ and make sure that new window is focused, does the hotkey work then?

If you temporarily change your hotkey to F9, does it work?

**Comment by AreFinstad** [comment]
its only when the program is highlighted. it works right away when i select another program.
and on the nordic keyboard its just one button and doesnt need shift at all. i can press it without an shift or alt hold. its right next to my left shift and z :D

**Comment by hydrusnetwork** [comment]
I had a look at the code and can't figure it out. I think my Accelerator Tables might be stealing the key events. These are something I will be removing in a future shortcut system rewrite, so your problem might be fixed in that.

The 'review services' frame doesn't use an Accelerator Table. If you have that focused, does the shortcut work then?

**Comment by AreFinstad** [comment]
so yeah, i tried using the keybinding with "review services" and all options pages aswell as "manage services" aswell.
no luck sadly, tho some windows did try to use the key in question eventho some didnt even supported key inputs (like a search bar).

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
