### ISSUE TITLE
flash and video thumbnails?

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#80]
with auto generate with ffmpeg (best way IMO) or enable us to choose a thumbnail for each file (a pain to do with LOADS of files IMO)

alot of flash files has its own main screen image that it uses for thumbs. images can be inbedded into videos aswell and those should be used if they have those in anycase.
if videos does not have image files inbedded it will scrobble down to 30% and grab a screen there

on windows i use this program to handle thumbs for windows, it has swf support and all that aswell with a range of options.
something like that would be perfect IMO. 

right now atleast swf is not supported in anyway and mp4's and webm's only pull thumbs from the first frame and not into the frame or inbedded images (like if i want to use hydrus for animated content and so on) 

like this image for example, it is an mp4 file and it has an inbedded image aswell as is very long, hydrus only pulls the first frame which is black and doesnt help with anything really.

![](http://i.imgur.com/MezBtDv.png)

all in all (might be on repeat here XD) is use inbedded image if there is any and if not it should scobble to 30% (sounds fair IMO) and grab a new thumb to use. 

flash on the other hand can use the first frame alot of the time, or maybe have it run for a 10-20 sec before grabbing a thumb as then it would usually get to the main screen where you can press play and so on.

**Comment by Sssssawdsaswad** [comment]
The developer has already said he wants to add thumbnail scrobbling, in fact his vision is to have the thumbnail flick through the video when you have your mouse hovering over it much like some websites do.

The SWF thumbnail thing is interesting though, I haven't heard of that implementation before.

**Comment by AreFinstad** [comment]
swf thumbs are great and and you can get thumbs for windows explorer with media preview ( http://babelsoft.net/products.htm ) aswell :D 

i do get that the thumb down on the lower left just runs the video all the way through and it does that now. 
i kinda meant the actual file picking thumbs (to the right on the image)
that is where its important, thumbs for what you have highlighted is little use IMO (never bother, either use the full viewer or not at all)

**Comment by Sssssawdsaswad** [comment]
I knew what you meant, I was not talking about the preview pane.
https://8ch.net/hydrus/res/471.html#1074

**Comment by hydrusnetwork** [comment]
I had a look around for ways to generate thumbs from swfs and have a fairly good lightweight and multiplatform solution in swfrender in SWFTools. It will be a big change, and will probably need a network version increment, so I don't want to rush it out this week, but I will make it top priority.

As said, animated thumbs and thumbnail frame offset is a future plan.

**Comment by AreFinstad** [comment]
dont need it to be animated imo, the program already is pretty slow. fast and simple does it IMO.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
