### ISSUE TITLE
client.exe keeps dissapearing.

### ISSUE THREAD

**Issue by lexvi** [hydrusnetwork/hydrus#814]
Hydrus version: 427
Platform: W10
OS specifics: Home.

Hydrus client.exe keeps dissapearing. seems to vanish everytime the client closes. or on computer restarts / completelly randomly. im using version 427. recently updated from 410 to 427 after which the dissapearing issue started.

Cannot update to 428, some error happens on launch which keeps me from updating.

1. Computer Restart seems to delete it 100% of the time
2. 50% chance when just closing the client.

**Comment by Zweibach** [comment]
Check your anti-virus for actions taken. There's been a much higher than usual rate of false positives the last few versions.

**Comment by lexvi** [comment]
i just realized after thinking a moment it cant really be an issue with the client..

Anti virus is not reporting it as being harmfull. which is weird if it keeps deleting it without asking me first or reporting it.

**Comment by lexvi** [comment]
ah, found it in Anti-Virus Quarantine, added an exception.

Thanks for your assistance.
