### ISSUE TITLE
"exclude (a tag) from current search" context menu does not toggle include/exclude

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#815]
## Description

Selecting **remove (a tag) from current search** in the context menu of the search list does not invert the search as in previous versions.  

## Reproduction Steps (example)

1.  Type `-creator:*` and add to search.  _Result: A new entry appears in the search list, e.g. `-creator:*anything*`, and only files that do not have any creator: namespace appear in the results._
2. Right click `-creator:\*anything*`, then select "exclude creator:\*anything* from current search".

## Expected

The selection changes to `creator:*anything*` and files with any creator: namespaced tag are included.

## Actual

`creator:\*anything\*` is added to the list, while `-creator:\*anything\*` remains.   No results are displayed.

## Environment

Hydrus version: v429 but (unsure when this issue first occurred.)
Platform:  Windows
OS specifics:  Windows 10 1909

**Comment by hydrusnetwork** [comment]
Thank you for this report. The data comparison here slipped through when I did the taglist backend overhaul a couple weeks ago. It is fixed for v430, please let me know if you have any more trouble!
