### ISSUE TITLE
merged download tab?

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#82]
been thinking a bit, why limit the program to have only one tab per booru/download site.
say if you want everything from one tag and so on, why cant we pull from more than one site at a time.
letting the user choose what booru they want and how many.

that way when people search for images with a tag it will search for more than one at a time.
also downloading the images can be done in sequence i would think giving each booru a break while only having one tab to take care of it.

ofc if the system can handle it, it would also be great to have a way to download more than one file at a time from different boorus and give us an option to limit sources (say you can set only two or three sources and it will only connect to two or three boorus at a time)

this is what i really miss with hydrus ATM, danboorudownloader did this where the user could check each booru they wanted to download and search from and it would search and download on all those sites within one tab.
that program did not download more than one image at a time but was much easier to manage in general as it was all on one page.

right now i need 3 or more tabs up at any time if i plan to download something, it can be a bit much IMO.

**Comment by AreFinstad** [comment]
any news on this? 
a neat ui should be used for this i think when changing where you download from, again pointing to danboorudownloader. 

![](http://i.imgur.com/yUwz8Z1.png)

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
