### ISSUE TITLE
\x00\x00\x00\x00\x00

### ISSUE THREAD

**Issue by wowregistering** [hydrusnetwork/hydrus#821]
I have recently been getting notifications that are just "\x00\" repeated many times, and the number of notifications keeps increasing.

## Environment

Hydrus version:428
Platform: windows
OS specifics: 10 64bit

## Steps to reproduce

I am not sure what steps to use to reproduce.  There is a gallery download going on in one tab, and a general tag search in another.
![Hydrus_Client_client_2021-02-26_23-15-51](https://user-images.githubusercontent.com/32309624/109375274-890b3d80-7889-11eb-8c0d-d7d652013b0d.png)

**Comment by Zweibach** [comment]
You're two versions behind. Upgrade and report back if the issue persists.

**Comment by wowregistering** [comment]
I have not seem to run into the issue again yet, even before updating but I have just applied the most recent release and will reopen this ticket if the issue comes back.

**Comment by wowregistering** [comment]
Issue has occurred again.


Hydrus version:430
Platform: windows
OS specifics: 10 64bit

What I was doing when the error occured:  Doing a tag search consisting of system:archive already applied and attempting to search and apply 'murata_range'.

After this error occurs I am no longer able to get the tag filtering interface to populate any results as a term is being input.

**Comment by wowregistering** [comment]
Images attached of attempted search and the notification window.
Every attempt to search/apply any non 'system:' entry causes another identical error to appear in the notifications.


![2021-03-03_14-47-46](https://user-images.githubusercontent.com/32309624/109863291-7731ed80-7c2f-11eb-947a-8076134fc996.gif)
![2021-03-03_14-49-57](https://user-images.githubusercontent.com/32309624/109863623-d98aee00-7c2f-11eb-971a-5562f3101817.gif)

**Comment by matjojo** [comment]
Can you show us your whole log? Just one of the log events should be okay, you can either copy them from there or via the log files in the DB folder.

**Comment by wowregistering** [comment]
Ways to reproduce error(for me)
1: Restart Hydrus
2:Set "system:archive" as the only filter
3:Enter and apply any other non-system filter
4:Fails here and gives /x00/x00 notifications(sometimes it will work this first time after a restart and properly populates the list on the right)

**Comment by wowregistering** [comment]
I am unable to copy the notification from the notification window like with other notifications(ex from subscriptions)

[client - 2021-3.log](https://github.com/hydrusnetwork/hydrus/files/6078828/client.-.2021-3.log)

**Comment by matjojo** [comment]
Here this is the trace. that is repeated quite often. Seems to me that there is a tag in your DB that only consist of elements that are cleaned up in trimming:


```
2021/03/03 14:58:21: Traceback (most recent call last):
  File "hydrus\core\HydrusThreading.py", line 401, in run
    callable( *args, **kwargs )
  File "hydrus\client\gui\search\ClientGUIACDropdown.py", line 323, in ReadFetch
    predicates = HG.client_controller.Read( 'media_predicates', tag_search_context, tags_to_count, parsed_autocomplete_text.inclusive, job_key = job_key )
  File "hydrus\core\HydrusController.py", line 625, in Read
    return self._Read( action, *args, **kwargs )
  File "hydrus\core\HydrusController.py", line 199, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "hydrus\core\HydrusDB.py", line 1091, in Read
    return job.GetResult()
  File "hydrus\core\HydrusData.py", line 1855, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: TagSizeException: "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               " tag seems not valid--when cleaned, it ends up with zero size!

Database Traceback (most recent call last):
  File "hydrus\client\db\ClientDBMaster.py", line 538, in GetTagId
    HydrusTags.CheckTagNotEmpty( clean_tag )
  File "hydrus\core\HydrusTags.py", line 181, in CheckTagNotEmpty
    raise HydrusExceptions.TagSizeException( 'Received a zero-length tag!' )
hydrus.core.HydrusExceptions.TagSizeException: Received a zero-length tag!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 722, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 15061, in _Read
    elif action == 'media_predicates': result = self._GetMediaPredicates( *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 10735, in _GetMediaPredicates
    tag_id = self.modules_tags.GetTagId( tag )
  File "hydrus\client\db\ClientDBMaster.py", line 542, in GetTagId
    raise HydrusExceptions.TagSizeException( '"{}" tag seems not valid--when cleaned, it ends up with zero size!'.format( tag ) )
hydrus.core.HydrusExceptions.TagSizeException: "  
```

I think your best bet is to try to email dev or message him on discord so that he can check this out.

**Comment by wowregistering** [comment]
I will be sure to do that. thank you for the replies.

**Comment by wowregistering** [comment]
After speaking with the hydrus_dev on discord my issue was resolved by running database->check and repair->fix invalid tags

**Comment by hydrusnetwork** [comment]
I will improve this error catching so it runs the 'fix invalid tags' routine automatically and gives a nicer popup!
