### ISSUE TITLE
Orphan File Record maintenance does not detect orphaned PTR updates

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#835]
## Environment

Hydrus version:428(source)
Platform: Mac 10.13
OS specifics: 

## What happens

Maintenance>clear orphan file records
Reports there are no orphan files

Exporting update files shows there are

```
2021/03/23 19:18:12: Trying to copy /Volumes/hydrus/f0e/0e4fbccac9f608880b005160b2a5740c6c133344019d25b94ed1af6fc41ef7b3 to updatefiles/0e4fbccac9f608880b005160b2a5740c6c133344019d25b94ed1af6fc41ef7b3 caused the following problem:
2021/03/23 19:18:12: Exception:
2021/03/23 19:18:12: FileNotFoundError
[Errno 2] No such file or directory: '/Volumes/hydrus/f0e/0e4fbccac9f608880b005160b2a5740c6c133344019d25b94ed1af6fc41ef7b3'
Traceback (most recent call last):
  File "hydrus/core/HydrusPaths.py", line 751, in MirrorFile
    shutil.copy2( source, dest )
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/hydrus/f0e/0e4fbccac9f608880b005160b2a5740c6c133344019d25b94ed1af6fc41ef7b3'
```

## Steps to reproduce

1.Delete an update file from storage and run orphan file record check

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am sorry I am getting to it so late. In the 'file records' context, 'orphans' means files that are in 'my files' but not in 'all local files' or vice versa, an actual invalid file storage record, whereas in this case the files are listed correctly in 'repository updates' file domain, but they are not actually needed by any current repository.

Unfortunately there is no automatic system for deleting no longer needed update files. Advanced users can load them up in a search page and delete manually, but of course this is no good. I think an extension to the trash monitoring system would be a good place to put this, although I also would want a grace period before deleting, so perhaps it could be integrated into the trash system generally, and allowing recovery from trash if, let's say, the service is re-added within a few hours and that file is wanted again.

I plan for the multiple local file service system to have more intelligent trash, trash that remembers which file service a file came from, which would be ideal for this problem, where we want trash for our repo files, but we don't want them mixed in with normal media files in the trash.

**Comment by bbappserver** [comment]
@hydrusnetwork This seems to have been fixed in ptr update recovery logic, and was a greater symptom of the weird update failures people were having at the time this issue was opened.  I believe it to be resolved and you may close it if you concur.

**Comment by bbappserver** [comment]
Issue appears fixed closing.
