### ISSUE TITLE
PTR update downloading can create file records for invalid PTR update files

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#837]
## Environment

Hydrus version:428
Platform: Mac 10.13 (Source)
OS specifics: 

## What happens

I have a corrupt PTR file in my history that is preventing further processing or download.  It must a valid file record, because running a file maintenance task to move out if incorrect does not remove the problem file.  This suggest that unlike regular files a different process is being used whereby a file record is created before the file is fully downloaded and moved to the correct location.

## Desired outcome

Ideally when hydrus detects the file is faulty on actually trying to process it,it should be able to automatically back up through history until it finds a hash that returns valid information from the PTR server and then use this to re-download the correct update files, and reject any update files which appear to be erroneous.

## Error message / Log file / Screenshots

```
2021/03/23 17:18:49: Attempting to download an update for public tag repository resulted in a network error:
2021/03/23 17:18:49: 404: This update hash does not exist on this service!
```

Specifically the hash `127e8cb49cc741e133de4a05ed680c8c195a55fe450e11e3f49ce75031ba51bc`
Is being requested which according to Suika doesn't exist.
https://discord.com/channels/207629417290268672/207629417290268672/824085436589932616

**Comment by Radtoo** [comment]
Same problem, but I have not seen if the hash matches.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am sorry I am only catching up with it now. I believe this issue is now fixed with the new automatic update maintenance system and the metadata resync command I added earlier this year. This problem _should_ now fix itself. Please let me know if you still have any trouble.
