### ISSUE TITLE
The /manage_pages/get_pages api endpoint returns incorrect data

### ISSUE THREAD

**Issue by vonthar** [hydrusnetwork/hydrus#841]
## Environment

Hydrus version: 433
Platform: Windows 7

## What happens

The json object returned by the /manage_pages/get_pages api endpoint has every page marked focused: true

## Steps to reproduce

1. Open browser
2. Go to http://localhost:45869/manage_pages/get_pages?Hydrus-Client-API-Access-Key=***

## Desired outcome

Only the focused page and its ancestors are marked focused: true, other page objects are marked focused: false

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am very sorry for the slow response! This is fixed for tomorrow's 453.
