### ISSUE TITLE
Prevent favourites from being sent to trash

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#846]
If you use the favourites service and mark something as favorite it, there should be a setting to make it impossible to trash it without unmarking it.

**Comment by F18SuperHornet** [comment]
I would suggest adding a checkbox to the settings, where files **in archive** are impossible to delete.

**Comment by hydrusnetwork** [comment]
I have written a prototype for this for tomorrow's release, for archived files. It will be expanded to support cleverer rules in future when I write the metadata conditional object, and I'll also improve some of the dialog notifications when it applies and add some sort of padlock icon.

If you use it, let me know how you get on!
