### ISSUE TITLE
Hydrus fails to start on MacOS Catalina.

### ISSUE THREAD

**Issue by arthurrasmusson** [hydrusnetwork/hydrus#848]
Hydrus fails to start on MacOS Catalina both on fresh installation (without a database present) and on a system with an existing database.

## Environment

Hydrus version: 431, 432, 433
Platform: MacOS Catalina
OS specifics: x86_64

I am running the Hydrus executable.

## What happens
Upon launching the Hydrus client after upgrading to MacOS Catalina the software does not appear to start. This appears to be the case even after wiping all files in the database as well as running a fresh reinstallation of the Hydrus software.

## Steps to reproduce
1.Run Hydrus on a MacOS Catalina device.

## Desired outcome
 Functioning Hydrus software on MacOS Catalina

## Error message / Log file / Screenshots
No graphical interface appears during startup and the process appears to hang in Activity Monitor.

When executed from the terminal output is as follows:
![image](https://user-images.githubusercontent.com/47877520/114286259-1914d900-9a2b-11eb-9d33-c2fa5ce6d207.png)
Note 100% CPU utilization.

**Comment by arthurrasmusson** [comment]
Additional note: this continues for several hours without any change in CPU utilization or additional logging in the terminal. I have copied my existing database to an external x86_64 Linux machine and confirmed it is working. I have also wiped all Hydrus data from `~/.hydrus` and `~/Library/Hydrus` on this machine and reinstalled several versions of Hydrus but the issue remains.

**Comment by professor-mesmerize** [comment]
Fwiw, Hydrus starts and functions for me on two different Macbooks that are also on Catalina (OSX 10.15.7), and I've been able to continue using it successfully throughout the past few updates, including the most recent one.

I haven't tried launching the executable right from the command line like that, but my primary installation (installed via the dmg distro) boots up fine, and I'm also able to run it from source by running the usual `client.pyw`. Happy to do further testing if it helps isolate the issue for you, @arthurrasmusson

**Comment by arthurrasmusson** [comment]
Hmm will take a look on if there are additional file reads or writes to files I have not cleared off my disk in full. I'll look to find a suitable debug utility. Procmon on Windows comes to mind - this would print a list of all file reads and writes during execution which would presumably provide the information needed to isolate the problem.

**Comment by arthurrasmusson** [comment]
v435 makes some changes improving MacOS Big Sur compatibility.
![image](https://user-images.githubusercontent.com/47877520/114947350-ff083b80-9e1a-11eb-97bf-b68b73234bf3.png)

![image](https://user-images.githubusercontent.com/47877520/114947482-3a0a6f00-9e1b-11eb-81ef-042857c42c66.png)
After testing v435 on my own machine I can confirm that the issue has been resolved for me.
