### ISSUE TITLE
Fail to start Mac Big Sur

### ISSUE THREAD

**Issue by jegornagel** [hydrusnetwork/hydrus#849]
The app fails to start on Big Sur 11.2.3

## Environment
MacBook Pro (15-inch, 2018)
Hydrus Version 434

I'm running app from executable from https://github.com/hydrusnetwork/hydrus/releases

## What happens

1. Launching the app
2. Icon appears in the dock panel
3. Hydrus "is not responding"
![image](https://dl.dropboxusercontent.com/s/pwms0dwy2xkqlie/Screenshot%202021-04-13%20at%2009.30.19.png?dl=0)

**Comment by Suika** [comment]
https://github.com/Suika/hydrus-build-test/releases/download/v668/HydrusNetwork-v668.dmg

**Comment by Suika** [comment]
Duplicate #729
