### ISSUE TITLE
Support for OR Logic Conditions in Client API

### ISSUE THREAD

**Issue by prof-m** [hydrusnetwork/hydrus#854]
In the Client API's `/get_files/search_files` endpoint, it'd be great if we could add support for OR conditions when searching for multiple tags. That would let API consumers make fewer API requests when trying to get a result set that contain optional tags, and allow for Hydrus to do the sorting on the results before they're returned to the API consumer (once the API supports sorting).

**Comment by floogulinc** [comment]
Added in https://github.com/hydrusnetwork/hydrus/releases/tag/v453
