### ISSUE TITLE
Tag Parent/Siblings prediction based on current usage

### ISSUE THREAD

**Issue by DonaldTsang** [hydrusnetwork/hydrus#856]
After reading these, there seems to be concrete effort in tag aids. They gravitate towards co-occurrence of tags within images, the "topic" of the images/tags, and sometimes tag usage patterns by users. 
- https://keg.cs.tsinghua.edu.cn/jietang/publications/IJCAI09-Tang-et-al-Ontology-Learning.pdf
- https://sci-hub.se/https://link.springer.com/article/10.1007/s11042-014-2309-3
- https://sci-hub.se/10.1007/11762256_31
- https://intranet.csc.liv.ac.uk/~frans/PostScriptFiles/Rules%20for%20Inducing%20Hierarchies%20from%20Social%20Tagging%20Data%20PRICAI2018.pdf
- http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.142.7712&rep=rep1&type=pdf
- https://www.aclweb.org/anthology/L18-1156.pdf
- https://www.kde.cs.uni-kassel.de/wp-content/uploads/pub/pdf/cattuto2008semantica.pdf
- https://www.scitepress.org/Papers/2011/31510/31510.pdf
- https://hal.archives-ouvertes.fr/hal-00530371/document

**Comment by Mengmoshu** [comment]
Not Actionable.
