### ISSUE TITLE
pinned tabs?

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#86]
pinned tabs, would be nice to have them. 
to be able to save a tab (download, file or any at all really) and save it in a tablist where the user can easily return to it at a later point.
this wouldn't be the same as having it open tho as it would just save the contents of the tab and close it (to save resources).

by having pinned tabs the user can make their favorite tabs saved, one tab for each of their favorite artists, one for each download tab (while remaining the download queue if possible) and ofc a combination of tag searches.

you could think of it as a bookmark for your tags.
i feel this is missing ATM as if you are importing/downloading and managing in general then you will most likely have alot of tabs open all the time and that can slow everything down in general.

**Comment by AreFinstad** [comment]
as a bookmark list might get bigger with time, i think it might be handy to have the ability to color code the text of the bookmarks/pins and even be able to set a thumbnail next to the text. 

the thumb size of how steam does it comes to mind: ![](http://i.imgur.com/3KUOcOh.png)

tooltips could also be used for this for showcase some of the files in the bookmark/pin (like an image carousel that shows previews of random files in the bookmark/pin

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
