### ISSUE TITLE
Hydrus v435 reports incorrect pending count(incorrectly detects pending content_updates done?)

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#860]
Hydrus is reporting that I have 842 pending tags, but committing them causes hydrus to report that upload is complete without changing the number, and, forgetting them doesn't change the number either.  Prior to this it was reporting 1400, but never seemed to finish uploading very quickly, almost as though it was repeatedly sending nothing and then not correctly detecting that it had nothing further to send, because it misread the count.  So I told it to forget pending and that's when it changed to 842.  But at least now it's not in a continuous loop of sending but the number not going down.  It was working as expected before the number hit 1400.

## Environment

Hydrus version:435
Platform: OSX 10.13(source)
OS specifics: 

## Error message / Log file / Screenshots

When in the 1400 send loop, db access was as follows:
```
2021/04/22 18:31:14: Running write content_updates
2021/04/22 18:31:14: Running read nums_pending
2021/04/22 18:31:14: Running read pending
2021/04/22 18:31:14: Running read nums_pending
2021/04/22 18:31:14: Running read nums_pending
2021/04/22 18:31:14: Running write content_updates
2021/04/22 18:31:14: Running read nums_pending
2021/04/22 18:31:14: Running read nums_pending
2021/04/22 18:31:14: Running read pending
2021/04/22 18:31:14: Running read nums_pending
2021/04/22 18:31:15: Running write content_updates
```

**Comment by QueenHek** [comment]
Update to 436, you're not on the last version.

Which coincidentally, addresses this bug.

**Comment by Zweibach** [comment]
From v436 patch notes:
> pending tag cache regen

>    two new maintenance tasks are added to the database->regenerate menu--one that forces a recalc of your total 'pending' count as used in the pending menu, and one that recalculates the cached pending tag mappings for storage tags (just like the display one added some time ago, but one layer deeper). the menu entries are relabelled appropriately
    these routines will be run on database update, and should correct the bad pending menu counts many users discovered last week (the new efficient way that the pending count is calculated exposed some legacy bad cached pending storage mappings entries. we'll see if they come back, or if this is just clearing up bad counts hanging around from ages ago)
    the quick pending mapping cache regen routines take a little longer to initialise now, but they now clear out surplus tag data, rather than just regenerating the 'correct' tags

Also, stop making bug reports on old versions.
