### ISSUE TITLE
macOS does not display images at full resolution

### ISSUE THREAD

**Issue by Quartzic** [hydrusnetwork/hydrus#864]
## Environment

Hydrus version: 437
Platform: macOS (Apple Silicon)
OS specifics: macOS 11.3 20E232 arm64

## What happens

When using a 4K monitor, media is still displayed at 1080p.

## Steps to reproduce

1. Install a 4K monitor.
2. View an image in Hydrus that is high-resolution (at least greater than 1080p so you can notice the difference).
3. It is displayed at less than native resolution.

## Desired outcome

I would like to see Hydrus on Mac display media with the same behavior as Windows; that is, full-resolution previews and full-resolution playback.

## Error message / Log file / Screenshots

![wMeHXG2W](https://user-images.githubusercontent.com/2530648/116734854-c2f8dd00-a9bb-11eb-91fb-ad99187cfc26.jpg)
The interface is displayed in 4K, but the image is not. You may have to zoom in to see - compare the pixels on an interface element to the pixels on the thumbnail.

**Comment by Quartzic** [comment]
Fixed in v496

**Comment by floogulinc** [comment]
> Media playback, which constitutes most of this issue, was fixed in v496. Thumbnails still appear to be unaware of UI scale.

Thumbnails are scaled up to display as the right size. Eg a 150 wide thumbnail will be scaled up to 300 wide on a 2x scaled display so it appears the same size as it would on a 1x display. This is intentional.

**Comment by floogulinc** [comment]
Thumbnail display size is currently tied to their physical size so to maintain consistent display size when switching between screens with different DPIs it was changed to display thumbnails based on the effective virtual resolution after DPI scaling. The real solution to this is to decouple the way thumbnails are displayed from their physical resolution but that hasn't happened yet.

**Comment by gabrielott** [comment]
This was fixed in version 511 with the 'Thumbnail UI scale supersampling %' option under options->thumbnails, so I think this issue can be closed.
