### ISSUE TITLE
url downloader randomly ignores urls

### ISSUE THREAD

**Issue by spiralw** [hydrusnetwork/hydrus#865]
## Environment

Hydrus version: 437 (running from source, installed dependencies via pip)
Platform / OS specifics: Linux Mint 

## What happens

sometimes the url downloader will say it ignored an url, but there isn't any clear reason why this happened

## Steps to reproduce

1. input the url of a booru image page into the url downloader (such as <https://danbooru.donmai.us/posts/4498082>)
2. the url downloader will say `0 successful, 1 ignored`
3. open the booru page in your browser and copy the raw image URL
4. the url downloader will correctly download it

(sometimes it will download the image correctly from the image page, but most times it does not)

## Desired outcome

either the downloader would correctly parse the page, or it would provide an error message as to why it did not

**Comment by floogulinc** [comment]
There usually is a reason provided in the notes when a URL is ignored. You need to look in the import log:
![image](https://user-images.githubusercontent.com/1300395/116805359-abb90d00-aaeb-11eb-8bc4-843c928b21dd.png)

There you will be able to see any provided error in the notes column. You can right click on an item in the list and copy the note to post here.

**Comment by spiralw** [comment]
the reason in the notes is `Could not find a file or post URL to download!`
clearly the URL is correct, since i can click on it in the OP and it opens a danbooru page, so not sure why it can't find it?

**Comment by spiralw** [comment]
that seems to have worked, at least for the example in OP. i will try downloading some more stuff later and see if the issue comes up again

> Hard to say without knowing what URLs you actually have.
is this a setting in hydrus or are you asking for which urls i'm trying to download?
