### ISSUE TITLE
v438 crashes when trying to view images on Gentoo

### ISSUE THREAD

**Issue by F18SuperHornet** [hydrusnetwork/hydrus#873]
## Environment
Hydrus version: v438, running from source, installed via this overlay: https://github.com/pkulev/riru
Please note that this version has a patch applied, but that should not matter: https://github.com/pkulev/riru/blob/master/media-gfx/hydrus/files/paths-in-opt.patch
Platform: Gentoo GNU/Linux

## What happens
When you try to view a file (preview or in the media viewer), the client crashes.
The client can display thumbnails without an issue.

## Steps to reproduce
1. Update the client to v438
2. Try to view an image
3. It crashes

## Desired outcome
I can view the image.

## Error message / Log file / Screenshots
Logfile:
2021/05/06 19:00:28: hydrus client started
2021/05/06 19:00:29: booting controller…
2021/05/06 19:00:29: booting db…
2021/05/06 19:00:35: checking database
2021/05/06 19:00:38: preparing db caches
2021/05/06 19:00:38: initialising managers
2021/05/06 19:00:39: booting gui…
2021/05/06 19:00:39: starting services…
2021/05/06 19:00:39: Running "client api" on port 45869.
2021/05/06 19:00:39: services started
2021/05/06 19:01:09: Uncaught exception:
2021/05/06 19:01:09: TypeError
unhashable type: 'QRect'
  File "/opt/hydrus/hydrus/client/gui/canvas/ClientGUICanvasMedia.py", line 1778, in paintEvent
    self._DrawTile( dirty_tile_coordinate )
  File "/opt/hydrus/hydrus/client/gui/canvas/ClientGUICanvasMedia.py", line 1677, in _DrawTile
    tile = self._tile_cache.GetTile( self._image_renderer, self._media, native_clip_rect, canvas_clip_rect.size() )
  File "/opt/hydrus/hydrus/client/ClientCaches.py", line 548, in GetTile
    result = self._data_cache.GetIfHasData( key )
  File "/opt/hydrus/hydrus/client/ClientCaches.py", line 149, in GetIfHasData
    if key in self._keys_to_data:

2021/05/06 19:01:10: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:10: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:10: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:10: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:10: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:11: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:11: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:11: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:12: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:12: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:12: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:13: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:13: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:14: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:14: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:14: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:15: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:15: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:15: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:15: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:15: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:16: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:16: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:16: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:16: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:16: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:17: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:17: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:17: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
2021/05/06 19:01:18: QPaintDevice: Cannot destroy paint device that is being painted
/usr/bin/hydrus-client: line 3: 15344 Segmentation fault      /usr/bin/env python3 -OO /opt/hydrus/client.pyw "$@"

![image](https://user-images.githubusercontent.com/80971489/117339541-242f1d80-aea0-11eb-99ce-936b17fbe4a0.png)

**Comment by F18SuperHornet** [comment]
> Hey, this causes errors if you are running from source and using PyQt5 (PySide2 is fine)! I will fix this for next week, so if you are source+QtPy5, please hold off for now.

Reading the changelog would be helpful...

**Comment by vaartis** [comment]
@F18SuperHornet hydrus is now in the official ebuild tree so you an install it from there (would be nice to have someone besides myself to test this package)

**Comment by F18SuperHornet** [comment]
> @F18SuperHornet hydrus is now in the official ebuild tree and has actual versions too, so you an install it from there (would be nice to have someone besides myself to test this package)
Thank you very much for the information, but the official package seems to be out of date. I use the version from the riru overlay (https://github.com/pkulev/riru), which is just github sources with a patch that changes all the paths to /opt. Please let me know if the official package gets an upstream version (9999), I would be very happy to switch.

**Comment by vaartis** [comment]
> > @F18SuperHornet hydrus is now in the official ebuild tree and has actual versions too, so you an install it from there (would be nice to have someone besides myself to test this package)
> 
> Thank you very much for the information, but the official package seems to be out of date. I use the version from the riru overlay (https://github.com/pkulev/riru), which is just github sources with a patch that changes all the paths to /opt. Please let me know if the official package gets an upstream version (9999), I would be very happy to switch.

Unfortunately the review process is somewhat slow. I try to update the package the day the new version comes out, but getting it merged takes some time. I'll see about getting 9999 in tree.

**Comment by vaartis** [comment]
@F18SuperHornet, got the current version merged and 9999 in too. In general it shouldn't take this long.

**Comment by F18SuperHornet** [comment]
> @F18SuperHornet, got the current version merged and 9999 in too. In general it shouldn't take this long.
Whoa, that was quick!
I'll check it out tomorrow, thank you very much!

**Comment by F18SuperHornet** [comment]
> > @F18SuperHornet, got the current version merged and 9999 in too. In general it shouldn't take this long.
> 
> Whoa, that was quick!
> I'll check it out tomorrow, thank you very much!

Migrated to the official package (version 9999) and it works wonderfully. Thanks!
