### ISSUE TITLE
Uncaught exception: BufferError

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#876]
## Environment

Hydrus version: 438, Windows install
Platform: Windows 10
OS specifics: Latest update as of time of writing

## What happens
In a similar fashion to how some animated files causes a straight to crash to desktop with no error, some files cause a BufferError of some kind. I have not been able to isolate the files yet because of how my a/d filtering workflow works. Hydrus displays the attached error, trying to copy the traceback causes a crash to desktop.

## Steps to reproduce

1. Filter some files
2. Get error
3. Click copy traceback

## Error message / Log file / Screenshots
```
2021/05/08 09:32:04: Uncaught exception:
2021/05/08 09:32:04: BufferError

memoryview: underlying buffer is not C-contiguous

  File "hydrus\client\gui\canvas\ClientGUICanvasMedia.py", line 1778, in paintEvent
    self._DrawTile( dirty_tile_coordinate )
  File "hydrus\client\gui\canvas\ClientGUICanvasMedia.py", line 1677, in _DrawTile
    tile = self._tile_cache.GetTile( self._image_renderer, self._media, native_clip_rect, canvas_clip_rect.size() )
  File "hydrus\client\ClientCaches.py", line 552, in GetTile
    qt_pixmap = image_renderer.GetQtPixmap( clip_rect = clip_rect, target_resolution = target_resolution )
  File "hydrus\client\ClientRendering.py", line 203, in GetQtPixmap
    return HG.client_controller.bitmap_manager.GetQtPixmapFromBuffer( width, height, depth * 8, data )
  File "hydrus\client\ClientManagers.py", line 197, in GetQtPixmapFromBuffer
    qt_image = QG.QImage( data, width, height, bytes_per_line, qt_image_format )

2021/05/08 09:32:05: QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
```

**Comment by hydrusnetwork** [comment]
Thank you very much for this report, and I am sorry for the late response. This should be fixed in tomorrow's release.
