### ISSUE TITLE
Toggle option to disable deleting tags in manage tags dialog

### ISSUE THREAD

**Issue by novakda** [hydrusnetwork/hydrus#880]
On files with many tags, it can be difficult to tell whether you're actually adding or removing tags, if you're using the keyboard to type/paste them in.  

Please add a way to temporarily disable deleting tags in the manage tags dialog, perhaps a checkbox under the gear icon.

**Comment by Zweibach** [comment]
Does the `[ ] allow remove/petition result on tag input for already existing tag`-option not already fulfil this role?

**Comment by novakda** [comment]
Why, so it does.  I've never noticed that - I thought "petition" stuff only applied to the PTR.

Thanks.
