### ISSUE TITLE
Seeing notes in media viewer

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#882]
I envision them being presented in a similar manner that the tag list currently is. Either on the opposite side of the screen, along the bottom perhaps, or in the same bar as the taglist.

If there's multiple notes they should be collapsible/expandable (individually and/or all at once), display the notes's name, and you should of course be able to scroll if the note goes past the window border.

Unlike #562 which I imagine to be its own slightly separate and special thing this should just be a simple display of notes on the file so we have an easy way of reading them without having to go into the manage notes window.

**Comment by LillyHrdn** [comment]
This is exactly what I was thinking. Couldn't have said it better myself!

**Comment by mruac** [comment]
Would be great for preserving context about an image, such as a short story associated with the image or a description detailing the backstory behind it (eg. meme, lore, idea, etc).

**Comment by hydrusnetwork** [comment]
First version of this is out in the most recent release! It is a little ugly, but I'll keep iterating. Please let me know how it works for you.
