### ISSUE TITLE
Can I recommend adding a scroll bar in the import folder option 

### ISSUE THREAD

**Issue by Phooh** [hydrusnetwork/hydrus#90]
In the Manage Import Folder, when you go to add a folder and it brings you to the edit import folder options. The menu is sort of cut off for those of us with tiny screens/laptops.
http://i.imgur.com/35tgTq4.jpg
It's just kind of tedious to have to always change my resolution is all.

**Comment by hydrusnetwork** [comment]
Thank you for this report.

Someone else with a small resolution mentioned similar problems recently. I would like write a system to scrollbar-ise all my dialogs at a higher level, but that will be a big job, so for now I will manually fix the worst offenders. I have done the Manage Import Folder dialog for v182, so please let me know if it still sizes bad for you in that.

Are there any other dialogs that you use that are too big?

**Comment by Phooh** [comment]
Thanks, I haven't found any as of yet but I'll keep checking.

**Comment by hydrusnetwork** [comment]
It is now a priority to rewrite all my dialogs to use the same flexible layout. Now I have cleared out my oldest bugs, I expect to get to it in the next few weeks. I am closing this issue, but please do reopen it or create a new one if any particular dialog breaks for you in the meantime.
