### ISSUE TITLE
Subscription filler uses default gug instead of the one used for the subscription

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#906]
## Environment

Hydrus version:443, Windows installer
Platform: Windows 10

## What happens
When Hydrus gives the popup about "100 new URLs without running into any it had seen before." and you get the prompt to create a downloader to fill the gap, a gallery page is opened with the query except the GUG that's used is the one set as default instead of the one used for the subscription that created the popup.

## Steps to reproduce

1. Have a subscription with a lot of new URLs.
2. Click the "start a new downloader to fill in the gap!"-button.
3. ~~Profit!~~ You get a gallery page with potentially the wrong gug for the query.

## Desired outcome
The gug the subscription used is used instead of whatever the default is.

## Error message / Log file / Screenshots
![](https://cdn.discordapp.com/attachments/207629417290268672/855158757067325480/unknown.png)
![](https://cdn.discordapp.com/attachments/207629417290268672/855158784816840774/unknown.png)

**Comment by hydrusnetwork** [comment]
Thank you for this report, I am sorry for the late reply. This was happening when the button click also opened a new downloader page--subsequent clicks were able to set the correct GUG.

I believe this is now fixed, please let me know if you have any more trouble with it.
