### ISSUE TITLE
a way to know the installed version outside of program

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#909]
I am not the smartest individual in the world, and I don't update immediately when the new version comes out all the time, some times depending on what's going on it takes me 4-8 versions to update, and remembering the exact version I was on... that's not happening. 

just now I closed the program out and forgot to check what version I was on... so I now have to open and close it again to see what version I was on. I am also sure at some point when installing the few versions im behind, I will again, forget what version I just updated and will have to again open the program back up to check then close. 

normally this may not be to bad, but my dumbass has a massive session that takes a good 5 minutes to open and close and that's when it doesn't crash on closing. I know the use of this is niche, and if its already a thing/way to tell version without reopening I would love to know, but if its not, would it be possible to have a text file that just has the version number as a name, or a version.txt that just lost the version numbers?

**Comment by Suika** [comment]
`sqlite3 client.db 'select * from version;'`
or in
https://github.com/hydrusnetwork/hydrus/blob/master/hydrus/core/HydrusConstants.py#L83-L85

**Comment by Suika** [comment]
If you are on windows the sqlite.exe is inside the `db` directory. If you are on linux, figure it out.

**Comment by Mengmoshu** [comment]
@Suika This is pretty obviously a feature request, not a support issue. Providing a workaround is great, but this issue shouldn't be closed.

As far as what the feature could/should look like, the client could output the version as the last thing in the log when closing normally.

**Comment by CuddleBear92** [comment]
could fill the version field of the exe maybe. then again, a text file will prob be easier in the end somehow. 
![image](https://user-images.githubusercontent.com/8496821/122994163-71ac0f00-d3a8-11eb-9e7b-c008603a653e.png)

**Comment by Zweibach** [comment]
The changelog.html in /help has version.
@CuddleBear92 not everybody uses exe.

**Comment by CuddleBear92** [comment]
there is always https://github.com/hydrusnetwork/hydrus/blob/62b50d41e530a6755cca7dfa55926ae7a4dbbc10/hydrus/core/HydrusConstants.py#L84

**Comment by Zweibach** [comment]
> 2021/06/10 17:44:02: updating db to v443
2021/06/10 17:44:02: updated db to v443

Prints to log when you update Hydrus. So there's like at least four different methods for finding out current version so I think this issue is safe to close.
