### ISSUE TITLE
Subscription filler doesn't add subscription related tags

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#910]
## Environment

Hydrus version: 444
Platform: Windows
OS specifics: 7, x64

## What happens

Upon clicking popup "100 new URLs without running into any it had seen before." downloading starts. Neither subscription folder tags nor single-subscription specific tags are applied.

## Steps to reproduce

1. Have a subscription with a lot of new URLs.
2. Click the "start a new downloader to fill in the gap!"-button.
3. You don't notice imports having zero tags.
4. Close filler tab.
5. Cry yourself to sleep because you have metric shitton to fix now.

## Desired outcome

Having files tagged.

## Error message / Log file / Screenshots

---

**Comment by CatPlanet** [comment]
Funny enough, after exiting and opening hydrus 2 days later it just works (tm). New filler popups gets all appropriate tags from its subscription.
I assume something is not propagating correctly just after client updating.

I'll leave this issue open just in case, this shouldn't happen.

**Comment by CatPlanet** [comment]
Correction: it *almost* work correctly. Last few images imported don't have any tags at all.

**Comment by hydrusnetwork** [comment]
Thank you for this report. The gap filler button was not propagating file import options or tag import options from the subscription to the downloader page--it was just using whatever your defaults would be for that page.

I have fixed this for tomorrow's release, it should now propagate from the subscription itself. Please let me know if you have any more trouble with it.
