### ISSUE TITLE
Client API: Read Main Gui Title

### ISSUE THREAD

**Issue by cinnamon-rolls** [hydrusnetwork/hydrus#916]
In `file->options->gui->Main gui title`, we can rename the client's title to something else (default is `hydrus client`). I would like to be able to read the client's gui title from the API.

### Motivation

This allows for a 3rd party app to identify which client it is connected to, e.g.

```
connected to 'my awesome client' on localhost:8080
```
vs
```
connected to 'test client' on localhost:8081
```

**Comment by floogulinc** [comment]
Added with https://github.com/hydrusnetwork/hydrus/pull/1460 in https://github.com/hydrusnetwork/hydrus/releases/tag/v552a
