### ISSUE TITLE
Cannot import a single folder

### ISSUE THREAD

**Issue by darlopvil** [hydrusnetwork/hydrus#918]
## Environment

Hydrus version: 445, using network version 20
Platform: Windows 
OS specifics: Windows 10 Pro x64 RAM: 12Gb CPU: i3-4005 at 1.70Ghz

## What happens

Hi,

So, after installing the program, i started reading the Manual. When i was [here](https://hydrusnetwork.github.io/hydrus/help/getting_started_files.html), opened Hydrus in order to import a small folder, just for testing issues. It didn't work. I've tried a ton of others folders without results (folders in other devices as well).
I don't understand why is showing "maybe in use by another process". What does it mean? Could i have a example?

## Steps to reproduce

1.
2.
3.

## Desired outcome
That it works

## Error message / Log file / Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/60988792/124471281-36d4ae80-dd8c-11eb-82f7-2d11d21f87cd.png)

**Comment by Zweibach** [comment]
> I don't understand why is showing "maybe in use by another process". What does it mean? Could i have a example?

This sounds like a generic Windows error as the OS is quite bad at telling the user what exact process is using a folder/file. The common perpetrator is the anti-virus.

**Comment by TheElo** [comment]
Normally that error message is very accurate!
Something locks access to the file, you could have it open/selected, close the folder and anything that could access it - also try turning off win10 AV as it blocks access to files until it´s reviewed them first.

try to import from a diffrent drive, to see if it´s maybe access policy related. Maybe running hydrus as admin could help.

**Comment by Zweibach** [comment]
Seeing as it's been a few days with no further response and this almost certainly not being a problem on Hydrus' end I'm closing this.
