### ISSUE TITLE
Client API: Query Tag Parent/Child Relationships

### ISSUE THREAD

**Issue by cinnamon-rolls** [hydrusnetwork/hydrus#921]
API path to grab the current parent/child tag relations

What I have in mind is something to the effect of (using somewhat contrived examples)

`get_tags/get_children?parent=dress`

which returns

```json
{
  "children": [ "red dress", "orange dress", "yellow dress", "..." ] 
}
```

and,

`get_tags/get_parents?child=red dress`

which returns

```json
{
  "parents": [ "dress", "red clothing", "..." ] 
}
```

But there are dozens of ways to probably go about this, so anything functionally equivalent works

(Sorry if this is a duplicate, I searched for this and didn't find this already. I'll move this to a comment of the pre-existing issue if it is)

**Comment by floogulinc** [comment]
I think a more general tag information API would be appropriate. Something where you can query a tag or array of tags and get it's parents, children, siblings, and display information at once. It may be useful to expose actual tag IDs in the file metadata API and use those here as well.

**Comment by cinnamon-rolls** [comment]
Sorry, late response

I'll support anything as long as it is functionally equivalent to what I described. The example above is just an example of what it _could_ look like, but not what it _has_ to look like.

**Comment by floogulinc** [comment]
This has been added in https://github.com/hydrusnetwork/hydrus/releases/tag/v541 with [`/add_tags/get_siblings_and_parents`](https://hydrusnetwork.github.io/hydrus/developer_api.html#add_tags_get_siblings_and_parents)
