### ISSUE TITLE
Client API: Don't interpret null as an existing value in optional fields

### ISSUE THREAD

**Issue by Trivernis** [hydrusnetwork/hydrus#922]
## Summary

When starting requests against the Client API, optional request parameters should be ignored when they are given `null` value. For example

```json
{
	"url": "https://www.pixiv.net/member_illust.php?illust_id=83406361&mode=medium",
	"service_names_to_additional_tags": {
		"my tags": ["ark mage", "grinning"]
	},
	"show_destination_page": true,
	"destination_page_name": "Rusty Url Import",
	"destination_page_key": null,
	"filterable_tags": []
}
```
to `add_urls/add_url` should be a valid request and not return `I was expecting to parse 'destination_page_key' as a hex string, but it failed.`. The same behaviour should apply to `add_files/add_file`.

## Environment

Hydrus version: 446 from the AUR as an executable
Network version: 20
Platform: Linux 5.12.15-arch1-1

## What happens

The client interprets the value `null` as an existing value of the field and throws an error when it can not be parsed. Since null is usually used to indicate that an optional field doesn't have a given value, the field should be ignored by the client api when the value is set to `null`.

## Steps to reproduce

1. Start a POST request with the JSON Body mentioned in the summary (provide the access token in the header)
2. Wait for the response
3. Yep, it doesn't work.

## Error message / Log file / Screenshots

![image](https://user-images.githubusercontent.com/19694973/125167945-55c7ac00-e1a3-11eb-8b9c-c8de877c4bfd.png)

**Comment by hydrusnetwork** [comment]
Thank you for this report. I did not know this was normal for JSON. I have updated the main Client API POST variable parsing to try to treat any null value as if the key were missing. Please let me know if you run into any more trouble with it!
