### ISSUE TITLE
Full metadata resync only updates database, while ignoring caches

### ISSUE THREAD

**Issue by F18SuperHornet** [hydrusnetwork/hydrus#924]
## Environment

Hydrus version: v446, running from source
Platform: any
OS specifics: n/a

## What happens
Whenever the client has a corrupt update hash for updates from tagging repos (e.g. the PTR), you can fix the relevant database table with a "full metadata resync". This updates the hashes in the master-DB, but does not remove any bad caches for the old (corrupt) hashes, making it seem like nothing happened, until the cache expires.
This means that the hash_id -> hash cache is bad, since it contains an entry that is not what it is in the actual database.

## Steps to reproduce
1. Have corrupted PTR hashes in client (will produce a 404 not found error when attempting to fetch newest archives) - no idea how to reproduce that, other than manually edit some hashes in the DB
2. Do a full metadata resync
3. The error is still there

## Desired outcome
* After the full metadata resync, update the hash_id -> hashes cache to include the updated entries
* Alternatively, force the user to regenerate the hash cache and restart the client

## Error message / Log file / Screenshots
>Attempting to download an update for public tag repository resulted in a network error:
> 404: This update hash does not exist on this service!

To check the issue, you can print the hashes and IDs that the `_GetRepositoryUpdateHashesIDoNotHave` function gets, those will come from cache, while the hash_id in the actual master db will contain a different (corrected) hash after the metadata resync.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I think we were talking about this somewhere else as well. This seems to have been a broader problem with databases that have had their client.master.db corrupted by a hard drive problem (and then recovered), now being desynchronised with the local hash cache. I forced everyone to get a local hash cache regen last week, which seems to fix this issue, but there may be other problems for other hash_ids that refer to either missing master hash rows or rows that now have a different hash (essentially, files may get given the wrong tags or urls or, as in your case, 'this is an update file' status).

There isn't an excellent comprehensive solution to this, but I have a longer term plan to deal with missing hash_ids, and surplus hash_ids, in future.

I am going to update my 'help my db is broke.txt' file to suggest users run the local hash cache regen after problems with client.master.db. That should fix most of these issues at the root. _Most_ of the time, if the cache is synced and the rows are PTR-related and just missing, the client will detect them missing and schedule some reprocessing to get them filled in again.

**Comment by F18SuperHornet** [comment]
Great, I just wanted to "officially" file a bug report here so it shows up when you search for the problem. And then I forgot to close it...
As far as I am concerned, the issue is resolved by putting this information in the help section. Also good to know that there are plans to get this fixed permanently later on. Cheers!
