### ISSUE TITLE
[Request] Simple way to add a namespace to tags

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#93]
My initial idea is limited but it's supposed to just give an example:
In the image(s) tag manager, if you choose a single or different tags and in the tag entering box below it there's a namespace, the selected tags gain the namespace.

![ex1](http://i.imgur.com/9PdXqyr.png)
![ex2](http://i.imgur.com/earGJeh.png)

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
