### ISSUE TITLE
sibling and parent window is not able to bulk remove tags already set

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#933]
In the Sibling and Parent windows, you cannot shift select and press enter to remove tags or pending tags, it just closes and confirms the window instead.
Discovered this issue when i was trying to dump 11k siblings from Kemono.Party and a large part of it was already on the PTR and needed to be removed, but since i cant bulk remove the changes so they stay on the PTR... im rather forced to do them one at a time which is not wanted.

**Comment by hydrusnetwork** [comment]
Thanks, I will check this out!

**Comment by hydrusnetwork** [comment]
This should be fixed for tomorrow's release. All multi-column lists across the program now capture an enter/return and send an 'activate' command as if you had double-clicked. Let me know if you have any more trouble with it!
