### ISSUE TITLE
psd thumbnail generation with ffmpeg

### ISSUE THREAD

**Issue by CuddleBear92** [hydrusnetwork/hydrus#936]
ffmpeg can generate thumbnails for .psd files. think thumbnails should still be a thing even if you cant open it in the client.

**Comment by cinnamon-rolls** [comment]
This shell command works for ffmpeg version 4.2.4-1ubuntu0.1

```
ffmpeg -i HASH.psd -s 100x100 OUTPUT.jpg
```

Where `HASH.psd` is the full psd file, and `OUTPUT.jpg` is the output, as the name suggests. The output is a 100x100 jpg image.

Experimentation has shown that it preserves the visible layers and works just as you'd expect a thumbnail to work.

## Alternative: ImageMagick

imagemagick can also be used, but I don't think imagemagick is used in Hydrus yet so this might be more trouble than it is worth...

```
convert HASH.psd -flatten -thumbnail 100x100 OUTPUT.jpg
```

https://imagemagick.org/index.php

**Comment by Suika** [comment]
Windows and macOS build install FFmpeg 4.4 "Rao" but ubuntu build uses FFmpeg 3.4.8 "Cantor" due to being built on Ubuntu bionic LTS.

**Comment by floogulinc** [comment]
It might be worth looking into imagemagick since it is probably useful for more in the future like thumbnails of PDFs

**Comment by Zweibach** [comment]
Hasn't there been request for finding rotated/flipped matches in the dupe finder? Because looking at some of the stuff that imagemagick can apparently do that's one of the things.

**Comment by cinnamon-rolls** [comment]
ImageMagick has a Python API of some kind, but information about it appears to be a little scarce. It appears to be something  you download and include with the project

- https://wiki.python.org/moin/ImageMagick
- https://download.imagemagick.org/ImageMagick/download/python/

All else fails, you could also detect if ImageMagick is installed on the system and feed it commands through the shell, which might just be easier.

**Comment by floogulinc** [comment]
Added in https://github.com/hydrusnetwork/hydrus/releases/tag/v448
