### ISSUE TITLE
[Request] When downloading from gallery, show which query was used to download an image

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#94]
In the detailed File Import Status window.
Just so when you input some wrong query, you can skip it.

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
