### ISSUE TITLE
When attempting to update pre-existing v446 or prior install, client.exe is just removed by installer

### ISSUE THREAD

**Issue by Feldherren** [hydrusnetwork/hydrus#946]
### Hydrus version

v447, v448

### Operating system

Windows 10

### Install method

Installer

### Install and OS comments

Windows 10. Pre-existing install of Hydrus, attempting to update by installing over existing location. This usually works, but v447 and v448 have both produced this issue for me. I think I first attempted the update from version v442 (or so) to v447, and it had the same issue then; I got client.exe back by updating to v446, which seems to work. v446 to v448 has the same issue.

### Bug description and reproduction

Reproduction steps:
1. Start from earlier installed version of Hydrus. I'm currently on v446, but the first time I encountered this bug I was at least a few versions back from it (possibly v442). The executable client.exe exists at this point.
2. Attempt to install v447 or v448
3. Point installer at pre-existing installation location
4. Set 'components' dropdown to Install (not sure what happens when you just extract)
5. Installer produces the following error message when attempting to rename/move client.exe:

[Window Title]
Error

[Main Instruction]
Select action

[Content]
D:\Pictures\Hydrus Network\client.exe

An error occurred while trying to rename a file in the destination directory:
MoveFile failed; code 5.
Access is denied.

[Try again] [Skip this file (not recommended)] [Cancel installation]

5. Looking in Hydrus installation location, client.exe is just gone, at this point. It doesn't appear to have been moved to the recycle bin, either.
6. At this point I cancel the install. client.exe is not reverted back into existence by this.

-----

Starting the v447 or v448 installer again and attempting to install over the location now missing its client.exe produces the same error. Not sure what happens when you decide to extract over, don't really want to try without knowing it won't just wipe my currently-stored images and tags.
Fortunately it looks like you can just run v446 to 'update' back to having a client.exe.

**Comment by artur-ag** [comment]
Check if Windows Security is false-flagging client.exe as malware. Mine flags it as Trojan:Script/Wacatac.B!ml, and I think this has happened in the past already.

**Comment by Feldherren** [comment]
I hadn't thought it would be that as I wasn't getting any notifications or logged reports that was happening (and there isn't, for whatever reason). But you appear to be completely right and sticking exceptions in my security solution did work.
