### ISSUE TITLE
Remove old non-working default pixiv parser components

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#947]
There are a number of leftover parser components for Pixiv that no longer work left in the defaults.

## Parsers
- `pixiv single file page parser - new layout` - non working, replaced by API
- `pixiv manga page parser` - non working, replaced by API
- `pixiv manga_big page parser` - non working, replaced by API
- `pixiv tag search gallery page parser` - non working, replaced by API

## URL Classes
- `pixiv tag search gallery page` - redirects to the standard tag page now so will never appear.
- `pixiv manga_big page` and `pixiv manga page` should be combined with `pixiv file page` by allowing `manga_big` and `manga` in its `mode` query param.

**Comment by hydrusnetwork** [comment]
Thanks again. All sorted for tomorrow, just as you say here.
