### ISSUE TITLE
[Issue] When adding a Tag Sibling, sometimes the tag does not enter

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#95]
It happens very randomly but happens more than the expected behaviour.

Finish typing the tag you want (left or right side), press enter and nothing happens.

You then have to **(not sure at all why, but it works)** add a space, erase the space and the last character of the tag, add that character again and press enter. Done.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I have done some more work on siblings this week. I might have fixed your problem. Please let me know if you still get it in v185.

**Comment by HASJ** [comment]
Confirmed fixed.
