### ISSUE TITLE
Setting to not trigger fill-in downloading for subs

### ISSUE THREAD

**Issue by Zweibach** [hydrusnetwork/hydrus#951]
I want a setting, preferably per subscription, to not be asked about doing a fill-in gallery download. I want this since I have a few subs I know I wont get everything new on but don't particularily care. For a similar case some sites and parsers for those sites are constructed in such a way that the question will be asked regardless if the sub got everything or not, such as Sankaku if I recall correctly.

**Comment by floogulinc** [comment]
Added in https://github.com/hydrusnetwork/hydrus/releases/tag/v452
