### ISSUE TITLE
Client-API: 'system:is not the best quality file of its duplicate group' is not accepted in search

### ISSUE THREAD

**Issue by Trivernis** [hydrusnetwork/hydrus#954]
### Hydrus version

v450

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Kernel: 5.13.9-arch1-1
Installed from the AUR

### Bug description and reproduction

1. start a `get_files/search_files` request with the tag `system:is not the best quality file of its duplicate group`
2. Get the error `Could not parse system predicate "system:is not the best quality file of its duplicate group'"!`

See #945 for a fix

### Log output

```text
2021/08/12 18:19:37: 45869 GET /get_files/search_files 400 in 813 microseconds
```

**Comment by Trivernis** [comment]
Oh by the way, because of the missing grouping in the regex expression `system:is not` is equivalent to `system:isn't best quality of group`.

**Comment by hydrusnetwork** [comment]
Thank you for this report, and the fix! Sorry for the delay, this is in for 453.
