### ISSUE TITLE
Client API - `file_sort_asc` query parameter not working on `/get_files/search_files` requests

### ISSUE THREAD

**Issue by prof-m** [hydrusnetwork/hydrus#959]
### Hydrus version

v450

### Operating system

macOS 10.15 "Catalina"

### Install method

Installer

### Install and OS comments

Queries against Client API were run with Postman and from the command line with `curl`.

### Bug description and reproduction

Was just testing this out on the new version 450. Good news: the file_sort_type parameter seems to be working as intended! Bad news: At least as far as I can tell, the file_sort_asc parameter doesn't seem to be respected. Whether I pass it true or false, the returned list of file_ids comes back in the exact same order.

I tried this for all sorting types 0-9, but the file_sort_asc parameter didn't seem to affect the results of any of them.

Here's an example of one of the GET URLs I was trying with:
`http://localhost:45869/get_files/search_files?file_sort_type=9&file_sort_asc=false&tags=["system:duration < 2 seconds"]`

**Steps to Reproduce:**
1. Setup a working Hydrus client with files, with a running Client API service
2. Make a basic `/get_files/search_files?` API GET request without a `file_sort_asc` query parameter. For demonstration purposes, try to make a query that ideall returns a decent but not overwhelming amount of files. Note the file_ids that are returned in the response.
3. Add the `file_sort_asc=true` query parameter to your API request URL, and run the request again. Note the file_ids returned - they should be returned in the exact same order as last time.
4. (Optional) For completeness, change the `file_sort_asc` query parameter to be `file_sort_asc=false`. Note the file_ids returned - they should be in identical order to the previous two responses.

**Comment by Trivernis** [comment]
Looks like it's parsed but not used ([line in the code](https://github.com/hydrusnetwork/hydrus/blob/b0a3e217bbb088c49c4744b3ad92a6f3265c9495/hydrus/client/networking/ClientLocalServerResources.py#L1697))

**Comment by floogulinc** [comment]
Ah yes. The sort order is parsed in the line above:
https://github.com/hydrusnetwork/hydrus/blob/b0a3e217bbb088c49c4744b3ad92a6f3265c9495/hydrus/client/networking/ClientLocalServerResources.py#L1694

But the actual query uses the old hardcoded `sort_order = CC.SORT_DESC`:
https://github.com/hydrusnetwork/hydrus/blob/b0a3e217bbb088c49c4744b3ad92a6f3265c9495/hydrus/client/networking/ClientLocalServerResources.py#L1697

So that line should be changed to 
```py
sort_by = ClientMedia.MediaSort( sort_type = ( 'system', file_sort_type ), sort_order = sort_order )
```

**Comment by Trivernis** [comment]
yes

**Comment by hydrusnetwork** [comment]
Damn, thank you for this report. I'll fix this! I threw this together last minute before the release and did not figure out proper tests--I will fix and put some time into nice unit tests. Sorry for the trouble, and thank you for testing for me!

**Comment by prof-m** [comment]
@hydrusnetwork No worries at all! This whole addition to the Client API is a huge improvement, and it's only natural for there to be a few kinks to work out. Thanks to everyone for looking into this, too!
