### ISSUE TITLE
Massive virustotal reports in 450

### ISSUE THREAD

**Issue by minakitty** [hydrusnetwork/hydrus#962]
### Hydrus version

450

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

1. Download from https://github.com/hydrusnetwork/hydrus/releases, then install
2. Send the server.exe hash to virustotal (https://www.virustotal.com/gui/file/342de1f48492102ae9690ce875805197057a0489308a95c41cf88f2d100267d9/detection) get 25/68 vendors flagging as malicious
3. Try to run. Have Avast quarantine the server.exe file

This is highly reminiscent of #791 but as that issue was claimed to be resolved, want to make sure that this is a false positive as opposed to something malicious that got merged in by accident

**Comment by Chad90b** [comment]
hello @minakitty 
this is a known issue and not a problem with hydrus itself. unfortunately. there is no efficient way to resolve this but for microsoft to correct their broken filters. dev has attempted a fix for next release; but we do not yet know if it will fix the issue.
you can see his response about it here https://twitter.com/hydrusnetwork/status/1426651354752331784

**Comment by minakitty** [comment]
Thanks, I wasn't following on Tweeters
