### ISSUE TITLE
CLI Utils

### ISSUE THREAD

**Issue by TheRevenantStar** [hydrusnetwork/hydrus#963]
Is it possible to load hydrus "headless" using the a CLI to do things like process repository updates?

Use Case:
I have hydrus running in a GitAnnex directory, this keeps it synced with a remote server (an old Cisco MCS device from 2010) that has way more CPU power than my laptop could ever muster. 
I'd like to, when hydrus is not running on my laptop, is to let the server open hydrus and complete processing and optionally backups, unattended.

**Comment by Zweibach** [comment]
No, it's not. https://github.com/floogulinc/hydrus-web is the best you'll get.

**Comment by hottellbt** [comment]
As of writing, Hydrus will put up a GUI whether you want it to or not, and won't function unless it gets its GUI. So, there is no "true" headless mode. But, you can use the [Client API](https://hydrusnetwork.github.io/hydrus/help/client_api.html) along with a command line script to get some things done without touching the GUI. (hydrus web, linked above, also uses the api)

Client API aside, I think this is a good feature request and I've been wanting something like this myself, but settled for crazy api-based hacks. If its worth anything as an unprivileged common user, I'd like to reopen this as a feature request.

**Comment by cinnamon-rolls** [comment]
As of writing, Hydrus will put up a GUI whether you want it to or not, and won't function unless it gets its GUI. So, there is no "true" headless mode. But, you can use the Client API along with a command line script to get some things done without touching the GUI. (hydrus web, linked above, also uses the api)

Client API aside, I think this is a good feature request and I've been wanting something like this myself, but settled for crazy api-based hacks. If its worth anything as an unprivileged common user, I'd like to reopen this as a feature request.

**Comment by thatfuckingbird** [comment]
You can start hydrus on linux without a running graphics server by using the Qt framebuffer backend (it's not real headless as there is still a gui, but pretty close).
