### ISSUE TITLE
increase tag as number filter's limit

### ISSUE THREAD

**Issue by dali99** [hydrusnetwork/hydrus#968]
the tag as number filter currently has an 8 digit limit in the UI:

https://github.com/hydrusnetwork/hydrus/blob/212088ba4b504c3dbce45c602741b0cce2e799b4/hydrus/client/gui/search/ClientGUIPredicatesSingle.py#L1803

I discovered this when I attempted to use the filter with tags which have unix timestamps in them.

It would be nice if this could be increased to at least 13 digits to account for the often used unix timestamp denoted in milliseconds.

This would allow one to search for files created between two time intervals for example.

**Comment by floogulinc** [comment]
Fixed in https://github.com/hydrusnetwork/hydrus/releases/tag/v453
