### ISSUE TITLE
Exporting file locally

### ISSUE THREAD

**Issue by eider-i128** [hydrusnetwork/hydrus#97]
Local file export GUI needs polishing. It currently does not inform about successful export and throws exception when manually typed directory (for example 'hydrus_export\newfolder') doesn't exists (should be able to create one)

**Comment by hydrusnetwork** [comment]
Thank you for this report. I don't have time right now to give the whole directory a makeover, but I can fit these two things in. New directories will now be created automatically and export progress will be reported through the export button, which will be disabled while the export progresses. I also moved the actual operation off the gui thread so it won't hang on big jobs.
