### ISSUE TITLE
Please make the duplicate statements_and_scores colors customizable

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#974]
i.e. please let this text inherit style information https://github.com/hydrusnetwork/hydrus/blob/2daf09a7434bb663e1fe9eaec73f69fba4c399be/hydrus/client/gui/canvas/ClientGUICanvasHoverFrames.py#L736-L746

**Comment by floogulinc** [comment]
I believe this has been added in https://github.com/hydrusnetwork/hydrus/releases/tag/v454
