### ISSUE TITLE
Hydrus Server - Update Period Changes Revert to Default On Reboot

### ISSUE THREAD

**Issue by prof-m** [hydrusnetwork/hydrus#976]
### Hydrus version

v454+

### Operating system

MacOS 10.15.17, Ubuntu 16.14, Windows 10

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

- Hydrus Server running from source (MacOS, Windows 10, Unix)
- Hydrus Server running in Docker, pulled from [ghcr.io/hydrusnetwork/hydrus:server](ghcr.io/hydrusnetwork/hydrus:server). 
  - Same issue occurs whether Docker image is run on Unix (Ubuntu 16.14) or Mac OSX (10.15.7).

### Bug Description
Any changes made to a remote repository's update period are not persisted between Hydrus Server reboots. All remote repositories running on a given hydrus server (both tag repos and file repos) will revert to the default update period whenever the server executable is restarted.

Note on version: I'm believe this has been a bug since the ability to change the update period was introduced several versions ago, but I haven't rolled back to double check.

### Reproduction Steps
1. Start Hydrus Server with one tag repository and one file repository.
2. From the Hydrus Client, connect to the server and add both repositories. Make sure you're set up as an admin user with permission to change the update period for both repositories.
3. Change the update period for either or both of the repositories to something other than the default period of 1 day 3 hours, etc etc
4. Open up the Review Services window in the client. Navigate to each remote repository service. In each, click 'Refresh Account' and confirm that the update period has changed.
5. Reboot the Hydrus Server. (Make sure the DB location is the same as when you first started it up)
6. Once the Hydrus Server is rebooted, repeat step 4, including hitting 'Refresh Account'. The update period displayed for each service will have reverted to the default period.

**Comment by prof-m** [comment]
Tested and confirmed that this bug can be reproduced when just running the server from source (rather than through a Docker container)

**Comment by hydrusnetwork** [comment]
Thank you for this report! This should be fixed in tomorrow's release. It also fixes saving the newer anonymisation period. I am sorry for the trouble!

**Comment by prof-m** [comment]
@hydrusnetwork No trouble at all, thank you for fixing this so quickly!
