### ISSUE TITLE
Can tbib or e621 be used as a tag repository?

### ISSUE THREAD

**Issue by KamillaPup** [hydrusnetwork/hydrus#985]
Most of my images come from these two sites but I can't figure out how to get the system to pull tags from these sites for the images that match the hash values there. I don't want to use the main repository due to its size and I would like to limit what tags are used (I don't need a tag for lamp if a lamp is in the background, etc.)

I know Boori Grabber can do this, but can Hydrus?

**Comment by QueenHek** [comment]
Read the docs

**Comment by Zweibach** [comment]
> 
> 
> Read the docs

**Comment by KamillaPup** [comment]
I've read through all the docs several times so your response isn't actually that useful. The docs only mention the main tag repository. If there is a specific doc that addresses this you could just link to it instead of saying "read the docs"

**Comment by KamillaPup** [comment]
> > I've read through all the docs several times so your response isn't actually that useful. The docs only mention the main tag repository. If there is a specific doc that addresses this you could just link to it instead of saying "read the docs"
> 
> what you are asking for is not possible. you cannot use external sources as your **_tag repo_**. tag repos are always local on your machine within the hydrus databases and they are based off tags hydrus has parsed from sites or tags entered manually by the user.
> 
> im not sure if you have read the docs and discovered how to enable your hydrus installation to grab tags at the same time as it downloads the file so i will quickly mention it here as im sure it would interest you. it is covered down on this page https://hydrusnetwork.github.io/hydrus/help/getting_started_downloading.html
> 
> md5 hash lookup to return tags is not well documented by hydrus developer iirc but it is nicely covered by hydrus users here https://wiki.hydrus.network/books/hydrus-manual/page/file-look-up

Thank you so much! Exactly what I was looking for.
