### ISSUE TITLE
[FR] add ability to move/specify client_files to external location

### ISSUE THREAD

**Issue by sttollgrin** [hydrusnetwork/hydrus#99]
As the title says.

I'd really like to move Hydrus client and its sqlite database to SSD drive, however with >50GB of client_files this is... well not impossible, but highly impractical. It would be really great if I could run Hydrus from SSD, let's say, C:/Hydrus/ and specify that client files are located in let's say D:/HydrusFiles/client_files

The current, workaround solution would be to symlink client_files to SSD from the HDD

**Comment by ScoreUnder** [comment]
>current, workaround solution

I do this kind of thing all the time, what makes it a "workaround"? It's another way to organize a filesystem to fit its contents, right?

**Comment by hydrusnetwork** [comment]
This is now done! Check out _file->options->file storage locations_ if you missed it. Let me know if it gives you any problems!
