### ISSUE TITLE
Permission to add to homebrew/cask package repository

### ISSUE THREAD

**Issue by SudoerWithAnOpinion** [hydrusnetwork/hydrus#991]
For ethical reasons, I'd like to formally request permission to include and maintain a [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) of Hydrus Network (hydrus-network).
This will allow Mac OS users to install hydrus by using ``brew install hydrus-network``

**Comment by Zweibach** [comment]
https://github.com/hydrusnetwork/hydrus/blob/master/license.txt
There's already user-made AUR repository, Chocholatey package, and a few other third-party distributions.
