### ISSUE TITLE
Media Preview widget aligning issues

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#998]
### Hydrus version

v458

### Operating system

Windows other (specify in comments)

### Install method

Installer

### Install and OS comments

Windows 7

### Bug description and reproduction

1. Have media preview window enabled
2. Have **custom scanbar height**.
3. Select some media with duration.

For "10":
![](https://i.imgur.com/pupaIj1.png)

For "50":
![](https://i.imgur.com/TI6iJuk.png)

Text should always center vertically for maximum readability.

**Comment by hydrusnetwork** [comment]
Thank you for this report and the screenshots. I have made the text align center-vertically as you suggest for tomorrow's release. This scanbar has been a mess for so long, I should really put some proper time into it to make it look nicer!
