### ISSUE TITLE
Media Preview "embed button" preventing video from displaying

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#999]
### Hydrus version

v458

### Operating system

Windows other (specify in comments)

### Install method

Installer

### Install and OS comments

Windows 7

### Bug description and reproduction

1. Options > Media > Video (or Animation) > **☑ preview starts covered with an embed button**
2. Select video (or animation) media
3. Click the dumb thing
4. Only audio plays, so video, frame is unclickable

With option **☑ preview starts paused** same as above happens + nothing ever plays because there is now no way to play anything.

**Comment by hydrusnetwork** [comment]
Thank you for this report. I am sorry for the trouble. I think I have this fixed for tomorrow's release, so please let me know if you have any more trouble.
